### Project Overview
This notebook implements a full end-to-end pipeline for the CSIRO Image2Biomass prediction task. 
https://www.kaggle.com/competitions/csiro-biomass/overview

The goal is to predict five biomass-related targets from plot images and associated metadata, with a competition metric based on Kaggle-style weighted R² over all targets.

raw CSV + JPEGs → processed folds → baselines → hybrid teacher → distilled student

In [39]:
# ==================== 0. Setup Reproducibility & Config ====================
import os, json, random, platform
from dataclasses import dataclass, asdict
from pathlib import Path

# Make TensorFlow as deterministic as possible (given hardware / ops)
os.environ["TF_DETERMINISTIC_OPS"] = "1"
os.environ["TF_CUDNN_DETERMINISTIC"] = "1" 
os.environ["PYTHONHASHSEED"] = str(42) 

import tensorflow as tf

tf.config.threading.set_inter_op_parallelism_threads(1)
tf.config.threading.set_intra_op_parallelism_threads(1)

import numpy as np, pandas as pd, matplotlib.pyplot as plt, matplotlib as mpl
import cv2 # OpenCV (Open Source Computer Vision Library)
import sklearn
from sklearn.model_selection import GroupKFold
from sklearn.model_selection import StratifiedGroupKFold
from datetime import datetime

# Log library versions for reproducibility
versions = {
    "python": platform.python_version(),
    "tensorflow": tf.__version__,
    "numpy": np.__version__,
    "pandas": pd.__version__,
    "sklearn": sklearn.__version__,
    "keras": tf.keras.__version__,
}
print("versions:", versions)

@dataclass
class CFG:
    """Global configuration for the CSIRO Image2Biomass project.

    This dataclass centralizes all tunable knobs and file paths so that
    the rest of the notebook can read configuration from a single object.

    Attributes:
        project_title: Human-readable project title.
        seed: Global random seed used for NumPy, Python, and TensorFlow.
        image_size_h: Height of input images in pixels.
        image_size_w: Width of input images in pixels.
        n_folds: Number of cross-validation folds.
        batch_size: Batch size for training and evaluation.
        raw_csv: Relative path to the original long-format training CSV.
        image_root: Root directory for image files referenced in the CSV.
        artifacts_dir: Directory where processed CSVs, configs, and models
            are saved.
        figs_dir: Directory where figures and diagnostic plots are saved.
        use_log1p: Whether to use log1p-transformed labels during training.
    """
    project_title: str = "CSIRO Image2Biomass Prediction"
    seed: int = 42
    image_size_h: int = 224
    image_size_w: int = 448 
    n_folds: int = 5
    batch_size: int = 8 # batch_size=8 for 357 images can be stable and better generalization
    raw_csv: str = "../csiro-biomass/train.csv"
    image_root: str = "../csiro-biomass"
    artifacts_dir: str = "../artifacts/"
    figs_dir: str = "../figs"
    use_log1p: bool = False

CFG = CFG()
Path(CFG.artifacts_dir).mkdir(parents=True, exist_ok=True)
Path(CFG.figs_dir).mkdir(parents=True, exist_ok=True)

# ---------- Targets ----------
CORE_TARGETS = ["Dry_Green_g","Dry_Dead_g","Dry_Clover_g"]  
RAW_TARGETS  = CORE_TARGETS + ["GDM_g","Dry_Total_g"]       


# ---------- Reproducibility ----------
def set_seed(seed=42):
    """Set global random seed for Python, NumPy, and TensorFlow"""
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)

set_seed(CFG.seed)

versions: {'python': '3.11.14', 'tensorflow': '2.17.1', 'numpy': '1.26.4', 'pandas': '2.3.3', 'sklearn': '1.7.2', 'keras': '3.12.0'}

In [40]:
# ==================== 1. read raw data ====================
df_raw = pd.read_csv(CFG.raw_csv)
display(df_raw.head(5))
# add tensor columns: abs_image_path & image_id
df_raw["abs_image_path"] = df_raw["image_path"].apply(lambda p: str(Path(CFG.image_root) / p))
df_raw["image_id"] = df_raw["abs_image_path"].map(lambda p: Path(p).stem)

,sample_id,image_path,Sampling_Date,State,Species,Pre_GSHH_NDVI,Height_Ave_cm,target_name,target
0,ID1011485656__Dry_Clover_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Clover_g,0.0000
1,ID1011485656__Dry_Dead_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Dead_g,31.9984
2,ID1011485656__Dry_Green_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Green_g,16.2751
3,ID1011485656__Dry_Total_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,Dry_Total_g,48.2735
4,ID1011485656__GDM_g,train/ID1011485656.jpg,2015/9/4,Tas,Ryegrass_Clover,0.62,4.6667,GDM_g,16.2750

In [41]:
# ==================== 2. Pivot ====================
def build_pivot_df(df):
    """convert long-format biomass table to a wide per-image table."""
    
    # 1) create wide table which has one row per image with all 5 targets as columns
    wide = (
        df.pivot_table(index="image_id", # → each img is a row
                       columns="target_name", # → the target columns to create 
                       values="target",  # → the values to fill the table
                       aggfunc="first") # → in case of duplicates, take the first
          .reset_index() # → add the index column, so image_id becomes a column again
    )
    
    # 2)target columns check ensure all present
    for col in RAW_TARGETS:
        if col not in wide.columns:
            wide[col] = np.nan # add missing value target columns with NaN values
    wide = wide[["image_id"] + RAW_TARGETS]

    # Join metadata: from original df extract unique rows
    meta_cols = ["image_id", "abs_image_path", "Sampling_Date", "State", "Species", "Pre_GSHH_NDVI", "Height_Ave_cm"]
    meta = df[meta_cols].drop_duplicates("image_id") # drop duplicate rows based on image_id
    out = wide.merge(meta, on="image_id", how="left") # merge: use wide as base, left join meta

    cols =  meta_cols + RAW_TARGETS # reorder columns: metadata → targets(features first, then targets)
    return out[cols]

# create and save (CSV)
df_pivot = build_pivot_df(df_raw)

out_dir = Path(CFG.artifacts_dir)
out_dir.mkdir(parents=True, exist_ok=True)
csv_path = out_dir / "train_wide.csv"
df_pivot.to_csv(csv_path, index=False)

print("Saved:", csv_path)
print("Pivot shape:", df_pivot.shape)

Saved: ../artifacts/train_wide.csv
Pivot shape: (357, 12)

In [42]:

# ==================== 3. Date features (update df_pivot)====================
from datetime import datetime
# 1) Date features
df_pivot["Sampling_Date"] = pd.to_datetime(df_pivot["Sampling_Date"], format="%Y/%m/%d", errors="coerce")
df_pivot["year"] = df_pivot["Sampling_Date"].dt.year
df_pivot["month"] = df_pivot["Sampling_Date"].dt.month
df_pivot["day_of_year"] = df_pivot["Sampling_Date"].dt.dayofyear

# 2) cyclical encodings
df_pivot['month_sin'] = np.sin(2 * np.pi * df_pivot['month'] / 12)
df_pivot['month_cos'] = np.cos(2 * np.pi * df_pivot['month'] / 12)
df_pivot['day_of_year_sin'] = np.sin(2 * np.pi * df_pivot['day_of_year'] / 365.25)
df_pivot['day_of_year_cos'] = np.cos(2 * np.pi * df_pivot['day_of_year'] / 365.25)

# 3) Categorical encoding (for tabular model)
# Convert "State" and "Species" features into numbers and save the mapping relationship for use during inference!
state_cat = df_pivot["State"].astype("category")    # 1. convert to category dtype
species_cat = df_pivot["Species"].astype("category")
df_pivot["State_encoded"] = state_cat.cat.codes     # 2. extract integer code as new column
df_pivot["Species_encoded"] = species_cat.cat.codes
STATE_MAP = dict(enumerate(state_cat.cat.categories)) # 3. create mapping dicts → int to category
SPECIES_MAP = dict(enumerate(species_cat.cat.categories))

# Reorder columns: metadata → targets
feature_cols = [col for col in df_pivot.columns if col not in RAW_TARGETS]
df_pivot = df_pivot[feature_cols + RAW_TARGETS]  # reorder columns: features first, then targets

In [43]:
# ==================== 4. StratifiedKFold by Species + Dry_Total_g ====================

from sklearn.model_selection import StratifiedKFold

# 1) Build stratification labels: Species + binned Dry_Total_g
y_for_bins = df_pivot["Dry_Total_g"]
if y_for_bins.isna().any():
    y_for_bins = (
        df_pivot["Dry_Green_g"] 
        + df_pivot["Dry_Dead_g"] 
        + df_pivot["Dry_Clover_g"]
    )

# Bin Dry_Total_g into 5 quantile-based buckets
bins = pd.qcut(y_for_bins, q=5, labels=False, duplicates="drop")

# Stratification label = species name + biomass bin index
strata = df_pivot["Species"].astype(str) + "_" + bins.astype(str)

# 2) StratifiedKFold: split into 5 folds, shuffled, stratified by `strata`
#    This is what makes each fold about 357 / 5 ≈ 71 samples.
skf = StratifiedKFold(
    n_splits=CFG.n_folds,   # decide how many folds → ~71 samples per fold
    shuffle=True,
    random_state=546195, # 7499
)

folds = np.full(len(df_pivot), -1)

for fold, (_, val_idx) in enumerate(skf.split(df_pivot, y=strata)):
    folds[val_idx] = fold

df_pivot["fold"] = folds.astype(int)

# 3) Sanity check: no species should appear in only a single fold
violations = []
species_counts = df_pivot["Species"].value_counts()

for sp, total in species_counts.items():
    per_fold = df_pivot[df_pivot["Species"] == sp]["fold"].value_counts()
    for fold_id, cnt in per_fold.items():
        if cnt == total:  # if this species is entirely contained in one fold
            violations.append((sp, fold_id, int(cnt), int(total)))

if violations:
    print("[Warn] Some species only appear in a single fold:")
    for sp, f, c, tot in violations:
        print(f"  - Species={sp}, fold={f}, count={c}/{tot}")
    # If you want to enforce this as a hard constraint, you can replace the
    # prints above with: `assert not violations`

# 4) Report: distribution of Dry_Total_g in each fold (original scale)
def fold_report(df):
    tgts = ["Dry_Green_g","Dry_Dead_g","Dry_Clover_g","GDM_g","Dry_Total_g"]
    return df.groupby("fold")[tgts].agg(["mean","std","min","max","count"]).round(2)

print("\n=== Fold report (on original scale, before any log transform) ===")
display(fold_report(df_pivot))

print("\n=== Fold sizes ===")
for fold_num in range(CFG.n_folds):
    print(f"Fold {fold_num}: {(df_pivot['fold'] == fold_num).sum()} samples")

# 5) save
processed_path = Path(CFG.artifacts_dir) / "train_processed.csv"
df_pivot.to_csv(processed_path, index=False)
print("Saved processed with folds to:", processed_path)

=== Fold report (on original scale, before any log transform) ===

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

     Dry_Green_g                            Dry_Dead_g                     \
            mean    std   min     max count       mean    std  min    max
fold
0          25.67  22.78  0.00  129.34    72      13.57  15.35  0.0  83.84
1          25.85  24.08  0.00  116.75    72      11.62  12.07  0.0  50.23
2          28.72  29.14  0.00  119.60    71      10.11  11.21  0.0  53.26
3          24.88  22.17  0.31   83.93    71      13.34  11.78  0.0  46.07
4          28.04  28.56  0.00  157.98    71      11.57  11.09  0.0  52.93

            ...  GDM_g                            Dry_Total_g               \
     count  ...   mean    std   min     max count        mean    std   min
fold        ...
0       72  ...  31.24  21.65  1.40  129.34    72       44.80  28.16  6.30
1       72  ...  33.00  24.31  3.78  116.75    72       44.63  24.36  9.20
2       71  ...  36.44  27.72  1.80  119.60    71       46.54  31.75  2.48
3       71  ...  32.14  22.23  2.40   96.76    71       45.49  24.89  4.30
4       71  ...  33.59  28.45  1.04  157.98    71       45.15  30.77  1.04


        max count
fold
0     157.9    72
1     120.4    72
2     166.1    71
3     119.1    71
4     185.7    71

[5 rows x 25 columns]

=== Fold sizes ===
Fold 0: 72 samples
Fold 1: 72 samples
Fold 2: 71 samples
Fold 3: 71 samples
Fold 4: 71 samples
Saved processed with folds to: ../artifacts/train_processed.csv

In [44]:
# ==================== 5. Label transform (log1p or gram) & Save processing_config ====================

# 1) Regardless of whether the current one is used or not, calculate the *_log column first (only once)
for t in RAW_TARGETS:
    neg_ct = (df_pivot[t] < 0).sum()
    if neg_ct > 0:
        print(f"[Warn] {t} has {neg_ct} negatives; clipping to 0 before log1p.")
        df_pivot.loc[df_pivot[t] < 0, t] = 0.0
        
for t in RAW_TARGETS:
    log_col = f"{t}_log"
    if log_col not in df_pivot.columns:
        df_pivot[log_col] = np.log1p(df_pivot[t].astype("float32"))
        
# ====================        

# 2) Define a helper to switch label mode (log1p vs gram)
def set_label_mode(use_log1p: bool):
    """
    Switch the target columns used during training:
        use_log1p=True → Use the *_log columns (log1p)
        use_log1p=False → Use the original gram columns 
    """
    global TRAIN_TARGETS, label_transform
    
    if not hasattr(CFG, 'use_log1p'):
        CFG.use_log1p = False
    
    CFG.use_log1p = use_log1p

    if use_log1p:
        TRAIN_TARGETS = [f"{t}_log" for t in RAW_TARGETS]
        label_transform = "log1p"
    else:
        TRAIN_TARGETS = RAW_TARGETS
        label_transform = "identity" # 'identity' means no transform / raw grams

    print(f"[set_label_mode] use_log1p={use_log1p} → TRAIN_TARGETS =", TRAIN_TARGETS)
    print(f"[init] fallback label_transform={label_transform}")
    
# 3) Set a default mode (e.g., gram) for preprocessing/config
set_label_mode(False)  # default set to gram
# ====================

# Overwrite save (contains both raw and *_log)
processed_path = Path(CFG.artifacts_dir) / "train_processed.csv"
df_pivot.to_csv(processed_path, index=False)
print("Saved (with log columns):", processed_path)


# Assemble and save processing_config.json
processing_cfg = {
    "project_title": CFG.project_title,
    "seed": CFG.seed,
    "image_size_h": CFG.image_size_h,
    "image_size_w": CFG.image_size_w,
    "n_folds": CFG.n_folds,
    "batch_size": CFG.batch_size,
    "use_log1p": CFG.use_log1p,  # will reflect the last mode you set
    "label_transform": label_transform,
    "train_target_cols": TRAIN_TARGETS,         # train reads these columns
    "train_target_cols_raw": CORE_TARGETS,      # corresponding physical meanings
    "all_targets_raw": RAW_TARGETS,
    "artifacts_dir": CFG.artifacts_dir,
    "image_root": CFG.image_root,
    "n_samples": int(len(df_pivot)),
    "n_unique_images": int(df_pivot["image_id"].nunique()),
    "State_map": STATE_MAP,
    "Species_map": SPECIES_MAP,
}

# save json
proc_cfg_path = Path(CFG.artifacts_dir) / "processing_config.json"
proc_cfg_path.parent.mkdir(parents=True, exist_ok=True)
with open(proc_cfg_path, "w", encoding="utf-8") as f:
    json.dump(processing_cfg, f, indent=2, ensure_ascii=False)

print("Saved processing config:", proc_cfg_path)

[set_label_mode] use_log1p=False → TRAIN_TARGETS = ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
[init] fallback label_transform=identity
Saved (with log columns): ../artifacts/train_processed.csv
Saved processing config: ../artifacts/processing_config.json

In [45]:
# ==================== 6. Config & Processed Data Saving ====================

from pathlib import Path
import json
from dataclasses import asdict
import numpy as np

# 1) Define the list of metadata features to be used
METADATA_FEATURES = [
    "Pre_GSHH_NDVI",      # Pre-season NDVI from satellite
    "Height_Ave_cm",      # Average plant height in cm
    "State_encoded",      # One-hot or label-encoded growth state
    "Species_encoded",    # Encoded plant species
    "year",               # Year of observation
    'month_sin',          # Cyclic encoding of month (sin)
    'month_cos',          # Cyclic encoding of month (cos)
    'day_of_year_sin',    # Cyclic encoding of day-of-year (sin)
    'day_of_year_cos',    # Cyclic encoding of day-of-year (cos)
]

# 2) Automatically separate categorical and continuous metadata columns
META_COLS_CAT  = [col for col in METADATA_FEATURES if 'encoded' in col]   # Categorical (already encoded)
META_COLS_CONT = [col for col in METADATA_FEATURES if col not in META_COLS_CAT]  # Continuous

# 3) Apply Z-score standardization to continuous metadata features
for col in META_COLS_CONT:
    mean_val = df_pivot[col].mean()
    std_val  = df_pivot[col].std()
    
    # Avoid division by zero or NaN
    if std_val == 0 or np.isnan(std_val):
        std_val = 1.0
    
    df_pivot[col] = (df_pivot[col] - mean_val) / std_val

print(f"Standardized continuous metadata features: {META_COLS_CONT}")
print(f"Categorical (encoded) metadata features: {META_COLS_CAT}")

# 4) Build configuration dictionary and save processed data
config_dict = {
    **asdict(CFG),                    # Include all settings from CFG dataclass
    "targets": RAW_TARGETS,    
    "metadata_features": METADATA_FEATURES,
    "n_samples": len(df_pivot),
    "n_unique_images": df_pivot["image_id"].nunique(),
    "n_metadata_features": len(METADATA_FEATURES),
    "n_categorical_meta": len(META_COLS_CAT),
    "n_continuous_meta": len(META_COLS_CONT),
}

# Pretty-print the final config
print("\nFinal Configuration:")
print(json.dumps(config_dict, indent=4, default=str))

# 5) Save the processed training dataframe (with folds, normalized features, etc.)
processed_path = Path(CFG.artifacts_dir) / "train_processed.csv"
df_pivot.to_csv(processed_path, index=False)

Standardized continuous metadata features: ['Pre_GSHH_NDVI', 'Height_Ave_cm', 'year', 'month_sin', 'month_cos', 'day_of_year_sin', 'day_of_year_cos']
Categorical (encoded) metadata features: ['State_encoded', 'Species_encoded']

Final Configuration:
{
    "project_title": "CSIRO Image2Biomass Prediction",
    "seed": 42,
    "image_size_h": 224,
    "image_size_w": 448,
    "n_folds": 5,
    "batch_size": 8,
    "raw_csv": "../csiro-biomass/train.csv",
    "image_root": "../csiro-biomass",
    "artifacts_dir": "../artifacts/",
    "figs_dir": "../figs",
    "use_log1p": false,
    "targets": [
        "Dry_Green_g",
        "Dry_Dead_g",
        "Dry_Clover_g",
        "GDM_g",
        "Dry_Total_g"
    ],
    "metadata_features": [
        "Pre_GSHH_NDVI",
        "Height_Ave_cm",
        "State_encoded",
        "Species_encoded",
        "year",
        "month_sin",
        "month_cos",
        "day_of_year_sin",
        "day_of_year_cos"
    ],
    "n_samples": 357,
    "n_unique_images": 357,
    "n_metadata_features": 9,
    "n_categorical_meta": 2,
    "n_continuous_meta": 7
}

## 2. images

In [46]:

import tensorflow as tf
from tensorflow.keras import layers

# ==================== 7. Augmentation primitives ====================

class ImageAugmentor(layers.Layer):
    """
    Custom Keras Layer for random image augmentation.
    
    Supports both:
      - Rank-3 inputs: (H, W, C)   → single image
      - Rank-4 inputs: (N, H, W, C) → batch of images
      
    Designed to be used:
      - Directly inside a Keras model (as a layer)
      - Or in tf.data pipelines via .map(tfdata_augmentor)
      
    Only augments the image (x), leaves labels (y) untouched.
    """
    
    def __init__(self, 
                 color_prob=0.15,
                #  gray_prob=0.0,
                 noise_prob=0.2,
                 blur_prob=0.2,
                 flip_lr_prob=0.5,
                 flip_ud_prob=0.5,
                 rot90_prob=0.5,
                 **kwargs):
        super().__init__(**kwargs)
        
        # augmentation config: (name, probability, apply function)
        self.ops = [
            ('Hue +0.02', color_prob, 
             lambda x: tf.image.adjust_hue(x, 0.02)),
            ('Saturation x1.1', color_prob, 
             lambda x: tf.image.adjust_saturation(x, 1.1)),
            ('Brightness +0.1', color_prob, 
             lambda x: tf.image.adjust_brightness(x, 0.1)),
            ('Contrast x1.1', color_prob, 
             lambda x: tf.image.adjust_contrast(x, 1.1)),
            # ('Grayscale', gray_prob, 
            #  lambda x: tf.image.grayscale_to_rgb(tf.image.rgb_to_grayscale(x))),
            ('Noise σ=0.02', noise_prob, 
             lambda x: x + tf.random.normal(tf.shape(x), stddev=0.02)),
            ('BoxBlur 3x3', blur_prob, 
             lambda x: tf.nn.avg_pool2d(x, 3, 1, 'SAME')),
            ('Flip LR', flip_lr_prob, 
             tf.image.flip_left_right),
            ('Flip UD', flip_ud_prob, 
             tf.image.flip_up_down),
            # ('Rotate 90°', rot90_prob, 
            #  lambda x: tf.image.rot90(x, k=1)),
        ]


    def get_visualization_ops(self, include_prob=False):
        """
        Helper to visualize what augmentations are applied (useful for debugging/logging).
        """
        if include_prob:
            return [(f"{name} ({prob:.0%})", fn) for name, prob, fn in self.ops]
        return [(name, fn) for name, prob, fn in self.ops]
    
    def call(self, x, training=None):
        """
        Keras Layer: g(x) -> x_aug
        - training=True/None: apply random augmentations
        - training=False: return img unchanged
        """
        # Handle single image (H,W,C) → temporarily add batch dim
        is_single = x.shape.rank == 3
        if is_single:
            x = x[None]  # (H,W,C) -> (1,H,W,C)
            
        # Default behavior in Keras: training=None means apply augmentations
        if training is None:
            training = True 
            
        # If training is a Tensor (e.g., traced in tf.data), use tf.cond to control overall logic
        def apply_all_ops(img):
            for _, prob, fn in self.ops:
                if prob > 0:
                    img = tf.cond(
                        tf.random.uniform(()) < prob,
                        lambda: tf.clip_by_value(fn(img), 0., 1.),
                        lambda: img,
                    )
            return img

        #  when training is a Tensor
        if isinstance(training, tf.Tensor):
            x = tf.cond(
                tf.cast(training, tf.bool),
                lambda: apply_all_ops(x),
                lambda: x,
            )
        elif training:
            x = apply_all_ops(x)
            
        # Remove batch dim if input was a single image
        return x[0] if is_single else x

# Instantiate the augmentor layer (can be reused)
img_aug_layer = ImageAugmentor(name="augmentor")

# def tfdata_augmentor(x, y): # f(x, y) → (x_aug, y)
#     return img_aug_layer(x, training=True), y


def tfdata_augmentor(x, y):
    """
    Universal augmentation wrapper for tf.data pipelines.
    
    Supports two input formats:
      - Image-only: x is a Tensor (H,W,C) or (N,H,W,C)
      - Hybrid model: x is a dict with key 'image'
      
    Returns: (x_augmented, y) — labels unchanged
    """
    # Case 1: x = (image, metadata)
    if isinstance(x, dict):
        x = dict(x)  # shallow copy to avoid mutating original
        x["image"] = img_aug_layer(x["image"], training=True)
        return x, y
    # Case 2: x = image only
    else:
        x_aug = img_aug_layer(x, training=True)
        return x_aug, y


def tfdata_clip(x, y): # Numerical Safety / Clamping
    """
    Universal clipping function (ensures pixel values stay in [0, 1]).
    Works with both image-only and dict-style inputs.
    """
    if isinstance(x, dict):
        x = dict(x)
        x["image"] = tf.clip_by_value(x["image"], 0.0, 1.0)
        return x, y
    else:
        return tf.clip_by_value(x, 0.0, 1.0), y

In [47]:
# ==================== 8. BiomassImgDataModule  ====================

class BiomassImgDataModule:
    def __init__(self, 
                 fold: int = 3, 
                 target_list: list = None,
                 include_meta: bool = False):  # <--- 1. tabular switch: Teacher-True,  Student/Baseline-False
        """
        include_meta=True: return ({'image': img, 'meta_cont':..., 'meta_cat':...}, y) → to Hybrid Teacher
        
        → **Input (x)**: A dictionary containing the image and all tabular metadata.
        → **Output (y)**: The 5 core biomass targets.
        
        ---------------------------------------------------------
        
        include_meta=False: return (img, y) → to Image-Only Student/Baseline
        
        → **Input (x)**: A tensor containing only the image (One image).
        → **Output (y)**: The 5 core biomass targets.
        
        **Summary:** Each record (One sample) corresponds to 5 targets.
        """
        self.fold = fold
        self.include_meta = include_meta       # <--- 2. include tabular
        
        if target_list is None:
            target_list = TRAIN_TARGETS
        self.target_list = target_list

        self.IMG_SIZE = (CFG.image_size_h, CFG.image_size_w)

        # --------------------- Load processed data ---------------------
        pivot_path = out_dir / "train_processed.csv"
        assert pivot_path.exists(), f"Missing: {pivot_path}"
        df = pd.read_csv(pivot_path)

        # Drop rows missing any target (critical for regression)
        df = df.dropna(subset=self.target_list).reset_index(drop=True)

        self.df = df
        self.y = df[self.target_list].astype("float32").values
        
        # --------------------- Metadata preprocessing (if used) ---------------------
        if self.include_meta:
            # 1. 
            self.meta_cols_cat  = META_COLS_CAT
            self.meta_cols_cont = META_COLS_CONT

            # Fill NaN in continuous metadata (common & safe default)
            self.df[self.meta_cols_cont] = self.df[self.meta_cols_cont].fillna(0.0)
            

    def load_img(self, path: str):
        img = cv2.cvtColor(cv2.imread(path), cv2.COLOR_BGR2RGB)
        img = cv2.resize(
            img,
            (self.IMG_SIZE[1], self.IMG_SIZE[0]), 
            interpolation=cv2.INTER_AREA
        )
        return img.astype("float32") / 255.0

    def make_arrays(self):
        # imgs → N x H x W x C
        imgs = np.stack([self.load_img(p) for p in self.df["abs_image_path"]])
        return imgs

    def make_datasets(self):
        imgs = self.make_arrays()
        y = self.y # y → N x T

        val_mask = (self.df["fold"] == self.fold).values
        tr_idx = np.where(~val_mask)[0]
        va_idx = np.where(val_mask)[0]

        print(f"Fold {self.fold} | Target: {self.target_list}")
        print(f"  Train: {len(tr_idx)} images | Val: {len(va_idx)} images")

        # # tf.data datasets
        # train_ds = tf.data.Dataset.from_tensor_slices((imgs[tr_idx], y[tr_idx]))
        # val_ds   = tf.data.Dataset.from_tensor_slices((imgs[va_idx], y[va_idx]))
        
        # ==========================================
        # Core Logic: Choose input format based on whether metadata is used
        # ==========================================
        if self.include_meta:
            # Mode A: Hybrid (Teacher) -> Returns a dictionary of inputs
            # Useful for models that accept multiple inputs (image + tabular metadata)
            meta_cont = self.df[self.meta_cols_cont].astype("float32").values # (N, 7)
            meta_cat  = self.df[self.meta_cols_cat].astype("int32").values # (N, 2)
            
            # Dataset yields (dict_of_inputs, labels)
            train_inputs = {
                "image":     imgs[tr_idx],
                "meta_cont": meta_cont[tr_idx],
                "meta_cat":  meta_cat[tr_idx],
            }
            val_inputs = {
                "image":     imgs[va_idx],
                "meta_cont": meta_cont[va_idx],
                "meta_cat":  meta_cat[va_idx],
            }

            train_ds = tf.data.Dataset.from_tensor_slices((train_inputs, y[tr_idx]))
            val_ds   = tf.data.Dataset.from_tensor_slices((val_inputs,   y[va_idx]))

        else:
            # Mode B: Image Only (Baseline / Student) -> Returns Tensor
            # Simpler and faster - perfect for pure CNNs or knowledge distillation students
            train_ds = tf.data.Dataset.from_tensor_slices((imgs[tr_idx], y[tr_idx]))
            val_ds   = tf.data.Dataset.from_tensor_slices((imgs[va_idx], y[va_idx]))


        # ==========================================
        # Pipeline (for all model)
        # ==========================================
        print(f"Fold {self.fold} | Meta={self.include_meta} | Train:{len(tr_idx)} Val:{len(va_idx)}")
        
        # Create Image Data Pipeline
        train_ds = (
            train_ds
            .map(tfdata_augmentor, num_parallel_calls=1)# x passed to aug function, preprocessing + Augmentation
            .shuffle(1024, seed=CFG.seed, reshuffle_each_iteration=False) # Shuffle order
            .batch(CFG.batch_size)  # batching
            .prefetch(1) # prefetch for performance(speed up training, important!)
        )

        val_ds = (
            val_ds
            .map(tfdata_clip, num_parallel_calls=1)
            .batch(CFG.batch_size)
            .prefetch(1)
        )

        return train_ds, val_ds

In [48]:
dm = BiomassImgDataModule(fold=1)
imgs = dm.make_arrays()
print(imgs.shape)   # should be (N, 112, 224, 3)

(357, 224, 448, 3)

## 3. cnn model

In [49]:

# ==================== 9. Weighted R² metric  ====================
import numpy as np
import pandas as pd

COMP_WEIGHTS = {
   "Dry_Green_g": 0.1,
   "Dry_Dead_g": 0.1,
   "Dry_Clover_g": 0.1,
   "GDM_g": 0.2,
   "Dry_Total_g": 0.5,
}

def get_loss_weights(target_names):
    """
    Given a list of training target column names (possibly *_log),
    return the per-target weights aligned with COMP_WEIGHTS.

    Example:
        target_names = ["Dry_Green_g", "Dry_Dead_g", "Dry_Clover_g"]
        or         = ["Dry_Green_g_log", ...] in log1p mode.

    Returns:
        list[float]: weights in the same order as target_names.
    """
    base_names = [name.replace("_log", "") for name in target_names]
    return [COMP_WEIGHTS[n] for n in base_names]


# LOSS_WEIGHTS_RAW = [COMP_WEIGHTS[t] for t in RAW_TARGETS]

# get_loss_weights(TRAIN_TARGETS) = [0.1,0.1,0.1,0.2,0.5]
# Loss weights for the three core competition targets
# loss_weights = get_loss_weights(target_names)


def weighted_r2_kaggle(df_true, df_pred):
    """
    df_true, df_pred: DataFrame, with columns:
      ['Dry_Green_g','Dry_Dead_g','Dry_Clover_g','GDM_g','Dry_Total_g']
    All values are on the ORIGINAL scale (grams), no logs.
    """

    cols = ["Dry_Green_g","Dry_Dead_g","Dry_Clover_g","GDM_g","Dry_Total_g"]

    y_list, yp_list, w_list = [], [], []

    for col in cols:
        y  = df_true[col].astype("float64").values
        yp = df_pred[col].astype("float64").values
        w  = np.full_like(y, fill_value=COMP_WEIGHTS[col], dtype="float64")

        y_list.append(y)
        yp_list.append(yp)
        w_list.append(w)

    y_all  = np.concatenate(y_list)      # all (image, target) in one array
    yp_all = np.concatenate(yp_list)
    w_all  = np.concatenate(w_list)

    # Global weighted average
    y_bar_w = np.sum(w_all * y_all) / np.sum(w_all)

    ss_res = np.sum(w_all * (y_all - yp_all)**2)
    ss_tot = np.sum(w_all * (y_all - y_bar_w)**2)

    r2w = 1.0 - ss_res / (ss_tot + 1e-12)
    return float(r2w)
      

def weighted_mse_loss(weights, max_err=None):
    """Create a weighted MSE loss function.

    Args:
        weights: 1D sequence of per-target weights.
        max_err: Optional max absolute error for clipping. If None, no clipping.

    Returns:
        Callable: Loss function `loss_fn(y_true, y_pred)` for Keras.
    """
    w = tf.constant(weights, tf.float32)

    def loss_fn(y_true, y_pred):
        err = y_true - y_pred  # (B, T)
        if max_err is not None:
            # Clip the absolute value of individual errors to prevent explosion
            err = tf.clip_by_value(err, -max_err, max_err)
        err2 = tf.square(err)
        return tf.reduce_mean(err2 * w)
    return loss_fn

def eval_weighted_r2_in_gram(
        val_df: pd.DataFrame,
        y_pred_default: np.ndarray,
        model_name: str = "",
        fold: int | None = None):
    """
    Evaluate model predictions using Kaggle-style Weighted R² in gram space.

    Args:
        val_df (DataFrame): Ground-truth labels in gram units.
        y_pred_default (ndarray): Model outputs (log1p or gram), shape (N, 3).
        model_name (str, optional): Name for logging.
        fold (int, optional): Fold index for logging.

    Returns:
        tuple: (weighted_r2, pred_df, true_df)
    """
    # 1) Convert model outputs to gram space based on the current label mode. log1p → gram /  gram
    if CFG.use_log1p:
        # default outputs are log1p → convert back to grams
        y_pred_gram = np.expm1(y_pred_default)
    else:
        # default outputs are already in grams
        y_pred_gram = y_pred_default
        
    n_out = y_pred_gram.shape[1]
    
    # 2) Build prediction DataFrame depending on output dimension. # pred_df
    if n_out == 3:
         # Old behavior: model outputs 3 core targets, we derive GDM & Dry_Total
        # Extract the three core targets
        dg_p = y_pred_gram[:, 0]
        dd_p = y_pred_gram[:, 1]
        dc_p = y_pred_gram[:, 2]

        # Construct prediction DataFrame (including derived GDM / Dry_Total)
        pred_df = pd.DataFrame({
            "Dry_Green_g":  dg_p,
            "Dry_Dead_g":   dd_p,
            "Dry_Clover_g": dc_p,
        })
        pred_df["GDM_g"]       = pred_df["Dry_Green_g"] + pred_df["Dry_Clover_g"]
        pred_df["Dry_Total_g"] = pred_df["Dry_Green_g"] + pred_df["Dry_Dead_g"] + pred_df["Dry_Clover_g"]
        
    elif n_out == 5:
        # New behavior: model directly outputs 5 targets in order RAW_TARGETS
        pred_df = pd.DataFrame(
            y_pred_gram,
            columns=["Dry_Green_g",
                     "Dry_Dead_g",
                     "Dry_Clover_g",
                     "GDM_g",
                     "Dry_Total_g"]
        )
    else:
        raise ValueError(f"Expected model to output 3 or 5 targets, got shape {y_pred_gram.shape}")


    # 3) Ground truth (always in gram space)
    true_df = val_df[[
        "Dry_Green_g", "Dry_Dead_g", "Dry_Clover_g", "GDM_g", "Dry_Total_g"
    ]].copy()

    # 4) Compute Weighted R²
    w_r2 = weighted_r2_kaggle(true_df, pred_df)

    tag = f"[{model_name}] " if model_name else ""
    if fold is not None:
        print(f"{tag}Fold {fold} Kaggle-style weighted R2 = {w_r2:.4f}")
    else:
        print(f"{tag}Kaggle-style weighted R2 = {w_r2:.4f}")

    return w_r2, pred_df, true_df

In [50]:
# ==================== 10. backbone ====================
# this model, it uses ONLY pure image data — no tabular features at all!

from tensorflow.keras import layers, models, optimizers, callbacks
def make_mae_metrics(target_names):
    """
    Create overall MAE metric + per-target MAE metrics for Keras model compilation.
    
    Supports two scenarios:
    - Normal training: y_true shape = (B, T)
    - Distillation training: y_true shape = (B, 2T), 
      where the first T dimensions are ground truth labels,
      and the latter T dimensions are teacher predictions.
    """
    n_targets = len(target_names)

    def mae_all(y_true, y_pred):
        # Only evaluate on the ground truth part (first half)
        y_true_core = y_true[:, :n_targets]  
        return tf.reduce_mean(tf.abs(y_true_core - y_pred))

    mae_all.__name__ = "mae_all"
    metric_list = [mae_all]

    def make_fn(idx, name):
        def mae_i(y_true, y_pred):
            y_true_core = y_true[:, :n_targets]
            return tf.reduce_mean(tf.abs(y_true_core[:, idx] - y_pred[:, idx]))
        mae_i.__name__ = name
        return mae_i

    for i, tname in enumerate(target_names):
        metric_list.append(make_fn(i, f"mae_{tname}"))
    return metric_list


# === shared image backbone ===
def build_image_backbone(
    image_size_h: int = CFG.image_size_h,
    image_size_w: int = CFG.image_size_w,
    name: str = "ImageBackbone",
):
    """Build a basic CNN backbone for image feature extraction.

    Args:
        image_size_h: Input image height in pixels.
        image_size_w: Input image width in pixels.

    Returns:
        tf.keras.Model: CNN backbone mapping (H, W, 3) → (batch, 256) features.
    """
    
    img_shape = (image_size_h, image_size_w, 3)
    inputs = layers.Input(shape=img_shape)

    x = layers.Conv2D(16, 3, padding="same", activation=None,
                      kernel_initializer="he_normal")(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)
    x = layers.MaxPooling2D(pool_size=2)(x)  # 112x224

    x = layers.Conv2D(32, 3, padding="same", activation=None,
                      kernel_initializer="he_normal")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)
    x = layers.MaxPooling2D(pool_size=2)(x)  # 56x112

    x = layers.Conv2D(64, 3, padding="same", activation=None,
                      kernel_initializer="he_normal")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)
    x = layers.MaxPooling2D(pool_size=2)(x)  # 28x56

    x = layers.Conv2D(256, 3, padding="same", activation=None,
                      kernel_initializer="he_normal")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)
    x = layers.GlobalAveragePooling2D()(x)   # -> (batch, 256)

    backbone = models.Model(inputs=inputs, outputs=x, name=name)
    return backbone
# ==================== 11A. BiomassConvBaseline (multi-target CNN regressor) ====================
def biomass_conv_baseline(
    image_size_h: int = CFG.image_size_h, 
    image_size_w: int = CFG.image_size_w, 
    target_names: list | None = None,
) -> tf.keras.Model:
    """
    Simple CNN baseline for multi-target biomass regression.
    Input : image (H,W,3)
    Output: len(target_names) regression values.
    """
    if target_names is None:
        target_names = TRAIN_TARGETS  # default to all targets
    n_targets = len(target_names)

    # Shared image backbone, as a layer for any model
    backbone = build_image_backbone(image_size_h, image_size_w, name="ImageBackbone")
    img_inputs = layers.Input(shape=(image_size_h, image_size_w, 3), name="image")
    x = backbone(img_inputs)

    # Head: regression part
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(
        n_targets,
        activation="softplus", # Softplus to ensure non-negative outputs
        name="biomass",
        dtype="float32",
    )(x)

    model = models.Model(
        inputs=img_inputs, 
        outputs=outputs,
        name="BiomassConvBaseline"
    )

    # Loss weights for all 5 competition targets
    loss_weights = get_loss_weights(target_names)

    model.compile(
        optimizer=optimizers.Adam(1e-3),
        loss=weighted_mse_loss(loss_weights), # Custom weighted MSE (assumed defined elsewhere)
        metrics=make_mae_metrics(target_names),
    )
    return model

In [51]:
# ==================== 11.0. refers: true Mean baseline ≈ 0.24  ====================
def mean_baseline_r2_for_fold(fold: int):
    """
    Compute weighted R² for a per-fold mean target baseline.

    For the given fold, this baseline predicts the mean of each target
    (computed on the training split) for all validation samples, then
    evaluates Kaggle-style weighted R².

    Args:
        fold: Fold index to use as validation split.

    Returns:
        float: Weighted R² score for this fold.
    """
    dm = BiomassImgDataModule(fold=fold, target_list=TRAIN_TARGETS)

    val_mask  = (dm.df["fold"] == fold).values
    train_mask = ~val_mask

    train_df = dm.df[train_mask].reset_index(drop=True)
    val_df   = dm.df[val_mask].reset_index(drop=True)

    # mean of train_df (gram)
    mean_df = train_df[["Dry_Green_g","Dry_Dead_g","Dry_Clover_g"]].mean()

    n_val = len(val_df)
    pred_df = pd.DataFrame({
        "Dry_Green_g":  np.full(n_val, mean_df["Dry_Green_g"]),
        "Dry_Dead_g":   np.full(n_val, mean_df["Dry_Dead_g"]),
        "Dry_Clover_g": np.full(n_val, mean_df["Dry_Clover_g"]),
    })
    pred_df["GDM_g"]       = pred_df["Dry_Green_g"] + pred_df["Dry_Clover_g"]
    pred_df["Dry_Total_g"] = pred_df["Dry_Green_g"] + pred_df["Dry_Dead_g"] + pred_df["Dry_Clover_g"]

    true_df = val_df[[
        "Dry_Green_g","Dry_Dead_g","Dry_Clover_g","GDM_g","Dry_Total_g"
    ]].copy()

    r2 = weighted_r2_kaggle(true_df, pred_df)
    print(f"[Mean baseline] Fold {fold}: weighted R² = {r2:.4f}")
    return r2

mean_r2 = []
for f in range(CFG.n_folds):
    mean_r2.append(mean_baseline_r2_for_fold(f))

print("Mean-baseline R² per fold:", np.round(mean_r2, 3),
      "mean =", np.mean(mean_r2))

[Mean baseline] Fold 0: weighted R² = 0.2467
[Mean baseline] Fold 1: weighted R² = 0.2703
[Mean baseline] Fold 2: weighted R² = 0.2077
[Mean baseline] Fold 3: weighted R² = 0.2795
[Mean baseline] Fold 4: weighted R² = 0.2122
Mean-baseline R² per fold: [0.247 0.27  0.208 0.279 0.212] mean = 0.24327056587010784

3 target:
Mean-baseline R² per fold: [0.247 0.27  0.208 0.279 0.212] mean = 0.24327056587010784

In [52]:
# ==================== 11. one fold train generic model ====================

from tensorflow.keras import callbacks

def build_callbacks(monitor, mode):
    """Create standard training callbacks.

    Args:
        monitor: Metric name to monitor (e.g. "val_mae_all").
        mode: "min" or "max", passed to Keras callbacks.

    Returns:
        list: [EarlyStopping, ReduceLROnPlateau] callbacks.
    """
    rlr = callbacks.ReduceLROnPlateau(
        monitor=monitor,
        mode=mode,                
        factor=0.5,
        patience=2,
        min_lr=1e-6,
        verbose=1,
    )
    es = callbacks.EarlyStopping(
        monitor=monitor,
        mode=mode,
        patience=5,
        restore_best_weights=True,
        verbose=1,
    )
    return [es, rlr] # callbacks_list, early_stopping


def build_val_inputs(
    dm: BiomassImgDataModule,
    fold: int,
    include_meta: bool,
):
    """Build validation inputs for R² evaluation.

    Args:
        dm: Data module holding processed DataFrame and image arrays.
        fold: Fold index to select validation rows.
        include_meta: If True, return dict(image + metadata); otherwise images only.

    Returns:
        tuple:
            - val_df (pd.DataFrame): Validation rows in gram space.
            - x_val: Validation inputs for model.predict (tensor or dict).
    """
    # 1) Select the current fold's val df (with 5 real targets in GRAM space)
    val_mask = (dm.df["fold"] == fold).values
    val_df   = dm.df[val_mask].reset_index(drop=True)

    # 2) prepare val img array
    imgs_all = dm.make_arrays()              # (N, H, W, 3)
    imgs_val = imgs_all[val_mask]            # (N_val, H, W, 3)

    # 3)Decide the structure of x_val based on include_meta
    # include_meta=False → image-only pipeline + x_val = imgs_val
    # include_meta=False → image-only pipeline + x_val = imgs_val
    # CFG.use_log1p control log/gram
    if include_meta:
        # Teacher: image + tabular dict
        meta_cont_all = dm.df[dm.meta_cols_cont].astype("float32").values
        meta_cat_all  = dm.df[dm.meta_cols_cat ].astype("int32").values

        meta_cont_val = meta_cont_all[val_mask]
        meta_cat_val  = meta_cat_all[val_mask]

        x_val = {
            "image":     imgs_val,
            "meta_cont": meta_cont_val,
            "meta_cat":  meta_cat_val,
        }
    else:
        # Baseline: image only
        x_val = imgs_val
    return val_df, x_val


def train_one_fold_generic(
    fold,
    *,
    include_meta: bool,
    model_fn,
    model_name: str,
    target_list=None,
    **model_kwargs, #  baseline_weights_path=baseline_ckpt pass to model_fn
):
    """
    Train one fold.

    If target_list is None, default to TRAIN_TARGETS.
    When using log1p, TRAIN_TARGETS should be the *_log names if CFG.use_log1p is True.
    Args:
        fold: which fold index to use as validation.
        target_list: list of target column names; default = TRAIN_TARGETS.
        model_fn: a function that builds and returns a compiled Keras model.
                  Signature: model_fn(image_size_h, image_size_w, target_names, **model_kwargs)
        model_kwargs: extra keyword args passed to model_fn (e.g. backbone_trainable_ratio).
    Returns:
        tuple: (best_val_mae, model, history, val_ds, w_r2)
    """
    
    if target_list is None:
        target_list = TRAIN_TARGETS

    print(f"\n===== Fold {fold} =====")
    print(f"[Baseline] use_log1p={CFG.use_log1p}, target_list={target_list}")

    # ---- Choose a fold for validation and train ----
    dm = BiomassImgDataModule(
        fold=fold, 
        target_list=target_list,
        include_meta=include_meta,   # <--- baseline exclude tabular,image only
    )
    train_ds, val_ds = dm.make_datasets()
  
    # ---- create model ----
    model = model_fn( # 9A.biomass_conv_baseline
        image_size_h = CFG.image_size_h, 
        image_size_w = CFG.image_size_w,
        target_names=target_list,
        **model_kwargs,
    )
  
    # ---- callbacks ----
    callbacks_list = build_callbacks(monitor="val_mae_all", mode="min")
    
    # ---- Train fold ----
    history = model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=30,
        callbacks=callbacks_list,
        verbose=1,
    )

    # ---- Evaluate fold ----
    #  Get best val_mae_all from 5 folds history
    best_val_mae = min(history.history["val_mae_all"])
    print(f"Fold {fold} best val_mae_all = {best_val_mae:.3f}")
    
    
    # =========  Weighted R² (eval ALWAYS in gram)  ========
    # build_val_inputs + eval_weighted_r2_in_gram
    
    # 1) Construct val_df + x_val (image-only or image+meta)
    val_df, x_val = build_val_inputs(
        dm=dm,
        fold=fold,
        include_meta=include_meta,
    )

    # 2) model predict (use gram to caculate R2), if its log1p, then convert to grams if needed
    y_pred_default= model.predict(x_val, batch_size=CFG.batch_size)
                        
    # 3) Calculate R² in gram
    w_r2, pred_df, true_df = eval_weighted_r2_in_gram(
        val_df=val_df,
        y_pred_default=y_pred_default,
        model_name=model_name,
        fold=fold,
    )
    # ========================================
    return best_val_mae, model, history, val_ds, w_r2,

In [53]:
import os
os.makedirs("./ckpt", exist_ok=True)
# wrappers 
def train_one_fold_baseline(
    fold,
    target_list=None,
    model_fn=biomass_conv_baseline,
    save_ckpt: bool = False,   # 👈 
    **model_kwargs,
):
    """
    Baseline CNN: image-only model (no metadata).
    return: best_val_mae, model, history, val_ds, w_r2
    option to save fold's weight to ./ckpt/
    """
    # Use the generic fold training pipeline
    best_val_mae, model, history, val_ds, w_r2 = train_one_fold_generic(
        fold=fold,
        model_fn=model_fn,
        include_meta=False,     # image-only baseline
        target_list=target_list,   # default = TRAIN_TARGETS via set_label_mode
        model_name=f"baseline_fold{fold}",
        **model_kwargs,
    )

    # Optionally save checkpoint for initializing student later
    if save_ckpt:
        mode = "log1p" if CFG.use_log1p else "gram"  
        ckpt_path = f"./ckpt/baseline_{mode}_fold{fold}.weights.h5"
        model.save_weights(ckpt_path)
        print(f"[Baseline] fold {fold} weights saved to {ckpt_path}")

    print(f"[Baseline] fold {fold} best val_mae_all = {best_val_mae:.3f}, "
          f"weighted R² = {w_r2:.3f}")
    return best_val_mae, model, history, val_ds, w_r2

In [16]:

# ==================== 11B. train CNN Baseline (gram) ====================
set_label_mode(False)  # use gram columns as training target
include_meta: bool = False # <--- 1. tabular switch, image only for baseline

# run 5-fold CV
baseline_fold_maes_gram = []
baseline_models_gram = []
baseline_val_ds_gram = []
baseline_w_r2_gram = []

# give each fold its own random seed
set_seed(CFG.seed)

for f in range(CFG.n_folds):  # CFG.n_folds = 5
# for f in [1]:               # [x] = specific fold number you want to run 
    mae, m, history, val_ds, w_r2 = train_one_fold_baseline(f, save_ckpt=True) # stop passing target_list, instead default to TRAIN_TARGETS
    baseline_fold_maes_gram.append(mae)
    baseline_models_gram.append(m)
    baseline_val_ds_gram.append(val_ds)
    baseline_w_r2_gram.append(w_r2)

baseline_fold_maes_gram = np.array(baseline_fold_maes_gram)
print("\n===== [CNN Baseline - gram] CV summary =====")
print("val_mae_all per fold:", np.round(baseline_fold_maes_gram, 3))
print("mean ± std =", baseline_fold_maes_gram.mean(), "±", baseline_fold_maes_gram.std())
print("weighted_r2 per fold:", np.round(baseline_w_r2_gram, 3))
print("basline_gram mean R2 =", np.mean(baseline_w_r2_gram))

[set_label_mode] use_log1p=False → TRAIN_TARGETS = ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
[init] fallback label_transform=identity

===== Fold 0 =====
[Baseline] use_log1p=False, target_list=['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
Fold 0 | Target: ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
  Train: 285 images | Val: 72 images
Fold 0 | Meta=False | Train:285 Val:72
Epoch 1/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 754ms/step - loss: 301.4460 - mae__dry__clover_g: 7.0915 - mae__dry__dead_g: 10.3539 - mae__dry__green_g: 26.2679 - mae__dry__total_g: 36.4703 - mae_all: 21.5627 - mae_gdm_g: 27.6301 - val_loss: 616.6448 - val_mae__dry__clover_g: 25.3887 - val_mae__dry__dead_g: 22.0247 - val_mae__dry__green_g: 25.6285 - val_mae__dry__total_g: 66.4384 - val_mae_all: 35.4413 - val_mae_gdm_g: 37.7261 - learning_rate: 0.0010
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 143.5224 - mae__dry__clover_g: 9.0834 - mae__dry__dead_g: 9.9485 - mae__dry__green_g: 21.6666 - mae__dry__total_g: 21.7267 - mae_all: 16.0525 - mae_gdm_g: 17.8370 - val_loss: 203.9333 - val_mae__dry__clover_g: 10.2235 - val_mae__dry__dead_g: 13.2494 - val_mae__dry__green_g: 14.8149 - val_mae__dry__total_g: 33.4314 - val_mae_all: 19.7571 - val_mae_gdm_g: 27.0663 - learning_rate: 0.0010
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 104.1176 - mae__dry__clover_g: 8.3123 - mae__dry__dead_g: 9.3582 - mae__dry__green_g: 16.5632 - mae__dry__total_g: 19.1821 - mae_all: 14.0260 - mae_gdm_g: 16.7143 - val_loss: 160.0256 - val_mae__dry__clover_g: 7.5185 - val_mae__dry__dead_g: 11.7151 - val_mae__dry__green_g: 18.8310 - val_mae__dry__total_g: 28.0312 - val_mae_all: 17.9882 - val_mae_gdm_g: 23.8454 - learning_rate: 0.0010
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 753ms/step - loss: 102.5882 - mae__dry__clover_g: 8.0566 - mae__dry__dead_g: 9.4568 - mae__dry__green_g: 16.1078 - mae__dry__total_g: 18.6661 - mae_all: 13.5953 - mae_gdm_g: 15.6894 - val_loss: 430.9894 - val_mae__dry__clover_g: 10.8960 - val_mae__dry__dead_g: 14.5966 - val_mae__dry__green_g: 34.2310 - val_mae__dry__total_g: 49.6470 - val_mae_all: 30.6169 - val_mae_gdm_g: 43.7141 - learning_rate: 0.0010
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 703ms/step - loss: 91.6375 - mae__dry__clover_g: 8.7541 - mae__dry__dead_g: 9.0549 - mae__dry__green_g: 15.4015 - mae__dry__total_g: 18.2506 - mae_all: 13.4396 - mae_gdm_g: 15.7372
Epoch 5: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 96.9512 - mae__dry__clover_g: 8.2144 - mae__dry__dead_g: 9.5092 - mae__dry__green_g: 16.0045 - mae__dry__total_g: 18.1684 - mae_all: 13.5313 - mae_gdm_g: 15.7598 - val_loss: 280.5502 - val_mae__dry__clover_g: 9.1122 - val_mae__dry__dead_g: 13.1695 - val_mae__dry__green_g: 27.9375 - val_mae__dry__total_g: 38.9013 - val_mae_all: 24.5195 - val_mae_gdm_g: 33.4771 - learning_rate: 0.0010
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 95.0245 - mae__dry__clover_g: 8.1316 - mae__dry__dead_g: 9.1776 - mae__dry__green_g: 16.1002 - mae__dry__total_g: 18.4390 - mae_all: 13.4776 - mae_gdm_g: 15.5398 - val_loss: 167.7215 - val_mae__dry__clover_g: 8.4783 - val_mae__dry__dead_g: 12.1485 - val_mae__dry__green_g: 20.6883 - val_mae__dry__total_g: 28.1805 - val_mae_all: 18.5267 - val_mae_gdm_g: 23.1377 - learning_rate: 5.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 87.1099 - mae__dry__clover_g: 8.3993 - mae__dry__dead_g: 8.9481 - mae__dry__green_g: 15.4853 - mae__dry__total_g: 17.1235 - mae_all: 12.9801 - mae_gdm_g: 14.9446 - val_loss: 127.7014 - val_mae__dry__clover_g: 7.7555 - val_mae__dry__dead_g: 11.3763 - val_mae__dry__green_g: 17.5214 - val_mae__dry__total_g: 24.1458 - val_mae_all: 15.7807 - val_mae_gdm_g: 18.1046 - learning_rate: 5.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 86.1637 - mae__dry__clover_g: 8.0406 - mae__dry__dead_g: 8.9396 - mae__dry__green_g: 15.4465 - mae__dry__total_g: 17.5518 - mae_all: 12.9807 - mae_gdm_g: 14.9249 - val_loss: 107.2350 - val_mae__dry__clover_g: 7.0736 - val_mae__dry__dead_g: 10.5306 - val_mae__dry__green_g: 14.7954 - val_mae__dry__total_g: 20.0217 - val_mae_all: 13.2961 - val_mae_gdm_g: 14.0591 - learning_rate: 5.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 85.5754 - mae__dry__clover_g: 7.8992 - mae__dry__dead_g: 8.8382 - mae__dry__green_g: 14.9354 - mae__dry__total_g: 17.0750 - mae_all: 12.7208 - mae_gdm_g: 14.8563 - val_loss: 105.8503 - val_mae__dry__clover_g: 7.2634 - val_mae__dry__dead_g: 10.4491 - val_mae__dry__green_g: 15.2406 - val_mae__dry__total_g: 20.4220 - val_mae_all: 13.6543 - val_mae_gdm_g: 14.8966 - learning_rate: 5.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 86.5548 - mae__dry__clover_g: 8.0713 - mae__dry__dead_g: 8.7543 - mae__dry__green_g: 15.8799 - mae__dry__total_g: 16.9969 - mae_all: 12.9243 - mae_gdm_g: 14.9192 - val_loss: 109.2404 - val_mae__dry__clover_g: 6.6573 - val_mae__dry__dead_g: 10.4281 - val_mae__dry__green_g: 14.3971 - val_mae__dry__total_g: 20.0510 - val_mae_all: 12.9853 - val_mae_gdm_g: 13.3931 - learning_rate: 5.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 86.1526 - mae__dry__clover_g: 7.9490 - mae__dry__dead_g: 8.8809 - mae__dry__green_g: 15.8488 - mae__dry__total_g: 17.1794 - mae_all: 13.0218 - mae_gdm_g: 15.2508 - val_loss: 108.1177 - val_mae__dry__clover_g: 6.6327 - val_mae__dry__dead_g: 10.1463 - val_mae__dry__green_g: 13.9257 - val_mae__dry__total_g: 18.8678 - val_mae_all: 12.4643 - val_mae_gdm_g: 12.7491 - learning_rate: 5.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 81.9112 - mae__dry__clover_g: 7.6580 - mae__dry__dead_g: 8.6031 - mae__dry__green_g: 15.2893 - mae__dry__total_g: 16.3093 - mae_all: 12.5107 - mae_gdm_g: 14.6939 - val_loss: 103.7505 - val_mae__dry__clover_g: 6.7509 - val_mae__dry__dead_g: 10.0070 - val_mae__dry__green_g: 13.5204 - val_mae__dry__total_g: 18.2924 - val_mae_all: 12.1806 - val_mae_gdm_g: 12.3323 - learning_rate: 5.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 90.5869 - mae__dry__clover_g: 8.1003 - mae__dry__dead_g: 8.5483 - mae__dry__green_g: 15.4834 - mae__dry__total_g: 17.4352 - mae_all: 12.9615 - mae_gdm_g: 15.2403 - val_loss: 102.6765 - val_mae__dry__clover_g: 6.6500 - val_mae__dry__dead_g: 9.8470 - val_mae__dry__green_g: 13.3197 - val_mae__dry__total_g: 18.2263 - val_mae_all: 12.0272 - val_mae_gdm_g: 12.0932 - learning_rate: 5.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 81.4611 - mae__dry__clover_g: 7.9534 - mae__dry__dead_g: 8.4189 - mae__dry__green_g: 15.6456 - mae__dry__total_g: 16.2752 - mae_all: 12.5671 - mae_gdm_g: 14.5425 - val_loss: 114.8797 - val_mae__dry__clover_g: 6.2881 - val_mae__dry__dead_g: 9.7380 - val_mae__dry__green_g: 13.8190 - val_mae__dry__total_g: 18.6067 - val_mae_all: 12.1702 - val_mae_gdm_g: 12.3991 - learning_rate: 5.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 706ms/step - loss: 70.9173 - mae__dry__clover_g: 7.6105 - mae__dry__dead_g: 8.3639 - mae__dry__green_g: 13.9852 - mae__dry__total_g: 16.0792 - mae_all: 11.9154 - mae_gdm_g: 13.5381
Epoch 15: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 78.5812 - mae__dry__clover_g: 7.5448 - mae__dry__dead_g: 8.5176 - mae__dry__green_g: 15.1577 - mae__dry__total_g: 16.3375 - mae_all: 12.3825 - mae_gdm_g: 14.3549 - val_loss: 130.0152 - val_mae__dry__clover_g: 6.0875 - val_mae__dry__dead_g: 9.5199 - val_mae__dry__green_g: 14.7792 - val_mae__dry__total_g: 19.7451 - val_mae_all: 12.7955 - val_mae_gdm_g: 13.8456 - learning_rate: 5.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 80.6694 - mae__dry__clover_g: 8.1979 - mae__dry__dead_g: 8.2657 - mae__dry__green_g: 15.3557 - mae__dry__total_g: 16.0735 - mae_all: 12.5132 - mae_gdm_g: 14.6731 - val_loss: 110.6053 - val_mae__dry__clover_g: 6.2736 - val_mae__dry__dead_g: 9.3452 - val_mae__dry__green_g: 13.8058 - val_mae__dry__total_g: 18.1542 - val_mae_all: 12.0188 - val_mae_gdm_g: 12.5151 - learning_rate: 2.5000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 769ms/step - loss: 71.7172 - mae__dry__clover_g: 8.1417 - mae__dry__dead_g: 7.8054 - mae__dry__green_g: 14.6693 - mae__dry__total_g: 15.3016 - mae_all: 11.9867 - mae_gdm_g: 14.0154 - val_loss: 102.0976 - val_mae__dry__clover_g: 6.2212 - val_mae__dry__dead_g: 9.2891 - val_mae__dry__green_g: 13.3712 - val_mae__dry__total_g: 17.3813 - val_mae_all: 11.6855 - val_mae_gdm_g: 12.1646 - learning_rate: 2.5000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 786ms/step - loss: 75.6499 - mae__dry__clover_g: 7.9351 - mae__dry__dead_g: 8.2072 - mae__dry__green_g: 15.0047 - mae__dry__total_g: 15.7706 - mae_all: 12.2716 - mae_gdm_g: 14.4403 - val_loss: 101.9310 - val_mae__dry__clover_g: 6.2596 - val_mae__dry__dead_g: 9.2362 - val_mae__dry__green_g: 13.4371 - val_mae__dry__total_g: 17.5482 - val_mae_all: 11.6909 - val_mae_gdm_g: 11.9732 - learning_rate: 2.5000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 729ms/step - loss: 67.7933 - mae__dry__clover_g: 7.9541 - mae__dry__dead_g: 7.9274 - mae__dry__green_g: 14.0774 - mae__dry__total_g: 14.9686 - mae_all: 11.6572 - mae_gdm_g: 13.3583
Epoch 19: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 781ms/step - loss: 74.2214 - mae__dry__clover_g: 7.8804 - mae__dry__dead_g: 8.0245 - mae__dry__green_g: 15.0902 - mae__dry__total_g: 15.4553 - mae_all: 12.2283 - mae_gdm_g: 14.6910 - val_loss: 108.6142 - val_mae__dry__clover_g: 6.1616 - val_mae__dry__dead_g: 9.1783 - val_mae__dry__green_g: 13.6055 - val_mae__dry__total_g: 17.9803 - val_mae_all: 11.8559 - val_mae_gdm_g: 12.3537 - learning_rate: 2.5000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 771ms/step - loss: 75.8786 - mae__dry__clover_g: 7.9484 - mae__dry__dead_g: 7.9764 - mae__dry__green_g: 15.1379 - mae__dry__total_g: 15.4822 - mae_all: 12.1634 - mae_gdm_g: 14.2723 - val_loss: 90.2223 - val_mae__dry__clover_g: 6.3203 - val_mae__dry__dead_g: 9.0987 - val_mae__dry__green_g: 13.1634 - val_mae__dry__total_g: 16.5772 - val_mae_all: 11.4137 - val_mae_gdm_g: 11.9092 - learning_rate: 1.2500e-04
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 763ms/step - loss: 70.9189 - mae__dry__clover_g: 7.7947 - mae__dry__dead_g: 8.1515 - mae__dry__green_g: 15.2255 - mae__dry__total_g: 15.4571 - mae_all: 12.1118 - mae_gdm_g: 13.9305 - val_loss: 87.5807 - val_mae__dry__clover_g: 6.3092 - val_mae__dry__dead_g: 9.0765 - val_mae__dry__green_g: 13.2670 - val_mae__dry__total_g: 16.7245 - val_mae_all: 11.4678 - val_mae_gdm_g: 11.9621 - learning_rate: 1.2500e-04
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 709ms/step - loss: 67.9039 - mae__dry__clover_g: 8.2534 - mae__dry__dead_g: 8.0910 - mae__dry__green_g: 13.7481 - mae__dry__total_g: 15.2377 - mae_all: 11.6295 - mae_gdm_g: 12.8171
Epoch 22: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 75.3568 - mae__dry__clover_g: 8.1785 - mae__dry__dead_g: 8.0207 - mae__dry__green_g: 14.8954 - mae__dry__total_g: 15.6377 - mae_all: 12.1646 - mae_gdm_g: 14.0909 - val_loss: 87.8251 - val_mae__dry__clover_g: 6.3468 - val_mae__dry__dead_g: 9.0044 - val_mae__dry__green_g: 13.3149 - val_mae__dry__total_g: 16.5792 - val_mae_all: 11.4492 - val_mae_gdm_g: 12.0009 - learning_rate: 1.2500e-04
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 752ms/step - loss: 70.8400 - mae__dry__clover_g: 8.0925 - mae__dry__dead_g: 8.5638 - mae__dry__green_g: 14.4598 - mae__dry__total_g: 15.2970 - mae_all: 12.0857 - mae_gdm_g: 14.0153 - val_loss: 86.1160 - val_mae__dry__clover_g: 6.3626 - val_mae__dry__dead_g: 8.9842 - val_mae__dry__green_g: 13.1862 - val_mae__dry__total_g: 16.4728 - val_mae_all: 11.3708 - val_mae_gdm_g: 11.8480 - learning_rate: 6.2500e-05
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 74.1509 - mae__dry__clover_g: 8.1686 - mae__dry__dead_g: 8.0478 - mae__dry__green_g: 14.7763 - mae__dry__total_g: 15.6233 - mae_all: 12.0886 - mae_gdm_g: 13.8270 - val_loss: 83.9749 - val_mae__dry__clover_g: 6.4131 - val_mae__dry__dead_g: 9.0272 - val_mae__dry__green_g: 13.6023 - val_mae__dry__total_g: 16.7717 - val_mae_all: 11.6304 - val_mae_gdm_g: 12.3379 - learning_rate: 6.2500e-05
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 71.5698 - mae__dry__clover_g: 8.1717 - mae__dry__dead_g: 8.2622 - mae__dry__green_g: 14.4700 - mae__dry__total_g: 15.3230 - mae_all: 11.9688 - mae_gdm_g: 13.6170 - val_loss: 86.7095 - val_mae__dry__clover_g: 6.3494 - val_mae__dry__dead_g: 8.9198 - val_mae__dry__green_g: 13.1524 - val_mae__dry__total_g: 16.4623 - val_mae_all: 11.3322 - val_mae_gdm_g: 11.7771 - learning_rate: 6.2500e-05
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 774ms/step - loss: 71.0182 - mae__dry__clover_g: 7.8873 - mae__dry__dead_g: 7.8137 - mae__dry__green_g: 15.0658 - mae__dry__total_g: 15.0287 - mae_all: 11.9822 - mae_gdm_g: 14.1156 - val_loss: 86.5358 - val_mae__dry__clover_g: 6.3356 - val_mae__dry__dead_g: 8.9332 - val_mae__dry__green_g: 13.2184 - val_mae__dry__total_g: 16.4789 - val_mae_all: 11.3606 - val_mae_gdm_g: 11.8368 - learning_rate: 6.2500e-05
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 703ms/step - loss: 63.6602 - mae__dry__clover_g: 8.3451 - mae__dry__dead_g: 8.0430 - mae__dry__green_g: 13.4420 - mae__dry__total_g: 14.7550 - mae_all: 11.4786 - mae_gdm_g: 12.8081
Epoch 27: ReduceLROnPlateau reducing learning rate to 3.125000148429535e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 71.5220 - mae__dry__clover_g: 8.2355 - mae__dry__dead_g: 8.2246 - mae__dry__green_g: 14.6714 - mae__dry__total_g: 15.2742 - mae_all: 12.0241 - mae_gdm_g: 13.7147 - val_loss: 82.4791 - val_mae__dry__clover_g: 6.5005 - val_mae__dry__dead_g: 9.1327 - val_mae__dry__green_g: 14.1270 - val_mae__dry__total_g: 17.1107 - val_mae_all: 11.9031 - val_mae_gdm_g: 12.6443 - learning_rate: 6.2500e-05
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 766ms/step - loss: 71.7357 - mae__dry__clover_g: 7.9677 - mae__dry__dead_g: 7.9418 - mae__dry__green_g: 14.7779 - mae__dry__total_g: 15.3052 - mae_all: 11.9714 - mae_gdm_g: 13.8644 - val_loss: 82.7729 - val_mae__dry__clover_g: 6.4017 - val_mae__dry__dead_g: 8.9800 - val_mae__dry__green_g: 13.5722 - val_mae__dry__total_g: 16.6678 - val_mae_all: 11.5550 - val_mae_gdm_g: 12.1531 - learning_rate: 3.1250e-05
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 714ms/step - loss: 65.9262 - mae__dry__clover_g: 8.0296 - mae__dry__dead_g: 7.9096 - mae__dry__green_g: 13.4387 - mae__dry__total_g: 14.7238 - mae_all: 11.4458 - mae_gdm_g: 13.1274
Epoch 29: ReduceLROnPlateau reducing learning rate to 1.5625000742147677e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 766ms/step - loss: 72.5593 - mae__dry__clover_g: 7.7854 - mae__dry__dead_g: 7.9683 - mae__dry__green_g: 14.5795 - mae__dry__total_g: 15.2241 - mae_all: 11.9207 - mae_gdm_g: 14.0460 - val_loss: 83.6118 - val_mae__dry__clover_g: 6.3540 - val_mae__dry__dead_g: 8.9389 - val_mae__dry__green_g: 13.3538 - val_mae__dry__total_g: 16.5643 - val_mae_all: 11.4238 - val_mae_gdm_g: 11.9083 - learning_rate: 3.1250e-05
Epoch 30/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 759ms/step - loss: 68.9036 - mae__dry__clover_g: 8.2070 - mae__dry__dead_g: 7.9462 - mae__dry__green_g: 14.2116 - mae__dry__total_g: 14.6632 - mae_all: 11.7351 - mae_gdm_g: 13.6474 - val_loss: 83.4786 - val_mae__dry__clover_g: 6.3426 - val_mae__dry__dead_g: 8.9230 - val_mae__dry__green_g: 13.4273 - val_mae__dry__total_g: 16.5737 - val_mae_all: 11.4497 - val_mae_gdm_g: 11.9819 - learning_rate: 1.5625e-05
Epoch 30: early stopping
Restoring model weights from the end of the best epoch: 25.
Fold 0 best val_mae_all = 11.332
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 195ms/step
[baseline_fold0] Fold 0 Kaggle-style weighted R2 = 0.4264
[Baseline] fold 0 weights saved to ./ckpt/baseline_gram_fold0.weights.h5
[Baseline] fold 0 best val_mae_all = 11.332, weighted R² = 0.426

===== Fold 1 =====
[Baseline] use_log1p=False, target_list=['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
Fold 1 | Target: ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
  Train: 285 images | Val: 72 images
Fold 1 | Meta=False | Train:285 Val:72
Epoch 1/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 30s 761ms/step - loss: 265.7800 - mae__dry__clover_g: 6.6967 - mae__dry__dead_g: 10.5272 - mae__dry__green_g: 22.7158 - mae__dry__total_g: 30.8691 - mae_all: 20.3446 - mae_gdm_g: 30.9143 - val_loss: 233.8335 - val_mae__dry__clover_g: 7.3036 - val_mae__dry__dead_g: 9.1985 - val_mae__dry__green_g: 21.7775 - val_mae__dry__total_g: 29.4237 - val_mae_all: 19.6196 - val_mae_gdm_g: 30.3948 - learning_rate: 0.0010
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 141.7928 - mae__dry__clover_g: 8.1470 - mae__dry__dead_g: 10.2869 - mae__dry__green_g: 17.4566 - mae__dry__total_g: 22.2216 - mae_all: 15.4751 - mae_gdm_g: 19.2635 - val_loss: 111.9474 - val_mae__dry__clover_g: 7.7655 - val_mae__dry__dead_g: 8.5640 - val_mae__dry__green_g: 19.0644 - val_mae__dry__total_g: 20.2109 - val_mae_all: 15.0238 - val_mae_gdm_g: 19.5142 - learning_rate: 0.0010
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 126.5575 - mae__dry__clover_g: 7.5328 - mae__dry__dead_g: 10.0007 - mae__dry__green_g: 17.7939 - mae__dry__total_g: 20.7907 - mae_all: 14.6912 - mae_gdm_g: 17.3382 - val_loss: 97.3085 - val_mae__dry__clover_g: 7.7941 - val_mae__dry__dead_g: 9.6645 - val_mae__dry__green_g: 18.4855 - val_mae__dry__total_g: 19.1910 - val_mae_all: 14.7656 - val_mae_gdm_g: 18.6929 - learning_rate: 0.0010
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 758ms/step - loss: 120.4576 - mae__dry__clover_g: 7.7250 - mae__dry__dead_g: 9.8933 - mae__dry__green_g: 17.4297 - mae__dry__total_g: 20.7063 - mae_all: 14.5975 - mae_gdm_g: 17.2331 - val_loss: 112.6719 - val_mae__dry__clover_g: 8.6307 - val_mae__dry__dead_g: 10.5603 - val_mae__dry__green_g: 20.1372 - val_mae__dry__total_g: 21.9853 - val_mae_all: 16.3479 - val_mae_gdm_g: 20.4261 - learning_rate: 0.0010
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 707ms/step - loss: 103.7713 - mae__dry__clover_g: 9.1522 - mae__dry__dead_g: 9.8363 - mae__dry__green_g: 15.8371 - mae__dry__total_g: 20.1945 - mae_all: 14.2494 - mae_gdm_g: 16.2270
Epoch 5: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 758ms/step - loss: 110.7834 - mae__dry__clover_g: 7.7607 - mae__dry__dead_g: 9.8881 - mae__dry__green_g: 16.4594 - mae__dry__total_g: 19.9465 - mae_all: 14.0269 - mae_gdm_g: 16.0796 - val_loss: 103.6004 - val_mae__dry__clover_g: 8.3504 - val_mae__dry__dead_g: 9.9042 - val_mae__dry__green_g: 19.2252 - val_mae__dry__total_g: 20.6778 - val_mae_all: 15.5827 - val_mae_gdm_g: 19.7561 - learning_rate: 0.0010
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 759ms/step - loss: 103.8230 - mae__dry__clover_g: 7.4494 - mae__dry__dead_g: 9.0369 - mae__dry__green_g: 15.8344 - mae__dry__total_g: 19.1173 - mae_all: 13.4519 - mae_gdm_g: 15.8212 - val_loss: 109.7472 - val_mae__dry__clover_g: 8.8214 - val_mae__dry__dead_g: 10.6325 - val_mae__dry__green_g: 19.7469 - val_mae__dry__total_g: 21.9036 - val_mae_all: 16.2308 - val_mae_gdm_g: 20.0494 - learning_rate: 5.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 707ms/step - loss: 94.8798 - mae__dry__clover_g: 9.0072 - mae__dry__dead_g: 9.2741 - mae__dry__green_g: 16.1291 - mae__dry__total_g: 18.8581 - mae_all: 13.8291 - mae_gdm_g: 15.8768
Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.

===== [CNN Baseline - gram] CV summary =====3 target
val_mae_all per fold: [10.121 11.914 10.549 10.01  10.141]
mean ± std = 10.54708251953125 ± 0.7075833822485404
weighted_r2 per fold: [ 0.304 -0.171  0.498  0.39   0.33 ]
basline_gram mean R2 = 0.2702052972636771

===== [CNN Baseline - gram] CV summary =====5 target
val_mae_all per fold: [11.332 14.766 12.259 16.392 12.652]
mean ± std = 13.479974555969239 ± 1.8397128198302635
weighted_r2 per fold: [ 0.426  0.287  0.595 -0.147  0.351]
basline_gram mean R2 = 0.30244747404764405

In [17]:
# only to check model structure summary

baseline_model = biomass_conv_baseline( 
    image_size_h=CFG.image_size_h,
    image_size_w=CFG.image_size_w,
    target_names=RAW_TARGETS,
)
baseline_model.summary()

Model: "BiomassConvBaseline"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 224, 448, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ ImageBackbone (Functional)      │ (None, 256)            │       172,768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ biomass (Dense)                 │ (None, 5)              │           645 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 206,309 (805.89 KB)

 Trainable params: 205,573 (803.02 KB)

 Non-trainable params: 736 (2.88 KB)

____________________________________________________________________________________________________________________________________

____________________________________________________________________________________________________________________________________

Advanced Multi-Modal Biomass Prediction with Knowledge Distillation
====================================================================

Architecture Hierarchy:
1. Hybrid Teacher (Multi-Modal) - uses ALL information
2. Meta-Aware Hybrid Teacher (Enhanced) - with attention mechanisms  
3. Distilled Student (Image-Only) - deployable model
4. Ensemble Strategy - combining multiple approaches


This module implements:
✓ Hybrid Teacher with cross-modal attention
✓ Knowledge distillation framework
✓ Image-only student for deployment
✓ Progressive training pipeline
✓ Ensemble strategies

$$x = \left\{
\begin{array}{ll}
\text{"image"}: & \text{Image Tensor} \\
\text{"meta\_cont"}: & \text{Continuous Features Tensor} \\
\text{"meta\_cat"}: & \text{Categorical Features Tensor}
\end{array}
\right\}$$

In [18]:
# ==================== 12.1. Hybrid Teacher model (Dict Input-key for Multi-Modal Fusion)====================

from tensorflow.keras import models
from tensorflow.keras import layers, models, optimizers, callbacks
# Hybrid Teacher model:
# image_backbone → 256-d tensor
# meta_cont → Dense(32/64) ×2
# meta_cat → Embedding(4+4/8+8) → concat
# concat → Dense(64/128) → Dropout → Dense(3)

def biomass_hybrid_teacher(
    image_size_h: int = CFG.image_size_h,
    image_size_w: int = CFG.image_size_w,
    target_names: list | None = None,
) -> tf.keras.Model:
    """
    Hybrid Teacher:
      Input x: dict
        - x["image"]:     (H, W, 3) Image tensor.
        - x["meta_cont"]: Continuous metadata features (e.g., NDVI, Height, sine/cosine dates).
        - x["meta_cat"]:  Categorical metadata encoded [State_encoded, Species_encoded].
      Output: len(target_names) core targets (default 3).
    """
    if target_names is None:
        target_names = TRAIN_TARGETS
    n_targets = len(target_names)

    # Dictionary Inputs (Defining the expected inputs for the Keras Functional API)
    inputs = {
        "image":     layers.Input(shape=(image_size_h, image_size_w, 3), name="image"),
        "meta_cont": layers.Input(shape=(len(META_COLS_CONT),),  name="meta_cont"),
        "meta_cat":  layers.Input(shape=(len(META_COLS_CAT),), dtype="int32", name="meta_cat"),
    }

    # 1) image backbone
    # This block uses the predefined CNN structure (assumed to be similar to BiomassConvBaseline).
    backbone = build_image_backbone(image_size_h, image_size_w, name="ImageBackboneTeacher")
    img_feat = backbone(inputs["image"])   # Output: (Batch, 256) feature vector

    # 2) Continuous Features MLP Branch
    # Processes numerical (continuous) metadata features like NDVI and Height.
    cont_x = layers.Dense(64, activation="relu")(inputs["meta_cont"])  # 32->64
    cont_x = layers.BatchNormalization()(cont_x) 
    cont_x = layers.Dense(64, activation="relu")(cont_x)  # 32->64
    cont_x = layers.Dropout(0.2)(cont_x) 

    # 3) Categorical Features Embedding Branch
    # Processes encoded categorical features (State and Species).
    cat_inputs = inputs["meta_cat"]  # Input tensor shape is (batch, 2) 
    
    # Slicing the tensor to feed individual columns into separate embedding layers
    # defaultlt META_COLS_CAT = ["State_encoded", "Species_encoded"] 
    state_ids   = layers.Lambda(lambda x: x[:, 0])(cat_inputs) # State_encoded->outcome 0, 1, 2, ..., n-1 ontinuous integers
    species_ids = layers.Lambda(lambda x: x[:, 1])(cat_inputs) # Species_encoded
    
    # Define embedding dimensions
    state_emb_dim   = 8 
    species_emb_dim = 8 
    
    # Create and apply Embedding layers (converts integer codes to dense vectors)
    state_emb_layer   = layers.Embedding(len(STATE_MAP),   state_emb_dim,   name="state_emb") 
    species_emb_layer = layers.Embedding(len(SPECIES_MAP), species_emb_dim, name="species_emb")

    state_emb   = state_emb_layer(state_ids)     # Output:(batch, 8)
    species_emb = species_emb_layer(species_ids) # Output:(batch, 8)
    
    # Combine all categorical embeddings
    cat_emb = layers.Concatenate(name="cat_emb")([state_emb, species_emb])  # Output: (batch, 16)
    
    # Combine Continuous MLP output and Categorical Embeddings to form Tabular Feature Vector
    tab_x = layers.Concatenate(name="tabular_fused")([cont_x, cat_emb])

    # 4) Image + Tabular Fusion & Regression Head
    # Concatenate the high-level image features with the processed tabular features.
    fused = layers.Concatenate(name="img_tab_fusion")([img_feat, tab_x])
    
    # Final regression head MLP
    x = layers.Dense(128, activation="relu")(fused)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(
        n_targets,
        activation="softplus", # Softplus ensures non-negative biomass predictions - softplus(z) = log(1 + e^z)
        name="biomass",
        dtype="float32",
    )(x)
    
    # Construct the model
    model = models.Model(inputs=inputs, outputs=outputs, name="HybridTeacher")
    
    # 5) Compile Model
    # Reuse existing weighted loss function and MAE metrics.
    loss_weights = get_loss_weights(target_names)

    model.compile(
        optimizer=optimizers.Adam(1e-3),
        loss=weighted_mse_loss(loss_weights, max_err=200.0),
        metrics=make_mae_metrics(target_names),
    )
    return model

In [19]:

def train_one_fold_teacher(
    fold,
    target_list=None,
    model_fn=biomass_hybrid_teacher,
    **model_kwargs,
):
    """
    Hybrid Teacher: image + metadata model.
    """
    return train_one_fold_generic(
        fold=fold,
        model_fn=model_fn,
        include_meta=True,      # image + tabular
        target_list=target_list,
        model_name="Teacher",
        **model_kwargs,
    )

In [20]:

# ====== run model: Hybrid Teacher (gram)======
set_label_mode(False)  # Set label mode to "gram"
# set_label_mode(True)  # Set label mode to "log1p"

teacher_fold_maes_gram = []
teacher_models_gram = []
teacher_val_ds_gram = []
teacher_w_r2_gram = []

set_seed(CFG.seed)

for f in range(CFG.n_folds):
# for f in [1]:
    mae, m, history, val_ds, w_r2 = train_one_fold_teacher(f)
    teacher_fold_maes_gram.append(mae)
    teacher_models_gram.append(m)
    teacher_val_ds_gram.append(val_ds)
    teacher_w_r2_gram.append(w_r2)

teacher_fold_maes_gram = np.array(teacher_fold_maes_gram)
print("\n===== [Teacher] 5-fold CV summary =====")
print("val_mae_all per fold:", np.round(teacher_fold_maes_gram, 3))
print("mean ± std =", teacher_fold_maes_gram.mean(), "±", teacher_fold_maes_gram.std())
print("weighted_r2 per fold:", np.round(teacher_w_r2_gram, 3))
print("teacher mean R2 =", np.mean(teacher_w_r2_gram))

[set_label_mode] use_log1p=False → TRAIN_TARGETS = ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
[init] fallback label_transform=identity

===== Fold 0 =====
[Baseline] use_log1p=False, target_list=['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
Fold 0 | Target: ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
  Train: 285 images | Val: 72 images
Fold 0 | Meta=True | Train:285 Val:72
Epoch 1/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 30s 753ms/step - loss: 267.3400 - mae__dry__clover_g: 6.7737 - mae__dry__dead_g: 11.3246 - mae__dry__green_g: 23.0752 - mae__dry__total_g: 31.7152 - mae_all: 20.8870 - mae_gdm_g: 31.5465 - val_loss: 456.4540 - val_mae__dry__clover_g: 12.1457 - val_mae__dry__dead_g: 12.7933 - val_mae__dry__green_g: 24.8311 - val_mae__dry__total_g: 59.9353 - val_mae_all: 25.0651 - val_mae_gdm_g: 15.6202 - learning_rate: 0.0010
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 102.0738 - mae__dry__clover_g: 8.6179 - mae__dry__dead_g: 9.6863 - mae__dry__green_g: 15.6012 - mae__dry__total_g: 17.9633 - mae_all: 13.8985 - mae_gdm_g: 17.6238 - val_loss: 100.1418 - val_mae__dry__clover_g: 6.5980 - val_mae__dry__dead_g: 10.8479 - val_mae__dry__green_g: 17.6785 - val_mae__dry__total_g: 19.6686 - val_mae_all: 14.3057 - val_mae_gdm_g: 16.7352 - learning_rate: 0.0010
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 72.3857 - mae__dry__clover_g: 7.7505 - mae__dry__dead_g: 9.3688 - mae__dry__green_g: 14.3132 - mae__dry__total_g: 15.4341 - mae_all: 12.0592 - mae_gdm_g: 13.4293 - val_loss: 94.3689 - val_mae__dry__clover_g: 6.4109 - val_mae__dry__dead_g: 10.3319 - val_mae__dry__green_g: 13.5039 - val_mae__dry__total_g: 17.7430 - val_mae_all: 12.1913 - val_mae_gdm_g: 12.9669 - learning_rate: 0.0010
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 67.5885 - mae__dry__clover_g: 7.6312 - mae__dry__dead_g: 9.2807 - mae__dry__green_g: 14.2922 - mae__dry__total_g: 14.8876 - mae_all: 11.7746 - mae_gdm_g: 12.7813 - val_loss: 94.0638 - val_mae__dry__clover_g: 6.5841 - val_mae__dry__dead_g: 10.5038 - val_mae__dry__green_g: 13.0741 - val_mae__dry__total_g: 18.0377 - val_mae_all: 12.1443 - val_mae_gdm_g: 12.5217 - learning_rate: 0.0010
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 61.6677 - mae__dry__clover_g: 7.9541 - mae__dry__dead_g: 8.9515 - mae__dry__green_g: 13.5652 - mae__dry__total_g: 14.2230 - mae_all: 11.3656 - mae_gdm_g: 12.1343 - val_loss: 97.7835 - val_mae__dry__clover_g: 6.2318 - val_mae__dry__dead_g: 10.4005 - val_mae__dry__green_g: 12.2250 - val_mae__dry__total_g: 17.2683 - val_mae_all: 11.4544 - val_mae_gdm_g: 11.1463 - learning_rate: 0.0010
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 56.9473 - mae__dry__clover_g: 7.7697 - mae__dry__dead_g: 8.5982 - mae__dry__green_g: 12.4628 - mae__dry__total_g: 13.8072 - mae_all: 10.7991 - mae_gdm_g: 11.3577 - val_loss: 104.8501 - val_mae__dry__clover_g: 6.4199 - val_mae__dry__dead_g: 10.3857 - val_mae__dry__green_g: 12.5568 - val_mae__dry__total_g: 17.6859 - val_mae_all: 11.5997 - val_mae_gdm_g: 10.9501 - learning_rate: 0.0010
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 51.3013 - mae__dry__clover_g: 7.3185 - mae__dry__dead_g: 8.6945 - mae__dry__green_g: 11.9353 - mae__dry__total_g: 13.0074 - mae_all: 10.4005 - mae_gdm_g: 11.0471 - val_loss: 91.0229 - val_mae__dry__clover_g: 6.5393 - val_mae__dry__dead_g: 9.9461 - val_mae__dry__green_g: 11.9380 - val_mae__dry__total_g: 16.3638 - val_mae_all: 11.0176 - val_mae_gdm_g: 10.3010 - learning_rate: 0.0010
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 53.0853 - mae__dry__clover_g: 7.3849 - mae__dry__dead_g: 8.7468 - mae__dry__green_g: 11.2226 - mae__dry__total_g: 13.5084 - mae_all: 10.4369 - mae_gdm_g: 11.3218 - val_loss: 80.3340 - val_mae__dry__clover_g: 6.0872 - val_mae__dry__dead_g: 9.4045 - val_mae__dry__green_g: 11.5960 - val_mae__dry__total_g: 15.4744 - val_mae_all: 10.4883 - val_mae_gdm_g: 9.8792 - learning_rate: 0.0010
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 46.5020 - mae__dry__clover_g: 7.1291 - mae__dry__dead_g: 8.4394 - mae__dry__green_g: 11.4573 - mae__dry__total_g: 12.5584 - mae_all: 10.0151 - mae_gdm_g: 10.4915 - val_loss: 80.6185 - val_mae__dry__clover_g: 6.0083 - val_mae__dry__dead_g: 9.3126 - val_mae__dry__green_g: 11.6169 - val_mae__dry__total_g: 15.1154 - val_mae_all: 10.3826 - val_mae_gdm_g: 9.8599 - learning_rate: 0.0010
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 44.2417 - mae__dry__clover_g: 7.2485 - mae__dry__dead_g: 8.1376 - mae__dry__green_g: 11.3773 - mae__dry__total_g: 12.2242 - mae_all: 9.8650 - mae_gdm_g: 10.3373 - val_loss: 71.8116 - val_mae__dry__clover_g: 6.0389 - val_mae__dry__dead_g: 8.9889 - val_mae__dry__green_g: 11.1162 - val_mae__dry__total_g: 14.5694 - val_mae_all: 9.9959 - val_mae_gdm_g: 9.2661 - learning_rate: 0.0010
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 36.8080 - mae__dry__clover_g: 7.2395 - mae__dry__dead_g: 8.1550 - mae__dry__green_g: 10.1395 - mae__dry__total_g: 11.1643 - mae_all: 9.2986 - mae_gdm_g: 9.7947 - val_loss: 77.3067 - val_mae__dry__clover_g: 5.7281 - val_mae__dry__dead_g: 9.0570 - val_mae__dry__green_g: 11.1743 - val_mae__dry__total_g: 14.9762 - val_mae_all: 10.0881 - val_mae_gdm_g: 9.5048 - learning_rate: 0.0010
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 42.9583 - mae__dry__clover_g: 7.1477 - mae__dry__dead_g: 8.3546 - mae__dry__green_g: 10.2867 - mae__dry__total_g: 12.0709 - mae_all: 9.6550 - mae_gdm_g: 10.4149 - val_loss: 71.0340 - val_mae__dry__clover_g: 5.7139 - val_mae__dry__dead_g: 9.1125 - val_mae__dry__green_g: 10.7269 - val_mae__dry__total_g: 14.5706 - val_mae_all: 9.8324 - val_mae_gdm_g: 9.0382 - learning_rate: 0.0010
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 36.2296 - mae__dry__clover_g: 6.8240 - mae__dry__dead_g: 7.6193 - mae__dry__green_g: 9.7593 - mae__dry__total_g: 11.2977 - mae_all: 8.9976 - mae_gdm_g: 9.4876 - val_loss: 66.7391 - val_mae__dry__clover_g: 5.4118 - val_mae__dry__dead_g: 9.1294 - val_mae__dry__green_g: 10.6693 - val_mae__dry__total_g: 14.3549 - val_mae_all: 9.7462 - val_mae_gdm_g: 9.1655 - learning_rate: 0.0010
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 38.3460 - mae__dry__clover_g: 6.7273 - mae__dry__dead_g: 7.9048 - mae__dry__green_g: 9.9471 - mae__dry__total_g: 11.1881 - mae_all: 9.0770 - mae_gdm_g: 9.6176 - val_loss: 65.7253 - val_mae__dry__clover_g: 5.6098 - val_mae__dry__dead_g: 9.1694 - val_mae__dry__green_g: 10.2256 - val_mae__dry__total_g: 14.3375 - val_mae_all: 9.6282 - val_mae_gdm_g: 8.7984 - learning_rate: 0.0010
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 38.0889 - mae__dry__clover_g: 6.6559 - mae__dry__dead_g: 7.8102 - mae__dry__green_g: 9.5311 - mae__dry__total_g: 11.4178 - mae_all: 9.0175 - mae_gdm_g: 9.6724 - val_loss: 70.1058 - val_mae__dry__clover_g: 4.9555 - val_mae__dry__dead_g: 8.3565 - val_mae__dry__green_g: 10.7275 - val_mae__dry__total_g: 13.8998 - val_mae_all: 9.3879 - val_mae_gdm_g: 9.0004 - learning_rate: 0.0010
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 36.1383 - mae__dry__clover_g: 6.5640 - mae__dry__dead_g: 7.8409 - mae__dry__green_g: 9.9871 - mae__dry__total_g: 10.7046 - mae_all: 8.8957 - mae_gdm_g: 9.3821 - val_loss: 62.0474 - val_mae__dry__clover_g: 5.0362 - val_mae__dry__dead_g: 9.0109 - val_mae__dry__green_g: 9.9897 - val_mae__dry__total_g: 13.8165 - val_mae_all: 9.3124 - val_mae_gdm_g: 8.7085 - learning_rate: 0.0010
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 35.6848 - mae__dry__clover_g: 6.6136 - mae__dry__dead_g: 7.6958 - mae__dry__green_g: 9.4201 - mae__dry__total_g: 10.7857 - mae_all: 8.6774 - mae_gdm_g: 8.8720 - val_loss: 68.3163 - val_mae__dry__clover_g: 5.4763 - val_mae__dry__dead_g: 8.3580 - val_mae__dry__green_g: 10.2863 - val_mae__dry__total_g: 13.7429 - val_mae_all: 9.2646 - val_mae_gdm_g: 8.4595 - learning_rate: 0.0010
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 35.1388 - mae__dry__clover_g: 6.5624 - mae__dry__dead_g: 7.5062 - mae__dry__green_g: 9.5269 - mae__dry__total_g: 10.7306 - mae_all: 8.6338 - mae_gdm_g: 8.8430 - val_loss: 60.6569 - val_mae__dry__clover_g: 4.9399 - val_mae__dry__dead_g: 8.3650 - val_mae__dry__green_g: 9.4818 - val_mae__dry__total_g: 13.4229 - val_mae_all: 8.8998 - val_mae_gdm_g: 8.2896 - learning_rate: 0.0010
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 31.5760 - mae__dry__clover_g: 6.5455 - mae__dry__dead_g: 7.3117 - mae__dry__green_g: 9.0938 - mae__dry__total_g: 10.6379 - mae_all: 8.4200 - mae_gdm_g: 8.5111 - val_loss: 70.1850 - val_mae__dry__clover_g: 4.4738 - val_mae__dry__dead_g: 10.9875 - val_mae__dry__green_g: 10.1103 - val_mae__dry__total_g: 15.8709 - val_mae_all: 10.0512 - val_mae_gdm_g: 8.8136 - learning_rate: 0.0010
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 700ms/step - loss: 33.2573 - mae__dry__clover_g: 6.0807 - mae__dry__dead_g: 7.6959 - mae__dry__green_g: 9.1367 - mae__dry__total_g: 10.7931 - mae_all: 8.3397 - mae_gdm_g: 7.9923
Epoch 20: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 32.9028 - mae__dry__clover_g: 6.2472 - mae__dry__dead_g: 7.6305 - mae__dry__green_g: 9.2993 - mae__dry__total_g: 10.5245 - mae_all: 8.4438 - mae_gdm_g: 8.5175 - val_loss: 62.7354 - val_mae__dry__clover_g: 4.5865 - val_mae__dry__dead_g: 9.5171 - val_mae__dry__green_g: 9.5439 - val_mae__dry__total_g: 14.3853 - val_mae_all: 9.2768 - val_mae_gdm_g: 8.3512 - learning_rate: 0.0010
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 30.8569 - mae__dry__clover_g: 5.9358 - mae__dry__dead_g: 7.3736 - mae__dry__green_g: 9.2830 - mae__dry__total_g: 10.2415 - mae_all: 8.2063 - mae_gdm_g: 8.1974 - val_loss: 63.6012 - val_mae__dry__clover_g: 5.1624 - val_mae__dry__dead_g: 8.6148 - val_mae__dry__green_g: 9.5317 - val_mae__dry__total_g: 14.8170 - val_mae_all: 9.4750 - val_mae_gdm_g: 9.2489 - learning_rate: 5.0000e-04
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 697ms/step - loss: 28.5062 - mae__dry__clover_g: 6.0742 - mae__dry__dead_g: 7.1936 - mae__dry__green_g: 8.3362 - mae__dry__total_g: 10.1533 - mae_all: 7.8713 - mae_gdm_g: 7.5991
Epoch 22: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 30.3526 - mae__dry__clover_g: 6.1126 - mae__dry__dead_g: 7.2252 - mae__dry__green_g: 8.9765 - mae__dry__total_g: 10.3352 - mae_all: 8.2106 - mae_gdm_g: 8.4037 - val_loss: 65.3444 - val_mae__dry__clover_g: 5.3813 - val_mae__dry__dead_g: 8.0353 - val_mae__dry__green_g: 9.4423 - val_mae__dry__total_g: 13.9923 - val_mae_all: 9.1681 - val_mae_gdm_g: 8.9891 - learning_rate: 5.0000e-04
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 29.1007 - mae__dry__clover_g: 6.1109 - mae__dry__dead_g: 7.2173 - mae__dry__green_g: 9.0906 - mae__dry__total_g: 10.0430 - mae_all: 8.2113 - mae_gdm_g: 8.5950 - val_loss: 59.7691 - val_mae__dry__clover_g: 4.8198 - val_mae__dry__dead_g: 8.3146 - val_mae__dry__green_g: 9.1186 - val_mae__dry__total_g: 13.2521 - val_mae_all: 8.7489 - val_mae_gdm_g: 8.2397 - learning_rate: 2.5000e-04
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 29.1103 - mae__dry__clover_g: 5.9366 - mae__dry__dead_g: 6.8219 - mae__dry__green_g: 8.7155 - mae__dry__total_g: 9.8743 - mae_all: 7.9098 - mae_gdm_g: 8.2008 - val_loss: 60.7913 - val_mae__dry__clover_g: 4.8937 - val_mae__dry__dead_g: 7.9923 - val_mae__dry__green_g: 9.1647 - val_mae__dry__total_g: 13.0097 - val_mae_all: 8.6793 - val_mae_gdm_g: 8.3360 - learning_rate: 2.5000e-04
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 28.6411 - mae__dry__clover_g: 6.1083 - mae__dry__dead_g: 7.1192 - mae__dry__green_g: 8.7681 - mae__dry__total_g: 9.9064 - mae_all: 7.9863 - mae_gdm_g: 8.0295 - val_loss: 61.7043 - val_mae__dry__clover_g: 4.9509 - val_mae__dry__dead_g: 8.0686 - val_mae__dry__green_g: 9.1782 - val_mae__dry__total_g: 13.1723 - val_mae_all: 8.7609 - val_mae_gdm_g: 8.4348 - learning_rate: 2.5000e-04
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 698ms/step - loss: 27.7913 - mae__dry__clover_g: 6.0684 - mae__dry__dead_g: 6.9947 - mae__dry__green_g: 8.1183 - mae__dry__total_g: 9.8264 - mae_all: 7.7021 - mae_gdm_g: 7.5028
Epoch 26: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 27.5236 - mae__dry__clover_g: 5.8479 - mae__dry__dead_g: 6.8685 - mae__dry__green_g: 8.6477 - mae__dry__total_g: 9.5200 - mae_all: 7.7051 - mae_gdm_g: 7.6414 - val_loss: 63.7165 - val_mae__dry__clover_g: 5.1534 - val_mae__dry__dead_g: 7.9841 - val_mae__dry__green_g: 9.1876 - val_mae__dry__total_g: 13.2763 - val_mae_all: 8.8618 - val_mae_gdm_g: 8.7077 - learning_rate: 2.5000e-04
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 25.4453 - mae__dry__clover_g: 5.8403 - mae__dry__dead_g: 6.7483 - mae__dry__green_g: 8.4196 - mae__dry__total_g: 9.3658 - mae_all: 7.7323 - mae_gdm_g: 8.2875 - val_loss: 62.2298 - val_mae__dry__clover_g: 5.0576 - val_mae__dry__dead_g: 8.1098 - val_mae__dry__green_g: 9.1732 - val_mae__dry__total_g: 13.4664 - val_mae_all: 8.9005 - val_mae_gdm_g: 8.6955 - learning_rate: 1.2500e-04
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 696ms/step - loss: 28.0174 - mae__dry__clover_g: 6.3065 - mae__dry__dead_g: 7.0094 - mae__dry__green_g: 8.5192 - mae__dry__total_g: 10.1120 - mae_all: 8.0122 - mae_gdm_g: 8.1138
Epoch 28: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 28.4719 - mae__dry__clover_g: 6.0947 - mae__dry__dead_g: 6.9709 - mae__dry__green_g: 8.5854 - mae__dry__total_g: 9.7928 - mae_all: 7.9720 - mae_gdm_g: 8.4163 - val_loss: 61.9090 - val_mae__dry__clover_g: 5.0245 - val_mae__dry__dead_g: 8.0136 - val_mae__dry__green_g: 9.1942 - val_mae__dry__total_g: 13.0286 - val_mae_all: 8.7168 - val_mae_gdm_g: 8.3232 - learning_rate: 1.2500e-04
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 24.9441 - mae__dry__clover_g: 5.7963 - mae__dry__dead_g: 6.9066 - mae__dry__green_g: 8.2367 - mae__dry__total_g: 8.9101 - mae_all: 7.5264 - mae_gdm_g: 7.7821 - val_loss: 60.8556 - val_mae__dry__clover_g: 4.9012 - val_mae__dry__dead_g: 8.0213 - val_mae__dry__green_g: 9.1420 - val_mae__dry__total_g: 13.1014 - val_mae_all: 8.7063 - val_mae_gdm_g: 8.3659 - learning_rate: 6.2500e-05
Epoch 29: early stopping
Restoring model weights from the end of the best epoch: 24.
Fold 0 best val_mae_all = 8.679
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 192ms/step
[Teacher] Fold 0 Kaggle-style weighted R2 = 0.5978

===== Fold 1 =====
[Baseline] use_log1p=False, target_list=['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
Fold 1 | Target: ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
  Train: 285 images | Val: 72 images
Fold 1 | Meta=True | Train:285 Val:72
Epoch 1/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 30s 753ms/step - loss: 246.1961 - mae__dry__clover_g: 6.8358 - mae__dry__dead_g: 11.3707 - mae__dry__green_g: 21.5422 - mae__dry__total_g: 29.0203 - mae_all: 19.7887 - mae_gdm_g: 30.1743 - val_loss: 258.3230 - val_mae__dry__clover_g: 12.4954 - val_mae__dry__dead_g: 7.8372 - val_mae__dry__green_g: 23.9507 - val_mae__dry__total_g: 38.4352 - val_mae_all: 20.6095 - val_mae_gdm_g: 20.3291 - learning_rate: 0.0010
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 777ms/step - loss: 105.5668 - mae__dry__clover_g: 7.8594 - mae__dry__dead_g: 9.7227 - mae__dry__green_g: 15.8806 - mae__dry__total_g: 18.9685 - mae_all: 13.7353 - mae_gdm_g: 16.2453 - val_loss: 120.1613 - val_mae__dry__clover_g: 7.8718 - val_mae__dry__dead_g: 8.3245 - val_mae__dry__green_g: 21.5894 - val_mae__dry__total_g: 21.6694 - val_mae_all: 16.3013 - val_mae_gdm_g: 22.0513 - learning_rate: 0.0010
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 81.5590 - mae__dry__clover_g: 7.6515 - mae__dry__dead_g: 9.7208 - mae__dry__green_g: 14.5032 - mae__dry__total_g: 16.5178 - mae_all: 12.4467 - mae_gdm_g: 13.8400 - val_loss: 121.2114 - val_mae__dry__clover_g: 6.9441 - val_mae__dry__dead_g: 8.4569 - val_mae__dry__green_g: 16.9397 - val_mae__dry__total_g: 20.6017 - val_mae_all: 14.0824 - val_mae_gdm_g: 17.4697 - learning_rate: 0.0010
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 75.6906 - mae__dry__clover_g: 7.1977 - mae__dry__dead_g: 9.3351 - mae__dry__green_g: 14.1949 - mae__dry__total_g: 15.8441 - mae_all: 11.8950 - mae_gdm_g: 12.9030 - val_loss: 116.4010 - val_mae__dry__clover_g: 6.9551 - val_mae__dry__dead_g: 8.9442 - val_mae__dry__green_g: 16.5870 - val_mae__dry__total_g: 20.3679 - val_mae_all: 13.8721 - val_mae_gdm_g: 16.5061 - learning_rate: 0.0010
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 763ms/step - loss: 63.9375 - mae__dry__clover_g: 7.3200 - mae__dry__dead_g: 9.4899 - mae__dry__green_g: 13.0231 - mae__dry__total_g: 14.6986 - mae_all: 11.2789 - mae_gdm_g: 11.8630 - val_loss: 86.5992 - val_mae__dry__clover_g: 7.2194 - val_mae__dry__dead_g: 8.9421 - val_mae__dry__green_g: 14.5721 - val_mae__dry__total_g: 16.9519 - val_mae_all: 12.1999 - val_mae_gdm_g: 13.3137 - learning_rate: 0.0010
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 770ms/step - loss: 59.5850 - mae__dry__clover_g: 7.1235 - mae__dry__dead_g: 9.1556 - mae__dry__green_g: 12.8442 - mae__dry__total_g: 14.1050 - mae_all: 11.0433 - mae_gdm_g: 11.9881 - val_loss: 85.3194 - val_mae__dry__clover_g: 7.2991 - val_mae__dry__dead_g: 9.0257 - val_mae__dry__green_g: 14.4612 - val_mae__dry__total_g: 17.2558 - val_mae_all: 12.2973 - val_mae_gdm_g: 13.4445 - learning_rate: 0.0010
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 729ms/step - loss: 64.9102 - mae__dry__clover_g: 8.0573 - mae__dry__dead_g: 9.3911 - mae__dry__green_g: 13.2419 - mae__dry__total_g: 14.8067 - mae_all: 11.4074 - mae_gdm_g: 11.5400
Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 780ms/step - loss: 60.5298 - mae__dry__clover_g: 6.8757 - mae__dry__dead_g: 9.0312 - mae__dry__green_g: 12.4247 - mae__dry__total_g: 14.1738 - mae_all: 10.7162 - mae_gdm_g: 11.0755 - val_loss: 89.4273 - val_mae__dry__clover_g: 7.2341 - val_mae__dry__dead_g: 8.8120 - val_mae__dry__green_g: 14.8510 - val_mae__dry__total_g: 17.5919 - val_mae_all: 12.7236 - val_mae_gdm_g: 15.1292 - learning_rate: 0.0010
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 764ms/step - loss: 58.1467 - mae__dry__clover_g: 6.7414 - mae__dry__dead_g: 8.9019 - mae__dry__green_g: 11.5552 - mae__dry__total_g: 13.4511 - mae_all: 10.4138 - mae_gdm_g: 11.4195 - val_loss: 61.8404 - val_mae__dry__clover_g: 7.0824 - val_mae__dry__dead_g: 8.6700 - val_mae__dry__green_g: 12.6617 - val_mae__dry__total_g: 14.0782 - val_mae_all: 10.8256 - val_mae_gdm_g: 11.6357 - learning_rate: 5.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 782ms/step - loss: 52.3475 - mae__dry__clover_g: 6.7647 - mae__dry__dead_g: 9.3209 - mae__dry__green_g: 11.4202 - mae__dry__total_g: 13.2163 - mae_all: 10.2983 - mae_gdm_g: 10.7692 - val_loss: 56.1298 - val_mae__dry__clover_g: 7.2216 - val_mae__dry__dead_g: 8.8285 - val_mae__dry__green_g: 12.0139 - val_mae__dry__total_g: 13.7905 - val_mae_all: 10.4676 - val_mae_gdm_g: 10.4834 - learning_rate: 5.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 781ms/step - loss: 51.0245 - mae__dry__clover_g: 6.6585 - mae__dry__dead_g: 8.4339 - mae__dry__green_g: 11.2924 - mae__dry__total_g: 12.8329 - mae_all: 9.9932 - mae_gdm_g: 10.7483 - val_loss: 51.7123 - val_mae__dry__clover_g: 7.2092 - val_mae__dry__dead_g: 8.9188 - val_mae__dry__green_g: 11.3581 - val_mae__dry__total_g: 13.5150 - val_mae_all: 10.1358 - val_mae_gdm_g: 9.6779 - learning_rate: 5.0000e-04
Epoch 11/30

===== [Teacher] 5-fold CV summary =====
val_mae_all per fold: [7.32  6.695 6.755 7.598 7.319]
mean ± std = 7.137342548370361 ± 0.35214325238677197
weighted_r2 per fold: [0.531 0.741 0.824 0.672 0.728]
teacher mean R2 = 0.6991199103874223

===== [Teacher] 5-fold CV summary =====
val_mae_all per fold: [8.679 8.835 7.733 8.014 8.233]
mean ± std = 8.299013805389404 ± 0.40934585632045123
weighted_r2 per fold: [0.598 0.702 0.855 0.742 0.802]
teacher mean R2 = 0.7396731941512208

In [21]:
# only to check model structure summary

teacher_model = biomass_hybrid_teacher( 
    image_size_h=CFG.image_size_h,
    image_size_w=CFG.image_size_w,
    target_names=RAW_TARGETS,
)
teacher_model.summary()

Model: "HybridTeacher"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ meta_cont           │ (None, 7)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_21 (Dense)    │ (None, 64)        │        512 │ meta_cont[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ meta_cat            │ (None, 2)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 64)        │        256 │ dense_21[0][0]    │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lambda_10 (Lambda)  │ (None)            │          0 │ meta_cat[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lambda_11 (Lambda)  │ (None)            │          0 │ meta_cat[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_22 (Dense)    │ (None, 64)        │      4,160 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ state_emb           │ (None, 8)         │         32 │ lambda_10[0][0]   │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ species_emb         │ (None, 8)         │        120 │ lambda_11[0][0]   │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ image (InputLayer)  │ (None, 224, 448,  │          0 │ -                 │
│                     │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_16          │ (None, 64)        │          0 │ dense_22[0][0]    │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ cat_emb             │ (None, 16)        │          0 │ state_emb[0][0],  │
│ (Concatenate)       │                   │            │ species_emb[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ ImageBackboneTeach… │ (None, 256)       │    172,768 │ image[0][0]       │
│ (Functional)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ tabular_fused       │ (None, 80)        │          0 │ dropout_16[0][0], │
│ (Concatenate)       │                   │            │ cat_emb[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ img_tab_fusion      │ (None, 336)       │          0 │ ImageBackboneTea… │
│ (Concatenate)       │                   │            │ tabular_fused[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_23 (Dense)    │ (None, 128)       │     43,136 │ img_tab_fusion[0… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_17          │ (None, 128)       │          0 │ dense_23[0][0]    │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ biomass (Dense)     │ (None, 5)         │        645 │ dropout_17[0][0]  │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 221,629 (865.74 KB)

 Trainable params: 220,765 (862.36 KB)

 Non-trainable params: 864 (3.38 KB)

____________________________________________________________________________________________________________________________________

In [54]:

# ==================== 12.2. Student model ====================
# Distillation Loss for Student(image-only)
def distillation_loss(
    target_names,
    alpha=0.4,      # weight for teacher loss  alpha ∈ {0.2, 0.3, 0.5}  
    tau=1.0,        # temperature for distillation
):
    """Create a distillation loss combining GT and teacher predictions.

    Args:
        alpha: Weight of the teacher term in the final loss
            (0 → pure GT, 1 → pure teacher).
        tau: Temperature used to soften student/teacher outputs.
        n_targets: Number of target dimensions.

    Returns:
        Callable: Loss function `loss_fn(y_true_concat, y_pred)` where
        `y_true_concat = [y_gt, y_teacher]` along the last dimension.
        
    Note:
    mse_distill ≈ (1 / tau**2) * MSE(y_pred, y_teacher)
    So the effective weights are:
    Loss ≈ (1 - alpha) * L_gt + alpha / (tau**2) * L_teacher
    """
    
    n_targets = len(target_names)
    loss_weights = tf.constant(get_loss_weights(target_names), tf.float32)

    def loss_fn(y_true_concat, y_pred):
        # Split ground truth and teacher predictions
        y_true    = y_true_concat[:, :n_targets]
        y_teacher = y_true_concat[:, n_targets:]
        
        # Student vs GT weighted MSE
        err_gt = tf.square(y_pred - y_true)
        mse_gt = tf.reduce_mean(err_gt * loss_weights, axis=-1) 
        
        # Student vs teacher weighted MSE (with temperature)
        y_pred_t    = y_pred    / tau
        y_teacher_t = y_teacher / tau
        err_distill = tf.square(y_pred_t - y_teacher_t)
        mse_distill = tf.reduce_mean(err_distill * loss_weights, axis=-1) 
        
        # Total loss = (1 - alpha) * GT + alpha * teacher
        return (1.0 - alpha) * mse_gt + alpha * mse_distill

    return loss_fn

In [23]:
def biomass_student_from_baseline(
    image_size_h: int = CFG.image_size_h, 
    image_size_w: int = CFG.image_size_w, 
    target_names: list | None = None,
    baseline_weights_path: str | None = None,
    distill_alpha: float = 0.4,
     distill_tau: float = 1.0, 
    use_distill_loss: bool = True,
) -> tf.keras.Model:
    """Build the student CNN model initialized from the baseline backbone.

    The student is an image-only CNN. Optionally, it:
      * Loads backbone weights from a pre-trained baseline model.
      * Uses a distillation loss that mixes GT and teacher predictions.

    Args:
        image_size_h: Input image height in pixels.
        image_size_w: Input image width in pixels.
        target_names: List of target column names; if None, defaults to TRAIN_TARGETS.
        baseline_weights_path: Optional path to baseline model weights (.h5). If
            provided, the student backbone is initialized from these weights.
        distill_alpha: Weight of the teacher term in the distillation loss.
        distill_tau: Temperature for the distillation loss.
        use_distill_loss: If True, use distillation loss; otherwise, use
            weighted MSE on ground-truth only.

    Returns:
        tf.keras.Model: Compiled student model ready for training.
    """
    if target_names is None:
        target_names = TRAIN_TARGETS
    n_targets = len(target_names)

    # 1) Student backbone (image-only)
    backbone = build_image_backbone(image_size_h, image_size_w, name="ImageBackboneStudent")
    img_inputs = layers.Input(shape=(image_size_h, image_size_w, 3), name="image")
    x = backbone(img_inputs)

    # 2) Regression head (can mirror baseline or be slightly deeper)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.3)(x)
    # Optionally add another layer:
    # x = layers.Dense(64, activation="relu")(x)
    # x = layers.Dropout(0.2)(x)

    outputs = layers.Dense(
        n_targets,
        activation="softplus",
        name="biomass",
        dtype="float32",
    )(x)

    model = models.Model(
        inputs=img_inputs, outputs=outputs, name="StudentFromBaseline"
    )

    # 3) If baseline weights are provided, copy its backbone weights
    if baseline_weights_path is not None:
        print(f"[Student] load baseline backbone from {baseline_weights_path}")
        # Create a temporary baseline model to load weights into
        baseline_tmp = biomass_conv_baseline(
            image_size_h=image_size_h,
            image_size_w=image_size_w,
            target_names=target_names,
        )
        baseline_tmp.load_weights(baseline_weights_path)

        # Extract backbones
        baseline_backbone = baseline_tmp.get_layer("ImageBackbone")
        student_backbone  = model.get_layer("ImageBackboneStudent")

         # Copy CNN backbone parameters
        student_backbone.set_weights(baseline_backbone.get_weights())
        print("[Student] backbone weights copied from baseline")

        # Free the temporary model
        del baseline_tmp

     # 4) Choose loss: distillation vs pure GT (weighted MSE)
    loss_weights = get_loss_weights(target_names)

    if use_distill_loss:
        # this alpha = “teacher w”
        loss_fn = distillation_loss(
            alpha=distill_alpha,
            tau=distill_tau,  
            target_names=target_names,
        )
    else:
        loss_fn = weighted_mse_loss(loss_weights, max_err=200.0)

    model.compile(
        optimizer=optimizers.Adam(1e-4),   # Finetuning LR is smaller than baseline
        loss=loss_fn,
        metrics=make_mae_metrics(target_names),
    )
    return model

In [ ]:
def run_one_fold_student_from_baseline_no_distill(fold):
    """Train a student initialized from baseline backbone without distillation.

    The student backbone is initialized from the baseline checkpoint and then
    trained using only ground-truth supervision (no distillation loss).

    Args:
        fold: Fold index used as validation split.

    Returns:
        tuple: (best_val_mae, model, history, val_ds, w_r2)
    """
    baseline_ckpt = f"./ckpt/baseline_gram_fold{fold}.weights.h5"
    
    best_val_mae, model, history, val_ds, w_r2 = train_one_fold_generic(
        fold=fold,
        include_meta=False,   # student is also image-only
        model_fn=biomass_student_from_baseline,
        model_name=f"student_from_baseline_fold{fold}",
        baseline_weights_path=baseline_ckpt,
        distill_alpha=0.0,
        use_distill_loss=False,   # no distillation/teacher loss here
    )
    return best_val_mae, model, history, val_ds, w_r2

In [ ]:
# ====== Train model: no-Distilled Student (image only)(gram) ======
set_label_mode(False)  # Set label mode to "gram"
# set_label_mode(True)  # Set label mode to "log1p"

student_results_gram_no_distill = {}
student_fold_maes_gram_no_distill = []
student_fold_r2_gram_no_distill = []

set_seed(CFG.seed)

for f in range(CFG.n_folds):
    
    student_mae, student_model, student_hist, student_valds, student_r2 = \
        run_one_fold_student_from_baseline_no_distill(
            fold=f,
            # teacher_model=teacher_models_gram[f],   # trained teacher
            # alpha=0.0,
            # tau=5.0,
        )
    student_results_gram_no_distill[f] = (student_mae, student_r2)
    student_fold_maes_gram_no_distill.append(student_mae)
    student_fold_r2_gram_no_distill.append(student_r2)

print("\n===== [Student Distill] 5-fold CV summary =====")
print("MAE per fold:", np.round(student_fold_maes_gram_no_distill, 3))
print("R2  per fold:", np.round(student_fold_r2_gram_no_distill, 3))
print("mean R2 =", np.mean(student_fold_r2_gram_no_distill))

[set_label_mode] use_log1p=False → TRAIN_TARGETS = ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
[init] fallback label_transform=identity

===== Fold 0 =====
[Baseline] use_log1p=False, target_list=['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
Fold 0 | Target: ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
  Train: 285 images | Val: 72 images
Fold 0 | Meta=False | Train:285 Val:72
[Student] load baseline backbone from ./ckpt/baseline_gram_fold0.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 30s 782ms/step - loss: 372.2223 - mae__dry__clover_g: 6.7088 - mae__dry__dead_g: 11.2861 - mae__dry__green_g: 26.4120 - mae__dry__total_g: 43.8675 - mae_all: 23.9814 - mae_gdm_g: 31.6327 - val_loss: 352.9891 - val_mae__dry__clover_g: 5.6177 - val_mae__dry__dead_g: 13.1163 - val_mae__dry__green_g: 25.2714 - val_mae__dry__total_g: 43.5591 - val_mae_all: 23.4189 - val_mae_gdm_g: 29.5299 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 777ms/step - loss: 348.5136 - mae__dry__clover_g: 6.6447 - mae__dry__dead_g: 11.1275 - mae__dry__green_g: 26.4756 - mae__dry__total_g: 41.8342 - mae_all: 23.4083 - mae_gdm_g: 30.9596 - val_loss: 338.1452 - val_mae__dry__clover_g: 5.6046 - val_mae__dry__dead_g: 12.9674 - val_mae__dry__green_g: 25.2811 - val_mae__dry__total_g: 42.1340 - val_mae_all: 23.0736 - val_mae_gdm_g: 29.3808 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 778ms/step - loss: 321.1686 - mae__dry__clover_g: 6.7450 - mae__dry__dead_g: 10.8605 - mae__dry__green_g: 26.5260 - mae__dry__total_g: 39.2669 - mae_all: 22.7164 - mae_gdm_g: 30.1836 - val_loss: 307.0889 - val_mae__dry__clover_g: 5.6638 - val_mae__dry__dead_g: 12.7840 - val_mae__dry__green_g: 25.3910 - val_mae__dry__total_g: 39.0698 - val_mae_all: 22.2340 - val_mae_gdm_g: 28.2614 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 779ms/step - loss: 295.5171 - mae__dry__clover_g: 6.8371 - mae__dry__dead_g: 10.7099 - mae__dry__green_g: 26.5110 - mae__dry__total_g: 36.5383 - mae_all: 22.0246 - mae_gdm_g: 29.5267 - val_loss: 260.3176 - val_mae__dry__clover_g: 5.8634 - val_mae__dry__dead_g: 12.3749 - val_mae__dry__green_g: 25.4728 - val_mae__dry__total_g: 33.9113 - val_mae_all: 20.7521 - val_mae_gdm_g: 26.1380 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 780ms/step - loss: 264.4492 - mae__dry__clover_g: 7.1907 - mae__dry__dead_g: 10.2959 - mae__dry__green_g: 26.4740 - mae__dry__total_g: 33.4227 - mae_all: 21.0922 - mae_gdm_g: 28.0774 - val_loss: 215.9895 - val_mae__dry__clover_g: 6.3796 - val_mae__dry__dead_g: 11.6404 - val_mae__dry__green_g: 25.4924 - val_mae__dry__total_g: 28.7261 - val_mae_all: 19.1632 - val_mae_gdm_g: 23.5774 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 780ms/step - loss: 235.6589 - mae__dry__clover_g: 7.6081 - mae__dry__dead_g: 9.9865 - mae__dry__green_g: 26.4102 - mae__dry__total_g: 30.2708 - mae_all: 20.1441 - mae_gdm_g: 26.4450 - val_loss: 185.4319 - val_mae__dry__clover_g: 6.8702 - val_mae__dry__dead_g: 10.9833 - val_mae__dry__green_g: 25.4150 - val_mae__dry__total_g: 25.3016 - val_mae_all: 17.9769 - val_mae_gdm_g: 21.3143 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 781ms/step - loss: 205.3954 - mae__dry__clover_g: 8.0754 - mae__dry__dead_g: 9.6458 - mae__dry__green_g: 26.2440 - mae__dry__total_g: 27.2348 - mae_all: 19.1598 - mae_gdm_g: 24.5990 - val_loss: 172.6863 - val_mae__dry__clover_g: 7.0534 - val_mae__dry__dead_g: 10.6122 - val_mae__dry__green_g: 24.9705 - val_mae__dry__total_g: 24.0904 - val_mae_all: 17.3407 - val_mae_gdm_g: 19.9769 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 781ms/step - loss: 179.5491 - mae__dry__clover_g: 8.3125 - mae__dry__dead_g: 9.3165 - mae__dry__green_g: 25.4812 - mae__dry__total_g: 24.4924 - mae_all: 18.0043 - mae_gdm_g: 22.4190 - val_loss: 156.6233 - val_mae__dry__clover_g: 7.2235 - val_mae__dry__dead_g: 10.2443 - val_mae__dry__green_g: 23.7036 - val_mae__dry__total_g: 22.5550 - val_mae_all: 16.4290 - val_mae_gdm_g: 18.4184 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 780ms/step - loss: 156.6576 - mae__dry__clover_g: 8.3174 - mae__dry__dead_g: 9.0129 - mae__dry__green_g: 24.2204 - mae__dry__total_g: 22.2379 - mae_all: 16.8928 - mae_gdm_g: 20.6752 - val_loss: 143.5753 - val_mae__dry__clover_g: 7.2881 - val_mae__dry__dead_g: 9.9721 - val_mae__dry__green_g: 21.9930 - val_mae__dry__total_g: 21.4010 - val_mae_all: 15.5664 - val_mae_gdm_g: 17.1781 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 780ms/step - loss: 137.7559 - mae__dry__clover_g: 8.9786 - mae__dry__dead_g: 8.7837 - mae__dry__green_g: 22.4382 - mae__dry__total_g: 20.3794 - mae_all: 15.9156 - mae_gdm_g: 18.9979 - val_loss: 144.6708 - val_mae__dry__clover_g: 7.0326 - val_mae__dry__dead_g: 9.9407 - val_mae__dry__green_g: 20.8354 - val_mae__dry__total_g: 21.8071 - val_mae_all: 15.3478 - val_mae_gdm_g: 17.1229 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 780ms/step - loss: 118.9697 - mae__dry__clover_g: 8.8377 - mae__dry__dead_g: 8.7419 - mae__dry__green_g: 20.8476 - mae__dry__total_g: 18.5479 - mae_all: 14.8901 - mae_gdm_g: 17.4751 - val_loss: 131.5247 - val_mae__dry__clover_g: 7.0413 - val_mae__dry__dead_g: 9.8274 - val_mae__dry__green_g: 19.4407 - val_mae__dry__total_g: 20.3645 - val_mae_all: 14.4943 - val_mae_gdm_g: 15.7977 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 775ms/step - loss: 102.6850 - mae__dry__clover_g: 8.6522 - mae__dry__dead_g: 8.3933 - mae__dry__green_g: 19.2040 - mae__dry__total_g: 16.8459 - mae_all: 13.8425 - mae_gdm_g: 16.1170 - val_loss: 128.9898 - val_mae__dry__clover_g: 6.9119 - val_mae__dry__dead_g: 9.8048 - val_mae__dry__green_g: 18.5803 - val_mae__dry__total_g: 20.2560 - val_mae_all: 14.2065 - val_mae_gdm_g: 15.4795 - learning_rate: 1.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 780ms/step - loss: 98.9040 - mae__dry__clover_g: 8.8890 - mae__dry__dead_g: 8.6748 - mae__dry__green_g: 17.9390 - mae__dry__total_g: 16.5382 - mae_all: 13.5435 - mae_gdm_g: 15.6765 - val_loss: 114.8776 - val_mae__dry__clover_g: 6.9578 - val_mae__dry__dead_g: 9.6756 - val_mae__dry__green_g: 17.2893 - val_mae__dry__total_g: 18.8560 - val_mae_all: 13.3737 - val_mae_gdm_g: 14.0897 - learning_rate: 1.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 782ms/step - loss: 86.7428 - mae__dry__clover_g: 8.5810 - mae__dry__dead_g: 8.5223 - mae__dry__green_g: 17.1507 - mae__dry__total_g: 15.5572 - mae_all: 12.9168 - mae_gdm_g: 14.7727 - val_loss: 112.4235 - val_mae__dry__clover_g: 6.8259 - val_mae__dry__dead_g: 9.6897 - val_mae__dry__green_g: 16.6635 - val_mae__dry__total_g: 18.6706 - val_mae_all: 13.1205 - val_mae_gdm_g: 13.7527 - learning_rate: 1.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 781ms/step - loss: 78.7957 - mae__dry__clover_g: 8.0584 - mae__dry__dead_g: 8.9621 - mae__dry__green_g: 15.8041 - mae__dry__total_g: 14.7853 - mae_all: 12.3122 - mae_gdm_g: 13.9513 - val_loss: 101.1624 - val_mae__dry__clover_g: 6.9334 - val_mae__dry__dead_g: 9.5024 - val_mae__dry__green_g: 15.6438 - val_mae__dry__total_g: 17.4308 - val_mae_all: 12.4794 - val_mae_gdm_g: 12.8866 - learning_rate: 1.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 780ms/step - loss: 80.8084 - mae__dry__clover_g: 8.9326 - mae__dry__dead_g: 8.8466 - mae__dry__green_g: 15.5194 - mae__dry__total_g: 14.9379 - mae_all: 12.4943 - mae_gdm_g: 14.2350 - val_loss: 90.6449 - val_mae__dry__clover_g: 7.0889 - val_mae__dry__dead_g: 9.5106 - val_mae__dry__green_g: 14.7228 - val_mae__dry__total_g: 16.6117 - val_mae_all: 12.0622 - val_mae_gdm_g: 12.3770 - learning_rate: 1.0000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 781ms/step - loss: 70.6869 - mae__dry__clover_g: 8.7731 - mae__dry__dead_g: 8.3146 - mae__dry__green_g: 14.8388 - mae__dry__total_g: 14.5664 - mae_all: 11.9646 - mae_gdm_g: 13.3303 - val_loss: 90.8688 - val_mae__dry__clover_g: 6.9022 - val_mae__dry__dead_g: 9.4557 - val_mae__dry__green_g: 14.4522 - val_mae__dry__total_g: 16.5695 - val_mae_all: 11.9629 - val_mae_gdm_g: 12.4351 - learning_rate: 1.0000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 781ms/step - loss: 71.9621 - mae__dry__clover_g: 8.4628 - mae__dry__dead_g: 8.7101 - mae__dry__green_g: 14.7856 - mae__dry__total_g: 14.8127 - mae_all: 12.0878 - mae_gdm_g: 13.6676 - val_loss: 90.3241 - val_mae__dry__clover_g: 6.8387 - val_mae__dry__dead_g: 9.4717 - val_mae__dry__green_g: 14.1656 - val_mae__dry__total_g: 16.5926 - val_mae_all: 11.8380 - val_mae_gdm_g: 12.1212 - learning_rate: 1.0000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 781ms/step - loss: 70.9139 - mae__dry__clover_g: 8.4754 - mae__dry__dead_g: 8.5847 - mae__dry__green_g: 14.5624 - mae__dry__total_g: 14.5305 - mae_all: 12.0509 - mae_gdm_g: 14.1015 - val_loss: 91.2283 - val_mae__dry__clover_g: 6.6829 - val_mae__dry__dead_g: 9.4454 - val_mae__dry__green_g: 13.9281 - val_mae__dry__total_g: 16.4943 - val_mae_all: 11.7360 - val_mae_gdm_g: 12.1292 - learning_rate: 1.0000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 777ms/step - loss: 72.3240 - mae__dry__clover_g: 8.3447 - mae__dry__dead_g: 8.2912 - mae__dry__green_g: 14.3640 - mae__dry__total_g: 14.7575 - mae_all: 11.9054 - mae_gdm_g: 13.7694 - val_loss: 88.6897 - val_mae__dry__clover_g: 6.6930 - val_mae__dry__dead_g: 9.3995 - val_mae__dry__green_g: 13.6468 - val_mae__dry__total_g: 16.3832 - val_mae_all: 11.6460 - val_mae_gdm_g: 12.1076 - learning_rate: 1.0000e-04
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 780ms/step - loss: 67.7648 - mae__dry__clover_g: 8.0858 - mae__dry__dead_g: 8.7817 - mae__dry__green_g: 14.6240 - mae__dry__total_g: 14.7066 - mae_all: 11.9464 - mae_gdm_g: 13.5340 - val_loss: 85.5180 - val_mae__dry__clover_g: 6.7128 - val_mae__dry__dead_g: 9.4313 - val_mae__dry__green_g: 13.3595 - val_mae__dry__total_g: 16.2937 - val_mae_all: 11.5669 - val_mae_gdm_g: 12.0373 - learning_rate: 1.0000e-04
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 780ms/step - loss: 71.8364 - mae__dry__clover_g: 8.5729 - mae__dry__dead_g: 8.5152 - mae__dry__green_g: 14.2483 - mae__dry__total_g: 14.9279 - mae_all: 11.9789 - mae_gdm_g: 13.6300 - val_loss: 83.7209 - val_mae__dry__clover_g: 6.7241 - val_mae__dry__dead_g: 9.3643 - val_mae__dry__green_g: 13.2752 - val_mae__dry__total_g: 16.0130 - val_mae_all: 11.4940 - val_mae_gdm_g: 12.0932 - learning_rate: 1.0000e-04
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 767ms/step - loss: 66.8578 - mae__dry__clover_g: 8.4853 - mae__dry__dead_g: 9.1469 - mae__dry__green_g: 13.8618 - mae__dry__total_g: 14.3746 - mae_all: 11.8831 - mae_gdm_g: 13.5470 - val_loss: 80.2775 - val_mae__dry__clover_g: 6.8184 - val_mae__dry__dead_g: 9.3471 - val_mae__dry__green_g: 13.1300 - val_mae__dry__total_g: 15.8138 - val_mae_all: 11.4214 - val_mae_gdm_g: 11.9976 - learning_rate: 1.0000e-04
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 744ms/step - loss: 70.0992 - mae__dry__clover_g: 8.3797 - mae__dry__dead_g: 8.4994 - mae__dry__green_g: 14.3554 - mae__dry__total_g: 14.9395 - mae_all: 11.9167 - mae_gdm_g: 13.4093 - val_loss: 81.0377 - val_mae__dry__clover_g: 6.7017 - val_mae__dry__dead_g: 9.3649 - val_mae__dry__green_g: 13.2658 - val_mae__dry__total_g: 15.9041 - val_mae_all: 11.4940 - val_mae_gdm_g: 12.2333 - learning_rate: 1.0000e-04
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 744ms/step - loss: 68.6560 - mae__dry__clover_g: 8.4392 - mae__dry__dead_g: 8.6462 - mae__dry__green_g: 13.9007 - mae__dry__total_g: 14.6265 - mae_all: 11.7647 - mae_gdm_g: 13.2108 - val_loss: 81.2267 - val_mae__dry__clover_g: 6.7255 - val_mae__dry__dead_g: 9.3225 - val_mae__dry__green_g: 13.0914 - val_mae__dry__total_g: 15.8174 - val_mae_all: 11.3780 - val_mae_gdm_g: 11.9331 - learning_rate: 1.0000e-04
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 744ms/step - loss: 68.0709 - mae__dry__clover_g: 8.2128 - mae__dry__dead_g: 8.3550 - mae__dry__green_g: 14.5675 - mae__dry__total_g: 14.2499 - mae_all: 11.7774 - mae_gdm_g: 13.5018 - val_loss: 84.3528 - val_mae__dry__clover_g: 6.6110 - val_mae__dry__dead_g: 9.3807 - val_mae__dry__green_g: 12.9683 - val_mae__dry__total_g: 15.9592 - val_mae_all: 11.3427 - val_mae_gdm_g: 11.7941 - learning_rate: 1.0000e-04
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 68.7772 - mae__dry__clover_g: 8.4628 - mae__dry__dead_g: 8.5234 - mae__dry__green_g: 14.0039 - mae__dry__total_g: 14.6058 - mae_all: 11.7822 - mae_gdm_g: 13.3152 - val_loss: 78.5760 - val_mae__dry__clover_g: 6.9808 - val_mae__dry__dead_g: 9.3986 - val_mae__dry__green_g: 14.2100 - val_mae__dry__total_g: 16.8559 - val_mae_all: 12.1286 - val_mae_gdm_g: 13.1975 - learning_rate: 1.0000e-04
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 695ms/step - loss: 61.1775 - mae__dry__clover_g: 8.4340 - mae__dry__dead_g: 8.1390 - mae__dry__green_g: 13.1245 - mae__dry__total_g: 13.9471 - mae_all: 11.2160 - mae_gdm_g: 12.4353
Epoch 28: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 68.3130 - mae__dry__clover_g: 8.0521 - mae__dry__dead_g: 8.2413 - mae__dry__green_g: 14.3598 - mae__dry__total_g: 14.7041 - mae_all: 11.7703 - mae_gdm_g: 13.4940 - val_loss: 78.6874 - val_mae__dry__clover_g: 6.7185 - val_mae__dry__dead_g: 9.3535 - val_mae__dry__green_g: 13.6361 - val_mae__dry__total_g: 16.0997 - val_mae_all: 11.6597 - val_mae_gdm_g: 12.4905 - learning_rate: 1.0000e-04
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 744ms/step - loss: 68.2883 - mae__dry__clover_g: 7.9501 - mae__dry__dead_g: 8.4097 - mae__dry__green_g: 14.2198 - mae__dry__total_g: 14.4703 - mae_all: 11.7578 - mae_gdm_g: 13.7391 - val_loss: 80.2525 - val_mae__dry__clover_g: 6.6160 - val_mae__dry__dead_g: 9.2742 - val_mae__dry__green_g: 13.0646 - val_mae__dry__total_g: 15.7167 - val_mae_all: 11.3059 - val_mae_gdm_g: 11.8581 - learning_rate: 5.0000e-05
Epoch 30/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 64.0179 - mae__dry__clover_g: 8.3504 - mae__dry__dead_g: 8.4703 - mae__dry__green_g: 13.5955 - mae__dry__total_g: 14.0095 - mae_all: 11.5075 - mae_gdm_g: 13.1118 - val_loss: 78.2964 - val_mae__dry__clover_g: 6.6503 - val_mae__dry__dead_g: 9.1913 - val_mae__dry__green_g: 13.4077 - val_mae__dry__total_g: 15.6997 - val_mae_all: 11.4510 - val_mae_gdm_g: 12.3061 - learning_rate: 5.0000e-05
Restoring model weights from the end of the best epoch: 29.
Fold 0 best val_mae_all = 11.306
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 194ms/step
[student_from_baseline_fold0] Fold 0 Kaggle-style weighted R2 = 0.4691

===== Fold 1 =====
[Baseline] use_log1p=False, target_list=['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
Fold 1 | Target: ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
  Train: 285 images | Val: 72 images
Fold 1 | Meta=False | Train:285 Val:72
[Student] load baseline backbone from ./ckpt/baseline_gram_fold1.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 746ms/step - loss: 384.3039 - mae__dry__clover_g: 6.3734 - mae__dry__dead_g: 11.4192 - mae__dry__green_g: 26.4009 - mae__dry__total_g: 44.4904 - mae_all: 24.1793 - mae_gdm_g: 32.2128 - val_loss: 341.3756 - val_mae__dry__clover_g: 7.0475 - val_mae__dry__dead_g: 10.3925 - val_mae__dry__green_g: 25.3311 - val_mae__dry__total_g: 42.9774 - val_mae_all: 23.6232 - val_mae_gdm_g: 32.3675 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 743ms/step - loss: 363.3276 - mae__dry__clover_g: 6.3711 - mae__dry__dead_g: 11.0696 - mae__dry__green_g: 26.4303 - mae__dry__total_g: 42.4329 - mae_all: 23.6194 - mae_gdm_g: 31.7934 - val_loss: 320.2050 - val_mae__dry__clover_g: 7.0455 - val_mae__dry__dead_g: 9.9616 - val_mae__dry__green_g: 25.2532 - val_mae__dry__total_g: 40.6538 - val_mae_all: 23.0039 - val_mae_gdm_g: 32.1057 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 742ms/step - loss: 333.9388 - mae__dry__clover_g: 6.3589 - mae__dry__dead_g: 10.6032 - mae__dry__green_g: 26.4250 - mae__dry__total_g: 39.4087 - mae_all: 22.7857 - mae_gdm_g: 31.1329 - val_loss: 294.2350 - val_mae__dry__clover_g: 7.0526 - val_mae__dry__dead_g: 9.5133 - val_mae__dry__green_g: 25.1881 - val_mae__dry__total_g: 37.8043 - val_mae_all: 22.1833 - val_mae_gdm_g: 31.3584 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 300.4137 - mae__dry__clover_g: 6.3555 - mae__dry__dead_g: 10.0734 - mae__dry__green_g: 26.2962 - mae__dry__total_g: 36.0716 - mae_all: 21.6586 - mae_gdm_g: 29.4966 - val_loss: 260.2092 - val_mae__dry__clover_g: 7.1149 - val_mae__dry__dead_g: 9.1938 - val_mae__dry__green_g: 25.0610 - val_mae__dry__total_g: 34.0928 - val_mae_all: 21.0211 - val_mae_gdm_g: 29.6432 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 268.9806 - mae__dry__clover_g: 6.4270 - mae__dry__dead_g: 9.7303 - mae__dry__green_g: 26.0516 - mae__dry__total_g: 32.7435 - mae_all: 20.4609 - mae_gdm_g: 27.3520 - val_loss: 224.0532 - val_mae__dry__clover_g: 7.2670 - val_mae__dry__dead_g: 9.0949 - val_mae__dry__green_g: 24.8370 - val_mae__dry__total_g: 30.0336 - val_mae_all: 19.6602 - val_mae_gdm_g: 27.0685 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 236.4058 - mae__dry__clover_g: 6.4346 - mae__dry__dead_g: 9.4386 - mae__dry__green_g: 25.4755 - mae__dry__total_g: 29.5139 - mae_all: 19.1791 - mae_gdm_g: 25.0329 - val_loss: 189.8654 - val_mae__dry__clover_g: 7.4865 - val_mae__dry__dead_g: 9.3820 - val_mae__dry__green_g: 24.1461 - val_mae__dry__total_g: 26.2027 - val_mae_all: 18.2606 - val_mae_gdm_g: 24.0859 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 207.2358 - mae__dry__clover_g: 7.0318 - mae__dry__dead_g: 9.5107 - mae__dry__green_g: 24.4754 - mae__dry__total_g: 26.4327 - mae_all: 18.0368 - mae_gdm_g: 22.7333 - val_loss: 161.7426 - val_mae__dry__clover_g: 7.7267 - val_mae__dry__dead_g: 9.9012 - val_mae__dry__green_g: 23.0415 - val_mae__dry__total_g: 23.0921 - val_mae_all: 16.9898 - val_mae_gdm_g: 21.1876 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 181.3972 - mae__dry__clover_g: 7.3510 - mae__dry__dead_g: 9.6318 - mae__dry__green_g: 23.1113 - mae__dry__total_g: 23.7116 - mae_all: 16.8331 - mae_gdm_g: 20.3599 - val_loss: 139.8428 - val_mae__dry__clover_g: 7.9497 - val_mae__dry__dead_g: 10.3502 - val_mae__dry__green_g: 21.7493 - val_mae__dry__total_g: 20.6660 - val_mae_all: 15.9122 - val_mae_gdm_g: 18.8458 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 158.9686 - mae__dry__clover_g: 7.2880 - mae__dry__dead_g: 9.9358 - mae__dry__green_g: 21.6220 - mae__dry__total_g: 21.6614 - mae_all: 15.7921 - mae_gdm_g: 18.4530 - val_loss: 120.5000 - val_mae__dry__clover_g: 8.1976 - val_mae__dry__dead_g: 10.6859 - val_mae__dry__green_g: 20.4234 - val_mae__dry__total_g: 18.4730 - val_mae_all: 14.8898 - val_mae_gdm_g: 16.6693 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 141.0103 - mae__dry__clover_g: 7.5479 - mae__dry__dead_g: 9.7834 - mae__dry__green_g: 20.0634 - mae__dry__total_g: 19.9549 - mae_all: 14.8164 - mae_gdm_g: 16.7323 - val_loss: 104.3135 - val_mae__dry__clover_g: 8.4432 - val_mae__dry__dead_g: 10.7676 - val_mae__dry__green_g: 19.0835 - val_mae__dry__total_g: 16.3960 - val_mae_all: 13.9245 - val_mae_gdm_g: 14.9322 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 129.1295 - mae__dry__clover_g: 8.2251 - mae__dry__dead_g: 10.3128 - mae__dry__green_g: 18.5051 - mae__dry__total_g: 19.2525 - mae_all: 14.4402 - mae_gdm_g: 15.9054 - val_loss: 100.2248 - val_mae__dry__clover_g: 8.4236 - val_mae__dry__dead_g: 10.5594 - val_mae__dry__green_g: 18.4091 - val_mae__dry__total_g: 16.1892 - val_mae_all: 13.6108 - val_mae_gdm_g: 14.4729 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 120.6312 - mae__dry__clover_g: 8.2003 - mae__dry__dead_g: 9.6742 - mae__dry__green_g: 17.8151 - mae__dry__total_g: 18.9704 - mae_all: 13.9587 - mae_gdm_g: 15.1332 - val_loss: 96.0598 - val_mae__dry__clover_g: 8.4193 - val_mae__dry__dead_g: 10.3614 - val_mae__dry__green_g: 17.7603 - val_mae__dry__total_g: 15.9549 - val_mae_all: 13.3522 - val_mae_gdm_g: 14.2650 - learning_rate: 1.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 110.7854 - mae__dry__clover_g: 8.3697 - mae__dry__dead_g: 9.9711 - mae__dry__green_g: 16.6980 - mae__dry__total_g: 18.1926 - mae_all: 13.6303 - mae_gdm_g: 14.9202 - val_loss: 94.1788 - val_mae__dry__clover_g: 8.2927 - val_mae__dry__dead_g: 10.1906 - val_mae__dry__green_g: 17.2939 - val_mae__dry__total_g: 15.9934 - val_mae_all: 13.1903 - val_mae_gdm_g: 14.1808 - learning_rate: 1.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 108.1672 - mae__dry__clover_g: 8.3345 - mae__dry__dead_g: 10.0072 - mae__dry__green_g: 16.0817 - mae__dry__total_g: 18.3999 - mae_all: 13.5866 - mae_gdm_g: 15.1097 - val_loss: 93.0435 - val_mae__dry__clover_g: 8.1815 - val_mae__dry__dead_g: 9.9558 - val_mae__dry__green_g: 16.9687 - val_mae__dry__total_g: 16.0579 - val_mae_all: 13.0812 - val_mae_gdm_g: 14.2421 - learning_rate: 1.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 103.4784 - mae__dry__clover_g: 8.3167 - mae__dry__dead_g: 9.8827 - mae__dry__green_g: 15.7243 - mae__dry__total_g: 18.0283 - mae_all: 13.2858 - mae_gdm_g: 14.4769 - val_loss: 92.2391 - val_mae__dry__clover_g: 8.0947 - val_mae__dry__dead_g: 9.7648 - val_mae__dry__green_g: 16.6958 - val_mae__dry__total_g: 16.0547 - val_mae_all: 12.9461 - val_mae_gdm_g: 14.1205 - learning_rate: 1.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 97.8031 - mae__dry__clover_g: 8.3379 - mae__dry__dead_g: 9.6858 - mae__dry__green_g: 15.1235 - mae__dry__total_g: 17.7974 - mae_all: 13.1507 - mae_gdm_g: 14.8089 - val_loss: 87.4159 - val_mae__dry__clover_g: 8.1251 - val_mae__dry__dead_g: 9.7707 - val_mae__dry__green_g: 16.0517 - val_mae__dry__total_g: 15.7941 - val_mae_all: 12.7142 - val_mae_gdm_g: 13.8295 - learning_rate: 1.0000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 102.4948 - mae__dry__clover_g: 7.7290 - mae__dry__dead_g: 9.5278 - mae__dry__green_g: 15.2605 - mae__dry__total_g: 18.3833 - mae_all: 13.2193 - mae_gdm_g: 15.1956 - val_loss: 85.4244 - val_mae__dry__clover_g: 8.0865 - val_mae__dry__dead_g: 9.7209 - val_mae__dry__green_g: 15.7149 - val_mae__dry__total_g: 15.8768 - val_mae_all: 12.6519 - val_mae_gdm_g: 13.8604 - learning_rate: 1.0000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 96.5207 - mae__dry__clover_g: 7.7163 - mae__dry__dead_g: 9.7192 - mae__dry__green_g: 14.8152 - mae__dry__total_g: 18.2613 - mae_all: 13.0840 - mae_gdm_g: 14.9081 - val_loss: 87.0604 - val_mae__dry__clover_g: 7.9339 - val_mae__dry__dead_g: 9.4981 - val_mae__dry__green_g: 15.7462 - val_mae__dry__total_g: 16.0105 - val_mae_all: 12.6330 - val_mae_gdm_g: 13.9762 - learning_rate: 1.0000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 101.7985 - mae__dry__clover_g: 7.8176 - mae__dry__dead_g: 9.2754 - mae__dry__green_g: 15.7438 - mae__dry__total_g: 18.3936 - mae_all: 13.3523 - mae_gdm_g: 15.5312 - val_loss: 82.9888 - val_mae__dry__clover_g: 7.9710 - val_mae__dry__dead_g: 9.5419 - val_mae__dry__green_g: 15.1828 - val_mae__dry__total_g: 15.8914 - val_mae_all: 12.4739 - val_mae_gdm_g: 13.7822 - learning_rate: 1.0000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 98.5961 - mae__dry__clover_g: 8.1110 - mae__dry__dead_g: 9.3305 - mae__dry__green_g: 14.9522 - mae__dry__total_g: 18.0394 - mae_all: 13.1224 - mae_gdm_g: 15.1790 - val_loss: 85.1214 - val_mae__dry__clover_g: 7.7683 - val_mae__dry__dead_g: 9.3980 - val_mae__dry__green_g: 15.3135 - val_mae__dry__total_g: 15.8875 - val_mae_all: 12.4417 - val_mae_gdm_g: 13.8411 - learning_rate: 1.0000e-04
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 97.3431 - mae__dry__clover_g: 7.8313 - mae__dry__dead_g: 9.3974 - mae__dry__green_g: 15.2700 - mae__dry__total_g: 18.4231 - mae_all: 13.2725 - mae_gdm_g: 15.4408 - val_loss: 84.0045 - val_mae__dry__clover_g: 7.7769 - val_mae__dry__dead_g: 9.3697 - val_mae__dry__green_g: 15.2283 - val_mae__dry__total_g: 15.8755 - val_mae_all: 12.4295 - val_mae_gdm_g: 13.8971 - learning_rate: 1.0000e-04
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 96.4203 - mae__dry__clover_g: 7.7614 - mae__dry__dead_g: 9.2608 - mae__dry__green_g: 14.8358 - mae__dry__total_g: 18.2310 - mae_all: 12.9981 - mae_gdm_g: 14.9013 - val_loss: 82.0094 - val_mae__dry__clover_g: 7.8163 - val_mae__dry__dead_g: 9.3233 - val_mae__dry__green_g: 15.0613 - val_mae__dry__total_g: 15.8368 - val_mae_all: 12.4037 - val_mae_gdm_g: 13.9807 - learning_rate: 1.0000e-04
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 92.5786 - mae__dry__clover_g: 7.8594 - mae__dry__dead_g: 9.6744 - mae__dry__green_g: 14.7463 - mae__dry__total_g: 17.3068 - mae_all: 12.8900 - mae_gdm_g: 14.8628 - val_loss: 79.6337 - val_mae__dry__clover_g: 7.8696 - val_mae__dry__dead_g: 9.3645 - val_mae__dry__green_g: 14.8953 - val_mae__dry__total_g: 15.8702 - val_mae_all: 12.3996 - val_mae_gdm_g: 13.9986 - learning_rate: 1.0000e-04
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 92.4568 - mae__dry__clover_g: 7.9328 - mae__dry__dead_g: 9.8284 - mae__dry__green_g: 15.0371 - mae__dry__total_g: 17.7710 - mae_all: 13.1701 - mae_gdm_g: 15.2814 - val_loss: 78.9898 - val_mae__dry__clover_g: 7.8213 - val_mae__dry__dead_g: 9.2666 - val_mae__dry__green_g: 14.8879 - val_mae__dry__total_g: 15.8921 - val_mae_all: 12.3874 - val_mae_gdm_g: 14.0692 - learning_rate: 1.0000e-04
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 93.0666 - mae__dry__clover_g: 7.6657 - mae__dry__dead_g: 9.1797 - mae__dry__green_g: 15.2237 - mae__dry__total_g: 17.9392 - mae_all: 13.0218 - mae_gdm_g: 15.1006 - val_loss: 78.7041 - val_mae__dry__clover_g: 7.8363 - val_mae__dry__dead_g: 9.4042 - val_mae__dry__green_g: 14.7945 - val_mae__dry__total_g: 16.1273 - val_mae_all: 12.4703 - val_mae_gdm_g: 14.1893 - learning_rate: 1.0000e-04
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 91.9843 - mae__dry__clover_g: 7.8985 - mae__dry__dead_g: 9.5437 - mae__dry__green_g: 14.9014 - mae__dry__total_g: 17.8402 - mae_all: 13.0940 - mae_gdm_g: 15.2860 - val_loss: 79.3367 - val_mae__dry__clover_g: 7.7292 - val_mae__dry__dead_g: 9.2953 - val_mae__dry__green_g: 14.7349 - val_mae__dry__total_g: 15.7862 - val_mae_all: 12.2919 - val_mae_gdm_g: 13.9137 - learning_rate: 1.0000e-04
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 91.7127 - mae__dry__clover_g: 7.5600 - mae__dry__dead_g: 9.5036 - mae__dry__green_g: 14.8835 - mae__dry__total_g: 17.5521 - mae_all: 12.8954 - mae_gdm_g: 14.9776 - val_loss: 78.7116 - val_mae__dry__clover_g: 7.7320 - val_mae__dry__dead_g: 9.2498 - val_mae__dry__green_g: 14.7893 - val_mae__dry__total_g: 15.8045 - val_mae_all: 12.3189 - val_mae_gdm_g: 14.0190 - learning_rate: 1.0000e-04
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 90.8763 - mae__dry__clover_g: 7.8926 - mae__dry__dead_g: 9.5397 - mae__dry__green_g: 15.0426 - mae__dry__total_g: 17.7071 - mae_all: 13.0111 - mae_gdm_g: 14.8736 - val_loss: 78.7087 - val_mae__dry__clover_g: 7.6485 - val_mae__dry__dead_g: 9.0867 - val_mae__dry__green_g: 14.8117 - val_mae__dry__total_g: 15.6021 - val_mae_all: 12.2346 - val_mae_gdm_g: 14.0239 - learning_rate: 1.0000e-04
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 91.3853 - mae__dry__clover_g: 7.4427 - mae__dry__dead_g: 9.0021 - mae__dry__green_g: 15.1046 - mae__dry__total_g: 17.8705 - mae_all: 12.9258 - mae_gdm_g: 15.2092 - val_loss: 78.2687 - val_mae__dry__clover_g: 7.6887 - val_mae__dry__dead_g: 9.0193 - val_mae__dry__green_g: 14.9183 - val_mae__dry__total_g: 15.5798 - val_mae_all: 12.2811 - val_mae_gdm_g: 14.1994 - learning_rate: 1.0000e-04
Epoch 30/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 91.5216 - mae__dry__clover_g: 7.8407 - mae__dry__dead_g: 9.3666 - mae__dry__green_g: 15.4031 - mae__dry__total_g: 17.4972 - mae_all: 12.9962 - mae_gdm_g: 14.8735 - val_loss: 79.3021 - val_mae__dry__clover_g: 7.5740 - val_mae__dry__dead_g: 9.0542 - val_mae__dry__green_g: 14.7643 - val_mae__dry__total_g: 15.6199 - val_mae_all: 12.1957 - val_mae_gdm_g: 13.9659 - learning_rate: 1.0000e-04
Restoring model weights from the end of the best epoch: 30.
Fold 1 best val_mae_all = 12.196
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 197ms/step
[student_from_baseline_fold1] Fold 1 Kaggle-style weighted R2 = 0.4191

===== Fold 2 =====
[Baseline] use_log1p=False, target_list=['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
Fold 2 | Target: ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
  Train: 286 images | Val: 71 images
Fold 2 | Meta=False | Train:286 Val:71
[Student] load baseline backbone from ./ckpt/baseline_gram_fold2.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 750ms/step - loss: 354.0236 - mae__dry__clover_g: 6.2498 - mae__dry__dead_g: 11.9946 - mae__dry__green_g: 24.8917 - mae__dry__total_g: 43.1845 - mae_all: 23.5667 - mae_gdm_g: 31.5128 - val_loss: 401.6042 - val_mae__dry__clover_g: 7.5012 - val_mae__dry__dead_g: 9.8379 - val_mae__dry__green_g: 27.8776 - val_mae__dry__total_g: 43.6507 - val_mae_all: 24.8734 - val_mae_gdm_g: 35.4994 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 744ms/step - loss: 324.9503 - mae__dry__clover_g: 6.2158 - mae__dry__dead_g: 11.8538 - mae__dry__green_g: 24.3259 - mae__dry__total_g: 40.5103 - mae_all: 22.7790 - mae_gdm_g: 30.9889 - val_loss: 353.9995 - val_mae__dry__clover_g: 7.4583 - val_mae__dry__dead_g: 9.6724 - val_mae__dry__green_g: 26.8993 - val_mae__dry__total_g: 39.5491 - val_mae_all: 23.6198 - val_mae_gdm_g: 34.5201 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 290.2296 - mae__dry__clover_g: 6.2140 - mae__dry__dead_g: 11.5238 - mae__dry__green_g: 23.3780 - mae__dry__total_g: 37.1279 - mae_all: 21.6594 - mae_gdm_g: 30.0535 - val_loss: 289.5322 - val_mae__dry__clover_g: 7.4295 - val_mae__dry__dead_g: 9.2258 - val_mae__dry__green_g: 25.0875 - val_mae__dry__total_g: 33.5473 - val_mae_all: 21.5783 - val_mae_gdm_g: 32.6016 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 255.4882 - mae__dry__clover_g: 6.3171 - mae__dry__dead_g: 11.1301 - mae__dry__green_g: 22.3077 - mae__dry__total_g: 33.5806 - mae_all: 20.3907 - mae_gdm_g: 28.6182 - val_loss: 221.7597 - val_mae__dry__clover_g: 7.4139 - val_mae__dry__dead_g: 8.4522 - val_mae__dry__green_g: 22.6526 - val_mae__dry__total_g: 26.8803 - val_mae_all: 18.9773 - val_mae_gdm_g: 29.4876 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 218.1089 - mae__dry__clover_g: 6.2634 - mae__dry__dead_g: 10.5419 - mae__dry__green_g: 21.2192 - mae__dry__total_g: 29.5714 - mae_all: 18.8569 - mae_gdm_g: 26.6888 - val_loss: 177.9410 - val_mae__dry__clover_g: 7.4259 - val_mae__dry__dead_g: 8.1911 - val_mae__dry__green_g: 20.6866 - val_mae__dry__total_g: 22.6925 - val_mae_all: 17.1010 - val_mae_gdm_g: 26.5089 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 762ms/step - loss: 185.1705 - mae__dry__clover_g: 6.3183 - mae__dry__dead_g: 10.0144 - mae__dry__green_g: 19.7042 - mae__dry__total_g: 25.7837 - mae_all: 17.2639 - mae_gdm_g: 24.4988 - val_loss: 160.4650 - val_mae__dry__clover_g: 7.4523 - val_mae__dry__dead_g: 8.0643 - val_mae__dry__green_g: 19.8358 - val_mae__dry__total_g: 21.4746 - val_mae_all: 16.3577 - val_mae_gdm_g: 24.9614 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 758ms/step - loss: 156.7998 - mae__dry__clover_g: 6.5876 - mae__dry__dead_g: 9.8317 - mae__dry__green_g: 18.0472 - mae__dry__total_g: 22.4104 - mae_all: 15.8222 - mae_gdm_g: 22.2340 - val_loss: 149.2247 - val_mae__dry__clover_g: 7.4947 - val_mae__dry__dead_g: 7.9888 - val_mae__dry__green_g: 19.1557 - val_mae__dry__total_g: 20.8256 - val_mae_all: 15.8360 - val_mae_gdm_g: 23.7151 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 752ms/step - loss: 130.0300 - mae__dry__clover_g: 6.4962 - mae__dry__dead_g: 9.5295 - mae__dry__green_g: 16.6302 - mae__dry__total_g: 20.1573 - mae_all: 14.5538 - mae_gdm_g: 19.9556 - val_loss: 144.5681 - val_mae__dry__clover_g: 7.5284 - val_mae__dry__dead_g: 7.9154 - val_mae__dry__green_g: 18.8052 - val_mae__dry__total_g: 20.8048 - val_mae_all: 15.6056 - val_mae_gdm_g: 22.9744 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 114.5565 - mae__dry__clover_g: 6.7994 - mae__dry__dead_g: 9.6420 - mae__dry__green_g: 15.5356 - mae__dry__total_g: 18.3206 - mae_all: 13.6684 - mae_gdm_g: 18.0442 - val_loss: 143.8157 - val_mae__dry__clover_g: 7.5831 - val_mae__dry__dead_g: 7.8317 - val_mae__dry__green_g: 18.6126 - val_mae__dry__total_g: 20.9358 - val_mae_all: 15.5051 - val_mae_gdm_g: 22.5624 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 99.7492 - mae__dry__clover_g: 7.0202 - mae__dry__dead_g: 9.4248 - mae__dry__green_g: 14.8866 - mae__dry__total_g: 16.5275 - mae_all: 12.8086 - mae_gdm_g: 16.1840 - val_loss: 131.8435 - val_mae__dry__clover_g: 7.6603 - val_mae__dry__dead_g: 7.8735 - val_mae__dry__green_g: 17.8696 - val_mae__dry__total_g: 19.9977 - val_mae_all: 14.9411 - val_mae_gdm_g: 21.3044 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 92.5068 - mae__dry__clover_g: 7.2308 - mae__dry__dead_g: 9.4385 - mae__dry__green_g: 14.5320 - mae__dry__total_g: 16.1270 - mae_all: 12.5398 - mae_gdm_g: 15.3707 - val_loss: 128.0761 - val_mae__dry__clover_g: 7.7307 - val_mae__dry__dead_g: 7.8196 - val_mae__dry__green_g: 17.7408 - val_mae__dry__total_g: 19.9315 - val_mae_all: 14.8121 - val_mae_gdm_g: 20.8378 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 85.2975 - mae__dry__clover_g: 7.1195 - mae__dry__dead_g: 9.5955 - mae__dry__green_g: 14.3009 - mae__dry__total_g: 15.3404 - mae_all: 12.1708 - mae_gdm_g: 14.4979 - val_loss: 107.8715 - val_mae__dry__clover_g: 7.9257 - val_mae__dry__dead_g: 7.9545 - val_mae__dry__green_g: 16.3908 - val_mae__dry__total_g: 17.8810 - val_mae_all: 13.7604 - val_mae_gdm_g: 18.6503 - learning_rate: 1.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 78.1730 - mae__dry__clover_g: 7.3605 - mae__dry__dead_g: 9.3730 - mae__dry__green_g: 13.3883 - mae__dry__total_g: 15.4259 - mae_all: 11.8453 - mae_gdm_g: 13.6790 - val_loss: 104.9567 - val_mae__dry__clover_g: 7.9891 - val_mae__dry__dead_g: 7.9335 - val_mae__dry__green_g: 16.1852 - val_mae__dry__total_g: 17.7583 - val_mae_all: 13.5852 - val_mae_gdm_g: 18.0598 - learning_rate: 1.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 73.6048 - mae__dry__clover_g: 7.6752 - mae__dry__dead_g: 9.6030 - mae__dry__green_g: 13.9889 - mae__dry__total_g: 15.0278 - mae_all: 11.9671 - mae_gdm_g: 13.5407 - val_loss: 95.5828 - val_mae__dry__clover_g: 8.0746 - val_mae__dry__dead_g: 7.9893 - val_mae__dry__green_g: 15.5244 - val_mae__dry__total_g: 16.9708 - val_mae_all: 13.0949 - val_mae_gdm_g: 16.9153 - learning_rate: 1.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 73.7570 - mae__dry__clover_g: 7.6643 - mae__dry__dead_g: 9.2680 - mae__dry__green_g: 14.0347 - mae__dry__total_g: 15.6796 - mae_all: 11.9467 - mae_gdm_g: 13.0871 - val_loss: 89.0950 - val_mae__dry__clover_g: 8.1514 - val_mae__dry__dead_g: 8.0508 - val_mae__dry__green_g: 15.0991 - val_mae__dry__total_g: 16.4520 - val_mae_all: 12.7769 - val_mae_gdm_g: 16.1313 - learning_rate: 1.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 72.7731 - mae__dry__clover_g: 7.5351 - mae__dry__dead_g: 9.7967 - mae__dry__green_g: 13.7893 - mae__dry__total_g: 15.3380 - mae_all: 11.9618 - mae_gdm_g: 13.3498 - val_loss: 79.0675 - val_mae__dry__clover_g: 8.2851 - val_mae__dry__dead_g: 8.1632 - val_mae__dry__green_g: 14.6867 - val_mae__dry__total_g: 15.4840 - val_mae_all: 12.3667 - val_mae_gdm_g: 15.2145 - learning_rate: 1.0000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 72.9502 - mae__dry__clover_g: 7.8549 - mae__dry__dead_g: 9.3375 - mae__dry__green_g: 13.7573 - mae__dry__total_g: 15.3174 - mae_all: 11.8799 - mae_gdm_g: 13.1322 - val_loss: 73.9490 - val_mae__dry__clover_g: 8.3298 - val_mae__dry__dead_g: 8.3158 - val_mae__dry__green_g: 14.2372 - val_mae__dry__total_g: 15.0888 - val_mae_all: 12.1402 - val_mae_gdm_g: 14.7293 - learning_rate: 1.0000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 72.4463 - mae__dry__clover_g: 7.7453 - mae__dry__dead_g: 9.7274 - mae__dry__green_g: 13.9443 - mae__dry__total_g: 15.4582 - mae_all: 12.0025 - mae_gdm_g: 13.1370 - val_loss: 84.4799 - val_mae__dry__clover_g: 8.1132 - val_mae__dry__dead_g: 7.9590 - val_mae__dry__green_g: 14.9378 - val_mae__dry__total_g: 16.1531 - val_mae_all: 12.5098 - val_mae_gdm_g: 15.3859 - learning_rate: 1.0000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 699ms/step - loss: 74.8619 - mae__dry__clover_g: 8.3571 - mae__dry__dead_g: 9.1202 - mae__dry__green_g: 14.4233 - mae__dry__total_g: 16.0516 - mae_all: 12.4951 - mae_gdm_g: 14.5235
Epoch 19: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 70.2539 - mae__dry__clover_g: 7.3475 - mae__dry__dead_g: 9.2046 - mae__dry__green_g: 13.8741 - mae__dry__total_g: 15.1619 - mae_all: 11.8157 - mae_gdm_g: 13.4905 - val_loss: 76.1299 - val_mae__dry__clover_g: 8.2325 - val_mae__dry__dead_g: 8.1283 - val_mae__dry__green_g: 14.6767 - val_mae__dry__total_g: 15.2318 - val_mae_all: 12.2073 - val_mae_gdm_g: 14.7672 - learning_rate: 1.0000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 71.2143 - mae__dry__clover_g: 7.8476 - mae__dry__dead_g: 9.8484 - mae__dry__green_g: 13.6963 - mae__dry__total_g: 15.2604 - mae_all: 12.0071 - mae_gdm_g: 13.3828 - val_loss: 74.0551 - val_mae__dry__clover_g: 8.2632 - val_mae__dry__dead_g: 8.1566 - val_mae__dry__green_g: 14.3949 - val_mae__dry__total_g: 15.0959 - val_mae_all: 12.0857 - val_mae_gdm_g: 14.5178 - learning_rate: 5.0000e-05
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 70.2437 - mae__dry__clover_g: 7.5628 - mae__dry__dead_g: 9.2442 - mae__dry__green_g: 13.9239 - mae__dry__total_g: 15.2381 - mae_all: 11.7811 - mae_gdm_g: 12.9366 - val_loss: 71.8747 - val_mae__dry__clover_g: 8.3245 - val_mae__dry__dead_g: 8.2096 - val_mae__dry__green_g: 14.4615 - val_mae__dry__total_g: 14.9737 - val_mae_all: 12.0944 - val_mae_gdm_g: 14.5026 - learning_rate: 5.0000e-05
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 699ms/step - loss: 72.4831 - mae__dry__clover_g: 8.7404 - mae__dry__dead_g: 9.0871 - mae__dry__green_g: 14.4939 - mae__dry__total_g: 15.9371 - mae_all: 12.5114 - mae_gdm_g: 14.2987
Epoch 22: ReduceLROnPlateau reducing learning rate to 2.499999936844688e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 69.4840 - mae__dry__clover_g: 7.9672 - mae__dry__dead_g: 9.4732 - mae__dry__green_g: 14.0469 - mae__dry__total_g: 14.9879 - mae_all: 11.9470 - mae_gdm_g: 13.2599 - val_loss: 69.1501 - val_mae__dry__clover_g: 8.4004 - val_mae__dry__dead_g: 8.3528 - val_mae__dry__green_g: 14.4873 - val_mae__dry__total_g: 14.9102 - val_mae_all: 12.1209 - val_mae_gdm_g: 14.4536 - learning_rate: 5.0000e-05
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 67.3835 - mae__dry__clover_g: 7.4724 - mae__dry__dead_g: 9.6206 - mae__dry__green_g: 13.7028 - mae__dry__total_g: 14.9237 - mae_all: 11.7292 - mae_gdm_g: 12.9267 - val_loss: 70.4808 - val_mae__dry__clover_g: 8.3343 - val_mae__dry__dead_g: 8.2211 - val_mae__dry__green_g: 14.4125 - val_mae__dry__total_g: 14.8324 - val_mae_all: 12.0528 - val_mae_gdm_g: 14.4637 - learning_rate: 2.5000e-05
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 68.2044 - mae__dry__clover_g: 7.6677 - mae__dry__dead_g: 9.3963 - mae__dry__green_g: 14.0607 - mae__dry__total_g: 15.1097 - mae_all: 11.9213 - mae_gdm_g: 13.3724 - val_loss: 69.6177 - val_mae__dry__clover_g: 8.3549 - val_mae__dry__dead_g: 8.2721 - val_mae__dry__green_g: 14.4118 - val_mae__dry__total_g: 14.7946 - val_mae_all: 12.0532 - val_mae_gdm_g: 14.4324 - learning_rate: 2.5000e-05
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 69.0661 - mae__dry__clover_g: 7.8398 - mae__dry__dead_g: 9.5189 - mae__dry__green_g: 13.2521 - mae__dry__total_g: 15.0962 - mae_all: 11.7948 - mae_gdm_g: 13.2673 - val_loss: 69.9247 - val_mae__dry__clover_g: 8.3131 - val_mae__dry__dead_g: 8.2480 - val_mae__dry__green_g: 14.3237 - val_mae__dry__total_g: 14.7982 - val_mae_all: 12.0053 - val_mae_gdm_g: 14.3434 - learning_rate: 2.5000e-05
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 65.7183 - mae__dry__clover_g: 7.5126 - mae__dry__dead_g: 9.5729 - mae__dry__green_g: 13.4685 - mae__dry__total_g: 14.7315 - mae_all: 11.6458 - mae_gdm_g: 12.9435 - val_loss: 69.2431 - val_mae__dry__clover_g: 8.3160 - val_mae__dry__dead_g: 8.2724 - val_mae__dry__green_g: 14.3722 - val_mae__dry__total_g: 14.8004 - val_mae_all: 12.0101 - val_mae_gdm_g: 14.2893 - learning_rate: 2.5000e-05
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 699ms/step - loss: 73.1658 - mae__dry__clover_g: 8.6213 - mae__dry__dead_g: 8.8717 - mae__dry__green_g: 14.3116 - mae__dry__total_g: 15.7036 - mae_all: 12.4346 - mae_gdm_g: 14.6649
Epoch 27: ReduceLROnPlateau reducing learning rate to 1.249999968422344e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 67.6978 - mae__dry__clover_g: 7.7258 - mae__dry__dead_g: 9.1976 - mae__dry__green_g: 13.5907 - mae__dry__total_g: 14.8113 - mae_all: 11.7200 - mae_gdm_g: 13.2747 - val_loss: 68.5006 - val_mae__dry__clover_g: 8.3392 - val_mae__dry__dead_g: 8.3207 - val_mae__dry__green_g: 14.4580 - val_mae__dry__total_g: 14.8107 - val_mae_all: 12.0500 - val_mae_gdm_g: 14.3216 - learning_rate: 2.5000e-05
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 68.1667 - mae__dry__clover_g: 7.6081 - mae__dry__dead_g: 9.0125 - mae__dry__green_g: 13.8273 - mae__dry__total_g: 14.8583 - mae_all: 11.7214 - mae_gdm_g: 13.3006 - val_loss: 68.5840 - val_mae__dry__clover_g: 8.3254 - val_mae__dry__dead_g: 8.3154 - val_mae__dry__green_g: 14.4457 - val_mae__dry__total_g: 14.8222 - val_mae_all: 12.0360 - val_mae_gdm_g: 14.2711 - learning_rate: 1.2500e-05
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 705ms/step - loss: 69.9376 - mae__dry__clover_g: 8.5527 - mae__dry__dead_g: 9.2461 - mae__dry__green_g: 14.3227 - mae__dry__total_g: 15.5218 - mae_all: 12.3229 - mae_gdm_g: 13.9713
Epoch 29: ReduceLROnPlateau reducing learning rate to 6.24999984211172e-06.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 68.6045 - mae__dry__clover_g: 7.7176 - mae__dry__dead_g: 9.3270 - mae__dry__green_g: 14.0055 - mae__dry__total_g: 15.0539 - mae_all: 11.7806 - mae_gdm_g: 12.7990 - val_loss: 68.7375 - val_mae__dry__clover_g: 8.3198 - val_mae__dry__dead_g: 8.2871 - val_mae__dry__green_g: 14.4493 - val_mae__dry__total_g: 14.8024 - val_mae_all: 12.0332 - val_mae_gdm_g: 14.3074 - learning_rate: 1.2500e-05
Epoch 30/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 778ms/step - loss: 68.0382 - mae__dry__clover_g: 7.6971 - mae__dry__dead_g: 9.3177 - mae__dry__green_g: 14.0269 - mae__dry__total_g: 15.2738 - mae_all: 11.8744 - mae_gdm_g: 13.0564 - val_loss: 68.3865 - val_mae__dry__clover_g: 8.3284 - val_mae__dry__dead_g: 8.3237 - val_mae__dry__green_g: 14.4494 - val_mae__dry__total_g: 14.8141 - val_mae_all: 12.0350 - val_mae_gdm_g: 14.2593 - learning_rate: 6.2500e-06
Epoch 30: early stopping
Restoring model weights from the end of the best epoch: 25.
Fold 2 best val_mae_all = 12.005
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 203ms/step
[student_from_baseline_fold2] Fold 2 Kaggle-style weighted R2 = 0.6397

===== Fold 3 =====
[Baseline] use_log1p=False, target_list=['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
Fold 3 | Target: ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
  Train: 286 images | Val: 71 images
Fold 3 | Meta=False | Train:286 Val:71
[Student] load baseline backbone from ./ckpt/baseline_gram_fold3.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 31s 789ms/step - loss: 375.4732 - mae__dry__clover_g: 6.3353 - mae__dry__dead_g: 11.3504 - mae__dry__green_g: 26.0848 - mae__dry__total_g: 43.4402 - mae_all: 23.9997 - mae_gdm_g: 32.7876 - val_loss: 321.2035 - val_mae__dry__clover_g: 6.9768 - val_mae__dry__dead_g: 12.8289 - val_mae__dry__green_g: 22.7503 - val_mae__dry__total_g: 41.1746 - val_mae_all: 23.0284 - val_mae_gdm_g: 31.4114 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 782ms/step - loss: 348.4005 - mae__dry__clover_g: 6.2799 - mae__dry__dead_g: 11.4224 - mae__dry__green_g: 25.5672 - mae__dry__total_g: 40.5837 - mae_all: 23.2913 - mae_gdm_g: 32.6035 - val_loss: 269.6367 - val_mae__dry__clover_g: 6.8900 - val_mae__dry__dead_g: 13.0172 - val_mae__dry__green_g: 21.1181 - val_mae__dry__total_g: 35.0096 - val_mae_all: 21.4967 - val_mae_gdm_g: 31.4485 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 782ms/step - loss: 319.1549 - mae__dry__clover_g: 6.3402 - mae__dry__dead_g: 11.4305 - mae__dry__green_g: 24.5937 - mae__dry__total_g: 37.3941 - mae_all: 22.3976 - mae_gdm_g: 32.2297 - val_loss: 223.8747 - val_mae__dry__clover_g: 7.1111 - val_mae__dry__dead_g: 13.1236 - val_mae__dry__green_g: 19.6482 - val_mae__dry__total_g: 29.0650 - val_mae_all: 19.9490 - val_mae_gdm_g: 30.7970 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 780ms/step - loss: 289.5934 - mae__dry__clover_g: 6.3484 - mae__dry__dead_g: 11.3648 - mae__dry__green_g: 23.5594 - mae__dry__total_g: 34.0480 - mae_all: 21.3579 - mae_gdm_g: 31.4690 - val_loss: 190.2151 - val_mae__dry__clover_g: 7.5919 - val_mae__dry__dead_g: 13.1231 - val_mae__dry__green_g: 18.2606 - val_mae__dry__total_g: 25.0530 - val_mae_all: 18.6587 - val_mae_gdm_g: 29.2649 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 785ms/step - loss: 260.9741 - mae__dry__clover_g: 6.4786 - mae__dry__dead_g: 11.3263 - mae__dry__green_g: 22.2550 - mae__dry__total_g: 30.9428 - mae_all: 20.2251 - mae_gdm_g: 30.1226 - val_loss: 161.4661 - val_mae__dry__clover_g: 8.3245 - val_mae__dry__dead_g: 13.0361 - val_mae__dry__green_g: 16.9112 - val_mae__dry__total_g: 22.2529 - val_mae_all: 17.4244 - val_mae_gdm_g: 26.5972 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 786ms/step - loss: 233.0185 - mae__dry__clover_g: 6.6553 - mae__dry__dead_g: 11.1366 - mae__dry__green_g: 21.1132 - mae__dry__total_g: 28.0543 - mae_all: 19.0382 - mae_gdm_g: 28.2318 - val_loss: 138.8882 - val_mae__dry__clover_g: 9.0167 - val_mae__dry__dead_g: 12.6114 - val_mae__dry__green_g: 15.8979 - val_mae__dry__total_g: 20.1832 - val_mae_all: 16.2327 - val_mae_gdm_g: 23.4542 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 786ms/step - loss: 205.1088 - mae__dry__clover_g: 7.1543 - mae__dry__dead_g: 10.8131 - mae__dry__green_g: 19.5914 - mae__dry__total_g: 25.1904 - mae_all: 17.7808 - mae_gdm_g: 26.1548 - val_loss: 130.5244 - val_mae__dry__clover_g: 9.1251 - val_mae__dry__dead_g: 11.6660 - val_mae__dry__green_g: 15.5789 - val_mae__dry__total_g: 19.8112 - val_mae_all: 15.4735 - val_mae_gdm_g: 21.1865 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 181.3660 - mae__dry__clover_g: 7.6064 - mae__dry__dead_g: 10.3961 - mae__dry__green_g: 18.5256 - mae__dry__total_g: 22.7234 - mae_all: 16.6576 - mae_gdm_g: 24.0364 - val_loss: 130.5721 - val_mae__dry__clover_g: 8.7159 - val_mae__dry__dead_g: 11.0978 - val_mae__dry__green_g: 15.6835 - val_mae__dry__total_g: 20.1950 - val_mae_all: 15.1493 - val_mae_gdm_g: 20.0541 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 786ms/step - loss: 164.1106 - mae__dry__clover_g: 8.0432 - mae__dry__dead_g: 9.9832 - mae__dry__green_g: 17.9763 - mae__dry__total_g: 21.3390 - mae_all: 15.8917 - mae_gdm_g: 22.1169 - val_loss: 126.0881 - val_mae__dry__clover_g: 8.3857 - val_mae__dry__dead_g: 10.7981 - val_mae__dry__green_g: 15.6117 - val_mae__dry__total_g: 20.1689 - val_mae_all: 14.7814 - val_mae_gdm_g: 18.9426 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 785ms/step - loss: 145.8081 - mae__dry__clover_g: 8.1487 - mae__dry__dead_g: 9.3743 - mae__dry__green_g: 16.8371 - mae__dry__total_g: 20.0353 - mae_all: 14.8855 - mae_gdm_g: 20.0320 - val_loss: 130.0657 - val_mae__dry__clover_g: 7.9005 - val_mae__dry__dead_g: 10.7199 - val_mae__dry__green_g: 15.8174 - val_mae__dry__total_g: 21.1553 - val_mae_all: 14.9071 - val_mae_gdm_g: 18.9425 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 738ms/step - loss: 175.1223 - mae__dry__clover_g: 8.0912 - mae__dry__dead_g: 9.2496 - mae__dry__green_g: 17.9207 - mae__dry__total_g: 20.5655 - mae_all: 15.2398 - mae_gdm_g: 20.3721
Epoch 11: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 788ms/step - loss: 133.2371 - mae__dry__clover_g: 8.2313 - mae__dry__dead_g: 9.4503 - mae__dry__green_g: 16.5060 - mae__dry__total_g: 18.9501 - mae_all: 14.3182 - mae_gdm_g: 18.4532 - val_loss: 129.2605 - val_mae__dry__clover_g: 7.6747 - val_mae__dry__dead_g: 10.6246 - val_mae__dry__green_g: 15.8889 - val_mae__dry__total_g: 21.5565 - val_mae_all: 14.8603 - val_mae_gdm_g: 18.5565 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 787ms/step - loss: 126.7658 - mae__dry__clover_g: 8.5520 - mae__dry__dead_g: 9.3893 - mae__dry__green_g: 15.8419 - mae__dry__total_g: 19.0552 - mae_all: 14.0213 - mae_gdm_g: 17.2681 - val_loss: 128.4619 - val_mae__dry__clover_g: 7.5678 - val_mae__dry__dead_g: 10.5500 - val_mae__dry__green_g: 15.8887 - val_mae__dry__total_g: 21.8292 - val_mae_all: 14.8620 - val_mae_gdm_g: 18.4743 - learning_rate: 5.0000e-05
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 788ms/step - loss: 120.9673 - mae__dry__clover_g: 8.0842 - mae__dry__dead_g: 9.5773 - mae__dry__green_g: 15.7497 - mae__dry__total_g: 18.2265 - mae_all: 13.7816 - mae_gdm_g: 17.2703 - val_loss: 120.2860 - val_mae__dry__clover_g: 7.5979 - val_mae__dry__dead_g: 10.4343 - val_mae__dry__green_g: 15.4566 - val_mae__dry__total_g: 21.0414 - val_mae_all: 14.4365 - val_mae_gdm_g: 17.6525 - learning_rate: 5.0000e-05
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 119.1682 - mae__dry__clover_g: 8.4595 - mae__dry__dead_g: 9.2582 - mae__dry__green_g: 15.7211 - mae__dry__total_g: 18.3867 - mae_all: 13.7283 - mae_gdm_g: 16.8161 - val_loss: 118.5406 - val_mae__dry__clover_g: 7.5445 - val_mae__dry__dead_g: 10.3719 - val_mae__dry__green_g: 15.4021 - val_mae__dry__total_g: 20.9203 - val_mae_all: 14.3259 - val_mae_gdm_g: 17.3906 - learning_rate: 5.0000e-05
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 786ms/step - loss: 117.8402 - mae__dry__clover_g: 8.5260 - mae__dry__dead_g: 9.3320 - mae__dry__green_g: 15.9319 - mae__dry__total_g: 18.2708 - mae_all: 13.6577 - mae_gdm_g: 16.2279 - val_loss: 114.7355 - val_mae__dry__clover_g: 7.5285 - val_mae__dry__dead_g: 10.2907 - val_mae__dry__green_g: 15.2282 - val_mae__dry__total_g: 20.4954 - val_mae_all: 14.0952 - val_mae_gdm_g: 16.9330 - learning_rate: 5.0000e-05
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 113.4287 - mae__dry__clover_g: 8.4995 - mae__dry__dead_g: 9.4774 - mae__dry__green_g: 15.8616 - mae__dry__total_g: 18.3697 - mae_all: 13.6453 - mae_gdm_g: 16.0180 - val_loss: 110.5869 - val_mae__dry__clover_g: 7.5120 - val_mae__dry__dead_g: 10.2291 - val_mae__dry__green_g: 15.0708 - val_mae__dry__total_g: 19.9600 - val_mae_all: 13.8390 - val_mae_gdm_g: 16.4230 - learning_rate: 5.0000e-05
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 785ms/step - loss: 113.7857 - mae__dry__clover_g: 8.2520 - mae__dry__dead_g: 8.9250 - mae__dry__green_g: 15.6524 - mae__dry__total_g: 18.5962 - mae_all: 13.4431 - mae_gdm_g: 15.7898 - val_loss: 106.8383 - val_mae__dry__clover_g: 7.5098 - val_mae__dry__dead_g: 10.1384 - val_mae__dry__green_g: 14.9475 - val_mae__dry__total_g: 19.6004 - val_mae_all: 13.6472 - val_mae_gdm_g: 16.0397 - learning_rate: 5.0000e-05
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 785ms/step - loss: 108.8103 - mae__dry__clover_g: 8.5072 - mae__dry__dead_g: 9.2934 - mae__dry__green_g: 15.7174 - mae__dry__total_g: 18.1183 - mae_all: 13.4422 - mae_gdm_g: 15.5745 - val_loss: 106.7225 - val_mae__dry__clover_g: 7.4572 - val_mae__dry__dead_g: 10.1047 - val_mae__dry__green_g: 14.9490 - val_mae__dry__total_g: 19.6024 - val_mae_all: 13.6128 - val_mae_gdm_g: 15.9505 - learning_rate: 5.0000e-05
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 785ms/step - loss: 109.0554 - mae__dry__clover_g: 8.2088 - mae__dry__dead_g: 9.5090 - mae__dry__green_g: 15.8142 - mae__dry__total_g: 17.9305 - mae_all: 13.3971 - mae_gdm_g: 15.5228 - val_loss: 105.6921 - val_mae__dry__clover_g: 7.4277 - val_mae__dry__dead_g: 10.0443 - val_mae__dry__green_g: 14.9463 - val_mae__dry__total_g: 19.5357 - val_mae_all: 13.5556 - val_mae_gdm_g: 15.8241 - learning_rate: 5.0000e-05
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 107.0725 - mae__dry__clover_g: 7.9240 - mae__dry__dead_g: 9.8192 - mae__dry__green_g: 15.6286 - mae__dry__total_g: 17.8352 - mae_all: 13.3313 - mae_gdm_g: 15.4492 - val_loss: 102.4488 - val_mae__dry__clover_g: 7.4210 - val_mae__dry__dead_g: 9.9810 - val_mae__dry__green_g: 14.8639 - val_mae__dry__total_g: 19.1230 - val_mae_all: 13.3748 - val_mae_gdm_g: 15.4850 - learning_rate: 5.0000e-05
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 107.4008 - mae__dry__clover_g: 7.8295 - mae__dry__dead_g: 9.7282 - mae__dry__green_g: 15.5131 - mae__dry__total_g: 17.9623 - mae_all: 13.2907 - mae_gdm_g: 15.4204 - val_loss: 97.6866 - val_mae__dry__clover_g: 7.4449 - val_mae__dry__dead_g: 9.9252 - val_mae__dry__green_g: 14.6905 - val_mae__dry__total_g: 18.5435 - val_mae_all: 13.1117 - val_mae_gdm_g: 14.9546 - learning_rate: 5.0000e-05
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 783ms/step - loss: 106.6597 - mae__dry__clover_g: 8.2486 - mae__dry__dead_g: 9.5343 - mae__dry__green_g: 15.7211 - mae__dry__total_g: 17.9088 - mae_all: 13.3482 - mae_gdm_g: 15.3282 - val_loss: 93.2129 - val_mae__dry__clover_g: 7.4849 - val_mae__dry__dead_g: 9.9076 - val_mae__dry__green_g: 14.5567 - val_mae__dry__total_g: 18.0703 - val_mae_all: 12.8970 - val_mae_gdm_g: 14.4654 - learning_rate: 5.0000e-05
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 105.9202 - mae__dry__clover_g: 7.6012 - mae__dry__dead_g: 9.7330 - mae__dry__green_g: 15.7833 - mae__dry__total_g: 18.3419 - mae_all: 13.3333 - mae_gdm_g: 15.2072 - val_loss: 90.5043 - val_mae__dry__clover_g: 7.4900 - val_mae__dry__dead_g: 9.8754 - val_mae__dry__green_g: 14.4712 - val_mae__dry__total_g: 17.7200 - val_mae_all: 12.7342 - val_mae_gdm_g: 14.1143 - learning_rate: 5.0000e-05
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 783ms/step - loss: 104.0117 - mae__dry__clover_g: 8.1780 - mae__dry__dead_g: 9.8514 - mae__dry__green_g: 15.6848 - mae__dry__total_g: 17.9915 - mae_all: 13.4364 - mae_gdm_g: 15.4764 - val_loss: 88.0974 - val_mae__dry__clover_g: 7.5032 - val_mae__dry__dead_g: 9.8337 - val_mae__dry__green_g: 14.4108 - val_mae__dry__total_g: 17.5097 - val_mae_all: 12.6291 - val_mae_gdm_g: 13.8880 - learning_rate: 5.0000e-05
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 103.9691 - mae__dry__clover_g: 8.1799 - mae__dry__dead_g: 9.8551 - mae__dry__green_g: 15.6052 - mae__dry__total_g: 18.1185 - mae_all: 13.3964 - mae_gdm_g: 15.2233 - val_loss: 87.6754 - val_mae__dry__clover_g: 7.4807 - val_mae__dry__dead_g: 9.7898 - val_mae__dry__green_g: 14.3760 - val_mae__dry__total_g: 17.4968 - val_mae_all: 12.5929 - val_mae_gdm_g: 13.8211 - learning_rate: 5.0000e-05
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 785ms/step - loss: 102.1531 - mae__dry__clover_g: 8.0778 - mae__dry__dead_g: 9.6428 - mae__dry__green_g: 15.6222 - mae__dry__total_g: 18.0206 - mae_all: 13.3296 - mae_gdm_g: 15.2845 - val_loss: 85.1132 - val_mae__dry__clover_g: 7.5008 - val_mae__dry__dead_g: 9.7659 - val_mae__dry__green_g: 14.3690 - val_mae__dry__total_g: 17.2966 - val_mae_all: 12.4917 - val_mae_gdm_g: 13.5263 - learning_rate: 5.0000e-05
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 102.4943 - mae__dry__clover_g: 7.8513 - mae__dry__dead_g: 9.8962 - mae__dry__green_g: 15.7285 - mae__dry__total_g: 18.0289 - mae_all: 13.3134 - mae_gdm_g: 15.0623 - val_loss: 83.9928 - val_mae__dry__clover_g: 7.5043 - val_mae__dry__dead_g: 9.7472 - val_mae__dry__green_g: 14.3829 - val_mae__dry__total_g: 17.3038 - val_mae_all: 12.4604 - val_mae_gdm_g: 13.3638 - learning_rate: 5.0000e-05
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 102.6018 - mae__dry__clover_g: 8.2142 - mae__dry__dead_g: 9.5553 - mae__dry__green_g: 15.8996 - mae__dry__total_g: 18.0467 - mae_all: 13.3411 - mae_gdm_g: 14.9898 - val_loss: 83.1873 - val_mae__dry__clover_g: 7.4798 - val_mae__dry__dead_g: 9.7288 - val_mae__dry__green_g: 14.3118 - val_mae__dry__total_g: 17.0906 - val_mae_all: 12.3603 - val_mae_gdm_g: 13.1903 - learning_rate: 5.0000e-05
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 783ms/step - loss: 100.1788 - mae__dry__clover_g: 8.4111 - mae__dry__dead_g: 9.7799 - mae__dry__green_g: 15.7666 - mae__dry__total_g: 17.8967 - mae_all: 13.4653 - mae_gdm_g: 15.4723 - val_loss: 81.9980 - val_mae__dry__clover_g: 7.4772 - val_mae__dry__dead_g: 9.7114 - val_mae__dry__green_g: 14.3176 - val_mae__dry__total_g: 17.0010 - val_mae_all: 12.3044 - val_mae_gdm_g: 13.0149 - learning_rate: 5.0000e-05
Epoch 30/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 101.1902 - mae__dry__clover_g: 7.8982 - mae__dry__dead_g: 9.3033 - mae__dry__green_g: 15.8695 - mae__dry__total_g: 18.0028 - mae_all: 13.2335 - mae_gdm_g: 15.0937 - val_loss: 81.2750 - val_mae__dry__clover_g: 7.4866 - val_mae__dry__dead_g: 9.6794 - val_mae__dry__green_g: 14.3997 - val_mae__dry__total_g: 17.0159 - val_mae_all: 12.3013 - val_mae_gdm_g: 12.9247 - learning_rate: 5.0000e-05
Restoring model weights from the end of the best epoch: 30.
Fold 3 best val_mae_all = 12.301
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 204ms/step
[student_from_baseline_fold3] Fold 3 Kaggle-style weighted R2 = 0.3953

===== Fold 4 =====
[Baseline] use_log1p=False, target_list=['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
Fold 4 | Target: ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
  Train: 286 images | Val: 71 images
Fold 4 | Meta=False | Train:286 Val:71
[Student] load baseline backbone from ./ckpt/baseline_gram_fold4.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 30s 776ms/step - loss: 360.6901 - mae__dry__clover_g: 6.7597 - mae__dry__dead_g: 11.3325 - mae__dry__green_g: 25.6998 - mae__dry__total_g: 43.4563 - mae_all: 23.9079 - mae_gdm_g: 32.2912 - val_loss: 370.9169 - val_mae__dry__clover_g: 5.4097 - val_mae__dry__dead_g: 10.6636 - val_mae__dry__green_g: 27.5246 - val_mae__dry__total_g: 41.3200 - val_mae_all: 23.5099 - val_mae_gdm_g: 32.6316 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 776ms/step - loss: 328.8571 - mae__dry__clover_g: 6.7979 - mae__dry__dead_g: 11.0132 - mae__dry__green_g: 25.6273 - mae__dry__total_g: 40.4203 - mae_all: 23.1579 - mae_gdm_g: 31.9310 - val_loss: 325.7004 - val_mae__dry__clover_g: 5.3914 - val_mae__dry__dead_g: 10.1952 - val_mae__dry__green_g: 27.4897 - val_mae__dry__total_g: 36.5984 - val_mae_all: 22.3297 - val_mae_gdm_g: 31.9739 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 775ms/step - loss: 295.1169 - mae__dry__clover_g: 6.7976 - mae__dry__dead_g: 10.6028 - mae__dry__green_g: 25.5307 - mae__dry__total_g: 37.1569 - mae_all: 22.2640 - mae_gdm_g: 31.2319 - val_loss: 304.0613 - val_mae__dry__clover_g: 5.4192 - val_mae__dry__dead_g: 9.9544 - val_mae__dry__green_g: 27.2873 - val_mae__dry__total_g: 34.3895 - val_mae_all: 21.6632 - val_mae_gdm_g: 31.2656 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 776ms/step - loss: 262.9616 - mae__dry__clover_g: 6.8139 - mae__dry__dead_g: 10.1758 - mae__dry__green_g: 25.1722 - mae__dry__total_g: 33.9118 - mae_all: 21.2705 - mae_gdm_g: 30.2789 - val_loss: 284.4461 - val_mae__dry__clover_g: 5.4886 - val_mae__dry__dead_g: 9.6173 - val_mae__dry__green_g: 26.7502 - val_mae__dry__total_g: 32.4176 - val_mae_all: 20.9162 - val_mae_gdm_g: 30.3074 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 234.4305 - mae__dry__clover_g: 6.8633 - mae__dry__dead_g: 9.8741 - mae__dry__green_g: 24.6000 - mae__dry__total_g: 31.1202 - mae_all: 20.2708 - mae_gdm_g: 28.8964 - val_loss: 272.3732 - val_mae__dry__clover_g: 5.5793 - val_mae__dry__dead_g: 9.4174 - val_mae__dry__green_g: 26.1486 - val_mae__dry__total_g: 31.4200 - val_mae_all: 20.3970 - val_mae_gdm_g: 29.4200 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 743ms/step - loss: 205.0945 - mae__dry__clover_g: 6.9889 - mae__dry__dead_g: 9.4830 - mae__dry__green_g: 23.6517 - mae__dry__total_g: 28.1070 - mae_all: 19.1349 - mae_gdm_g: 27.4439 - val_loss: 251.5822 - val_mae__dry__clover_g: 5.7175 - val_mae__dry__dead_g: 9.0776 - val_mae__dry__green_g: 25.2630 - val_mae__dry__total_g: 29.2731 - val_mae_all: 19.4844 - val_mae_gdm_g: 28.0907 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 177.8249 - mae__dry__clover_g: 7.0868 - mae__dry__dead_g: 9.3548 - mae__dry__green_g: 22.7604 - mae__dry__total_g: 24.9421 - mae_all: 17.9980 - mae_gdm_g: 25.8458 - val_loss: 239.6849 - val_mae__dry__clover_g: 5.8325 - val_mae__dry__dead_g: 8.8826 - val_mae__dry__green_g: 24.4748 - val_mae__dry__total_g: 28.1814 - val_mae_all: 18.9041 - val_mae_gdm_g: 27.1495 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 154.3512 - mae__dry__clover_g: 7.4463 - mae__dry__dead_g: 9.1788 - mae__dry__green_g: 21.6204 - mae__dry__total_g: 22.4290 - mae_all: 16.8915 - mae_gdm_g: 23.7829 - val_loss: 227.6359 - val_mae__dry__clover_g: 5.8566 - val_mae__dry__dead_g: 8.7322 - val_mae__dry__green_g: 23.5830 - val_mae__dry__total_g: 26.9821 - val_mae_all: 18.2553 - val_mae_gdm_g: 26.1228 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 132.4354 - mae__dry__clover_g: 7.5130 - mae__dry__dead_g: 9.1714 - mae__dry__green_g: 20.0624 - mae__dry__total_g: 19.9592 - mae_all: 15.7562 - mae_gdm_g: 22.0752 - val_loss: 211.1389 - val_mae__dry__clover_g: 5.9611 - val_mae__dry__dead_g: 8.5531 - val_mae__dry__green_g: 22.4680 - val_mae__dry__total_g: 25.4278 - val_mae_all: 17.4297 - val_mae_gdm_g: 24.7384 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 115.7998 - mae__dry__clover_g: 7.5778 - mae__dry__dead_g: 9.3369 - mae__dry__green_g: 19.0091 - mae__dry__total_g: 18.4332 - mae_all: 14.9838 - mae_gdm_g: 20.5620 - val_loss: 203.0744 - val_mae__dry__clover_g: 6.0140 - val_mae__dry__dead_g: 8.4153 - val_mae__dry__green_g: 21.6740 - val_mae__dry__total_g: 24.6693 - val_mae_all: 16.9140 - val_mae_gdm_g: 23.7972 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 101.2824 - mae__dry__clover_g: 7.9735 - mae__dry__dead_g: 9.1389 - mae__dry__green_g: 18.2868 - mae__dry__total_g: 16.8988 - mae_all: 14.2435 - mae_gdm_g: 18.9194 - val_loss: 183.7330 - val_mae__dry__clover_g: 6.1469 - val_mae__dry__dead_g: 8.2971 - val_mae__dry__green_g: 20.3264 - val_mae__dry__total_g: 22.8245 - val_mae_all: 15.9395 - val_mae_gdm_g: 22.1028 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 93.3602 - mae__dry__clover_g: 8.0995 - mae__dry__dead_g: 8.9529 - mae__dry__green_g: 17.0359 - mae__dry__total_g: 16.3715 - mae_all: 13.5482 - mae_gdm_g: 17.2813 - val_loss: 174.0534 - val_mae__dry__clover_g: 6.2037 - val_mae__dry__dead_g: 8.1966 - val_mae__dry__green_g: 19.4593 - val_mae__dry__total_g: 21.8716 - val_mae_all: 15.3497 - val_mae_gdm_g: 21.0175 - learning_rate: 1.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 87.1651 - mae__dry__clover_g: 7.8383 - mae__dry__dead_g: 9.1125 - mae__dry__green_g: 16.5289 - mae__dry__total_g: 15.8922 - mae_all: 13.1356 - mae_gdm_g: 16.3063 - val_loss: 165.1745 - val_mae__dry__clover_g: 6.2797 - val_mae__dry__dead_g: 8.2051 - val_mae__dry__green_g: 18.6290 - val_mae__dry__total_g: 21.1319 - val_mae_all: 14.8217 - val_mae_gdm_g: 19.8627 - learning_rate: 1.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 82.7320 - mae__dry__clover_g: 8.0321 - mae__dry__dead_g: 9.2922 - mae__dry__green_g: 15.8557 - mae__dry__total_g: 16.0209 - mae_all: 12.9118 - mae_gdm_g: 15.3584 - val_loss: 155.3720 - val_mae__dry__clover_g: 6.3657 - val_mae__dry__dead_g: 8.0999 - val_mae__dry__green_g: 17.8777 - val_mae__dry__total_g: 20.3090 - val_mae_all: 14.3021 - val_mae_gdm_g: 18.8582 - learning_rate: 1.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 77.5010 - mae__dry__clover_g: 8.2366 - mae__dry__dead_g: 9.1914 - mae__dry__green_g: 15.1367 - mae__dry__total_g: 15.4209 - mae_all: 12.5121 - mae_gdm_g: 14.5747 - val_loss: 147.9357 - val_mae__dry__clover_g: 6.3909 - val_mae__dry__dead_g: 8.0806 - val_mae__dry__green_g: 17.1215 - val_mae__dry__total_g: 19.7160 - val_mae_all: 13.8399 - val_mae_gdm_g: 17.8904 - learning_rate: 1.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 72.1215 - mae__dry__clover_g: 8.0815 - mae__dry__dead_g: 9.5903 - mae__dry__green_g: 14.6958 - mae__dry__total_g: 15.1156 - mae_all: 12.2661 - mae_gdm_g: 13.8474 - val_loss: 141.5180 - val_mae__dry__clover_g: 6.4254 - val_mae__dry__dead_g: 8.0858 - val_mae__dry__green_g: 16.5323 - val_mae__dry__total_g: 19.2365 - val_mae_all: 13.5026 - val_mae_gdm_g: 17.2326 - learning_rate: 1.0000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 71.2067 - mae__dry__clover_g: 8.2539 - mae__dry__dead_g: 9.3555 - mae__dry__green_g: 14.7332 - mae__dry__total_g: 15.1453 - mae_all: 12.3174 - mae_gdm_g: 14.0992 - val_loss: 131.7573 - val_mae__dry__clover_g: 6.5310 - val_mae__dry__dead_g: 8.0506 - val_mae__dry__green_g: 15.6833 - val_mae__dry__total_g: 18.4033 - val_mae_all: 13.0259 - val_mae_gdm_g: 16.4614 - learning_rate: 1.0000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 67.4675 - mae__dry__clover_g: 8.6158 - mae__dry__dead_g: 9.5228 - mae__dry__green_g: 14.0090 - mae__dry__total_g: 14.6013 - mae_all: 12.0829 - mae_gdm_g: 13.6657 - val_loss: 134.5504 - val_mae__dry__clover_g: 6.4014 - val_mae__dry__dead_g: 8.0425 - val_mae__dry__green_g: 15.6872 - val_mae__dry__total_g: 18.7622 - val_mae_all: 13.0827 - val_mae_gdm_g: 16.5201 - learning_rate: 1.0000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 697ms/step - loss: 57.6519 - mae__dry__clover_g: 7.7710 - mae__dry__dead_g: 8.7642 - mae__dry__green_g: 13.0906 - mae__dry__total_g: 13.9045 - mae_all: 11.0785 - mae_gdm_g: 11.8621
Epoch 19: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 67.6525 - mae__dry__clover_g: 8.3285 - mae__dry__dead_g: 8.9106 - mae__dry__green_g: 14.2920 - mae__dry__total_g: 14.6300 - mae_all: 11.8821 - mae_gdm_g: 13.2491 - val_loss: 143.2959 - val_mae__dry__clover_g: 6.2320 - val_mae__dry__dead_g: 7.9437 - val_mae__dry__green_g: 16.1317 - val_mae__dry__total_g: 19.5478 - val_mae_all: 13.3459 - val_mae_gdm_g: 16.8744 - learning_rate: 1.0000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 66.3061 - mae__dry__clover_g: 8.1958 - mae__dry__dead_g: 9.0963 - mae__dry__green_g: 14.4558 - mae__dry__total_g: 14.6085 - mae_all: 11.9587 - mae_gdm_g: 13.4369 - val_loss: 125.4568 - val_mae__dry__clover_g: 6.4802 - val_mae__dry__dead_g: 8.0212 - val_mae__dry__green_g: 14.9549 - val_mae__dry__total_g: 18.1575 - val_mae_all: 12.7060 - val_mae_gdm_g: 15.9162 - learning_rate: 5.0000e-05
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 65.8373 - mae__dry__clover_g: 7.9357 - mae__dry__dead_g: 9.3262 - mae__dry__green_g: 13.8750 - mae__dry__total_g: 14.9768 - mae_all: 11.9290 - mae_gdm_g: 13.5314 - val_loss: 125.7477 - val_mae__dry__clover_g: 6.4655 - val_mae__dry__dead_g: 8.0050 - val_mae__dry__green_g: 14.9638 - val_mae__dry__total_g: 18.2117 - val_mae_all: 12.7038 - val_mae_gdm_g: 15.8733 - learning_rate: 5.0000e-05
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 63.5399 - mae__dry__clover_g: 8.4613 - mae__dry__dead_g: 9.4985 - mae__dry__green_g: 14.2752 - mae__dry__total_g: 14.5982 - mae_all: 11.9640 - mae_gdm_g: 12.9869 - val_loss: 120.2436 - val_mae__dry__clover_g: 6.5785 - val_mae__dry__dead_g: 8.0469 - val_mae__dry__green_g: 14.6872 - val_mae__dry__total_g: 18.0402 - val_mae_all: 12.5898 - val_mae_gdm_g: 15.5961 - learning_rate: 5.0000e-05
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 65.3462 - mae__dry__clover_g: 8.0759 - mae__dry__dead_g: 9.2569 - mae__dry__green_g: 14.2948 - mae__dry__total_g: 14.5472 - mae_all: 11.8776 - mae_gdm_g: 13.2133 - val_loss: 120.6560 - val_mae__dry__clover_g: 6.5564 - val_mae__dry__dead_g: 8.0493 - val_mae__dry__green_g: 14.6899 - val_mae__dry__total_g: 18.0757 - val_mae_all: 12.5994 - val_mae_gdm_g: 15.6260 - learning_rate: 5.0000e-05
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 698ms/step - loss: 57.1095 - mae__dry__clover_g: 8.1811 - mae__dry__dead_g: 9.5109 - mae__dry__green_g: 13.1848 - mae__dry__total_g: 14.4039 - mae_all: 11.4721 - mae_gdm_g: 12.0801
Epoch 24: ReduceLROnPlateau reducing learning rate to 2.499999936844688e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 64.6791 - mae__dry__clover_g: 8.5837 - mae__dry__dead_g: 9.2462 - mae__dry__green_g: 14.1059 - mae__dry__total_g: 14.6320 - mae_all: 11.9141 - mae_gdm_g: 13.0025 - val_loss: 118.3104 - val_mae__dry__clover_g: 6.6160 - val_mae__dry__dead_g: 7.9892 - val_mae__dry__green_g: 14.6521 - val_mae__dry__total_g: 18.1115 - val_mae_all: 12.6061 - val_mae_gdm_g: 15.6618 - learning_rate: 5.0000e-05
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 65.6768 - mae__dry__clover_g: 8.4434 - mae__dry__dead_g: 9.3758 - mae__dry__green_g: 14.0530 - mae__dry__total_g: 14.8340 - mae_all: 11.9871 - mae_gdm_g: 13.2291 - val_loss: 118.1666 - val_mae__dry__clover_g: 6.6140 - val_mae__dry__dead_g: 7.9967 - val_mae__dry__green_g: 14.6420 - val_mae__dry__total_g: 18.0585 - val_mae_all: 12.5859 - val_mae_gdm_g: 15.6185 - learning_rate: 2.5000e-05
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 64.5723 - mae__dry__clover_g: 8.3942 - mae__dry__dead_g: 9.0757 - mae__dry__green_g: 14.2102 - mae__dry__total_g: 14.2186 - mae_all: 11.8485 - mae_gdm_g: 13.3441 - val_loss: 116.7234 - val_mae__dry__clover_g: 6.6419 - val_mae__dry__dead_g: 8.0424 - val_mae__dry__green_g: 14.6000 - val_mae__dry__total_g: 18.1089 - val_mae_all: 12.6009 - val_mae_gdm_g: 15.6112 - learning_rate: 2.5000e-05
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 698ms/step - loss: 56.4986 - mae__dry__clover_g: 8.1784 - mae__dry__dead_g: 9.2157 - mae__dry__green_g: 13.2718 - mae__dry__total_g: 13.9442 - mae_all: 11.4001 - mae_gdm_g: 12.3906
Epoch 27: ReduceLROnPlateau reducing learning rate to 1.249999968422344e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 64.8163 - mae__dry__clover_g: 8.5407 - mae__dry__dead_g: 9.2819 - mae__dry__green_g: 14.0138 - mae__dry__total_g: 14.6001 - mae_all: 12.0132 - mae_gdm_g: 13.6294 - val_loss: 116.2953 - val_mae__dry__clover_g: 6.6293 - val_mae__dry__dead_g: 8.0897 - val_mae__dry__green_g: 14.5473 - val_mae__dry__total_g: 18.1131 - val_mae_all: 12.5917 - val_mae_gdm_g: 15.5792 - learning_rate: 2.5000e-05
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 61.9202 - mae__dry__clover_g: 8.2325 - mae__dry__dead_g: 9.5698 - mae__dry__green_g: 13.8399 - mae__dry__total_g: 14.3327 - mae_all: 11.7929 - mae_gdm_g: 12.9896 - val_loss: 115.4506 - val_mae__dry__clover_g: 6.6495 - val_mae__dry__dead_g: 8.0947 - val_mae__dry__green_g: 14.5308 - val_mae__dry__total_g: 18.0935 - val_mae_all: 12.5879 - val_mae_gdm_g: 15.5710 - learning_rate: 1.2500e-05
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 696ms/step - loss: 52.9208 - mae__dry__clover_g: 7.7648 - mae__dry__dead_g: 9.5085 - mae__dry__green_g: 13.3807 - mae__dry__total_g: 13.7418 - mae_all: 11.2909 - mae_gdm_g: 12.0589
Epoch 29: ReduceLROnPlateau reducing learning rate to 6.24999984211172e-06.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 60.9475 - mae__dry__clover_g: 8.0520 - mae__dry__dead_g: 9.4841 - mae__dry__green_g: 14.1620 - mae__dry__total_g: 14.4190 - mae_all: 11.8369 - mae_gdm_g: 13.0675 - val_loss: 114.5602 - val_mae__dry__clover_g: 6.6722 - val_mae__dry__dead_g: 8.0950 - val_mae__dry__green_g: 14.5194 - val_mae__dry__total_g: 18.1333 - val_mae_all: 12.6067 - val_mae_gdm_g: 15.6133 - learning_rate: 1.2500e-05
Epoch 30/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 63.1337 - mae__dry__clover_g: 8.7395 - mae__dry__dead_g: 9.6859 - mae__dry__green_g: 13.9813 - mae__dry__total_g: 14.5884 - mae_all: 11.9563 - mae_gdm_g: 12.7863 - val_loss: 113.3975 - val_mae__dry__clover_g: 6.7143 - val_mae__dry__dead_g: 8.1035 - val_mae__dry__green_g: 14.5299 - val_mae__dry__total_g: 18.2072 - val_mae_all: 12.6456 - val_mae_gdm_g: 15.6733 - learning_rate: 6.2500e-06
Epoch 30: early stopping
Restoring model weights from the end of the best epoch: 25.
Fold 4 best val_mae_all = 12.586
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 199ms/step
[student_from_baseline_fold4] Fold 4 Kaggle-style weighted R2 = 0.3618

===== [Student Distill] 5-fold CV summary =====
MAE per fold: [11.306 12.196 12.005 12.301 12.586]
R2  per fold: [0.469 0.419 0.64  0.395 0.362]
mean R2 = 0.4569973935200549

===== [Student no-Distill] 5-fold CV summary ===== 3 target
MAE per fold: [ 9.151 10.531 10.454  9.288  9.149]
R2  per fold: [0.383 0.414 0.353 0.48  0.231]
mean R2 = 0.37238640442242643

===== [Student no-Distill] 5-fold CV summary ===== 5 target
MAE per fold: [11.306 12.196 12.005 12.301 12.586]
R2  per fold: [0.469 0.419 0.64  0.395 0.362]
mean R2 = 0.4569973935200549

--------------------------------------

In [57]:
def train_one_fold_student_distill(
    fold,
    teacher_model,
    alpha=0.4,
    tau=3.0,
    target_list=None,
    model_fn=biomass_student_from_baseline,
    **model_kwargs,
):
    """Train a distilled student for one fold using a fixed teacher model.

    Args:
        fold: Fold index used as validation split.
        teacher_model: Trained teacher model (image + metadata) used to
            generate soft labels.
        alpha: Distillation weight (teacher term) passed to the loss.
        tau: Distillation temperature passed to the loss.
        target_list: List of target column names; if None, defaults to TRAIN_TARGETS.
        model_fn: Function that builds the student model.
        **model_kwargs: Extra keyword arguments forwarded to `model_fn`.

    Returns:
        tuple: (best_val_mae, student_model, history, val_ds, w_r2)
    """
    
    if target_list is None:
        target_list = TRAIN_TARGETS

    print(f"\n===== [Student Distill] Fold {fold} (alpha={alpha}, tau={tau}) =====")

    # 1) Build data module and collect all data
    dm = BiomassImgDataModule(fold=fold, target_list=target_list, include_meta=True)
    imgs_all = dm.make_arrays()          # (N, H, W, 3)
    y_gt_all = dm.y                     # (N, T)

    meta_cont_all = dm.df[dm.meta_cols_cont].astype("float32").values
    meta_cat_all  = dm.df[dm.meta_cols_cat ].astype("int32").values

    # 2) Teacher predictions for all samples 
    x_all = {
        "image":     imgs_all,
        "meta_cont": meta_cont_all,
        "meta_cat":  meta_cat_all,
    }
    teacher_preds_all = teacher_model.predict(
        x_all,
        batch_size=CFG.batch_size,
        verbose=1,   # (N, T)
    )                                 

    # 3) Concatenate GT and teacher predictions: y_true_concat = [y_gt, y_teacher]
    y_concat_all = np.concatenate([y_gt_all, teacher_preds_all], axis=1)  # (N, 2T)

    # 4) Train / Val split
    val_mask = (dm.df["fold"] == fold).values
    tr_idx = np.where(~val_mask)[0]
    va_idx = np.where(val_mask)[0]

    print(f"[Student] Fold {fold} Train: {len(tr_idx)} | Val: {len(va_idx)}")

    train_ds = tf.data.Dataset.from_tensor_slices(
        (imgs_all[tr_idx], y_concat_all[tr_idx])
    )
    val_ds = tf.data.Dataset.from_tensor_slices(
        (imgs_all[va_idx], y_concat_all[va_idx])
    )

    train_ds = (
        train_ds
        .map(tfdata_augmentor, num_parallel_calls=1)
        .shuffle(1024, seed=CFG.seed, reshuffle_each_iteration=False)
        .batch(CFG.batch_size)
        .prefetch(1)
    )
    val_ds = (
        val_ds
        .map(tfdata_clip, num_parallel_calls=1)
        .batch(CFG.batch_size)
        .prefetch(1)
    )

    # 5) Build student-from-baseline + distillation loss
    mode = "log1p" if CFG.use_log1p else "gram"
    baseline_ckpt = f"./ckpt/baseline_{mode}_fold{fold}.weights.h5"

    student_model = model_fn(
        image_size_h=CFG.image_size_h,
        image_size_w=CFG.image_size_w,
        target_names=target_list,
        baseline_weights_path=baseline_ckpt,
        distill_alpha=alpha, # teacher weight in distillation loss
        distill_tau=tau,      # biomass_student_from_baseline 
        use_distill_loss=True,
        **model_kwargs,
    )

    # 6) callbacks
    callbacks_list = build_callbacks(monitor="val_mae_all", mode="min")

    # 7) train
    history = student_model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=30,
        callbacks=callbacks_list,
        verbose=1,
    )

    best_val_mae = min(history.history["val_mae_all"])
    print(f"[Student] Fold {fold} best val_mae_all = {best_val_mae:.3f}")

    # 8) Evaluate in gram space
    val_df, x_val = build_val_inputs(
        dm=dm,
        fold=fold,
        include_meta=False,   # student uses image only for inference
    )
    y_pred_default = student_model.predict(x_val, batch_size=CFG.batch_size)

    w_r2, pred_df, true_df = eval_weighted_r2_in_gram(
        val_df=val_df,
        y_pred_default=y_pred_default,
        model_name="Student",
        fold=fold,
        # target_list=target_list,
    )

    return best_val_mae, student_model, history, val_ds, w_r2

In [30]:
# ====== Train model: Distilled Student (image only)(gram) ======
set_label_mode(False)  # Set label mode to "gram"
# set_label_mode(True)  # Set label mode to "log1p"

student_results_gram = {}
student_fold_maes_gram = []
student_fold_r2_gram = []

set_seed(CFG.seed)

for f in range(CFG.n_folds):
    
    student_mae, student_model, student_hist, student_valds, student_r2 = \
        train_one_fold_student_distill(
            fold=f,
            teacher_model=teacher_models_gram[f],   # trained teacher fisrt
            alpha=0.5,
            tau=1.0,
        )
    student_results_gram[f] = (student_mae, student_r2)
    student_fold_maes_gram.append(student_mae)
    student_fold_r2_gram.append(student_r2)

print("\n===== [Student Distill] 5-fold CV summary =====")
print("MAE per fold:", np.round(student_fold_maes_gram, 3))
print("R2  per fold:", np.round(student_fold_r2_gram, 3))
print("mean R2 =", np.mean(student_fold_r2_gram))

[set_label_mode] use_log1p=False → TRAIN_TARGETS = ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
[init] fallback label_transform=identity

===== [Student Distill] Fold 0 (alpha=0.5, tau=1.0) =====
45/45 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step
[Student] Fold 0 Train: 285 | Val: 72
[Student] load baseline backbone from ./ckpt/baseline_gram_fold0.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 30s 765ms/step - loss: 358.1673 - mae__dry__clover_g: 6.7097 - mae__dry__dead_g: 11.2876 - mae__dry__green_g: 26.4126 - mae__dry__total_g: 43.8530 - mae_all: 23.9791 - mae_gdm_g: 31.6325 - val_loss: 335.0154 - val_mae__dry__clover_g: 5.6195 - val_mae__dry__dead_g: 13.1183 - val_mae__dry__green_g: 25.2691 - val_mae__dry__total_g: 43.5578 - val_mae_all: 23.4184 - val_mae_gdm_g: 29.5274 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 761ms/step - loss: 334.3819 - mae__dry__clover_g: 6.6465 - mae__dry__dead_g: 11.1237 - mae__dry__green_g: 26.4759 - mae__dry__total_g: 41.7957 - mae_all: 23.4004 - mae_gdm_g: 30.9601 - val_loss: 320.1736 - val_mae__dry__clover_g: 5.6058 - val_mae__dry__dead_g: 12.9639 - val_mae__dry__green_g: 25.2763 - val_mae__dry__total_g: 42.1608 - val_mae_all: 23.0779 - val_mae_gdm_g: 29.3827 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 306.8572 - mae__dry__clover_g: 6.7531 - mae__dry__dead_g: 10.8370 - mae__dry__green_g: 26.5231 - mae__dry__total_g: 39.1955 - mae_all: 22.6979 - mae_gdm_g: 30.1805 - val_loss: 288.3405 - val_mae__dry__clover_g: 5.6782 - val_mae__dry__dead_g: 12.7633 - val_mae__dry__green_g: 25.3852 - val_mae__dry__total_g: 39.0505 - val_mae_all: 22.2181 - val_mae_gdm_g: 28.2132 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 280.8928 - mae__dry__clover_g: 6.8790 - mae__dry__dead_g: 10.6745 - mae__dry__green_g: 26.5064 - mae__dry__total_g: 36.4355 - mae_all: 22.0015 - mae_gdm_g: 29.5120 - val_loss: 242.1057 - val_mae__dry__clover_g: 5.9028 - val_mae__dry__dead_g: 12.2570 - val_mae__dry__green_g: 25.4628 - val_mae__dry__total_g: 33.9916 - val_mae_all: 20.7513 - val_mae_gdm_g: 26.1424 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 761ms/step - loss: 250.2600 - mae__dry__clover_g: 7.2626 - mae__dry__dead_g: 10.2171 - mae__dry__green_g: 26.4710 - mae__dry__total_g: 33.3213 - mae_all: 21.0724 - mae_gdm_g: 28.0901 - val_loss: 196.9987 - val_mae__dry__clover_g: 6.4646 - val_mae__dry__dead_g: 11.3531 - val_mae__dry__green_g: 25.4929 - val_mae__dry__total_g: 28.7116 - val_mae_all: 19.1308 - val_mae_gdm_g: 23.6320 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 762ms/step - loss: 221.5533 - mae__dry__clover_g: 7.6975 - mae__dry__dead_g: 9.8623 - mae__dry__green_g: 26.4081 - mae__dry__total_g: 30.2036 - mae_all: 20.1289 - mae_gdm_g: 26.4730 - val_loss: 167.5441 - val_mae__dry__clover_g: 6.9546 - val_mae__dry__dead_g: 10.8944 - val_mae__dry__green_g: 25.4030 - val_mae__dry__total_g: 25.4892 - val_mae_all: 18.0270 - val_mae_gdm_g: 21.3941 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 761ms/step - loss: 191.5378 - mae__dry__clover_g: 8.1685 - mae__dry__dead_g: 9.5836 - mae__dry__green_g: 26.2167 - mae__dry__total_g: 27.1825 - mae_all: 19.1398 - mae_gdm_g: 24.5476 - val_loss: 151.6265 - val_mae__dry__clover_g: 7.1648 - val_mae__dry__dead_g: 10.5787 - val_mae__dry__green_g: 24.9206 - val_mae__dry__total_g: 23.8479 - val_mae_all: 17.2511 - val_mae_gdm_g: 19.7433 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 761ms/step - loss: 165.7462 - mae__dry__clover_g: 8.3706 - mae__dry__dead_g: 9.2975 - mae__dry__green_g: 25.3783 - mae__dry__total_g: 24.5124 - mae_all: 17.9736 - mae_gdm_g: 22.3089 - val_loss: 136.6405 - val_mae__dry__clover_g: 7.2336 - val_mae__dry__dead_g: 10.3149 - val_mae__dry__green_g: 23.5204 - val_mae__dry__total_g: 22.4886 - val_mae_all: 16.3572 - val_mae_gdm_g: 18.2285 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 144.0204 - mae__dry__clover_g: 8.2905 - mae__dry__dead_g: 9.0567 - mae__dry__green_g: 23.9556 - mae__dry__total_g: 22.3244 - mae_all: 16.8419 - mae_gdm_g: 20.5822 - val_loss: 127.5865 - val_mae__dry__clover_g: 7.1616 - val_mae__dry__dead_g: 10.1105 - val_mae__dry__green_g: 21.8194 - val_mae__dry__total_g: 21.8512 - val_mae_all: 15.6565 - val_mae_gdm_g: 17.3396 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 763ms/step - loss: 125.6736 - mae__dry__clover_g: 8.8480 - mae__dry__dead_g: 8.8685 - mae__dry__green_g: 22.1611 - mae__dry__total_g: 20.5401 - mae_all: 15.8695 - mae_gdm_g: 18.9299 - val_loss: 135.2778 - val_mae__dry__clover_g: 6.7969 - val_mae__dry__dead_g: 10.1735 - val_mae__dry__green_g: 20.9413 - val_mae__dry__total_g: 23.0707 - val_mae_all: 15.7636 - val_mae_gdm_g: 17.8357 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 766ms/step - loss: 107.6206 - mae__dry__clover_g: 8.6243 - mae__dry__dead_g: 8.8620 - mae__dry__green_g: 20.5732 - mae__dry__total_g: 18.7559 - mae_all: 14.8462 - mae_gdm_g: 17.4154 - val_loss: 126.4901 - val_mae__dry__clover_g: 6.7032 - val_mae__dry__dead_g: 10.0925 - val_mae__dry__green_g: 19.7973 - val_mae__dry__total_g: 22.1089 - val_mae_all: 15.1240 - val_mae_gdm_g: 16.9183 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 761ms/step - loss: 92.5317 - mae__dry__clover_g: 8.3343 - mae__dry__dead_g: 8.5038 - mae__dry__green_g: 18.9418 - mae__dry__total_g: 17.1084 - mae_all: 13.7948 - mae_gdm_g: 16.0858 - val_loss: 121.7139 - val_mae__dry__clover_g: 6.6059 - val_mae__dry__dead_g: 10.0224 - val_mae__dry__green_g: 18.8953 - val_mae__dry__total_g: 21.6391 - val_mae_all: 14.7016 - val_mae_gdm_g: 16.3454 - learning_rate: 1.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 88.2123 - mae__dry__clover_g: 8.5357 - mae__dry__dead_g: 8.7483 - mae__dry__green_g: 17.6990 - mae__dry__total_g: 16.7073 - mae_all: 13.4730 - mae_gdm_g: 15.6746 - val_loss: 105.7781 - val_mae__dry__clover_g: 6.6376 - val_mae__dry__dead_g: 9.8695 - val_mae__dry__green_g: 17.5750 - val_mae__dry__total_g: 19.8521 - val_mae_all: 13.7386 - val_mae_gdm_g: 14.7587 - learning_rate: 1.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 761ms/step - loss: 77.9184 - mae__dry__clover_g: 8.2048 - mae__dry__dead_g: 8.5614 - mae__dry__green_g: 16.9698 - mae__dry__total_g: 15.6250 - mae_all: 12.8323 - mae_gdm_g: 14.8003 - val_loss: 103.9455 - val_mae__dry__clover_g: 6.5060 - val_mae__dry__dead_g: 9.8647 - val_mae__dry__green_g: 16.9681 - val_mae__dry__total_g: 19.7561 - val_mae_all: 13.5062 - val_mae_gdm_g: 14.4359 - learning_rate: 1.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 759ms/step - loss: 69.7448 - mae__dry__clover_g: 7.6291 - mae__dry__dead_g: 8.9854 - mae__dry__green_g: 15.6257 - mae__dry__total_g: 15.0121 - mae_all: 12.2587 - mae_gdm_g: 14.0411 - val_loss: 89.4094 - val_mae__dry__clover_g: 6.6116 - val_mae__dry__dead_g: 9.6702 - val_mae__dry__green_g: 15.7430 - val_mae__dry__total_g: 18.1317 - val_mae_all: 12.6638 - val_mae_gdm_g: 13.1628 - learning_rate: 1.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 763ms/step - loss: 71.2635 - mae__dry__clover_g: 8.5728 - mae__dry__dead_g: 8.8381 - mae__dry__green_g: 15.3719 - mae__dry__total_g: 15.1206 - mae_all: 12.4355 - mae_gdm_g: 14.2743 - val_loss: 77.7556 - val_mae__dry__clover_g: 6.7108 - val_mae__dry__dead_g: 9.5912 - val_mae__dry__green_g: 14.7577 - val_mae__dry__total_g: 17.1644 - val_mae_all: 12.1141 - val_mae_gdm_g: 12.3463 - learning_rate: 1.0000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 759ms/step - loss: 62.9855 - mae__dry__clover_g: 8.3585 - mae__dry__dead_g: 8.3299 - mae__dry__green_g: 14.7621 - mae__dry__total_g: 14.7283 - mae_all: 11.9151 - mae_gdm_g: 13.3970 - val_loss: 77.7125 - val_mae__dry__clover_g: 6.5693 - val_mae__dry__dead_g: 9.5466 - val_mae__dry__green_g: 14.4410 - val_mae__dry__total_g: 17.1376 - val_mae_all: 12.0334 - val_mae_gdm_g: 12.4724 - learning_rate: 1.0000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 64.5401 - mae__dry__clover_g: 8.1261 - mae__dry__dead_g: 8.6831 - mae__dry__green_g: 14.6769 - mae__dry__total_g: 14.9926 - mae_all: 12.0475 - mae_gdm_g: 13.7588 - val_loss: 73.2264 - val_mae__dry__clover_g: 6.6235 - val_mae__dry__dead_g: 9.5684 - val_mae__dry__green_g: 13.9120 - val_mae__dry__total_g: 16.8228 - val_mae_all: 11.7823 - val_mae_gdm_g: 11.9847 - learning_rate: 1.0000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 761ms/step - loss: 62.9306 - mae__dry__clover_g: 8.1359 - mae__dry__dead_g: 8.5901 - mae__dry__green_g: 14.5181 - mae__dry__total_g: 14.7338 - mae_all: 12.0273 - mae_gdm_g: 14.1586 - val_loss: 73.2412 - val_mae__dry__clover_g: 6.4929 - val_mae__dry__dead_g: 9.5055 - val_mae__dry__green_g: 13.6961 - val_mae__dry__total_g: 16.5812 - val_mae_all: 11.6573 - val_mae_gdm_g: 12.0109 - learning_rate: 1.0000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 65.3404 - mae__dry__clover_g: 8.0179 - mae__dry__dead_g: 8.1991 - mae__dry__green_g: 14.3563 - mae__dry__total_g: 14.8431 - mae_all: 11.8485 - mae_gdm_g: 13.8259 - val_loss: 70.0277 - val_mae__dry__clover_g: 6.5313 - val_mae__dry__dead_g: 9.4480 - val_mae__dry__green_g: 13.4139 - val_mae__dry__total_g: 16.4251 - val_mae_all: 11.5536 - val_mae_gdm_g: 11.9496 - learning_rate: 1.0000e-04
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 765ms/step - loss: 60.6873 - mae__dry__clover_g: 7.8171 - mae__dry__dead_g: 8.7074 - mae__dry__green_g: 14.6701 - mae__dry__total_g: 14.8769 - mae_all: 11.9418 - mae_gdm_g: 13.6376 - val_loss: 69.1131 - val_mae__dry__clover_g: 6.5017 - val_mae__dry__dead_g: 9.4820 - val_mae__dry__green_g: 13.2562 - val_mae__dry__total_g: 16.4829 - val_mae_all: 11.5210 - val_mae_gdm_g: 11.8820 - learning_rate: 1.0000e-04
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 763ms/step - loss: 64.8361 - mae__dry__clover_g: 8.3047 - mae__dry__dead_g: 8.4801 - mae__dry__green_g: 14.3442 - mae__dry__total_g: 15.0267 - mae_all: 11.9703 - mae_gdm_g: 13.6959 - val_loss: 67.2891 - val_mae__dry__clover_g: 6.5079 - val_mae__dry__dead_g: 9.3944 - val_mae__dry__green_g: 13.1124 - val_mae__dry__total_g: 16.1762 - val_mae_all: 11.4116 - val_mae_gdm_g: 11.8673 - learning_rate: 1.0000e-04
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 762ms/step - loss: 60.1045 - mae__dry__clover_g: 8.1792 - mae__dry__dead_g: 9.0962 - mae__dry__green_g: 13.9159 - mae__dry__total_g: 14.5402 - mae_all: 11.8548 - mae_gdm_g: 13.5423 - val_loss: 64.1628 - val_mae__dry__clover_g: 6.5950 - val_mae__dry__dead_g: 9.3861 - val_mae__dry__green_g: 12.9825 - val_mae__dry__total_g: 16.0345 - val_mae_all: 11.3622 - val_mae_gdm_g: 11.8131 - learning_rate: 1.0000e-04
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 763ms/step - loss: 62.0218 - mae__dry__clover_g: 8.1341 - mae__dry__dead_g: 8.4695 - mae__dry__green_g: 14.4288 - mae__dry__total_g: 15.0596 - mae_all: 11.9122 - mae_gdm_g: 13.4692 - val_loss: 63.9052 - val_mae__dry__clover_g: 6.5047 - val_mae__dry__dead_g: 9.3346 - val_mae__dry__green_g: 13.0735 - val_mae__dry__total_g: 15.8711 - val_mae_all: 11.3654 - val_mae_gdm_g: 12.0433 - learning_rate: 1.0000e-04
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 763ms/step - loss: 60.2388 - mae__dry__clover_g: 8.2068 - mae__dry__dead_g: 8.5763 - mae__dry__green_g: 13.9449 - mae__dry__total_g: 14.7134 - mae_all: 11.7470 - mae_gdm_g: 13.2935 - val_loss: 64.1227 - val_mae__dry__clover_g: 6.5635 - val_mae__dry__dead_g: 9.3414 - val_mae__dry__green_g: 12.9205 - val_mae__dry__total_g: 15.9605 - val_mae_all: 11.3054 - val_mae_gdm_g: 11.7411 - learning_rate: 1.0000e-04
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 761ms/step - loss: 60.5941 - mae__dry__clover_g: 7.9776 - mae__dry__dead_g: 8.3250 - mae__dry__green_g: 14.6289 - mae__dry__total_g: 14.4686 - mae_all: 11.7949 - mae_gdm_g: 13.5744 - val_loss: 67.5987 - val_mae__dry__clover_g: 6.4534 - val_mae__dry__dead_g: 9.3846 - val_mae__dry__green_g: 12.7921 - val_mae__dry__total_g: 16.1575 - val_mae_all: 11.2740 - val_mae_gdm_g: 11.5826 - learning_rate: 1.0000e-04
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 61.1430 - mae__dry__clover_g: 8.2317 - mae__dry__dead_g: 8.5339 - mae__dry__green_g: 14.0240 - mae__dry__total_g: 14.6863 - mae_all: 11.7616 - mae_gdm_g: 13.3321 - val_loss: 61.3405 - val_mae__dry__clover_g: 6.6862 - val_mae__dry__dead_g: 9.2788 - val_mae__dry__green_g: 13.7109 - val_mae__dry__total_g: 16.1478 - val_mae_all: 11.6929 - val_mae_gdm_g: 12.6409 - learning_rate: 1.0000e-04
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 708ms/step - loss: 53.8837 - mae__dry__clover_g: 8.2140 - mae__dry__dead_g: 8.0796 - mae__dry__green_g: 13.3346 - mae__dry__total_g: 14.3091 - mae_all: 11.3084 - mae_gdm_g: 12.6048
Epoch 28: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 759ms/step - loss: 61.5259 - mae__dry__clover_g: 7.8417 - mae__dry__dead_g: 8.1997 - mae__dry__green_g: 14.4267 - mae__dry__total_g: 14.8944 - mae_all: 11.7791 - mae_gdm_g: 13.5330 - val_loss: 62.5809 - val_mae__dry__clover_g: 6.4392 - val_mae__dry__dead_g: 9.2664 - val_mae__dry__green_g: 13.0900 - val_mae__dry__total_g: 15.8593 - val_mae_all: 11.3182 - val_mae_gdm_g: 11.9362 - learning_rate: 1.0000e-04
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 61.4173 - mae__dry__clover_g: 7.7309 - mae__dry__dead_g: 8.3708 - mae__dry__green_g: 14.3174 - mae__dry__total_g: 14.6908 - mae_all: 11.7768 - mae_gdm_g: 13.7743 - val_loss: 63.7114 - val_mae__dry__clover_g: 6.4143 - val_mae__dry__dead_g: 9.2387 - val_mae__dry__green_g: 12.8375 - val_mae__dry__total_g: 15.8757 - val_mae_all: 11.2101 - val_mae_gdm_g: 11.6843 - learning_rate: 5.0000e-05
Epoch 30/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 759ms/step - loss: 58.2191 - mae__dry__clover_g: 8.1166 - mae__dry__dead_g: 8.4206 - mae__dry__green_g: 13.6826 - mae__dry__total_g: 14.2302 - mae_all: 11.5332 - mae_gdm_g: 13.2161 - val_loss: 62.4237 - val_mae__dry__clover_g: 6.4161 - val_mae__dry__dead_g: 9.1318 - val_mae__dry__green_g: 13.0876 - val_mae__dry__total_g: 15.6321 - val_mae_all: 11.2532 - val_mae_gdm_g: 11.9985 - learning_rate: 5.0000e-05
Restoring model weights from the end of the best epoch: 29.
[Student] Fold 0 best val_mae_all = 11.210
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 198ms/step
[Student] Fold 0 Kaggle-style weighted R2 = 0.4715

===== [Student Distill] Fold 1 (alpha=0.5, tau=1.0) =====
45/45 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step
[Student] Fold 1 Train: 285 | Val: 72
[Student] load baseline backbone from ./ckpt/baseline_gram_fold1.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 30s 764ms/step - loss: 360.5936 - mae__dry__clover_g: 6.3729 - mae__dry__dead_g: 11.4139 - mae__dry__green_g: 26.4001 - mae__dry__total_g: 44.4755 - mae_all: 24.1747 - mae_gdm_g: 32.2113 - val_loss: 331.4297 - val_mae__dry__clover_g: 7.0454 - val_mae__dry__dead_g: 10.3648 - val_mae__dry__green_g: 25.3204 - val_mae__dry__total_g: 42.9328 - val_mae_all: 23.6080 - val_mae_gdm_g: 32.3769 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 752ms/step - loss: 339.2737 - mae__dry__clover_g: 6.3686 - mae__dry__dead_g: 11.0435 - mae__dry__green_g: 26.4299 - mae__dry__total_g: 42.3628 - mae_all: 23.6017 - mae_gdm_g: 31.8038 - val_loss: 309.7262 - val_mae__dry__clover_g: 7.0490 - val_mae__dry__dead_g: 9.8922 - val_mae__dry__green_g: 25.2560 - val_mae__dry__total_g: 40.5313 - val_mae_all: 22.9724 - val_mae_gdm_g: 32.1336 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 309.6623 - mae__dry__clover_g: 6.3601 - mae__dry__dead_g: 10.5425 - mae__dry__green_g: 26.4240 - mae__dry__total_g: 39.2866 - mae_all: 22.7523 - mae_gdm_g: 31.1484 - val_loss: 283.8212 - val_mae__dry__clover_g: 7.0820 - val_mae__dry__dead_g: 9.4331 - val_mae__dry__green_g: 25.2059 - val_mae__dry__total_g: 37.6500 - val_mae_all: 22.1636 - val_mae_gdm_g: 31.4471 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 276.4005 - mae__dry__clover_g: 6.3708 - mae__dry__dead_g: 9.9763 - mae__dry__green_g: 26.2917 - mae__dry__total_g: 35.9008 - mae_all: 21.6145 - mae_gdm_g: 29.5329 - val_loss: 250.0234 - val_mae__dry__clover_g: 7.2142 - val_mae__dry__dead_g: 9.0976 - val_mae__dry__green_g: 25.0820 - val_mae__dry__total_g: 33.9149 - val_mae_all: 21.0186 - val_mae_gdm_g: 29.7841 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 244.7730 - mae__dry__clover_g: 6.4842 - mae__dry__dead_g: 9.6371 - mae__dry__green_g: 26.0268 - mae__dry__total_g: 32.5297 - mae_all: 20.4150 - mae_gdm_g: 27.3971 - val_loss: 214.2526 - val_mae__dry__clover_g: 7.4525 - val_mae__dry__dead_g: 9.0751 - val_mae__dry__green_g: 24.8416 - val_mae__dry__total_g: 29.8761 - val_mae_all: 19.6966 - val_mae_gdm_g: 27.2378 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 212.4581 - mae__dry__clover_g: 6.5539 - mae__dry__dead_g: 9.3859 - mae__dry__green_g: 25.3919 - mae__dry__total_g: 29.2728 - mae_all: 19.1350 - mae_gdm_g: 25.0704 - val_loss: 180.0934 - val_mae__dry__clover_g: 7.7321 - val_mae__dry__dead_g: 9.4538 - val_mae__dry__green_g: 24.0994 - val_mae__dry__total_g: 26.1083 - val_mae_all: 18.3344 - val_mae_gdm_g: 24.2783 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 761ms/step - loss: 183.6140 - mae__dry__clover_g: 7.1971 - mae__dry__dead_g: 9.5659 - mae__dry__green_g: 24.3310 - mae__dry__total_g: 26.1918 - mae_all: 18.0169 - mae_gdm_g: 22.7986 - val_loss: 150.2301 - val_mae__dry__clover_g: 7.9778 - val_mae__dry__dead_g: 10.1123 - val_mae__dry__green_g: 22.9027 - val_mae__dry__total_g: 22.8405 - val_mae_all: 17.0332 - val_mae_gdm_g: 21.3327 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 158.9019 - mae__dry__clover_g: 7.5246 - mae__dry__dead_g: 9.7909 - mae__dry__green_g: 22.9352 - mae__dry__total_g: 23.5113 - mae_all: 16.8411 - mae_gdm_g: 20.4434 - val_loss: 126.2926 - val_mae__dry__clover_g: 8.1457 - val_mae__dry__dead_g: 10.6097 - val_mae__dry__green_g: 21.5497 - val_mae__dry__total_g: 20.2506 - val_mae_all: 15.8848 - val_mae_gdm_g: 18.8686 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 137.5548 - mae__dry__clover_g: 7.3821 - mae__dry__dead_g: 10.1400 - mae__dry__green_g: 21.4559 - mae__dry__total_g: 21.5593 - mae_all: 15.8188 - mae_gdm_g: 18.5567 - val_loss: 105.9897 - val_mae__dry__clover_g: 8.3205 - val_mae__dry__dead_g: 10.9581 - val_mae__dry__green_g: 20.1598 - val_mae__dry__total_g: 18.0793 - val_mae_all: 14.8399 - val_mae_gdm_g: 16.6818 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 119.6686 - mae__dry__clover_g: 7.5378 - mae__dry__dead_g: 9.9197 - mae__dry__green_g: 19.8934 - mae__dry__total_g: 19.7640 - mae_all: 14.7946 - mae_gdm_g: 16.8583 - val_loss: 90.6544 - val_mae__dry__clover_g: 8.4393 - val_mae__dry__dead_g: 10.9740 - val_mae__dry__green_g: 18.8237 - val_mae__dry__total_g: 16.1424 - val_mae_all: 13.8800 - val_mae_gdm_g: 15.0205 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 108.0919 - mae__dry__clover_g: 8.1123 - mae__dry__dead_g: 10.4130 - mae__dry__green_g: 18.3228 - mae__dry__total_g: 19.1601 - mae_all: 14.4073 - mae_gdm_g: 16.0286 - val_loss: 86.2276 - val_mae__dry__clover_g: 8.3080 - val_mae__dry__dead_g: 10.6708 - val_mae__dry__green_g: 18.1485 - val_mae__dry__total_g: 16.0411 - val_mae_all: 13.5552 - val_mae_gdm_g: 14.6074 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 100.8261 - mae__dry__clover_g: 7.9727 - mae__dry__dead_g: 9.7309 - mae__dry__green_g: 17.6033 - mae__dry__total_g: 18.9793 - mae_all: 13.9107 - mae_gdm_g: 15.2671 - val_loss: 83.8737 - val_mae__dry__clover_g: 8.1710 - val_mae__dry__dead_g: 10.3498 - val_mae__dry__green_g: 17.6243 - val_mae__dry__total_g: 16.0623 - val_mae_all: 13.3589 - val_mae_gdm_g: 14.5872 - learning_rate: 1.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 91.8294 - mae__dry__clover_g: 8.0151 - mae__dry__dead_g: 9.9833 - mae__dry__green_g: 16.5234 - mae__dry__total_g: 18.2590 - mae_all: 13.5582 - mae_gdm_g: 15.0099 - val_loss: 82.1017 - val_mae__dry__clover_g: 7.9736 - val_mae__dry__dead_g: 10.1045 - val_mae__dry__green_g: 17.1492 - val_mae__dry__total_g: 16.1248 - val_mae_all: 13.1575 - val_mae_gdm_g: 14.4351 - learning_rate: 1.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 89.8897 - mae__dry__clover_g: 7.9323 - mae__dry__dead_g: 9.9829 - mae__dry__green_g: 15.9012 - mae__dry__total_g: 18.5004 - mae_all: 13.5122 - mae_gdm_g: 15.2444 - val_loss: 81.5671 - val_mae__dry__clover_g: 7.8188 - val_mae__dry__dead_g: 9.8285 - val_mae__dry__green_g: 16.8614 - val_mae__dry__total_g: 16.3002 - val_mae_all: 13.0629 - val_mae_gdm_g: 14.5054 - learning_rate: 1.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 85.6620 - mae__dry__clover_g: 7.9317 - mae__dry__dead_g: 9.8179 - mae__dry__green_g: 15.6024 - mae__dry__total_g: 18.1402 - mae_all: 13.2050 - mae_gdm_g: 14.5328 - val_loss: 80.3495 - val_mae__dry__clover_g: 7.7463 - val_mae__dry__dead_g: 9.6403 - val_mae__dry__green_g: 16.5858 - val_mae__dry__total_g: 16.2353 - val_mae_all: 12.9049 - val_mae_gdm_g: 14.3169 - learning_rate: 1.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 80.3467 - mae__dry__clover_g: 7.8799 - mae__dry__dead_g: 9.6484 - mae__dry__green_g: 15.0568 - mae__dry__total_g: 17.8086 - mae_all: 13.0587 - mae_gdm_g: 14.8999 - val_loss: 76.2332 - val_mae__dry__clover_g: 7.7430 - val_mae__dry__dead_g: 9.6327 - val_mae__dry__green_g: 16.0358 - val_mae__dry__total_g: 15.8962 - val_mae_all: 12.6693 - val_mae_gdm_g: 14.0389 - learning_rate: 1.0000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 84.5019 - mae__dry__clover_g: 7.2917 - mae__dry__dead_g: 9.4644 - mae__dry__green_g: 15.2469 - mae__dry__total_g: 18.4182 - mae_all: 13.1277 - mae_gdm_g: 15.2171 - val_loss: 73.9037 - val_mae__dry__clover_g: 7.7120 - val_mae__dry__dead_g: 9.6014 - val_mae__dry__green_g: 15.6858 - val_mae__dry__total_g: 15.9489 - val_mae_all: 12.5953 - val_mae_gdm_g: 14.0282 - learning_rate: 1.0000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 78.4792 - mae__dry__clover_g: 7.2927 - mae__dry__dead_g: 9.6771 - mae__dry__green_g: 14.7387 - mae__dry__total_g: 18.3544 - mae_all: 13.0036 - mae_gdm_g: 14.9550 - val_loss: 74.6554 - val_mae__dry__clover_g: 7.6014 - val_mae__dry__dead_g: 9.4176 - val_mae__dry__green_g: 15.6864 - val_mae__dry__total_g: 16.1023 - val_mae_all: 12.5846 - val_mae_gdm_g: 14.1153 - learning_rate: 1.0000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 83.9051 - mae__dry__clover_g: 7.4159 - mae__dry__dead_g: 9.2318 - mae__dry__green_g: 15.7262 - mae__dry__total_g: 18.4643 - mae_all: 13.2591 - mae_gdm_g: 15.4572 - val_loss: 71.3823 - val_mae__dry__clover_g: 7.6109 - val_mae__dry__dead_g: 9.4189 - val_mae__dry__green_g: 15.1932 - val_mae__dry__total_g: 15.9361 - val_mae_all: 12.3963 - val_mae_gdm_g: 13.8223 - learning_rate: 1.0000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 80.8972 - mae__dry__clover_g: 7.6691 - mae__dry__dead_g: 9.2774 - mae__dry__green_g: 14.9626 - mae__dry__total_g: 18.0798 - mae_all: 13.0297 - mae_gdm_g: 15.1593 - val_loss: 73.1302 - val_mae__dry__clover_g: 7.4712 - val_mae__dry__dead_g: 9.2871 - val_mae__dry__green_g: 15.3845 - val_mae__dry__total_g: 15.9987 - val_mae_all: 12.4243 - val_mae_gdm_g: 13.9801 - learning_rate: 1.0000e-04
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 706ms/step - loss: 74.6590 - mae__dry__clover_g: 8.7006 - mae__dry__dead_g: 9.5338 - mae__dry__green_g: 14.6614 - mae__dry__total_g: 18.6674 - mae_all: 13.4269 - mae_gdm_g: 15.5711
Epoch 21: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 80.0342 - mae__dry__clover_g: 7.4352 - mae__dry__dead_g: 9.3810 - mae__dry__green_g: 15.2785 - mae__dry__total_g: 18.4347 - mae_all: 13.1960 - mae_gdm_g: 15.4506 - val_loss: 72.6290 - val_mae__dry__clover_g: 7.4860 - val_mae__dry__dead_g: 9.2558 - val_mae__dry__green_g: 15.3764 - val_mae__dry__total_g: 16.0556 - val_mae_all: 12.4438 - val_mae_gdm_g: 14.0452 - learning_rate: 1.0000e-04
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 78.8312 - mae__dry__clover_g: 7.4227 - mae__dry__dead_g: 9.2597 - mae__dry__green_g: 14.7690 - mae__dry__total_g: 18.1611 - mae_all: 12.8780 - mae_gdm_g: 14.7776 - val_loss: 70.3431 - val_mae__dry__clover_g: 7.5283 - val_mae__dry__dead_g: 9.3096 - val_mae__dry__green_g: 15.1484 - val_mae__dry__total_g: 15.9329 - val_mae_all: 12.3723 - val_mae_gdm_g: 13.9424 - learning_rate: 5.0000e-05
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 75.5442 - mae__dry__clover_g: 7.5163 - mae__dry__dead_g: 9.6837 - mae__dry__green_g: 14.7530 - mae__dry__total_g: 17.2672 - mae_all: 12.7885 - mae_gdm_g: 14.7222 - val_loss: 68.5103 - val_mae__dry__clover_g: 7.5667 - val_mae__dry__dead_g: 9.3707 - val_mae__dry__green_g: 14.9697 - val_mae__dry__total_g: 15.8976 - val_mae_all: 12.3356 - val_mae_gdm_g: 13.8735 - learning_rate: 5.0000e-05
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 75.2222 - mae__dry__clover_g: 7.6099 - mae__dry__dead_g: 9.8800 - mae__dry__green_g: 15.0248 - mae__dry__total_g: 17.6939 - mae_all: 13.0778 - mae_gdm_g: 15.1806 - val_loss: 67.5989 - val_mae__dry__clover_g: 7.5598 - val_mae__dry__dead_g: 9.3417 - val_mae__dry__green_g: 14.9376 - val_mae__dry__total_g: 15.9606 - val_mae_all: 12.3361 - val_mae_gdm_g: 13.8809 - learning_rate: 5.0000e-05
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 705ms/step - loss: 68.4442 - mae__dry__clover_g: 8.6820 - mae__dry__dead_g: 9.5828 - mae__dry__green_g: 14.1327 - mae__dry__total_g: 17.7898 - mae_all: 12.9766 - mae_gdm_g: 14.6958
Epoch 25: ReduceLROnPlateau reducing learning rate to 2.499999936844688e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 76.9300 - mae__dry__clover_g: 7.3970 - mae__dry__dead_g: 9.2062 - mae__dry__green_g: 15.1064 - mae__dry__total_g: 17.8822 - mae_all: 12.9123 - mae_gdm_g: 14.9697 - val_loss: 67.2649 - val_mae__dry__clover_g: 7.5974 - val_mae__dry__dead_g: 9.4356 - val_mae__dry__green_g: 14.8754 - val_mae__dry__total_g: 16.1417 - val_mae_all: 12.3998 - val_mae_gdm_g: 13.9488 - learning_rate: 5.0000e-05
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 75.5376 - mae__dry__clover_g: 7.5891 - mae__dry__dead_g: 9.5521 - mae__dry__green_g: 14.7121 - mae__dry__total_g: 17.8349 - mae_all: 12.9680 - mae_gdm_g: 15.1517 - val_loss: 67.2991 - val_mae__dry__clover_g: 7.5912 - val_mae__dry__dead_g: 9.4685 - val_mae__dry__green_g: 14.8333 - val_mae__dry__total_g: 16.1960 - val_mae_all: 12.4059 - val_mae_gdm_g: 13.9406 - learning_rate: 2.5000e-05
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 706ms/step - loss: 69.9631 - mae__dry__clover_g: 8.9956 - mae__dry__dead_g: 9.5507 - mae__dry__green_g: 14.4819 - mae__dry__total_g: 17.7733 - mae_all: 13.2070 - mae_gdm_g: 15.2333
Epoch 27: ReduceLROnPlateau reducing learning rate to 1.249999968422344e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 75.4149 - mae__dry__clover_g: 7.2835 - mae__dry__dead_g: 9.5346 - mae__dry__green_g: 14.8476 - mae__dry__total_g: 17.5066 - mae_all: 12.8064 - mae_gdm_g: 14.8598 - val_loss: 67.1636 - val_mae__dry__clover_g: 7.5802 - val_mae__dry__dead_g: 9.4760 - val_mae__dry__green_g: 14.8395 - val_mae__dry__total_g: 16.2132 - val_mae_all: 12.4122 - val_mae_gdm_g: 13.9521 - learning_rate: 2.5000e-05
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 75.2282 - mae__dry__clover_g: 7.6148 - mae__dry__dead_g: 9.6175 - mae__dry__green_g: 14.9221 - mae__dry__total_g: 17.7224 - mae_all: 12.9093 - mae_gdm_g: 14.6695 - val_loss: 67.0796 - val_mae__dry__clover_g: 7.5797 - val_mae__dry__dead_g: 9.4922 - val_mae__dry__green_g: 14.8293 - val_mae__dry__total_g: 16.2571 - val_mae_all: 12.4293 - val_mae_gdm_g: 13.9880 - learning_rate: 1.2500e-05
Epoch 28: early stopping
Restoring model weights from the end of the best epoch: 23.
[Student] Fold 1 best val_mae_all = 12.336
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 199ms/step
[Student] Fold 1 Kaggle-style weighted R2 = 0.3994

===== [Student Distill] Fold 2 (alpha=0.5, tau=1.0) =====
45/45 ━━━━━━━━━━━━━━━━━━━━ 9s 203ms/step
[Student] Fold 2 Train: 286 | Val: 71
[Student] load baseline backbone from ./ckpt/baseline_gram_fold2.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 31s 802ms/step - loss: 333.5544 - mae__dry__clover_g: 6.2506 - mae__dry__dead_g: 11.9917 - mae__dry__green_g: 24.8854 - mae__dry__total_g: 43.1721 - mae_all: 23.5632 - mae_gdm_g: 31.5163 - val_loss: 369.1415 - val_mae__dry__clover_g: 7.4941 - val_mae__dry__dead_g: 9.8263 - val_mae__dry__green_g: 27.8348 - val_mae__dry__total_g: 43.5034 - val_mae_all: 24.8300 - val_mae_gdm_g: 35.4912 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 790ms/step - loss: 304.0817 - mae__dry__clover_g: 6.2171 - mae__dry__dead_g: 11.8372 - mae__dry__green_g: 24.3086 - mae__dry__total_g: 40.4529 - mae_all: 22.7611 - mae_gdm_g: 30.9896 - val_loss: 319.5610 - val_mae__dry__clover_g: 7.4404 - val_mae__dry__dead_g: 9.6271 - val_mae__dry__green_g: 26.7611 - val_mae__dry__total_g: 39.1147 - val_mae_all: 23.4804 - val_mae_gdm_g: 34.4584 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 785ms/step - loss: 268.8802 - mae__dry__clover_g: 6.2177 - mae__dry__dead_g: 11.4681 - mae__dry__green_g: 23.3253 - mae__dry__total_g: 37.0109 - mae_all: 21.6123 - mae_gdm_g: 30.0393 - val_loss: 252.8319 - val_mae__dry__clover_g: 7.3978 - val_mae__dry__dead_g: 9.0712 - val_mae__dry__green_g: 24.7759 - val_mae__dry__total_g: 32.6446 - val_mae_all: 21.2491 - val_mae_gdm_g: 32.3560 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 788ms/step - loss: 233.3324 - mae__dry__clover_g: 6.3390 - mae__dry__dead_g: 11.0289 - mae__dry__green_g: 22.2106 - mae__dry__total_g: 33.3777 - mae_all: 20.3038 - mae_gdm_g: 28.5627 - val_loss: 183.8246 - val_mae__dry__clover_g: 7.4085 - val_mae__dry__dead_g: 8.3676 - val_mae__dry__green_g: 22.1142 - val_mae__dry__total_g: 25.6070 - val_mae_all: 18.4848 - val_mae_gdm_g: 28.9267 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 786ms/step - loss: 195.5294 - mae__dry__clover_g: 6.3236 - mae__dry__dead_g: 10.4654 - mae__dry__green_g: 21.0821 - mae__dry__total_g: 29.2813 - mae_all: 18.7513 - mae_gdm_g: 26.6040 - val_loss: 144.4036 - val_mae__dry__clover_g: 7.4523 - val_mae__dry__dead_g: 8.2028 - val_mae__dry__green_g: 20.1568 - val_mae__dry__total_g: 21.8213 - val_mae_all: 16.7155 - val_mae_gdm_g: 25.9444 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 789ms/step - loss: 162.7107 - mae__dry__clover_g: 6.3941 - mae__dry__dead_g: 9.9359 - mae__dry__green_g: 19.5263 - mae__dry__total_g: 25.4749 - mae_all: 17.1393 - mae_gdm_g: 24.3652 - val_loss: 132.1569 - val_mae__dry__clover_g: 7.5418 - val_mae__dry__dead_g: 8.1786 - val_mae__dry__green_g: 19.4720 - val_mae__dry__total_g: 21.2306 - val_mae_all: 16.2155 - val_mae_gdm_g: 24.6547 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 788ms/step - loss: 135.2177 - mae__dry__clover_g: 6.7733 - mae__dry__dead_g: 9.8834 - mae__dry__green_g: 17.8544 - mae__dry__total_g: 22.1908 - mae_all: 15.7427 - mae_gdm_g: 22.0115 - val_loss: 125.4669 - val_mae__dry__clover_g: 7.6232 - val_mae__dry__dead_g: 8.0936 - val_mae__dry__green_g: 18.9865 - val_mae__dry__total_g: 21.0184 - val_mae_all: 15.8708 - val_mae_gdm_g: 23.6326 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 787ms/step - loss: 110.2101 - mae__dry__clover_g: 6.6824 - mae__dry__dead_g: 9.7092 - mae__dry__green_g: 16.3715 - mae__dry__total_g: 20.1222 - mae_all: 14.5143 - mae_gdm_g: 19.6865 - val_loss: 124.3150 - val_mae__dry__clover_g: 7.6603 - val_mae__dry__dead_g: 7.9918 - val_mae__dry__green_g: 18.8306 - val_mae__dry__total_g: 21.3075 - val_mae_all: 15.7872 - val_mae_gdm_g: 23.1459 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 95.2983 - mae__dry__clover_g: 6.9952 - mae__dry__dead_g: 9.8246 - mae__dry__green_g: 15.3065 - mae__dry__total_g: 18.4226 - mae_all: 13.6835 - mae_gdm_g: 17.8687 - val_loss: 127.8923 - val_mae__dry__clover_g: 7.6792 - val_mae__dry__dead_g: 7.8733 - val_mae__dry__green_g: 18.8923 - val_mae__dry__total_g: 21.8917 - val_mae_all: 15.8831 - val_mae_gdm_g: 23.0789 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 82.0265 - mae__dry__clover_g: 7.2337 - mae__dry__dead_g: 9.6745 - mae__dry__green_g: 14.7040 - mae__dry__total_g: 16.6887 - mae_all: 12.8628 - mae_gdm_g: 16.0128 - val_loss: 118.2775 - val_mae__dry__clover_g: 7.7400 - val_mae__dry__dead_g: 7.8965 - val_mae__dry__green_g: 18.2571 - val_mae__dry__total_g: 21.1874 - val_mae_all: 15.4189 - val_mae_gdm_g: 22.0137 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 75.2388 - mae__dry__clover_g: 7.4201 - mae__dry__dead_g: 9.6819 - mae__dry__green_g: 14.3516 - mae__dry__total_g: 16.2668 - mae_all: 12.5779 - mae_gdm_g: 15.1692 - val_loss: 117.7430 - val_mae__dry__clover_g: 7.7697 - val_mae__dry__dead_g: 7.8081 - val_mae__dry__green_g: 18.2506 - val_mae__dry__total_g: 21.4430 - val_mae_all: 15.4162 - val_mae_gdm_g: 21.8098 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 68.5864 - mae__dry__clover_g: 7.2575 - mae__dry__dead_g: 9.8119 - mae__dry__green_g: 14.1495 - mae__dry__total_g: 15.5307 - mae_all: 12.2169 - mae_gdm_g: 14.3347 - val_loss: 98.4409 - val_mae__dry__clover_g: 7.9040 - val_mae__dry__dead_g: 7.8632 - val_mae__dry__green_g: 17.0062 - val_mae__dry__total_g: 19.3728 - val_mae_all: 14.3996 - val_mae_gdm_g: 19.8520 - learning_rate: 1.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 62.8798 - mae__dry__clover_g: 7.3941 - mae__dry__dead_g: 9.5017 - mae__dry__green_g: 13.2586 - mae__dry__total_g: 15.6927 - mae_all: 11.8759 - mae_gdm_g: 13.5324 - val_loss: 96.8901 - val_mae__dry__clover_g: 7.8902 - val_mae__dry__dead_g: 7.8190 - val_mae__dry__green_g: 16.8410 - val_mae__dry__total_g: 19.3682 - val_mae_all: 14.2692 - val_mae_gdm_g: 19.4273 - learning_rate: 1.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 58.3077 - mae__dry__clover_g: 7.6097 - mae__dry__dead_g: 9.6970 - mae__dry__green_g: 13.8635 - mae__dry__total_g: 15.1900 - mae_all: 11.9453 - mae_gdm_g: 13.3665 - val_loss: 86.8219 - val_mae__dry__clover_g: 7.9136 - val_mae__dry__dead_g: 7.8492 - val_mae__dry__green_g: 16.1390 - val_mae__dry__total_g: 18.4620 - val_mae_all: 13.7088 - val_mae_gdm_g: 18.1802 - learning_rate: 1.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 58.9145 - mae__dry__clover_g: 7.5513 - mae__dry__dead_g: 9.3172 - mae__dry__green_g: 13.8446 - mae__dry__total_g: 15.8004 - mae_all: 11.8812 - mae_gdm_g: 12.8923 - val_loss: 79.7405 - val_mae__dry__clover_g: 7.9552 - val_mae__dry__dead_g: 7.9011 - val_mae__dry__green_g: 15.6080 - val_mae__dry__total_g: 17.6813 - val_mae_all: 13.2528 - val_mae_gdm_g: 17.1183 - learning_rate: 1.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 58.6940 - mae__dry__clover_g: 7.4080 - mae__dry__dead_g: 9.8412 - mae__dry__green_g: 13.6177 - mae__dry__total_g: 15.4632 - mae_all: 11.9071 - mae_gdm_g: 13.2054 - val_loss: 66.3227 - val_mae__dry__clover_g: 8.1150 - val_mae__dry__dead_g: 8.0016 - val_mae__dry__green_g: 14.8183 - val_mae__dry__total_g: 16.2228 - val_mae_all: 12.5612 - val_mae_gdm_g: 15.6485 - learning_rate: 1.0000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 58.1673 - mae__dry__clover_g: 7.7135 - mae__dry__dead_g: 9.4093 - mae__dry__green_g: 13.5954 - mae__dry__total_g: 15.4536 - mae_all: 11.8252 - mae_gdm_g: 12.9543 - val_loss: 60.6326 - val_mae__dry__clover_g: 8.1705 - val_mae__dry__dead_g: 8.1655 - val_mae__dry__green_g: 14.1753 - val_mae__dry__total_g: 15.5286 - val_mae_all: 12.2002 - val_mae_gdm_g: 14.9612 - learning_rate: 1.0000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 58.2159 - mae__dry__clover_g: 7.6115 - mae__dry__dead_g: 9.7546 - mae__dry__green_g: 13.7599 - mae__dry__total_g: 15.6192 - mae_all: 11.9452 - mae_gdm_g: 12.9809 - val_loss: 72.3159 - val_mae__dry__clover_g: 7.9640 - val_mae__dry__dead_g: 7.8677 - val_mae__dry__green_g: 15.0784 - val_mae__dry__total_g: 17.0180 - val_mae_all: 12.7550 - val_mae_gdm_g: 15.8468 - learning_rate: 1.0000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 702ms/step - loss: 61.4681 - mae__dry__clover_g: 8.2295 - mae__dry__dead_g: 9.1639 - mae__dry__green_g: 14.1219 - mae__dry__total_g: 16.1786 - mae_all: 12.3943 - mae_gdm_g: 14.2776
Epoch 19: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 752ms/step - loss: 55.2440 - mae__dry__clover_g: 7.2072 - mae__dry__dead_g: 9.2846 - mae__dry__green_g: 13.6056 - mae__dry__total_g: 15.2659 - mae_all: 11.7242 - mae_gdm_g: 13.2576 - val_loss: 61.1108 - val_mae__dry__clover_g: 8.1058 - val_mae__dry__dead_g: 8.1017 - val_mae__dry__green_g: 14.5932 - val_mae__dry__total_g: 15.6425 - val_mae_all: 12.2423 - val_mae_gdm_g: 14.7684 - learning_rate: 1.0000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 56.8293 - mae__dry__clover_g: 7.7074 - mae__dry__dead_g: 9.9024 - mae__dry__green_g: 13.4475 - mae__dry__total_g: 15.3110 - mae_all: 11.8975 - mae_gdm_g: 13.1191 - val_loss: 59.0712 - val_mae__dry__clover_g: 8.1275 - val_mae__dry__dead_g: 8.1634 - val_mae__dry__green_g: 14.3266 - val_mae__dry__total_g: 15.4675 - val_mae_all: 12.1225 - val_mae_gdm_g: 14.5276 - learning_rate: 5.0000e-05
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 55.9195 - mae__dry__clover_g: 7.4380 - mae__dry__dead_g: 9.3051 - mae__dry__green_g: 13.6938 - mae__dry__total_g: 15.3683 - mae_all: 11.6809 - mae_gdm_g: 12.5995 - val_loss: 57.8184 - val_mae__dry__clover_g: 8.1808 - val_mae__dry__dead_g: 8.2137 - val_mae__dry__green_g: 14.4348 - val_mae__dry__total_g: 15.3602 - val_mae_all: 12.1476 - val_mae_gdm_g: 14.5483 - learning_rate: 5.0000e-05
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 55.8220 - mae__dry__clover_g: 7.8335 - mae__dry__dead_g: 9.5333 - mae__dry__green_g: 13.8518 - mae__dry__total_g: 15.1459 - mae_all: 11.8716 - mae_gdm_g: 12.9938 - val_loss: 55.6497 - val_mae__dry__clover_g: 8.2395 - val_mae__dry__dead_g: 8.3383 - val_mae__dry__green_g: 14.3744 - val_mae__dry__total_g: 15.2003 - val_mae_all: 12.1136 - val_mae_gdm_g: 14.4156 - learning_rate: 5.0000e-05
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 753ms/step - loss: 53.7631 - mae__dry__clover_g: 7.3227 - mae__dry__dead_g: 9.6504 - mae__dry__green_g: 13.4967 - mae__dry__total_g: 15.0738 - mae_all: 11.6520 - mae_gdm_g: 12.7162 - val_loss: 57.2302 - val_mae__dry__clover_g: 8.1461 - val_mae__dry__dead_g: 8.1680 - val_mae__dry__green_g: 14.3430 - val_mae__dry__total_g: 15.2264 - val_mae_all: 12.0713 - val_mae_gdm_g: 14.4731 - learning_rate: 5.0000e-05
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 54.8142 - mae__dry__clover_g: 7.5204 - mae__dry__dead_g: 9.4142 - mae__dry__green_g: 13.8330 - mae__dry__total_g: 15.2639 - mae_all: 11.8319 - mae_gdm_g: 13.1280 - val_loss: 55.8365 - val_mae__dry__clover_g: 8.1720 - val_mae__dry__dead_g: 8.2670 - val_mae__dry__green_g: 14.2504 - val_mae__dry__total_g: 15.0936 - val_mae_all: 12.0230 - val_mae_gdm_g: 14.3319 - learning_rate: 5.0000e-05
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 54.8327 - mae__dry__clover_g: 7.6487 - mae__dry__dead_g: 9.5881 - mae__dry__green_g: 13.0309 - mae__dry__total_g: 15.1486 - mae_all: 11.6836 - mae_gdm_g: 13.0018 - val_loss: 56.6292 - val_mae__dry__clover_g: 8.0945 - val_mae__dry__dead_g: 8.2018 - val_mae__dry__green_g: 14.2721 - val_mae__dry__total_g: 15.1666 - val_mae_all: 11.9990 - val_mae_gdm_g: 14.2600 - learning_rate: 5.0000e-05
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 52.1932 - mae__dry__clover_g: 7.3159 - mae__dry__dead_g: 9.6024 - mae__dry__green_g: 13.1946 - mae__dry__total_g: 14.8855 - mae_all: 11.5561 - mae_gdm_g: 12.7822 - val_loss: 56.2891 - val_mae__dry__clover_g: 8.0881 - val_mae__dry__dead_g: 8.1700 - val_mae__dry__green_g: 14.3260 - val_mae__dry__total_g: 15.1077 - val_mae_all: 12.0031 - val_mae_gdm_g: 14.3236 - learning_rate: 5.0000e-05
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 54.4832 - mae__dry__clover_g: 7.5145 - mae__dry__dead_g: 9.2381 - mae__dry__green_g: 13.4469 - mae__dry__total_g: 15.0094 - mae_all: 11.6681 - mae_gdm_g: 13.1315 - val_loss: 55.1665 - val_mae__dry__clover_g: 8.0978 - val_mae__dry__dead_g: 8.2268 - val_mae__dry__green_g: 14.3239 - val_mae__dry__total_g: 15.0412 - val_mae_all: 11.9983 - val_mae_gdm_g: 14.3020 - learning_rate: 5.0000e-05
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 55.1631 - mae__dry__clover_g: 7.4130 - mae__dry__dead_g: 9.0944 - mae__dry__green_g: 13.5865 - mae__dry__total_g: 15.0122 - mae_all: 11.6409 - mae_gdm_g: 13.0984 - val_loss: 56.4908 - val_mae__dry__clover_g: 8.0500 - val_mae__dry__dead_g: 8.1669 - val_mae__dry__green_g: 14.3710 - val_mae__dry__total_g: 15.1506 - val_mae_all: 12.0138 - val_mae_gdm_g: 14.3307 - learning_rate: 5.0000e-05
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 53.8911 - mae__dry__clover_g: 7.5069 - mae__dry__dead_g: 9.3389 - mae__dry__green_g: 13.7472 - mae__dry__total_g: 15.1252 - mae_all: 11.6651 - mae_gdm_g: 12.6075 - val_loss: 56.2864 - val_mae__dry__clover_g: 8.0557 - val_mae__dry__dead_g: 8.1462 - val_mae__dry__green_g: 14.3402 - val_mae__dry__total_g: 15.0968 - val_mae_all: 11.9931 - val_mae_gdm_g: 14.3264 - learning_rate: 5.0000e-05
Epoch 30/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 54.6927 - mae__dry__clover_g: 7.4746 - mae__dry__dead_g: 9.3733 - mae__dry__green_g: 13.7959 - mae__dry__total_g: 15.3905 - mae_all: 11.7806 - mae_gdm_g: 12.8687 - val_loss: 54.4941 - val_mae__dry__clover_g: 8.0948 - val_mae__dry__dead_g: 8.3104 - val_mae__dry__green_g: 14.2080 - val_mae__dry__total_g: 15.0254 - val_mae_all: 11.9412 - val_mae_gdm_g: 14.0673 - learning_rate: 5.0000e-05
Restoring model weights from the end of the best epoch: 30.
[Student] Fold 2 best val_mae_all = 11.941
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 199ms/step
[Student] Fold 2 Kaggle-style weighted R2 = 0.6417

===== [Student Distill] Fold 3 (alpha=0.5, tau=1.0) =====
45/45 ━━━━━━━━━━━━━━━━━━━━ 9s 195ms/step
[Student] Fold 3 Train: 286 | Val: 71
[Student] load baseline backbone from ./ckpt/baseline_gram_fold3.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 754ms/step - loss: 346.3378 - mae__dry__clover_g: 6.3350 - mae__dry__dead_g: 11.3510 - mae__dry__green_g: 26.0833 - mae__dry__total_g: 43.4274 - mae_all: 23.9974 - mae_gdm_g: 32.7902 - val_loss: 309.4688 - val_mae__dry__clover_g: 6.9703 - val_mae__dry__dead_g: 12.8316 - val_mae__dry__green_g: 22.7058 - val_mae__dry__total_g: 41.0474 - val_mae_all: 22.9939 - val_mae_gdm_g: 31.4142 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 320.0337 - mae__dry__clover_g: 6.2784 - mae__dry__dead_g: 11.4233 - mae__dry__green_g: 25.5560 - mae__dry__total_g: 40.5410 - mae_all: 23.2810 - mae_gdm_g: 32.6064 - val_loss: 256.2596 - val_mae__dry__clover_g: 6.9047 - val_mae__dry__dead_g: 13.0206 - val_mae__dry__green_g: 20.9824 - val_mae__dry__total_g: 34.5127 - val_mae_all: 21.3688 - val_mae_gdm_g: 31.4239 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 291.5620 - mae__dry__clover_g: 6.3435 - mae__dry__dead_g: 11.4256 - mae__dry__green_g: 24.5695 - mae__dry__total_g: 37.3442 - mae_all: 22.3783 - mae_gdm_g: 32.2085 - val_loss: 209.8908 - val_mae__dry__clover_g: 7.2507 - val_mae__dry__dead_g: 13.1148 - val_mae__dry__green_g: 19.4183 - val_mae__dry__total_g: 28.3425 - val_mae_all: 19.7616 - val_mae_gdm_g: 30.6815 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 263.3819 - mae__dry__clover_g: 6.3646 - mae__dry__dead_g: 11.3476 - mae__dry__green_g: 23.5273 - mae__dry__total_g: 34.0164 - mae_all: 21.3349 - mae_gdm_g: 31.4186 - val_loss: 175.9906 - val_mae__dry__clover_g: 7.8528 - val_mae__dry__dead_g: 13.0994 - val_mae__dry__green_g: 17.8945 - val_mae__dry__total_g: 24.3174 - val_mae_all: 18.4342 - val_mae_gdm_g: 29.0071 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 236.1866 - mae__dry__clover_g: 6.5290 - mae__dry__dead_g: 11.2860 - mae__dry__green_g: 22.1923 - mae__dry__total_g: 30.9450 - mae_all: 20.1964 - mae_gdm_g: 30.0298 - val_loss: 148.6326 - val_mae__dry__clover_g: 8.6220 - val_mae__dry__dead_g: 12.9472 - val_mae__dry__green_g: 16.5840 - val_mae__dry__total_g: 21.6457 - val_mae_all: 17.2115 - val_mae_gdm_g: 26.2586 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 209.7958 - mae__dry__clover_g: 6.7214 - mae__dry__dead_g: 11.0387 - mae__dry__green_g: 21.0421 - mae__dry__total_g: 28.1145 - mae_all: 19.0136 - mae_gdm_g: 28.1515 - val_loss: 128.8587 - val_mae__dry__clover_g: 9.1762 - val_mae__dry__dead_g: 12.2680 - val_mae__dry__green_g: 15.6699 - val_mae__dry__total_g: 19.9535 - val_mae_all: 16.0522 - val_mae_gdm_g: 23.1933 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 183.8899 - mae__dry__clover_g: 7.2266 - mae__dry__dead_g: 10.6739 - mae__dry__green_g: 19.5173 - mae__dry__total_g: 25.2887 - mae_all: 17.7719 - mae_gdm_g: 26.1529 - val_loss: 123.7744 - val_mae__dry__clover_g: 8.9677 - val_mae__dry__dead_g: 11.3671 - val_mae__dry__green_g: 15.4829 - val_mae__dry__total_g: 19.9528 - val_mae_all: 15.4327 - val_mae_gdm_g: 21.3930 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 752ms/step - loss: 162.7262 - mae__dry__clover_g: 7.5980 - mae__dry__dead_g: 10.2416 - mae__dry__green_g: 18.3928 - mae__dry__total_g: 22.8235 - mae_all: 16.6442 - mae_gdm_g: 24.1653 - val_loss: 126.8957 - val_mae__dry__clover_g: 8.3341 - val_mae__dry__dead_g: 10.9710 - val_mae__dry__green_g: 15.7243 - val_mae__dry__total_g: 20.7410 - val_mae_all: 15.2926 - val_mae_gdm_g: 20.6926 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 753ms/step - loss: 146.3481 - mae__dry__clover_g: 7.8986 - mae__dry__dead_g: 9.8830 - mae__dry__green_g: 17.8689 - mae__dry__total_g: 21.3862 - mae_all: 15.8690 - mae_gdm_g: 22.3085 - val_loss: 122.3651 - val_mae__dry__clover_g: 8.0167 - val_mae__dry__dead_g: 10.7189 - val_mae__dry__green_g: 15.7055 - val_mae__dry__total_g: 20.7581 - val_mae_all: 14.9657 - val_mae_gdm_g: 19.6292 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 129.5228 - mae__dry__clover_g: 7.9073 - mae__dry__dead_g: 9.3410 - mae__dry__green_g: 16.7730 - mae__dry__total_g: 20.0073 - mae_all: 14.8412 - mae_gdm_g: 20.1777 - val_loss: 126.0808 - val_mae__dry__clover_g: 7.6492 - val_mae__dry__dead_g: 10.6576 - val_mae__dry__green_g: 15.9991 - val_mae__dry__total_g: 21.8650 - val_mae_all: 15.1475 - val_mae_gdm_g: 19.5664 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 117.7515 - mae__dry__clover_g: 7.9601 - mae__dry__dead_g: 9.4810 - mae__dry__green_g: 16.4758 - mae__dry__total_g: 19.0464 - mae_all: 14.2962 - mae_gdm_g: 18.5176 - val_loss: 121.7040 - val_mae__dry__clover_g: 7.5395 - val_mae__dry__dead_g: 10.5369 - val_mae__dry__green_g: 15.9281 - val_mae__dry__total_g: 21.9024 - val_mae_all: 14.9405 - val_mae_gdm_g: 18.7956 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 110.9015 - mae__dry__clover_g: 8.2373 - mae__dry__dead_g: 9.5616 - mae__dry__green_g: 15.7502 - mae__dry__total_g: 18.9839 - mae_all: 13.9132 - mae_gdm_g: 17.0329 - val_loss: 122.9166 - val_mae__dry__clover_g: 7.3993 - val_mae__dry__dead_g: 10.4332 - val_mae__dry__green_g: 16.0449 - val_mae__dry__total_g: 22.4417 - val_mae_all: 14.9803 - val_mae_gdm_g: 18.5822 - learning_rate: 1.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 103.3313 - mae__dry__clover_g: 7.7401 - mae__dry__dead_g: 9.7439 - mae__dry__green_g: 15.6247 - mae__dry__total_g: 18.1627 - mae_all: 13.5719 - mae_gdm_g: 16.5880 - val_loss: 111.7609 - val_mae__dry__clover_g: 7.3842 - val_mae__dry__dead_g: 10.3379 - val_mae__dry__green_g: 15.5230 - val_mae__dry__total_g: 21.3391 - val_mae_all: 14.3756 - val_mae_gdm_g: 17.2938 - learning_rate: 1.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 101.0130 - mae__dry__clover_g: 8.0519 - mae__dry__dead_g: 9.5506 - mae__dry__green_g: 15.5964 - mae__dry__total_g: 18.2249 - mae_all: 13.4826 - mae_gdm_g: 15.9894 - val_loss: 110.2738 - val_mae__dry__clover_g: 7.3206 - val_mae__dry__dead_g: 10.2952 - val_mae__dry__green_g: 15.4578 - val_mae__dry__total_g: 21.2741 - val_mae_all: 14.2447 - val_mae_gdm_g: 16.8759 - learning_rate: 1.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 99.2819 - mae__dry__clover_g: 7.9838 - mae__dry__dead_g: 9.5613 - mae__dry__green_g: 15.8619 - mae__dry__total_g: 18.0168 - mae_all: 13.3914 - mae_gdm_g: 15.5330 - val_loss: 105.8148 - val_mae__dry__clover_g: 7.2748 - val_mae__dry__dead_g: 10.2349 - val_mae__dry__green_g: 15.2170 - val_mae__dry__total_g: 20.7642 - val_mae_all: 13.9546 - val_mae_gdm_g: 16.2820 - learning_rate: 1.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 94.7044 - mae__dry__clover_g: 7.9375 - mae__dry__dead_g: 9.7604 - mae__dry__green_g: 15.8002 - mae__dry__total_g: 18.0742 - mae_all: 13.3786 - mae_gdm_g: 15.3205 - val_loss: 98.4394 - val_mae__dry__clover_g: 7.2807 - val_mae__dry__dead_g: 10.1897 - val_mae__dry__green_g: 14.8633 - val_mae__dry__total_g: 19.6604 - val_mae_all: 13.4613 - val_mae_gdm_g: 15.3123 - learning_rate: 1.0000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 96.4138 - mae__dry__clover_g: 7.6011 - mae__dry__dead_g: 9.1160 - mae__dry__green_g: 15.7345 - mae__dry__total_g: 18.4577 - mae_all: 13.2665 - mae_gdm_g: 15.4233 - val_loss: 93.9071 - val_mae__dry__clover_g: 7.2637 - val_mae__dry__dead_g: 10.0588 - val_mae__dry__green_g: 14.6277 - val_mae__dry__total_g: 19.2794 - val_mae_all: 13.2226 - val_mae_gdm_g: 14.8835 - learning_rate: 1.0000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 90.6898 - mae__dry__clover_g: 7.7997 - mae__dry__dead_g: 9.3532 - mae__dry__green_g: 15.8534 - mae__dry__total_g: 17.9458 - mae_all: 13.2516 - mae_gdm_g: 15.3057 - val_loss: 94.7645 - val_mae__dry__clover_g: 7.2325 - val_mae__dry__dead_g: 10.0903 - val_mae__dry__green_g: 14.7014 - val_mae__dry__total_g: 19.3456 - val_mae_all: 13.2275 - val_mae_gdm_g: 14.7676 - learning_rate: 1.0000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 92.0538 - mae__dry__clover_g: 7.5347 - mae__dry__dead_g: 9.5965 - mae__dry__green_g: 15.7978 - mae__dry__total_g: 17.8147 - mae_all: 13.2120 - mae_gdm_g: 15.3162 - val_loss: 91.4828 - val_mae__dry__clover_g: 7.2116 - val_mae__dry__dead_g: 9.9970 - val_mae__dry__green_g: 14.5559 - val_mae__dry__total_g: 19.0977 - val_mae_all: 13.0596 - val_mae_gdm_g: 14.4361 - learning_rate: 1.0000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 89.6027 - mae__dry__clover_g: 7.2164 - mae__dry__dead_g: 9.9411 - mae__dry__green_g: 15.6245 - mae__dry__total_g: 17.5976 - mae_all: 13.1084 - mae_gdm_g: 15.1625 - val_loss: 82.6577 - val_mae__dry__clover_g: 7.2372 - val_mae__dry__dead_g: 9.9046 - val_mae__dry__green_g: 14.1901 - val_mae__dry__total_g: 17.9428 - val_mae_all: 12.5517 - val_mae_gdm_g: 13.4837 - learning_rate: 1.0000e-04
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 91.0417 - mae__dry__clover_g: 7.2540 - mae__dry__dead_g: 9.7327 - mae__dry__green_g: 15.5636 - mae__dry__total_g: 17.7487 - mae_all: 13.0859 - mae_gdm_g: 15.1306 - val_loss: 75.0504 - val_mae__dry__clover_g: 7.2881 - val_mae__dry__dead_g: 9.8459 - val_mae__dry__green_g: 13.9242 - val_mae__dry__total_g: 17.0759 - val_mae_all: 12.1704 - val_mae_gdm_g: 12.7179 - learning_rate: 1.0000e-04
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 752ms/step - loss: 91.8881 - mae__dry__clover_g: 7.6735 - mae__dry__dead_g: 9.6261 - mae__dry__green_g: 15.6767 - mae__dry__total_g: 17.6639 - mae_all: 13.2146 - mae_gdm_g: 15.4328 - val_loss: 72.3788 - val_mae__dry__clover_g: 7.3288 - val_mae__dry__dead_g: 9.8147 - val_mae__dry__green_g: 13.9007 - val_mae__dry__total_g: 17.0102 - val_mae_all: 12.0995 - val_mae_gdm_g: 12.4432 - learning_rate: 1.0000e-04
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 789ms/step - loss: 90.3586 - mae__dry__clover_g: 7.0855 - mae__dry__dead_g: 9.7202 - mae__dry__green_g: 15.8140 - mae__dry__total_g: 18.0959 - mae_all: 13.1713 - mae_gdm_g: 15.1408 - val_loss: 68.6016 - val_mae__dry__clover_g: 7.3668 - val_mae__dry__dead_g: 9.7303 - val_mae__dry__green_g: 13.9819 - val_mae__dry__total_g: 16.4649 - val_mae_all: 11.9421 - val_mae_gdm_g: 12.1664 - learning_rate: 1.0000e-04
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 788ms/step - loss: 89.7411 - mae__dry__clover_g: 7.6947 - mae__dry__dead_g: 9.7458 - mae__dry__green_g: 15.7810 - mae__dry__total_g: 17.6962 - mae_all: 13.2979 - mae_gdm_g: 15.5716 - val_loss: 68.3840 - val_mae__dry__clover_g: 7.3548 - val_mae__dry__dead_g: 9.7163 - val_mae__dry__green_g: 13.9841 - val_mae__dry__total_g: 16.5761 - val_mae_all: 11.9580 - val_mae_gdm_g: 12.1585 - learning_rate: 1.0000e-04
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 790ms/step - loss: 88.3084 - mae__dry__clover_g: 7.6805 - mae__dry__dead_g: 9.7489 - mae__dry__green_g: 15.5758 - mae__dry__total_g: 17.7473 - mae_all: 13.2162 - mae_gdm_g: 15.3287 - val_loss: 67.6985 - val_mae__dry__clover_g: 7.3656 - val_mae__dry__dead_g: 9.6715 - val_mae__dry__green_g: 13.8473 - val_mae__dry__total_g: 16.5886 - val_mae_all: 11.9098 - val_mae_gdm_g: 12.0763 - learning_rate: 1.0000e-04
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 789ms/step - loss: 88.3288 - mae__dry__clover_g: 7.5718 - mae__dry__dead_g: 9.5217 - mae__dry__green_g: 15.7042 - mae__dry__total_g: 17.6605 - mae_all: 13.1617 - mae_gdm_g: 15.3505 - val_loss: 65.9065 - val_mae__dry__clover_g: 7.3909 - val_mae__dry__dead_g: 9.6333 - val_mae__dry__green_g: 14.1255 - val_mae__dry__total_g: 16.4495 - val_mae_all: 11.9130 - val_mae_gdm_g: 11.9659 - learning_rate: 1.0000e-04
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 739ms/step - loss: 107.8560 - mae__dry__clover_g: 7.4550 - mae__dry__dead_g: 9.2542 - mae__dry__green_g: 17.3771 - mae__dry__total_g: 19.5669 - mae_all: 14.1277 - mae_gdm_g: 16.9854
Epoch 27: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 790ms/step - loss: 87.6476 - mae__dry__clover_g: 7.4780 - mae__dry__dead_g: 9.7016 - mae__dry__green_g: 15.7255 - mae__dry__total_g: 17.5464 - mae_all: 13.1003 - mae_gdm_g: 15.0499 - val_loss: 65.1881 - val_mae__dry__clover_g: 7.4116 - val_mae__dry__dead_g: 9.6012 - val_mae__dry__green_g: 14.1297 - val_mae__dry__total_g: 16.5685 - val_mae_all: 11.9353 - val_mae_gdm_g: 11.9653 - learning_rate: 1.0000e-04
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 789ms/step - loss: 86.3653 - mae__dry__clover_g: 7.7627 - mae__dry__dead_g: 9.3963 - mae__dry__green_g: 15.6314 - mae__dry__total_g: 17.3971 - mae_all: 12.9970 - mae_gdm_g: 14.7977 - val_loss: 64.9686 - val_mae__dry__clover_g: 7.4008 - val_mae__dry__dead_g: 9.6039 - val_mae__dry__green_g: 13.9926 - val_mae__dry__total_g: 16.5395 - val_mae_all: 11.8815 - val_mae_gdm_g: 11.8706 - learning_rate: 5.0000e-05
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 789ms/step - loss: 84.7353 - mae__dry__clover_g: 7.9180 - mae__dry__dead_g: 9.5735 - mae__dry__green_g: 15.4613 - mae__dry__total_g: 17.2674 - mae_all: 13.1136 - mae_gdm_g: 15.3477 - val_loss: 65.1148 - val_mae__dry__clover_g: 7.3814 - val_mae__dry__dead_g: 9.5780 - val_mae__dry__green_g: 13.9234 - val_mae__dry__total_g: 16.5814 - val_mae_all: 11.8736 - val_mae_gdm_g: 11.9037 - learning_rate: 5.0000e-05
Epoch 30/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 788ms/step - loss: 84.8423 - mae__dry__clover_g: 7.4594 - mae__dry__dead_g: 9.2022 - mae__dry__green_g: 15.6004 - mae__dry__total_g: 17.4191 - mae_all: 12.9310 - mae_gdm_g: 14.9738 - val_loss: 64.8206 - val_mae__dry__clover_g: 7.3902 - val_mae__dry__dead_g: 9.5466 - val_mae__dry__green_g: 14.0089 - val_mae__dry__total_g: 16.5813 - val_mae_all: 11.9018 - val_mae_gdm_g: 11.9819 - learning_rate: 5.0000e-05
Restoring model weights from the end of the best epoch: 29.
[Student] Fold 3 best val_mae_all = 11.874
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 205ms/step
[Student] Fold 3 Kaggle-style weighted R2 = 0.4453

===== [Student Distill] Fold 4 (alpha=0.5, tau=1.0) =====
45/45 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step
[Student] Fold 4 Train: 286 | Val: 71
[Student] load baseline backbone from ./ckpt/baseline_gram_fold4.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 30s 785ms/step - loss: 345.3598 - mae__dry__clover_g: 6.7598 - mae__dry__dead_g: 11.3299 - mae__dry__green_g: 25.6999 - mae__dry__total_g: 43.4435 - mae_all: 23.9050 - mae_gdm_g: 32.2920 - val_loss: 333.5408 - val_mae__dry__clover_g: 5.4132 - val_mae__dry__dead_g: 10.6489 - val_mae__dry__green_g: 27.5334 - val_mae__dry__total_g: 41.2042 - val_mae_all: 23.4821 - val_mae_gdm_g: 32.6106 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 782ms/step - loss: 313.2156 - mae__dry__clover_g: 6.8003 - mae__dry__dead_g: 10.9958 - mae__dry__green_g: 25.6296 - mae__dry__total_g: 40.3630 - mae_all: 23.1434 - mae_gdm_g: 31.9282 - val_loss: 281.4457 - val_mae__dry__clover_g: 5.4021 - val_mae__dry__dead_g: 10.0205 - val_mae__dry__green_g: 27.4818 - val_mae__dry__total_g: 35.6633 - val_mae_all: 22.0799 - val_mae_gdm_g: 31.8320 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 781ms/step - loss: 279.3792 - mae__dry__clover_g: 6.8003 - mae__dry__dead_g: 10.5673 - mae__dry__green_g: 25.5293 - mae__dry__total_g: 37.0446 - mae_all: 22.2326 - mae_gdm_g: 31.2217 - val_loss: 252.0965 - val_mae__dry__clover_g: 5.4696 - val_mae__dry__dead_g: 9.6915 - val_mae__dry__green_g: 27.2310 - val_mae__dry__total_g: 32.4868 - val_mae_all: 21.1479 - val_mae_gdm_g: 30.8606 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 781ms/step - loss: 247.2832 - mae__dry__clover_g: 6.8240 - mae__dry__dead_g: 10.1129 - mae__dry__green_g: 25.1686 - mae__dry__total_g: 33.7425 - mae_all: 21.2191 - mae_gdm_g: 30.2476 - val_loss: 237.3416 - val_mae__dry__clover_g: 5.5648 - val_mae__dry__dead_g: 9.4179 - val_mae__dry__green_g: 26.6335 - val_mae__dry__total_g: 31.1682 - val_mae_all: 20.5422 - val_mae_gdm_g: 29.9269 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 782ms/step - loss: 218.9986 - mae__dry__clover_g: 6.9063 - mae__dry__dead_g: 9.8391 - mae__dry__green_g: 24.5486 - mae__dry__total_g: 30.9254 - mae_all: 20.2165 - mae_gdm_g: 28.8632 - val_loss: 230.2425 - val_mae__dry__clover_g: 5.6443 - val_mae__dry__dead_g: 9.2429 - val_mae__dry__green_g: 25.9663 - val_mae__dry__total_g: 30.8025 - val_mae_all: 20.1824 - val_mae_gdm_g: 29.2561 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 785ms/step - loss: 189.9799 - mae__dry__clover_g: 7.0480 - mae__dry__dead_g: 9.4953 - mae__dry__green_g: 23.5437 - mae__dry__total_g: 27.9227 - mae_all: 19.0928 - mae_gdm_g: 27.4541 - val_loss: 212.9470 - val_mae__dry__clover_g: 5.8384 - val_mae__dry__dead_g: 9.0407 - val_mae__dry__green_g: 25.1241 - val_mae__dry__total_g: 29.1488 - val_mae_all: 19.4387 - val_mae_gdm_g: 28.0413 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 162.9408 - mae__dry__clover_g: 7.2378 - mae__dry__dead_g: 9.4457 - mae__dry__green_g: 22.5952 - mae__dry__total_g: 24.7888 - mae_all: 17.9736 - mae_gdm_g: 25.8007 - val_loss: 204.4789 - val_mae__dry__clover_g: 5.9436 - val_mae__dry__dead_g: 8.9246 - val_mae__dry__green_g: 24.3829 - val_mae__dry__total_g: 28.5229 - val_mae_all: 19.0053 - val_mae_gdm_g: 27.2524 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 783ms/step - loss: 139.4269 - mae__dry__clover_g: 7.6991 - mae__dry__dead_g: 9.3093 - mae__dry__green_g: 21.4195 - mae__dry__total_g: 22.2760 - mae_all: 16.8722 - mae_gdm_g: 23.6570 - val_loss: 194.1164 - val_mae__dry__clover_g: 6.0067 - val_mae__dry__dead_g: 8.8166 - val_mae__dry__green_g: 23.5888 - val_mae__dry__total_g: 27.5077 - val_mae_all: 18.4413 - val_mae_gdm_g: 26.2868 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 783ms/step - loss: 118.0301 - mae__dry__clover_g: 7.7871 - mae__dry__dead_g: 9.3188 - mae__dry__green_g: 19.8734 - mae__dry__total_g: 19.9930 - mae_all: 15.7756 - mae_gdm_g: 21.9056 - val_loss: 181.9697 - val_mae__dry__clover_g: 6.1055 - val_mae__dry__dead_g: 8.7040 - val_mae__dry__green_g: 22.6792 - val_mae__dry__total_g: 26.3368 - val_mae_all: 17.7980 - val_mae_gdm_g: 25.1643 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 782ms/step - loss: 102.9834 - mae__dry__clover_g: 7.8908 - mae__dry__dead_g: 9.5932 - mae__dry__green_g: 18.8363 - mae__dry__total_g: 18.5384 - mae_all: 15.0467 - mae_gdm_g: 20.3749 - val_loss: 173.8183 - val_mae__dry__clover_g: 6.1554 - val_mae__dry__dead_g: 8.5637 - val_mae__dry__green_g: 21.9202 - val_mae__dry__total_g: 25.5310 - val_mae_all: 17.2732 - val_mae_gdm_g: 24.1956 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 90.6231 - mae__dry__clover_g: 8.2593 - mae__dry__dead_g: 9.3986 - mae__dry__green_g: 18.1407 - mae__dry__total_g: 17.1511 - mae_all: 14.3387 - mae_gdm_g: 18.7440 - val_loss: 156.0046 - val_mae__dry__clover_g: 6.2735 - val_mae__dry__dead_g: 8.4575 - val_mae__dry__green_g: 20.7102 - val_mae__dry__total_g: 23.7955 - val_mae_all: 16.3701 - val_mae_gdm_g: 22.6140 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 785ms/step - loss: 82.5655 - mae__dry__clover_g: 8.3650 - mae__dry__dead_g: 9.2254 - mae__dry__green_g: 16.8849 - mae__dry__total_g: 16.6731 - mae_all: 13.6386 - mae_gdm_g: 17.0448 - val_loss: 144.9653 - val_mae__dry__clover_g: 6.3108 - val_mae__dry__dead_g: 8.3217 - val_mae__dry__green_g: 19.6999 - val_mae__dry__total_g: 22.6295 - val_mae_all: 15.6728 - val_mae_gdm_g: 21.4024 - learning_rate: 1.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 783ms/step - loss: 77.2000 - mae__dry__clover_g: 8.0192 - mae__dry__dead_g: 9.3021 - mae__dry__green_g: 16.3795 - mae__dry__total_g: 16.1310 - mae_all: 13.2016 - mae_gdm_g: 16.1760 - val_loss: 135.5748 - val_mae__dry__clover_g: 6.3469 - val_mae__dry__dead_g: 8.2638 - val_mae__dry__green_g: 18.8574 - val_mae__dry__total_g: 21.7273 - val_mae_all: 15.0849 - val_mae_gdm_g: 20.2289 - learning_rate: 1.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 72.9318 - mae__dry__clover_g: 8.1521 - mae__dry__dead_g: 9.4942 - mae__dry__green_g: 15.6886 - mae__dry__total_g: 16.1622 - mae_all: 12.9551 - mae_gdm_g: 15.2786 - val_loss: 121.6003 - val_mae__dry__clover_g: 6.4498 - val_mae__dry__dead_g: 8.1633 - val_mae__dry__green_g: 17.8233 - val_mae__dry__total_g: 20.5041 - val_mae_all: 14.3883 - val_mae_gdm_g: 19.0012 - learning_rate: 1.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 775ms/step - loss: 67.8622 - mae__dry__clover_g: 8.2972 - mae__dry__dead_g: 9.3315 - mae__dry__green_g: 14.9546 - mae__dry__total_g: 15.6143 - mae_all: 12.5322 - mae_gdm_g: 14.4632 - val_loss: 111.3578 - val_mae__dry__clover_g: 6.4826 - val_mae__dry__dead_g: 8.1429 - val_mae__dry__green_g: 16.8069 - val_mae__dry__total_g: 19.4855 - val_mae_all: 13.7270 - val_mae_gdm_g: 17.7171 - learning_rate: 1.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 64.1228 - mae__dry__clover_g: 8.1033 - mae__dry__dead_g: 9.7783 - mae__dry__green_g: 14.4960 - mae__dry__total_g: 15.2664 - mae_all: 12.2745 - mae_gdm_g: 13.7285 - val_loss: 103.8048 - val_mae__dry__clover_g: 6.5115 - val_mae__dry__dead_g: 8.1492 - val_mae__dry__green_g: 16.0605 - val_mae__dry__total_g: 18.9093 - val_mae_all: 13.3174 - val_mae_gdm_g: 16.9567 - learning_rate: 1.0000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 785ms/step - loss: 62.5886 - mae__dry__clover_g: 8.1983 - mae__dry__dead_g: 9.4844 - mae__dry__green_g: 14.5239 - mae__dry__total_g: 15.3706 - mae_all: 12.3067 - mae_gdm_g: 13.9565 - val_loss: 97.3133 - val_mae__dry__clover_g: 6.5740 - val_mae__dry__dead_g: 8.1135 - val_mae__dry__green_g: 15.4385 - val_mae__dry__total_g: 18.4682 - val_mae_all: 13.0047 - val_mae_gdm_g: 16.4294 - learning_rate: 1.0000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 59.8139 - mae__dry__clover_g: 8.5971 - mae__dry__dead_g: 9.6414 - mae__dry__green_g: 13.8299 - mae__dry__total_g: 14.7325 - mae_all: 12.0702 - mae_gdm_g: 13.5499 - val_loss: 99.1657 - val_mae__dry__clover_g: 6.4574 - val_mae__dry__dead_g: 8.1092 - val_mae__dry__green_g: 15.3975 - val_mae__dry__total_g: 18.6125 - val_mae_all: 12.9999 - val_mae_gdm_g: 16.4229 - learning_rate: 1.0000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 59.9238 - mae__dry__clover_g: 8.2349 - mae__dry__dead_g: 9.0559 - mae__dry__green_g: 14.0996 - mae__dry__total_g: 14.7339 - mae_all: 11.8385 - mae_gdm_g: 13.0681 - val_loss: 104.6733 - val_mae__dry__clover_g: 6.3373 - val_mae__dry__dead_g: 8.0341 - val_mae__dry__green_g: 15.6434 - val_mae__dry__total_g: 19.0540 - val_mae_all: 13.1237 - val_mae_gdm_g: 16.5500 - learning_rate: 1.0000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 783ms/step - loss: 58.9055 - mae__dry__clover_g: 8.1925 - mae__dry__dead_g: 9.2988 - mae__dry__green_g: 14.2408 - mae__dry__total_g: 14.8777 - mae_all: 11.9660 - mae_gdm_g: 13.2202 - val_loss: 93.0464 - val_mae__dry__clover_g: 6.4949 - val_mae__dry__dead_g: 8.1578 - val_mae__dry__green_g: 14.7732 - val_mae__dry__total_g: 18.2679 - val_mae_all: 12.7080 - val_mae_gdm_g: 15.8460 - learning_rate: 1.0000e-04
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 783ms/step - loss: 59.1872 - mae__dry__clover_g: 7.9471 - mae__dry__dead_g: 9.4381 - mae__dry__green_g: 13.7002 - mae__dry__total_g: 15.2736 - mae_all: 11.9684 - mae_gdm_g: 13.4831 - val_loss: 97.9451 - val_mae__dry__clover_g: 6.4183 - val_mae__dry__dead_g: 8.0929 - val_mae__dry__green_g: 15.0266 - val_mae__dry__total_g: 18.5703 - val_mae_all: 12.8330 - val_mae_gdm_g: 16.0569 - learning_rate: 1.0000e-04
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 783ms/step - loss: 56.4254 - mae__dry__clover_g: 8.5060 - mae__dry__dead_g: 9.6008 - mae__dry__green_g: 14.1571 - mae__dry__total_g: 14.8650 - mae_all: 12.0092 - mae_gdm_g: 12.9170 - val_loss: 89.0738 - val_mae__dry__clover_g: 6.5849 - val_mae__dry__dead_g: 8.1516 - val_mae__dry__green_g: 14.6376 - val_mae__dry__total_g: 18.1187 - val_mae_all: 12.6398 - val_mae_gdm_g: 15.7060 - learning_rate: 1.0000e-04
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 786ms/step - loss: 58.5219 - mae__dry__clover_g: 8.0923 - mae__dry__dead_g: 9.3829 - mae__dry__green_g: 14.1570 - mae__dry__total_g: 14.7617 - mae_all: 11.9009 - mae_gdm_g: 13.1106 - val_loss: 90.8858 - val_mae__dry__clover_g: 6.5815 - val_mae__dry__dead_g: 8.0969 - val_mae__dry__green_g: 14.6691 - val_mae__dry__total_g: 18.2050 - val_mae_all: 12.6617 - val_mae_gdm_g: 15.7560 - learning_rate: 1.0000e-04
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 734ms/step - loss: 52.2357 - mae__dry__clover_g: 8.3135 - mae__dry__dead_g: 9.6546 - mae__dry__green_g: 13.0345 - mae__dry__total_g: 14.4984 - mae_all: 11.5044 - mae_gdm_g: 12.0209
Epoch 24: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 57.0472 - mae__dry__clover_g: 8.6767 - mae__dry__dead_g: 9.3644 - mae__dry__green_g: 13.9173 - mae__dry__total_g: 14.8013 - mae_all: 11.9331 - mae_gdm_g: 12.9057 - val_loss: 91.7093 - val_mae__dry__clover_g: 6.5325 - val_mae__dry__dead_g: 8.0734 - val_mae__dry__green_g: 14.6446 - val_mae__dry__total_g: 18.2648 - val_mae_all: 12.6726 - val_mae_gdm_g: 15.8478 - learning_rate: 1.0000e-04
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 783ms/step - loss: 57.9421 - mae__dry__clover_g: 8.4788 - mae__dry__dead_g: 9.4980 - mae__dry__green_g: 14.0089 - mae__dry__total_g: 14.9341 - mae_all: 11.9970 - mae_gdm_g: 13.0651 - val_loss: 87.6536 - val_mae__dry__clover_g: 6.6276 - val_mae__dry__dead_g: 8.0498 - val_mae__dry__green_g: 14.6069 - val_mae__dry__total_g: 17.9075 - val_mae_all: 12.5720 - val_mae_gdm_g: 15.6683 - learning_rate: 5.0000e-05
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 781ms/step - loss: 56.3427 - mae__dry__clover_g: 8.4506 - mae__dry__dead_g: 9.2695 - mae__dry__green_g: 14.0779 - mae__dry__total_g: 14.3099 - mae_all: 11.8219 - mae_gdm_g: 13.0015 - val_loss: 85.2286 - val_mae__dry__clover_g: 6.6652 - val_mae__dry__dead_g: 8.1192 - val_mae__dry__green_g: 14.5346 - val_mae__dry__total_g: 18.0356 - val_mae_all: 12.6213 - val_mae_gdm_g: 15.7519 - learning_rate: 5.0000e-05
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 735ms/step - loss: 51.4226 - mae__dry__clover_g: 8.2000 - mae__dry__dead_g: 9.4059 - mae__dry__green_g: 13.0085 - mae__dry__total_g: 14.0742 - mae_all: 11.3641 - mae_gdm_g: 12.1318
Epoch 27: ReduceLROnPlateau reducing learning rate to 2.499999936844688e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 785ms/step - loss: 56.9114 - mae__dry__clover_g: 8.5585 - mae__dry__dead_g: 9.4134 - mae__dry__green_g: 13.8584 - mae__dry__total_g: 14.6726 - mae_all: 11.9823 - mae_gdm_g: 13.4085 - val_loss: 86.0487 - val_mae__dry__clover_g: 6.6108 - val_mae__dry__dead_g: 8.1618 - val_mae__dry__green_g: 14.4855 - val_mae__dry__total_g: 18.0575 - val_mae_all: 12.5905 - val_mae_gdm_g: 15.6370 - learning_rate: 5.0000e-05
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 53.8514 - mae__dry__clover_g: 8.2132 - mae__dry__dead_g: 9.6910 - mae__dry__green_g: 13.6676 - mae__dry__total_g: 14.3212 - mae_all: 11.7257 - mae_gdm_g: 12.7352 - val_loss: 83.4255 - val_mae__dry__clover_g: 6.6863 - val_mae__dry__dead_g: 8.1731 - val_mae__dry__green_g: 14.4568 - val_mae__dry__total_g: 17.9756 - val_mae_all: 12.5928 - val_mae_gdm_g: 15.6721 - learning_rate: 2.5000e-05
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 731ms/step - loss: 48.3570 - mae__dry__clover_g: 7.7937 - mae__dry__dead_g: 9.6714 - mae__dry__green_g: 13.2847 - mae__dry__total_g: 13.7956 - mae_all: 11.2950 - mae_gdm_g: 11.9294
Epoch 29: ReduceLROnPlateau reducing learning rate to 1.249999968422344e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 782ms/step - loss: 53.1192 - mae__dry__clover_g: 8.0566 - mae__dry__dead_g: 9.6171 - mae__dry__green_g: 14.0143 - mae__dry__total_g: 14.4453 - mae_all: 11.7942 - mae_gdm_g: 12.8377 - val_loss: 81.9251 - val_mae__dry__clover_g: 6.7330 - val_mae__dry__dead_g: 8.1708 - val_mae__dry__green_g: 14.4943 - val_mae__dry__total_g: 18.0893 - val_mae_all: 12.6518 - val_mae_gdm_g: 15.7717 - learning_rate: 2.5000e-05
Epoch 30/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 784ms/step - loss: 55.2841 - mae__dry__clover_g: 8.7325 - mae__dry__dead_g: 9.7963 - mae__dry__green_g: 13.8181 - mae__dry__total_g: 14.6406 - mae_all: 11.9058 - mae_gdm_g: 12.5415 - val_loss: 80.4888 - val_mae__dry__clover_g: 6.7910 - val_mae__dry__dead_g: 8.1871 - val_mae__dry__green_g: 14.5679 - val_mae__dry__total_g: 18.1783 - val_mae_all: 12.7160 - val_mae_gdm_g: 15.8558 - learning_rate: 1.2500e-05
Epoch 30: early stopping
Restoring model weights from the end of the best epoch: 25.
[Student] Fold 4 best val_mae_all = 12.572
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 203ms/step
[Student] Fold 4 Kaggle-style weighted R2 = 0.3533

===== [Student Distill] 5-fold CV summary =====
MAE per fold: [11.21  12.336 11.941 11.874 12.572]
R2  per fold: [0.471 0.399 0.642 0.445 0.353]
mean R2 = 0.46223788567622853

In [60]:
# ====== Train model: Distilled Student (image only)(gram) ======
set_label_mode(False)  # Set label mode to "gram"
# set_label_mode(True)  # Set label mode to "log1p"

student_results_gram_2 = {}
student_fold_maes_gram_2 = []
student_fold_r2_gram_2 = []

set_seed(CFG.seed)

for f in range(CFG.n_folds):
    
    student_mae, student_model, student_hist, student_valds, student_r2 = \
        train_one_fold_student_distill(
            fold=f,
            teacher_model=teacher_models_gram[f],   # trained teacher fisrt
            alpha=0.55,
            tau=1.0,
        )
    student_results_gram_2[f] = (student_mae, student_r2)
    student_fold_maes_gram_2.append(student_mae)
    student_fold_r2_gram_2.append(student_r2)

print("\n===== [Student Distill] 5-fold CV summary =====")
print("MAE per fold:", np.round(student_fold_maes_gram_2, 3))
print("R2  per fold:", np.round(student_fold_r2_gram_2, 3))
print("mean R2 =", np.mean(student_fold_r2_gram_2))

[set_label_mode] use_log1p=False → TRAIN_TARGETS = ['Dry_Green_g', 'Dry_Dead_g', 'Dry_Clover_g', 'GDM_g', 'Dry_Total_g']
[init] fallback label_transform=identity

===== [Student Distill] Fold 0 (alpha=0.55, tau=1.0) =====
45/45 ━━━━━━━━━━━━━━━━━━━━ 9s 197ms/step
[Student] Fold 0 Train: 285 | Val: 72
[Student] load baseline backbone from ./ckpt/baseline_gram_fold0.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 30s 756ms/step - loss: 356.7682 - mae__dry__clover_g: 6.7097 - mae__dry__dead_g: 11.2878 - mae__dry__green_g: 26.4126 - mae__dry__total_g: 43.8522 - mae_all: 23.9789 - mae_gdm_g: 31.6322 - val_loss: 333.1559 - val_mae__dry__clover_g: 5.6201 - val_mae__dry__dead_g: 13.1199 - val_mae__dry__green_g: 25.2704 - val_mae__dry__total_g: 43.5535 - val_mae_all: 23.4165 - val_mae_gdm_g: 29.5188 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 332.9925 - mae__dry__clover_g: 6.6469 - mae__dry__dead_g: 11.1239 - mae__dry__green_g: 26.4760 - mae__dry__total_g: 41.7947 - mae_all: 23.4003 - mae_gdm_g: 30.9600 - val_loss: 318.1068 - val_mae__dry__clover_g: 5.6063 - val_mae__dry__dead_g: 12.9644 - val_mae__dry__green_g: 25.2768 - val_mae__dry__total_g: 42.1398 - val_mae_all: 23.0714 - val_mae_gdm_g: 29.3699 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 753ms/step - loss: 305.4496 - mae__dry__clover_g: 6.7542 - mae__dry__dead_g: 10.8360 - mae__dry__green_g: 26.5228 - mae__dry__total_g: 39.1918 - mae_all: 22.6971 - mae_gdm_g: 30.1807 - val_loss: 286.6438 - val_mae__dry__clover_g: 5.6784 - val_mae__dry__dead_g: 12.7623 - val_mae__dry__green_g: 25.3825 - val_mae__dry__total_g: 39.0693 - val_mae_all: 22.2218 - val_mae_gdm_g: 28.2165 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 279.4623 - mae__dry__clover_g: 6.8832 - mae__dry__dead_g: 10.6721 - mae__dry__green_g: 26.5057 - mae__dry__total_g: 36.4300 - mae_all: 22.0005 - mae_gdm_g: 29.5112 - val_loss: 241.3908 - val_mae__dry__clover_g: 5.8994 - val_mae__dry__dead_g: 12.2603 - val_mae__dry__green_g: 25.4574 - val_mae__dry__total_g: 34.1396 - val_mae_all: 20.7917 - val_mae_gdm_g: 26.2016 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 248.8522 - mae__dry__clover_g: 7.2706 - mae__dry__dead_g: 10.2132 - mae__dry__green_g: 26.4697 - mae__dry__total_g: 33.3153 - mae_all: 21.0714 - mae_gdm_g: 28.0880 - val_loss: 196.9224 - val_mae__dry__clover_g: 6.4510 - val_mae__dry__dead_g: 11.3697 - val_mae__dry__green_g: 25.4863 - val_mae__dry__total_g: 28.9445 - val_mae_all: 19.2013 - val_mae_gdm_g: 23.7549 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 752ms/step - loss: 220.1462 - mae__dry__clover_g: 7.7076 - mae__dry__dead_g: 9.8583 - mae__dry__green_g: 26.4059 - mae__dry__total_g: 30.2003 - mae_all: 20.1281 - mae_gdm_g: 26.4683 - val_loss: 167.4837 - val_mae__dry__clover_g: 6.9289 - val_mae__dry__dead_g: 10.9155 - val_mae__dry__green_g: 25.3941 - val_mae__dry__total_g: 25.7336 - val_mae_all: 18.1011 - val_mae_gdm_g: 21.5334 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 758ms/step - loss: 190.2008 - mae__dry__clover_g: 8.1762 - mae__dry__dead_g: 9.5827 - mae__dry__green_g: 26.2116 - mae__dry__total_g: 27.1843 - mae_all: 19.1394 - mae_gdm_g: 24.5420 - val_loss: 152.6313 - val_mae__dry__clover_g: 7.1083 - val_mae__dry__dead_g: 10.6239 - val_mae__dry__green_g: 24.9062 - val_mae__dry__total_g: 24.2522 - val_mae_all: 17.3752 - val_mae_gdm_g: 19.9851 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 164.4245 - mae__dry__clover_g: 8.3709 - mae__dry__dead_g: 9.3003 - mae__dry__green_g: 25.3652 - mae__dry__total_g: 24.5262 - mae_all: 17.9731 - mae_gdm_g: 22.3031 - val_loss: 136.7235 - val_mae__dry__clover_g: 7.1871 - val_mae__dry__dead_g: 10.3427 - val_mae__dry__green_g: 23.5214 - val_mae__dry__total_g: 22.7520 - val_mae_all: 16.4437 - val_mae_gdm_g: 18.4155 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 752ms/step - loss: 142.8364 - mae__dry__clover_g: 8.2804 - mae__dry__dead_g: 9.0660 - mae__dry__green_g: 23.9317 - mae__dry__total_g: 22.3485 - mae_all: 16.8411 - mae_gdm_g: 20.5788 - val_loss: 127.0442 - val_mae__dry__clover_g: 7.1296 - val_mae__dry__dead_g: 10.1362 - val_mae__dry__green_g: 21.8330 - val_mae__dry__total_g: 22.0307 - val_mae_all: 15.7186 - val_mae_gdm_g: 17.4635 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 753ms/step - loss: 124.5409 - mae__dry__clover_g: 8.8276 - mae__dry__dead_g: 8.8812 - mae__dry__green_g: 22.1411 - mae__dry__total_g: 20.5704 - mae_all: 15.8710 - mae_gdm_g: 18.9348 - val_loss: 132.9483 - val_mae__dry__clover_g: 6.7934 - val_mae__dry__dead_g: 10.1816 - val_mae__dry__green_g: 20.9141 - val_mae__dry__total_g: 23.0310 - val_mae_all: 15.7431 - val_mae_gdm_g: 17.7953 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 753ms/step - loss: 106.5536 - mae__dry__clover_g: 8.5970 - mae__dry__dead_g: 8.8774 - mae__dry__green_g: 20.5559 - mae__dry__total_g: 18.7933 - mae_all: 14.8483 - mae_gdm_g: 17.4178 - val_loss: 121.5318 - val_mae__dry__clover_g: 6.7254 - val_mae__dry__dead_g: 10.0817 - val_mae__dry__green_g: 19.6674 - val_mae__dry__total_g: 21.7364 - val_mae_all: 14.9672 - val_mae_gdm_g: 16.6251 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 91.5822 - mae__dry__clover_g: 8.3039 - mae__dry__dead_g: 8.5189 - mae__dry__green_g: 18.9293 - mae__dry__total_g: 17.1544 - mae_all: 13.8004 - mae_gdm_g: 16.0954 - val_loss: 120.9026 - val_mae__dry__clover_g: 6.5840 - val_mae__dry__dead_g: 10.0509 - val_mae__dry__green_g: 18.9373 - val_mae__dry__total_g: 21.7902 - val_mae_all: 14.7592 - val_mae_gdm_g: 16.4338 - learning_rate: 1.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 87.1989 - mae__dry__clover_g: 8.4994 - mae__dry__dead_g: 8.7559 - mae__dry__green_g: 17.6887 - mae__dry__total_g: 16.7388 - mae_all: 13.4745 - mae_gdm_g: 15.6894 - val_loss: 106.0401 - val_mae__dry__clover_g: 6.5983 - val_mae__dry__dead_g: 9.9011 - val_mae__dry__green_g: 17.6817 - val_mae__dry__total_g: 20.0891 - val_mae_all: 13.8457 - val_mae_gdm_g: 14.9580 - learning_rate: 1.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 752ms/step - loss: 77.0770 - mae__dry__clover_g: 8.1683 - mae__dry__dead_g: 8.5689 - mae__dry__green_g: 16.9645 - mae__dry__total_g: 15.6502 - mae_all: 12.8328 - mae_gdm_g: 14.8122 - val_loss: 104.8069 - val_mae__dry__clover_g: 6.4662 - val_mae__dry__dead_g: 9.8992 - val_mae__dry__green_g: 17.1126 - val_mae__dry__total_g: 20.0750 - val_mae_all: 13.6471 - val_mae_gdm_g: 14.6824 - learning_rate: 1.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 752ms/step - loss: 68.8403 - mae__dry__clover_g: 7.5887 - mae__dry__dead_g: 8.9878 - mae__dry__green_g: 15.6194 - mae__dry__total_g: 15.0511 - mae_all: 12.2613 - mae_gdm_g: 14.0595 - val_loss: 89.8446 - val_mae__dry__clover_g: 6.5642 - val_mae__dry__dead_g: 9.7110 - val_mae__dry__green_g: 15.8533 - val_mae__dry__total_g: 18.4012 - val_mae_all: 12.7706 - val_mae_gdm_g: 13.3234 - learning_rate: 1.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 752ms/step - loss: 70.2957 - mae__dry__clover_g: 8.5395 - mae__dry__dead_g: 8.8365 - mae__dry__green_g: 15.3638 - mae__dry__total_g: 15.1519 - mae_all: 12.4363 - mae_gdm_g: 14.2899 - val_loss: 76.9338 - val_mae__dry__clover_g: 6.6742 - val_mae__dry__dead_g: 9.6124 - val_mae__dry__green_g: 14.7943 - val_mae__dry__total_g: 17.2697 - val_mae_all: 12.1506 - val_mae_gdm_g: 12.4022 - learning_rate: 1.0000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 771ms/step - loss: 62.1925 - mae__dry__clover_g: 8.3206 - mae__dry__dead_g: 8.3324 - mae__dry__green_g: 14.7597 - mae__dry__total_g: 14.7531 - mae_all: 11.9162 - mae_gdm_g: 13.4149 - val_loss: 76.6539 - val_mae__dry__clover_g: 6.5386 - val_mae__dry__dead_g: 9.5628 - val_mae__dry__green_g: 14.4663 - val_mae__dry__total_g: 17.2265 - val_mae_all: 12.0587 - val_mae_gdm_g: 12.4995 - learning_rate: 1.0000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 63.7601 - mae__dry__clover_g: 8.0964 - mae__dry__dead_g: 8.6820 - mae__dry__green_g: 14.6704 - mae__dry__total_g: 15.0217 - mae_all: 12.0497 - mae_gdm_g: 13.7782 - val_loss: 70.8292 - val_mae__dry__clover_g: 6.6194 - val_mae__dry__dead_g: 9.5741 - val_mae__dry__green_g: 13.8522 - val_mae__dry__total_g: 16.8083 - val_mae_all: 11.7639 - val_mae_gdm_g: 11.9655 - learning_rate: 1.0000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 62.0829 - mae__dry__clover_g: 8.1061 - mae__dry__dead_g: 8.5928 - mae__dry__green_g: 14.5188 - mae__dry__total_g: 14.7625 - mae_all: 12.0299 - mae_gdm_g: 14.1694 - val_loss: 71.3916 - val_mae__dry__clover_g: 6.4790 - val_mae__dry__dead_g: 9.5143 - val_mae__dry__green_g: 13.6748 - val_mae__dry__total_g: 16.6031 - val_mae_all: 11.6548 - val_mae_gdm_g: 12.0029 - learning_rate: 1.0000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 64.5851 - mae__dry__clover_g: 7.9894 - mae__dry__dead_g: 8.1948 - mae__dry__green_g: 14.3604 - mae__dry__total_g: 14.8610 - mae_all: 11.8492 - mae_gdm_g: 13.8404 - val_loss: 68.7048 - val_mae__dry__clover_g: 6.5090 - val_mae__dry__dead_g: 9.4593 - val_mae__dry__green_g: 13.4244 - val_mae__dry__total_g: 16.4958 - val_mae_all: 11.5694 - val_mae_gdm_g: 11.9585 - learning_rate: 1.0000e-04
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 742ms/step - loss: 59.9104 - mae__dry__clover_g: 7.7925 - mae__dry__dead_g: 8.7013 - mae__dry__green_g: 14.6845 - mae__dry__total_g: 14.9081 - mae_all: 11.9485 - mae_gdm_g: 13.6560 - val_loss: 67.9329 - val_mae__dry__clover_g: 6.4781 - val_mae__dry__dead_g: 9.4928 - val_mae__dry__green_g: 13.2696 - val_mae__dry__total_g: 16.5523 - val_mae_all: 11.5375 - val_mae_gdm_g: 11.8950 - learning_rate: 1.0000e-04
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 64.0609 - mae__dry__clover_g: 8.2791 - mae__dry__dead_g: 8.4808 - mae__dry__green_g: 14.3622 - mae__dry__total_g: 15.0392 - mae_all: 11.9744 - mae_gdm_g: 13.7106 - val_loss: 65.9926 - val_mae__dry__clover_g: 6.4850 - val_mae__dry__dead_g: 9.4008 - val_mae__dry__green_g: 13.1132 - val_mae__dry__total_g: 16.2379 - val_mae_all: 11.4187 - val_mae_gdm_g: 11.8567 - learning_rate: 1.0000e-04
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 59.3510 - mae__dry__clover_g: 8.1503 - mae__dry__dead_g: 9.0901 - mae__dry__green_g: 13.9277 - mae__dry__total_g: 14.5670 - mae_all: 11.8564 - mae_gdm_g: 13.5471 - val_loss: 62.7655 - val_mae__dry__clover_g: 6.5695 - val_mae__dry__dead_g: 9.3809 - val_mae__dry__green_g: 12.9849 - val_mae__dry__total_g: 16.1050 - val_mae_all: 11.3678 - val_mae_gdm_g: 11.7985 - learning_rate: 1.0000e-04
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 744ms/step - loss: 61.1247 - mae__dry__clover_g: 8.1088 - mae__dry__dead_g: 8.4517 - mae__dry__green_g: 14.4460 - mae__dry__total_g: 15.0863 - mae_all: 11.9133 - mae_gdm_g: 13.4739 - val_loss: 62.1797 - val_mae__dry__clover_g: 6.4868 - val_mae__dry__dead_g: 9.3145 - val_mae__dry__green_g: 13.0713 - val_mae__dry__total_g: 15.8897 - val_mae_all: 11.3616 - val_mae_gdm_g: 12.0454 - learning_rate: 1.0000e-04
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 739ms/step - loss: 59.2739 - mae__dry__clover_g: 8.1850 - mae__dry__dead_g: 8.5517 - mae__dry__green_g: 13.9648 - mae__dry__total_g: 14.7385 - mae_all: 11.7483 - mae_gdm_g: 13.3017 - val_loss: 62.2775 - val_mae__dry__clover_g: 6.5582 - val_mae__dry__dead_g: 9.3284 - val_mae__dry__green_g: 12.9242 - val_mae__dry__total_g: 15.9816 - val_mae_all: 11.3116 - val_mae_gdm_g: 11.7654 - learning_rate: 1.0000e-04
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 740ms/step - loss: 59.7499 - mae__dry__clover_g: 7.9540 - mae__dry__dead_g: 8.3086 - mae__dry__green_g: 14.6515 - mae__dry__total_g: 14.5055 - mae_all: 11.8024 - mae_gdm_g: 13.5926 - val_loss: 65.8243 - val_mae__dry__clover_g: 6.4474 - val_mae__dry__dead_g: 9.3929 - val_mae__dry__green_g: 12.7842 - val_mae__dry__total_g: 16.1941 - val_mae_all: 11.2798 - val_mae_gdm_g: 11.5803 - learning_rate: 1.0000e-04
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 738ms/step - loss: 60.2863 - mae__dry__clover_g: 8.2155 - mae__dry__dead_g: 8.5316 - mae__dry__green_g: 14.0387 - mae__dry__total_g: 14.7070 - mae_all: 11.7670 - mae_gdm_g: 13.3423 - val_loss: 59.7226 - val_mae__dry__clover_g: 6.6673 - val_mae__dry__dead_g: 9.2774 - val_mae__dry__green_g: 13.6718 - val_mae__dry__total_g: 16.1417 - val_mae_all: 11.6751 - val_mae_gdm_g: 12.6171 - learning_rate: 1.0000e-04
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 689ms/step - loss: 53.1175 - mae__dry__clover_g: 8.2004 - mae__dry__dead_g: 8.0719 - mae__dry__green_g: 13.3717 - mae__dry__total_g: 14.3586 - mae_all: 11.3271 - mae_gdm_g: 12.6331
Epoch 28: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 739ms/step - loss: 60.7608 - mae__dry__clover_g: 7.8283 - mae__dry__dead_g: 8.1952 - mae__dry__green_g: 14.4479 - mae__dry__total_g: 14.9260 - mae_all: 11.7884 - mae_gdm_g: 13.5444 - val_loss: 61.0122 - val_mae__dry__clover_g: 6.4202 - val_mae__dry__dead_g: 9.2673 - val_mae__dry__green_g: 13.0484 - val_mae__dry__total_g: 15.8829 - val_mae_all: 11.3063 - val_mae_gdm_g: 11.9129 - learning_rate: 1.0000e-04
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 738ms/step - loss: 60.6338 - mae__dry__clover_g: 7.7076 - mae__dry__dead_g: 8.3637 - mae__dry__green_g: 14.3338 - mae__dry__total_g: 14.7222 - mae_all: 11.7826 - mae_gdm_g: 13.7855 - val_loss: 62.3624 - val_mae__dry__clover_g: 6.3861 - val_mae__dry__dead_g: 9.2495 - val_mae__dry__green_g: 12.7964 - val_mae__dry__total_g: 15.9431 - val_mae_all: 11.2045 - val_mae_gdm_g: 11.6476 - learning_rate: 5.0000e-05
Epoch 30/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 739ms/step - loss: 57.5363 - mae__dry__clover_g: 8.0928 - mae__dry__dead_g: 8.4150 - mae__dry__green_g: 13.7032 - mae__dry__total_g: 14.2688 - mae_all: 11.5417 - mae_gdm_g: 13.2290 - val_loss: 61.0662 - val_mae__dry__clover_g: 6.3847 - val_mae__dry__dead_g: 9.1363 - val_mae__dry__green_g: 13.0091 - val_mae__dry__total_g: 15.6711 - val_mae_all: 11.2265 - val_mae_gdm_g: 11.9314 - learning_rate: 5.0000e-05
Restoring model weights from the end of the best epoch: 29.
[Student] Fold 0 best val_mae_all = 11.205
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 192ms/step
[Student] Fold 0 Kaggle-style weighted R2 = 0.4686

===== [Student Distill] Fold 1 (alpha=0.55, tau=1.0) =====
45/45 ━━━━━━━━━━━━━━━━━━━━ 9s 194ms/step
[Student] Fold 1 Train: 285 | Val: 72
[Student] load baseline backbone from ./ckpt/baseline_gram_fold1.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 739ms/step - loss: 358.2258 - mae__dry__clover_g: 6.3727 - mae__dry__dead_g: 11.4142 - mae__dry__green_g: 26.4005 - mae__dry__total_g: 44.4741 - mae_all: 24.1746 - mae_gdm_g: 32.2116 - val_loss: 330.4433 - val_mae__dry__clover_g: 7.0451 - val_mae__dry__dead_g: 10.3653 - val_mae__dry__green_g: 25.3214 - val_mae__dry__total_g: 42.9286 - val_mae_all: 23.6078 - val_mae_gdm_g: 32.3783 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 735ms/step - loss: 336.8837 - mae__dry__clover_g: 6.3684 - mae__dry__dead_g: 11.0428 - mae__dry__green_g: 26.4307 - mae__dry__total_g: 42.3570 - mae_all: 23.6010 - mae_gdm_g: 31.8059 - val_loss: 308.7046 - val_mae__dry__clover_g: 7.0498 - val_mae__dry__dead_g: 9.8885 - val_mae__dry__green_g: 25.2581 - val_mae__dry__total_g: 40.5209 - val_mae_all: 22.9708 - val_mae_gdm_g: 32.1366 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 738ms/step - loss: 307.2593 - mae__dry__clover_g: 6.3603 - mae__dry__dead_g: 10.5395 - mae__dry__green_g: 26.4242 - mae__dry__total_g: 39.2764 - mae_all: 22.7505 - mae_gdm_g: 31.1524 - val_loss: 282.7910 - val_mae__dry__clover_g: 7.0876 - val_mae__dry__dead_g: 9.4248 - val_mae__dry__green_g: 25.2070 - val_mae__dry__total_g: 37.6376 - val_mae_all: 22.1609 - val_mae_gdm_g: 31.4474 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 737ms/step - loss: 274.0625 - mae__dry__clover_g: 6.3727 - mae__dry__dead_g: 9.9719 - mae__dry__green_g: 26.2881 - mae__dry__total_g: 35.8881 - mae_all: 21.6135 - mae_gdm_g: 29.5469 - val_loss: 249.0564 - val_mae__dry__clover_g: 7.2264 - val_mae__dry__dead_g: 9.0911 - val_mae__dry__green_g: 25.0773 - val_mae__dry__total_g: 33.9035 - val_mae_all: 21.0191 - val_mae_gdm_g: 29.7971 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 737ms/step - loss: 242.4499 - mae__dry__clover_g: 6.4930 - mae__dry__dead_g: 9.6324 - mae__dry__green_g: 26.0166 - mae__dry__total_g: 32.5175 - mae_all: 20.4153 - mae_gdm_g: 27.4168 - val_loss: 213.4966 - val_mae__dry__clover_g: 7.4734 - val_mae__dry__dead_g: 9.0731 - val_mae__dry__green_g: 24.8290 - val_mae__dry__total_g: 29.8873 - val_mae_all: 19.7069 - val_mae_gdm_g: 27.2719 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 738ms/step - loss: 210.1781 - mae__dry__clover_g: 6.5714 - mae__dry__dead_g: 9.3858 - mae__dry__green_g: 25.3728 - mae__dry__total_g: 29.2633 - mae_all: 19.1369 - mae_gdm_g: 25.0913 - val_loss: 179.3640 - val_mae__dry__clover_g: 7.7557 - val_mae__dry__dead_g: 9.4550 - val_mae__dry__green_g: 24.0849 - val_mae__dry__total_g: 26.1297 - val_mae_all: 18.3503 - val_mae_gdm_g: 24.3264 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 737ms/step - loss: 181.4032 - mae__dry__clover_g: 7.2122 - mae__dry__dead_g: 9.5702 - mae__dry__green_g: 24.3098 - mae__dry__total_g: 26.1885 - mae_all: 18.0215 - mae_gdm_g: 22.8269 - val_loss: 149.3309 - val_mae__dry__clover_g: 7.9974 - val_mae__dry__dead_g: 10.1174 - val_mae__dry__green_g: 22.8878 - val_mae__dry__total_g: 22.8473 - val_mae_all: 17.0452 - val_mae_gdm_g: 21.3765 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 739ms/step - loss: 156.7920 - mae__dry__clover_g: 7.5341 - mae__dry__dead_g: 9.8017 - mae__dry__green_g: 22.9146 - mae__dry__total_g: 23.5114 - mae_all: 16.8467 - mae_gdm_g: 20.4718 - val_loss: 125.2180 - val_mae__dry__clover_g: 8.1523 - val_mae__dry__dead_g: 10.6197 - val_mae__dry__green_g: 21.5335 - val_mae__dry__total_g: 20.2411 - val_mae_all: 15.8900 - val_mae_gdm_g: 18.9033 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 738ms/step - loss: 135.5515 - mae__dry__clover_g: 7.3801 - mae__dry__dead_g: 10.1541 - mae__dry__green_g: 21.4390 - mae__dry__total_g: 21.5691 - mae_all: 15.8251 - mae_gdm_g: 18.5833 - val_loss: 105.0808 - val_mae__dry__clover_g: 8.3100 - val_mae__dry__dead_g: 10.9664 - val_mae__dry__green_g: 20.1519 - val_mae__dry__total_g: 18.1180 - val_mae_all: 14.8569 - val_mae_gdm_g: 16.7380 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 737ms/step - loss: 117.6313 - mae__dry__clover_g: 7.5224 - mae__dry__dead_g: 9.9281 - mae__dry__green_g: 19.8810 - mae__dry__total_g: 19.7596 - mae_all: 14.7950 - mae_gdm_g: 16.8837 - val_loss: 89.8072 - val_mae__dry__clover_g: 8.4130 - val_mae__dry__dead_g: 10.9740 - val_mae__dry__green_g: 18.8233 - val_mae__dry__total_g: 16.1983 - val_mae_all: 13.8988 - val_mae_gdm_g: 15.0855 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 738ms/step - loss: 106.0509 - mae__dry__clover_g: 8.0880 - mae__dry__dead_g: 10.4173 - mae__dry__green_g: 18.3120 - mae__dry__total_g: 19.1639 - mae_all: 14.4063 - mae_gdm_g: 16.0505 - val_loss: 85.3587 - val_mae__dry__clover_g: 8.2722 - val_mae__dry__dead_g: 10.6638 - val_mae__dry__green_g: 18.1539 - val_mae__dry__total_g: 16.0849 - val_mae_all: 13.5699 - val_mae_gdm_g: 14.6744 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 739ms/step - loss: 98.8853 - mae__dry__clover_g: 7.9367 - mae__dry__dead_g: 9.7319 - mae__dry__green_g: 17.5903 - mae__dry__total_g: 18.9897 - mae_all: 13.9078 - mae_gdm_g: 15.2904 - val_loss: 82.7744 - val_mae__dry__clover_g: 8.1331 - val_mae__dry__dead_g: 10.3468 - val_mae__dry__green_g: 17.6218 - val_mae__dry__total_g: 16.0913 - val_mae_all: 13.3645 - val_mae_gdm_g: 14.6292 - learning_rate: 1.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 742ms/step - loss: 89.9572 - mae__dry__clover_g: 7.9718 - mae__dry__dead_g: 9.9817 - mae__dry__green_g: 16.5150 - mae__dry__total_g: 18.2772 - mae_all: 13.5538 - mae_gdm_g: 15.0234 - val_loss: 81.0189 - val_mae__dry__clover_g: 7.9285 - val_mae__dry__dead_g: 10.0970 - val_mae__dry__green_g: 17.1476 - val_mae__dry__total_g: 16.1512 - val_mae_all: 13.1581 - val_mae_gdm_g: 14.4661 - learning_rate: 1.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 744ms/step - loss: 88.0641 - mae__dry__clover_g: 7.8842 - mae__dry__dead_g: 9.9779 - mae__dry__green_g: 15.8904 - mae__dry__total_g: 18.5137 - mae_all: 13.5059 - mae_gdm_g: 15.2634 - val_loss: 80.3364 - val_mae__dry__clover_g: 7.7814 - val_mae__dry__dead_g: 9.8228 - val_mae__dry__green_g: 16.8559 - val_mae__dry__total_g: 16.3259 - val_mae_all: 13.0640 - val_mae_gdm_g: 14.5342 - learning_rate: 1.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 743ms/step - loss: 83.8643 - mae__dry__clover_g: 7.8900 - mae__dry__dead_g: 9.8130 - mae__dry__green_g: 15.5963 - mae__dry__total_g: 18.1541 - mae_all: 13.2001 - mae_gdm_g: 14.5470 - val_loss: 79.0340 - val_mae__dry__clover_g: 7.7145 - val_mae__dry__dead_g: 9.6363 - val_mae__dry__green_g: 16.5727 - val_mae__dry__total_g: 16.2535 - val_mae_all: 12.9029 - val_mae_gdm_g: 14.3377 - learning_rate: 1.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 78.5823 - mae__dry__clover_g: 7.8283 - mae__dry__dead_g: 9.6482 - mae__dry__green_g: 15.0552 - mae__dry__total_g: 17.8149 - mae_all: 13.0511 - mae_gdm_g: 14.9088 - val_loss: 74.8375 - val_mae__dry__clover_g: 7.7055 - val_mae__dry__dead_g: 9.6431 - val_mae__dry__green_g: 16.0200 - val_mae__dry__total_g: 15.9198 - val_mae_all: 12.6696 - val_mae_gdm_g: 14.0599 - learning_rate: 1.0000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 744ms/step - loss: 82.6682 - mae__dry__clover_g: 7.2431 - mae__dry__dead_g: 9.4659 - mae__dry__green_g: 15.2420 - mae__dry__total_g: 18.4298 - mae_all: 13.1204 - mae_gdm_g: 15.2213 - val_loss: 72.6784 - val_mae__dry__clover_g: 7.6697 - val_mae__dry__dead_g: 9.6066 - val_mae__dry__green_g: 15.6917 - val_mae__dry__total_g: 15.9796 - val_mae_all: 12.6026 - val_mae_gdm_g: 14.0651 - learning_rate: 1.0000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 743ms/step - loss: 76.6297 - mae__dry__clover_g: 7.2466 - mae__dry__dead_g: 9.6787 - mae__dry__green_g: 14.7337 - mae__dry__total_g: 18.3669 - mae_all: 12.9982 - mae_gdm_g: 14.9652 - val_loss: 73.4941 - val_mae__dry__clover_g: 7.5677 - val_mae__dry__dead_g: 9.4154 - val_mae__dry__green_g: 15.6994 - val_mae__dry__total_g: 16.1444 - val_mae_all: 12.5945 - val_mae_gdm_g: 14.1457 - learning_rate: 1.0000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 753ms/step - loss: 82.0668 - mae__dry__clover_g: 7.3800 - mae__dry__dead_g: 9.2285 - mae__dry__green_g: 15.7223 - mae__dry__total_g: 18.4720 - mae_all: 13.2517 - mae_gdm_g: 15.4557 - val_loss: 70.2144 - val_mae__dry__clover_g: 7.5782 - val_mae__dry__dead_g: 9.4141 - val_mae__dry__green_g: 15.2089 - val_mae__dry__total_g: 15.9401 - val_mae_all: 12.3939 - val_mae_gdm_g: 13.8280 - learning_rate: 1.0000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 770ms/step - loss: 79.0765 - mae__dry__clover_g: 7.6270 - mae__dry__dead_g: 9.2747 - mae__dry__green_g: 14.9664 - mae__dry__total_g: 18.0884 - mae_all: 13.0246 - mae_gdm_g: 15.1664 - val_loss: 71.9486 - val_mae__dry__clover_g: 7.4473 - val_mae__dry__dead_g: 9.2827 - val_mae__dry__green_g: 15.3998 - val_mae__dry__total_g: 16.0186 - val_mae_all: 12.4296 - val_mae_gdm_g: 13.9998 - learning_rate: 1.0000e-04
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 712ms/step - loss: 72.7564 - mae__dry__clover_g: 8.6736 - mae__dry__dead_g: 9.5335 - mae__dry__green_g: 14.6680 - mae__dry__total_g: 18.6681 - mae_all: 13.4244 - mae_gdm_g: 15.5787
Epoch 21: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 764ms/step - loss: 78.2536 - mae__dry__clover_g: 7.4021 - mae__dry__dead_g: 9.3798 - mae__dry__green_g: 15.2753 - mae__dry__total_g: 18.4363 - mae_all: 13.1911 - mae_gdm_g: 15.4619 - val_loss: 71.2082 - val_mae__dry__clover_g: 7.4647 - val_mae__dry__dead_g: 9.2613 - val_mae__dry__green_g: 15.3641 - val_mae__dry__total_g: 16.0536 - val_mae_all: 12.4381 - val_mae_gdm_g: 14.0470 - learning_rate: 1.0000e-04
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 759ms/step - loss: 77.0581 - mae__dry__clover_g: 7.3935 - mae__dry__dead_g: 9.2610 - mae__dry__green_g: 14.7700 - mae__dry__total_g: 18.1698 - mae_all: 12.8755 - mae_gdm_g: 14.7833 - val_loss: 68.9638 - val_mae__dry__clover_g: 7.5047 - val_mae__dry__dead_g: 9.3137 - val_mae__dry__green_g: 15.1336 - val_mae__dry__total_g: 15.9302 - val_mae_all: 12.3644 - val_mae_gdm_g: 13.9395 - learning_rate: 5.0000e-05
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 73.8140 - mae__dry__clover_g: 7.4852 - mae__dry__dead_g: 9.6846 - mae__dry__green_g: 14.7570 - mae__dry__total_g: 17.2731 - mae_all: 12.7852 - mae_gdm_g: 14.7262 - val_loss: 67.1547 - val_mae__dry__clover_g: 7.5451 - val_mae__dry__dead_g: 9.3816 - val_mae__dry__green_g: 14.9653 - val_mae__dry__total_g: 15.9049 - val_mae_all: 12.3360 - val_mae_gdm_g: 13.8832 - learning_rate: 5.0000e-05
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 761ms/step - loss: 73.4653 - mae__dry__clover_g: 7.5776 - mae__dry__dead_g: 9.8830 - mae__dry__green_g: 15.0328 - mae__dry__total_g: 17.6974 - mae_all: 13.0755 - mae_gdm_g: 15.1867 - val_loss: 66.2842 - val_mae__dry__clover_g: 7.5310 - val_mae__dry__dead_g: 9.3485 - val_mae__dry__green_g: 14.9313 - val_mae__dry__total_g: 15.9548 - val_mae_all: 12.3282 - val_mae_gdm_g: 13.8756 - learning_rate: 5.0000e-05
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 75.2537 - mae__dry__clover_g: 7.3700 - mae__dry__dead_g: 9.2070 - mae__dry__green_g: 15.1068 - mae__dry__total_g: 17.8870 - mae_all: 12.9081 - mae_gdm_g: 14.9699 - val_loss: 65.9657 - val_mae__dry__clover_g: 7.5701 - val_mae__dry__dead_g: 9.4438 - val_mae__dry__green_g: 14.8775 - val_mae__dry__total_g: 16.1458 - val_mae_all: 12.3972 - val_mae_gdm_g: 13.9487 - learning_rate: 5.0000e-05
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 694ms/step - loss: 68.8370 - mae__dry__clover_g: 8.8315 - mae__dry__dead_g: 9.4662 - mae__dry__green_g: 14.2214 - mae__dry__total_g: 18.1810 - mae_all: 13.1965 - mae_gdm_g: 15.2826
Epoch 26: ReduceLROnPlateau reducing learning rate to 2.499999936844688e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 74.1359 - mae__dry__clover_g: 7.5541 - mae__dry__dead_g: 9.5598 - mae__dry__green_g: 14.7581 - mae__dry__total_g: 17.8995 - mae_all: 12.9925 - mae_gdm_g: 15.1912 - val_loss: 66.1629 - val_mae__dry__clover_g: 7.5428 - val_mae__dry__dead_g: 9.4480 - val_mae__dry__green_g: 14.8271 - val_mae__dry__total_g: 16.1382 - val_mae_all: 12.3703 - val_mae_gdm_g: 13.8953 - learning_rate: 5.0000e-05
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 746ms/step - loss: 73.5658 - mae__dry__clover_g: 7.2509 - mae__dry__dead_g: 9.5424 - mae__dry__green_g: 14.8629 - mae__dry__total_g: 17.5075 - mae_all: 12.8037 - mae_gdm_g: 14.8550 - val_loss: 65.8779 - val_mae__dry__clover_g: 7.5407 - val_mae__dry__dead_g: 9.4620 - val_mae__dry__green_g: 14.8405 - val_mae__dry__total_g: 16.1720 - val_mae_all: 12.3895 - val_mae_gdm_g: 13.9322 - learning_rate: 2.5000e-05
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 693ms/step - loss: 67.4856 - mae__dry__clover_g: 8.7169 - mae__dry__dead_g: 10.0703 - mae__dry__green_g: 14.6777 - mae__dry__total_g: 17.7929 - mae_all: 13.2042 - mae_gdm_g: 14.7631
Epoch 28: ReduceLROnPlateau reducing learning rate to 1.249999968422344e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 27s 743ms/step - loss: 73.5789 - mae__dry__clover_g: 7.5779 - mae__dry__dead_g: 9.6172 - mae__dry__green_g: 14.9529 - mae__dry__total_g: 17.7364 - mae_all: 12.9133 - mae_gdm_g: 14.6819 - val_loss: 65.6895 - val_mae__dry__clover_g: 7.5286 - val_mae__dry__dead_g: 9.4455 - val_mae__dry__green_g: 14.8456 - val_mae__dry__total_g: 16.1687 - val_mae_all: 12.3887 - val_mae_gdm_g: 13.9549 - learning_rate: 2.5000e-05
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 744ms/step - loss: 74.5966 - mae__dry__clover_g: 7.1729 - mae__dry__dead_g: 9.1338 - mae__dry__green_g: 14.9349 - mae__dry__total_g: 17.9355 - mae_all: 12.8280 - mae_gdm_g: 14.9631 - val_loss: 65.4958 - val_mae__dry__clover_g: 7.5528 - val_mae__dry__dead_g: 9.4703 - val_mae__dry__green_g: 14.8480 - val_mae__dry__total_g: 16.2261 - val_mae_all: 12.4270 - val_mae_gdm_g: 14.0377 - learning_rate: 1.2500e-05
Epoch 29: early stopping
Restoring model weights from the end of the best epoch: 24.
[Student] Fold 1 best val_mae_all = 12.328
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 199ms/step
[Student] Fold 1 Kaggle-style weighted R2 = 0.4047

===== [Student Distill] Fold 2 (alpha=0.55, tau=1.0) =====
45/45 ━━━━━━━━━━━━━━━━━━━━ 9s 194ms/step
[Student] Fold 2 Train: 286 | Val: 71
[Student] load baseline backbone from ./ckpt/baseline_gram_fold2.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 30s 770ms/step - loss: 331.5127 - mae__dry__clover_g: 6.2506 - mae__dry__dead_g: 11.9915 - mae__dry__green_g: 24.8851 - mae__dry__total_g: 43.1714 - mae_all: 23.5630 - mae_gdm_g: 31.5166 - val_loss: 366.0359 - val_mae__dry__clover_g: 7.4941 - val_mae__dry__dead_g: 9.8274 - val_mae__dry__green_g: 27.8342 - val_mae__dry__total_g: 43.5001 - val_mae_all: 24.8297 - val_mae_gdm_g: 35.4927 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 302.0152 - mae__dry__clover_g: 6.2172 - mae__dry__dead_g: 11.8364 - mae__dry__green_g: 24.3093 - mae__dry__total_g: 40.4482 - mae_all: 22.7606 - mae_gdm_g: 30.9919 - val_loss: 316.7690 - val_mae__dry__clover_g: 7.4399 - val_mae__dry__dead_g: 9.6280 - val_mae__dry__green_g: 26.7679 - val_mae__dry__total_g: 39.1309 - val_mae_all: 23.4870 - val_mae_gdm_g: 34.4686 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 266.7889 - mae__dry__clover_g: 6.2182 - mae__dry__dead_g: 11.4648 - mae__dry__green_g: 23.3243 - mae__dry__total_g: 37.0026 - mae_all: 21.6106 - mae_gdm_g: 30.0432 - val_loss: 250.6643 - val_mae__dry__clover_g: 7.3980 - val_mae__dry__dead_g: 9.0774 - val_mae__dry__green_g: 24.7952 - val_mae__dry__total_g: 32.7175 - val_mae_all: 21.2765 - val_mae_gdm_g: 32.3944 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 231.1904 - mae__dry__clover_g: 6.3412 - mae__dry__dead_g: 11.0235 - mae__dry__green_g: 22.2061 - mae__dry__total_g: 33.3654 - mae_all: 20.3001 - mae_gdm_g: 28.5643 - val_loss: 181.4684 - val_mae__dry__clover_g: 7.4095 - val_mae__dry__dead_g: 8.3695 - val_mae__dry__green_g: 22.1151 - val_mae__dry__total_g: 25.6404 - val_mae_all: 18.4978 - val_mae_gdm_g: 28.9545 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 752ms/step - loss: 193.4107 - mae__dry__clover_g: 6.3321 - mae__dry__dead_g: 10.4641 - mae__dry__green_g: 21.0821 - mae__dry__total_g: 29.2699 - mae_all: 18.7510 - mae_gdm_g: 26.6070 - val_loss: 142.0664 - val_mae__dry__clover_g: 7.4631 - val_mae__dry__dead_g: 8.2081 - val_mae__dry__green_g: 20.1612 - val_mae__dry__total_g: 21.8308 - val_mae_all: 16.7269 - val_mae_gdm_g: 25.9715 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 160.6516 - mae__dry__clover_g: 6.4050 - mae__dry__dead_g: 9.9361 - mae__dry__green_g: 19.5287 - mae__dry__total_g: 25.4684 - mae_all: 17.1417 - mae_gdm_g: 24.3703 - val_loss: 130.2633 - val_mae__dry__clover_g: 7.5543 - val_mae__dry__dead_g: 8.1853 - val_mae__dry__green_g: 19.4924 - val_mae__dry__total_g: 21.2867 - val_mae_all: 16.2442 - val_mae_gdm_g: 24.7023 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 133.2393 - mae__dry__clover_g: 6.7966 - mae__dry__dead_g: 9.8944 - mae__dry__green_g: 17.8535 - mae__dry__total_g: 22.1949 - mae_all: 15.7515 - mae_gdm_g: 22.0180 - val_loss: 124.3765 - val_mae__dry__clover_g: 7.6382 - val_mae__dry__dead_g: 8.0926 - val_mae__dry__green_g: 19.0422 - val_mae__dry__total_g: 21.1572 - val_mae_all: 15.9354 - val_mae_gdm_g: 23.7469 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 108.4034 - mae__dry__clover_g: 6.7059 - mae__dry__dead_g: 9.7275 - mae__dry__green_g: 16.3601 - mae__dry__total_g: 20.1381 - mae_all: 14.5263 - mae_gdm_g: 19.6998 - val_loss: 122.2829 - val_mae__dry__clover_g: 7.6758 - val_mae__dry__dead_g: 7.9962 - val_mae__dry__green_g: 18.8265 - val_mae__dry__total_g: 21.3453 - val_mae_all: 15.8060 - val_mae_gdm_g: 23.1862 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 93.5110 - mae__dry__clover_g: 7.0133 - mae__dry__dead_g: 9.8451 - mae__dry__green_g: 15.2942 - mae__dry__total_g: 18.4540 - mae_all: 13.6973 - mae_gdm_g: 17.8801 - val_loss: 125.2043 - val_mae__dry__clover_g: 7.6944 - val_mae__dry__dead_g: 7.8824 - val_mae__dry__green_g: 18.8657 - val_mae__dry__total_g: 21.8550 - val_mae_all: 15.8708 - val_mae_gdm_g: 23.0567 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 758ms/step - loss: 80.3566 - mae__dry__clover_g: 7.2506 - mae__dry__dead_g: 9.6994 - mae__dry__green_g: 14.6935 - mae__dry__total_g: 16.7220 - mae_all: 12.8773 - mae_gdm_g: 16.0209 - val_loss: 116.7488 - val_mae__dry__clover_g: 7.7456 - val_mae__dry__dead_g: 7.8978 - val_mae__dry__green_g: 18.2892 - val_mae__dry__total_g: 21.2691 - val_mae_all: 15.4541 - val_mae_gdm_g: 22.0689 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 73.5801 - mae__dry__clover_g: 7.4294 - mae__dry__dead_g: 9.7035 - mae__dry__green_g: 14.3466 - mae__dry__total_g: 16.3026 - mae_all: 12.5902 - mae_gdm_g: 15.1687 - val_loss: 116.8019 - val_mae__dry__clover_g: 7.7678 - val_mae__dry__dead_g: 7.8061 - val_mae__dry__green_g: 18.3033 - val_mae__dry__total_g: 21.5990 - val_mae_all: 15.4761 - val_mae_gdm_g: 21.9041 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 66.9462 - mae__dry__clover_g: 7.2611 - mae__dry__dead_g: 9.8314 - mae__dry__green_g: 14.1419 - mae__dry__total_g: 15.5612 - mae_all: 12.2255 - mae_gdm_g: 14.3317 - val_loss: 97.2677 - val_mae__dry__clover_g: 7.8981 - val_mae__dry__dead_g: 7.8591 - val_mae__dry__green_g: 17.0502 - val_mae__dry__total_g: 19.4896 - val_mae_all: 14.4456 - val_mae_gdm_g: 19.9311 - learning_rate: 1.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 61.3477 - mae__dry__clover_g: 7.3891 - mae__dry__dead_g: 9.5140 - mae__dry__green_g: 13.2537 - mae__dry__total_g: 15.7219 - mae_all: 11.8815 - mae_gdm_g: 13.5285 - val_loss: 95.7840 - val_mae__dry__clover_g: 7.8792 - val_mae__dry__dead_g: 7.8146 - val_mae__dry__green_g: 16.8848 - val_mae__dry__total_g: 19.4813 - val_mae_all: 14.3136 - val_mae_gdm_g: 19.5080 - learning_rate: 1.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 752ms/step - loss: 56.7544 - mae__dry__clover_g: 7.5970 - mae__dry__dead_g: 9.7075 - mae__dry__green_g: 13.8554 - mae__dry__total_g: 15.2165 - mae_all: 11.9462 - mae_gdm_g: 13.3543 - val_loss: 85.8538 - val_mae__dry__clover_g: 7.8995 - val_mae__dry__dead_g: 7.8421 - val_mae__dry__green_g: 16.1915 - val_mae__dry__total_g: 18.5954 - val_mae_all: 13.7614 - val_mae_gdm_g: 18.2784 - learning_rate: 1.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 753ms/step - loss: 57.3827 - mae__dry__clover_g: 7.5350 - mae__dry__dead_g: 9.3267 - mae__dry__green_g: 13.8301 - mae__dry__total_g: 15.8193 - mae_all: 11.8774 - mae_gdm_g: 12.8759 - val_loss: 79.4080 - val_mae__dry__clover_g: 7.9354 - val_mae__dry__dead_g: 7.8842 - val_mae__dry__green_g: 15.7035 - val_mae__dry__total_g: 17.8939 - val_mae_all: 13.3407 - val_mae_gdm_g: 17.2863 - learning_rate: 1.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 57.2303 - mae__dry__clover_g: 7.3873 - mae__dry__dead_g: 9.8478 - mae__dry__green_g: 13.6087 - mae__dry__total_g: 15.4847 - mae_all: 11.9050 - mae_gdm_g: 13.1967 - val_loss: 65.6495 - val_mae__dry__clover_g: 8.0910 - val_mae__dry__dead_g: 7.9791 - val_mae__dry__green_g: 14.8739 - val_mae__dry__total_g: 16.3929 - val_mae_all: 12.6215 - val_mae_gdm_g: 15.7708 - learning_rate: 1.0000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 56.6396 - mae__dry__clover_g: 7.6912 - mae__dry__dead_g: 9.4186 - mae__dry__green_g: 13.5863 - mae__dry__total_g: 15.4748 - mae_all: 11.8233 - mae_gdm_g: 12.9456 - val_loss: 59.9217 - val_mae__dry__clover_g: 8.1421 - val_mae__dry__dead_g: 8.1250 - val_mae__dry__green_g: 14.2113 - val_mae__dry__total_g: 15.6528 - val_mae_all: 12.2339 - val_mae_gdm_g: 15.0382 - learning_rate: 1.0000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 752ms/step - loss: 56.7372 - mae__dry__clover_g: 7.5893 - mae__dry__dead_g: 9.7612 - mae__dry__green_g: 13.7481 - mae__dry__total_g: 15.6474 - mae_all: 11.9450 - mae_gdm_g: 12.9792 - val_loss: 71.4272 - val_mae__dry__clover_g: 7.9372 - val_mae__dry__dead_g: 7.8686 - val_mae__dry__green_g: 15.1372 - val_mae__dry__total_g: 17.1459 - val_mae_all: 12.8021 - val_mae_gdm_g: 15.9214 - learning_rate: 1.0000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 699ms/step - loss: 60.0523 - mae__dry__clover_g: 8.2035 - mae__dry__dead_g: 9.1789 - mae__dry__green_g: 14.0956 - mae__dry__total_g: 16.2015 - mae_all: 12.3880 - mae_gdm_g: 14.2607
Epoch 19: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 53.6722 - mae__dry__clover_g: 7.1777 - mae__dry__dead_g: 9.3024 - mae__dry__green_g: 13.5819 - mae__dry__total_g: 15.2849 - mae_all: 11.7184 - mae_gdm_g: 13.2454 - val_loss: 60.0565 - val_mae__dry__clover_g: 8.0612 - val_mae__dry__dead_g: 8.1023 - val_mae__dry__green_g: 14.6233 - val_mae__dry__total_g: 15.7438 - val_mae_all: 12.2671 - val_mae_gdm_g: 14.8049 - learning_rate: 1.0000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 55.3006 - mae__dry__clover_g: 7.6726 - mae__dry__dead_g: 9.9183 - mae__dry__green_g: 13.4258 - mae__dry__total_g: 15.3226 - mae_all: 11.8874 - mae_gdm_g: 13.0975 - val_loss: 57.7723 - val_mae__dry__clover_g: 8.0841 - val_mae__dry__dead_g: 8.1753 - val_mae__dry__green_g: 14.3478 - val_mae__dry__total_g: 15.5391 - val_mae_all: 12.1380 - val_mae_gdm_g: 14.5436 - learning_rate: 5.0000e-05
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 761ms/step - loss: 54.3949 - mae__dry__clover_g: 7.3956 - mae__dry__dead_g: 9.3236 - mae__dry__green_g: 13.6791 - mae__dry__total_g: 15.3944 - mae_all: 11.6742 - mae_gdm_g: 12.5780 - val_loss: 56.5283 - val_mae__dry__clover_g: 8.1344 - val_mae__dry__dead_g: 8.2256 - val_mae__dry__green_g: 14.4542 - val_mae__dry__total_g: 15.4249 - val_mae_all: 12.1636 - val_mae_gdm_g: 14.5791 - learning_rate: 5.0000e-05
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 761ms/step - loss: 54.3628 - mae__dry__clover_g: 7.7939 - mae__dry__dead_g: 9.5511 - mae__dry__green_g: 13.8344 - mae__dry__total_g: 15.1751 - mae_all: 11.8656 - mae_gdm_g: 12.9736 - val_loss: 54.4192 - val_mae__dry__clover_g: 8.1870 - val_mae__dry__dead_g: 8.3384 - val_mae__dry__green_g: 14.3682 - val_mae__dry__total_g: 15.2391 - val_mae_all: 12.1154 - val_mae_gdm_g: 14.4445 - learning_rate: 5.0000e-05
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 759ms/step - loss: 52.2812 - mae__dry__clover_g: 7.2846 - mae__dry__dead_g: 9.6677 - mae__dry__green_g: 13.4762 - mae__dry__total_g: 15.1009 - mae_all: 11.6455 - mae_gdm_g: 12.6978 - val_loss: 55.7841 - val_mae__dry__clover_g: 8.1070 - val_mae__dry__dead_g: 8.1878 - val_mae__dry__green_g: 14.3529 - val_mae__dry__total_g: 15.2751 - val_mae_all: 12.0823 - val_mae_gdm_g: 14.4888 - learning_rate: 5.0000e-05
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 53.3736 - mae__dry__clover_g: 7.4948 - mae__dry__dead_g: 9.4234 - mae__dry__green_g: 13.8156 - mae__dry__total_g: 15.2892 - mae_all: 11.8254 - mae_gdm_g: 13.1041 - val_loss: 54.5048 - val_mae__dry__clover_g: 8.1310 - val_mae__dry__dead_g: 8.2803 - val_mae__dry__green_g: 14.2601 - val_mae__dry__total_g: 15.1443 - val_mae_all: 12.0318 - val_mae_gdm_g: 14.3432 - learning_rate: 5.0000e-05
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 753ms/step - loss: 53.3144 - mae__dry__clover_g: 7.6176 - mae__dry__dead_g: 9.6010 - mae__dry__green_g: 13.0149 - mae__dry__total_g: 15.1707 - mae_all: 11.6788 - mae_gdm_g: 12.9898 - val_loss: 55.4055 - val_mae__dry__clover_g: 8.0567 - val_mae__dry__dead_g: 8.2009 - val_mae__dry__green_g: 14.2778 - val_mae__dry__total_g: 15.2293 - val_mae_all: 12.0118 - val_mae_gdm_g: 14.2945 - learning_rate: 5.0000e-05
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 50.7391 - mae__dry__clover_g: 7.2869 - mae__dry__dead_g: 9.6136 - mae__dry__green_g: 13.1738 - mae__dry__total_g: 14.9172 - mae_all: 11.5524 - mae_gdm_g: 12.7705 - val_loss: 55.2532 - val_mae__dry__clover_g: 8.0494 - val_mae__dry__dead_g: 8.1530 - val_mae__dry__green_g: 14.3263 - val_mae__dry__total_g: 15.1953 - val_mae_all: 12.0182 - val_mae_gdm_g: 14.3672 - learning_rate: 5.0000e-05
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 53.0682 - mae__dry__clover_g: 7.4855 - mae__dry__dead_g: 9.2508 - mae__dry__green_g: 13.4436 - mae__dry__total_g: 15.0461 - mae_all: 11.6704 - mae_gdm_g: 13.1261 - val_loss: 53.8979 - val_mae__dry__clover_g: 8.0697 - val_mae__dry__dead_g: 8.2275 - val_mae__dry__green_g: 14.3188 - val_mae__dry__total_g: 15.0885 - val_mae_all: 12.0043 - val_mae_gdm_g: 14.3169 - learning_rate: 5.0000e-05
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 53.7700 - mae__dry__clover_g: 7.3928 - mae__dry__dead_g: 9.1034 - mae__dry__green_g: 13.5741 - mae__dry__total_g: 15.0443 - mae_all: 11.6411 - mae_gdm_g: 13.0910 - val_loss: 55.4763 - val_mae__dry__clover_g: 8.0222 - val_mae__dry__dead_g: 8.1545 - val_mae__dry__green_g: 14.3901 - val_mae__dry__total_g: 15.2392 - val_mae_all: 12.0366 - val_mae_gdm_g: 14.3768 - learning_rate: 5.0000e-05
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 699ms/step - loss: 55.8383 - mae__dry__clover_g: 8.3427 - mae__dry__dead_g: 9.2810 - mae__dry__green_g: 13.9087 - mae__dry__total_g: 15.6407 - mae_all: 12.1738 - mae_gdm_g: 13.6958
Epoch 29: ReduceLROnPlateau reducing learning rate to 2.499999936844688e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 749ms/step - loss: 52.3262 - mae__dry__clover_g: 7.4850 - mae__dry__dead_g: 9.3476 - mae__dry__green_g: 13.7212 - mae__dry__total_g: 15.1471 - mae_all: 11.6571 - mae_gdm_g: 12.5846 - val_loss: 55.2765 - val_mae__dry__clover_g: 8.0298 - val_mae__dry__dead_g: 8.1418 - val_mae__dry__green_g: 14.3714 - val_mae__dry__total_g: 15.1885 - val_mae_all: 12.0202 - val_mae_gdm_g: 14.3697 - learning_rate: 5.0000e-05
Epoch 30/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 53.0074 - mae__dry__clover_g: 7.4513 - mae__dry__dead_g: 9.3703 - mae__dry__green_g: 13.7632 - mae__dry__total_g: 15.3723 - mae_all: 11.7606 - mae_gdm_g: 12.8461 - val_loss: 53.8692 - val_mae__dry__clover_g: 8.0598 - val_mae__dry__dead_g: 8.2711 - val_mae__dry__green_g: 14.2920 - val_mae__dry__total_g: 15.1112 - val_mae_all: 11.9844 - val_mae_gdm_g: 14.1877 - learning_rate: 2.5000e-05
Restoring model weights from the end of the best epoch: 30.
[Student] Fold 2 best val_mae_all = 11.984
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 201ms/step
[Student] Fold 2 Kaggle-style weighted R2 = 0.6355

===== [Student Distill] Fold 3 (alpha=0.55, tau=1.0) =====
45/45 ━━━━━━━━━━━━━━━━━━━━ 9s 196ms/step
[Student] Fold 3 Train: 286 | Val: 71
[Student] load baseline backbone from ./ckpt/baseline_gram_fold3.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 750ms/step - loss: 343.4329 - mae__dry__clover_g: 6.3350 - mae__dry__dead_g: 11.3511 - mae__dry__green_g: 26.0833 - mae__dry__total_g: 43.4269 - mae_all: 23.9973 - mae_gdm_g: 32.7904 - val_loss: 308.3741 - val_mae__dry__clover_g: 6.9700 - val_mae__dry__dead_g: 12.8327 - val_mae__dry__green_g: 22.7037 - val_mae__dry__total_g: 41.0430 - val_mae_all: 22.9929 - val_mae_gdm_g: 31.4150 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 317.2516 - mae__dry__clover_g: 6.2785 - mae__dry__dead_g: 11.4232 - mae__dry__green_g: 25.5570 - mae__dry__total_g: 40.5423 - mae_all: 23.2815 - mae_gdm_g: 32.6066 - val_loss: 255.1552 - val_mae__dry__clover_g: 6.9056 - val_mae__dry__dead_g: 13.0212 - val_mae__dry__green_g: 20.9725 - val_mae__dry__total_g: 34.4899 - val_mae_all: 21.3635 - val_mae_gdm_g: 31.4281 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 288.9284 - mae__dry__clover_g: 6.3437 - mae__dry__dead_g: 11.4245 - mae__dry__green_g: 24.5732 - mae__dry__total_g: 37.3526 - mae_all: 22.3808 - mae_gdm_g: 32.2099 - val_loss: 208.6732 - val_mae__dry__clover_g: 7.2615 - val_mae__dry__dead_g: 13.1153 - val_mae__dry__green_g: 19.4024 - val_mae__dry__total_g: 28.2862 - val_mae_all: 19.7492 - val_mae_gdm_g: 30.6805 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 260.9142 - mae__dry__clover_g: 6.3664 - mae__dry__dead_g: 11.3435 - mae__dry__green_g: 23.5297 - mae__dry__total_g: 34.0312 - mae_all: 21.3389 - mae_gdm_g: 31.4237 - val_loss: 174.7343 - val_mae__dry__clover_g: 7.8749 - val_mae__dry__dead_g: 13.0988 - val_mae__dry__green_g: 17.8623 - val_mae__dry__total_g: 24.2527 - val_mae_all: 18.4174 - val_mae_gdm_g: 28.9985 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 758ms/step - loss: 233.8964 - mae__dry__clover_g: 6.5343 - mae__dry__dead_g: 11.2781 - mae__dry__green_g: 22.1901 - mae__dry__total_g: 30.9673 - mae_all: 20.2015 - mae_gdm_g: 30.0378 - val_loss: 147.3513 - val_mae__dry__clover_g: 8.6551 - val_mae__dry__dead_g: 12.9393 - val_mae__dry__green_g: 16.5502 - val_mae__dry__total_g: 21.5775 - val_mae_all: 17.1901 - val_mae_gdm_g: 26.2282 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 207.6444 - mae__dry__clover_g: 6.7275 - mae__dry__dead_g: 11.0212 - mae__dry__green_g: 21.0409 - mae__dry__total_g: 28.1433 - mae_all: 19.0186 - mae_gdm_g: 28.1600 - val_loss: 128.1944 - val_mae__dry__clover_g: 9.1877 - val_mae__dry__dead_g: 12.2377 - val_mae__dry__green_g: 15.6609 - val_mae__dry__total_g: 19.9691 - val_mae_all: 16.0497 - val_mae_gdm_g: 23.1932 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 181.8965 - mae__dry__clover_g: 7.2332 - mae__dry__dead_g: 10.6507 - mae__dry__green_g: 19.5167 - mae__dry__total_g: 25.3253 - mae_all: 17.7777 - mae_gdm_g: 26.1628 - val_loss: 123.4910 - val_mae__dry__clover_g: 8.9432 - val_mae__dry__dead_g: 11.3413 - val_mae__dry__green_g: 15.4903 - val_mae__dry__total_g: 20.0210 - val_mae_all: 15.4444 - val_mae_gdm_g: 21.4262 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 160.9452 - mae__dry__clover_g: 7.5983 - mae__dry__dead_g: 10.2145 - mae__dry__green_g: 18.3937 - mae__dry__total_g: 22.8585 - mae_all: 16.6482 - mae_gdm_g: 24.1759 - val_loss: 126.3699 - val_mae__dry__clover_g: 8.3149 - val_mae__dry__dead_g: 10.9473 - val_mae__dry__green_g: 15.7323 - val_mae__dry__total_g: 20.7966 - val_mae_all: 15.2986 - val_mae_gdm_g: 20.7021 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 144.5755 - mae__dry__clover_g: 7.9060 - mae__dry__dead_g: 9.8534 - mae__dry__green_g: 17.9090 - mae__dry__total_g: 21.4139 - mae_all: 15.8730 - mae_gdm_g: 22.2826 - val_loss: 121.8206 - val_mae__dry__clover_g: 8.0134 - val_mae__dry__dead_g: 10.6949 - val_mae__dry__green_g: 15.7572 - val_mae__dry__total_g: 20.8155 - val_mae_all: 14.9736 - val_mae_gdm_g: 19.5869 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 127.7869 - mae__dry__clover_g: 7.9258 - mae__dry__dead_g: 9.3285 - mae__dry__green_g: 16.8630 - mae__dry__total_g: 20.0272 - mae_all: 14.8469 - mae_gdm_g: 20.0900 - val_loss: 126.0590 - val_mae__dry__clover_g: 7.6408 - val_mae__dry__dead_g: 10.6404 - val_mae__dry__green_g: 16.1167 - val_mae__dry__total_g: 22.0104 - val_mae_all: 15.1911 - val_mae_gdm_g: 19.5471 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 116.0187 - mae__dry__clover_g: 7.9520 - mae__dry__dead_g: 9.4802 - mae__dry__green_g: 16.5535 - mae__dry__total_g: 19.0657 - mae_all: 14.2916 - mae_gdm_g: 18.4067 - val_loss: 121.0279 - val_mae__dry__clover_g: 7.5290 - val_mae__dry__dead_g: 10.5201 - val_mae__dry__green_g: 16.0051 - val_mae__dry__total_g: 21.9577 - val_mae_all: 14.9486 - val_mae_gdm_g: 18.7309 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 109.2194 - mae__dry__clover_g: 8.2068 - mae__dry__dead_g: 9.6107 - mae__dry__green_g: 15.7870 - mae__dry__total_g: 18.9910 - mae_all: 13.9064 - mae_gdm_g: 16.9365 - val_loss: 121.7870 - val_mae__dry__clover_g: 7.3892 - val_mae__dry__dead_g: 10.4150 - val_mae__dry__green_g: 16.0747 - val_mae__dry__total_g: 22.4326 - val_mae_all: 14.9615 - val_mae_gdm_g: 18.4962 - learning_rate: 1.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 101.8014 - mae__dry__clover_g: 7.6916 - mae__dry__dead_g: 9.7590 - mae__dry__green_g: 15.6568 - mae__dry__total_g: 18.1806 - mae_all: 13.5690 - mae_gdm_g: 16.5572 - val_loss: 110.3872 - val_mae__dry__clover_g: 7.3724 - val_mae__dry__dead_g: 10.3285 - val_mae__dry__green_g: 15.5271 - val_mae__dry__total_g: 21.2978 - val_mae_all: 14.3443 - val_mae_gdm_g: 17.1956 - learning_rate: 1.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 32s 857ms/step - loss: 99.6264 - mae__dry__clover_g: 8.0014 - mae__dry__dead_g: 9.5665 - mae__dry__green_g: 15.5961 - mae__dry__total_g: 18.2335 - mae_all: 13.4746 - mae_gdm_g: 15.9756 - val_loss: 110.2007 - val_mae__dry__clover_g: 7.3056 - val_mae__dry__dead_g: 10.2886 - val_mae__dry__green_g: 15.5104 - val_mae__dry__total_g: 21.4096 - val_mae_all: 14.2879 - val_mae_gdm_g: 16.9253 - learning_rate: 1.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 97.8589 - mae__dry__clover_g: 7.9247 - mae__dry__dead_g: 9.5559 - mae__dry__green_g: 15.8557 - mae__dry__total_g: 18.0177 - mae_all: 13.3763 - mae_gdm_g: 15.5278 - val_loss: 105.3440 - val_mae__dry__clover_g: 7.2624 - val_mae__dry__dead_g: 10.2270 - val_mae__dry__green_g: 15.2422 - val_mae__dry__total_g: 20.8530 - val_mae_all: 13.9778 - val_mae_gdm_g: 16.3044 - learning_rate: 1.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 93.3556 - mae__dry__clover_g: 7.8862 - mae__dry__dead_g: 9.7606 - mae__dry__green_g: 15.7932 - mae__dry__total_g: 18.0738 - mae_all: 13.3700 - mae_gdm_g: 15.3360 - val_loss: 97.0241 - val_mae__dry__clover_g: 7.2696 - val_mae__dry__dead_g: 10.1849 - val_mae__dry__green_g: 14.8353 - val_mae__dry__total_g: 19.5942 - val_mae_all: 13.4242 - val_mae_gdm_g: 15.2369 - learning_rate: 1.0000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 95.1616 - mae__dry__clover_g: 7.5487 - mae__dry__dead_g: 9.1019 - mae__dry__green_g: 15.7251 - mae__dry__total_g: 18.4559 - mae_all: 13.2538 - mae_gdm_g: 15.4376 - val_loss: 92.4023 - val_mae__dry__clover_g: 7.2567 - val_mae__dry__dead_g: 10.0543 - val_mae__dry__green_g: 14.5884 - val_mae__dry__total_g: 19.2002 - val_mae_all: 13.1802 - val_mae_gdm_g: 14.8013 - learning_rate: 1.0000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 89.3374 - mae__dry__clover_g: 7.7544 - mae__dry__dead_g: 9.3143 - mae__dry__green_g: 15.8556 - mae__dry__total_g: 17.9348 - mae_all: 13.2336 - mae_gdm_g: 15.3087 - val_loss: 92.9015 - val_mae__dry__clover_g: 7.2271 - val_mae__dry__dead_g: 10.0897 - val_mae__dry__green_g: 14.6400 - val_mae__dry__total_g: 19.2272 - val_mae_all: 13.1643 - val_mae_gdm_g: 14.6373 - learning_rate: 1.0000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 758ms/step - loss: 90.7927 - mae__dry__clover_g: 7.4919 - mae__dry__dead_g: 9.5709 - mae__dry__green_g: 15.7721 - mae__dry__total_g: 17.8027 - mae_all: 13.1924 - mae_gdm_g: 15.3242 - val_loss: 89.0317 - val_mae__dry__clover_g: 7.2089 - val_mae__dry__dead_g: 9.9985 - val_mae__dry__green_g: 14.4615 - val_mae__dry__total_g: 18.8931 - val_mae_all: 12.9598 - val_mae_gdm_g: 14.2371 - learning_rate: 1.0000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 88.2878 - mae__dry__clover_g: 7.1863 - mae__dry__dead_g: 9.9429 - mae__dry__green_g: 15.6216 - mae__dry__total_g: 17.5971 - mae_all: 13.1014 - mae_gdm_g: 15.1592 - val_loss: 81.0821 - val_mae__dry__clover_g: 7.2350 - val_mae__dry__dead_g: 9.9085 - val_mae__dry__green_g: 14.1417 - val_mae__dry__total_g: 17.8505 - val_mae_all: 12.5062 - val_mae_gdm_g: 13.3955 - learning_rate: 1.0000e-04
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 89.8009 - mae__dry__clover_g: 7.2270 - mae__dry__dead_g: 9.7316 - mae__dry__green_g: 15.5636 - mae__dry__total_g: 17.7366 - mae_all: 13.0766 - mae_gdm_g: 15.1244 - val_loss: 74.2234 - val_mae__dry__clover_g: 7.2805 - val_mae__dry__dead_g: 9.8591 - val_mae__dry__green_g: 13.9116 - val_mae__dry__total_g: 17.0934 - val_mae_all: 12.1698 - val_mae_gdm_g: 12.7045 - learning_rate: 1.0000e-04
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 90.7767 - mae__dry__clover_g: 7.6440 - mae__dry__dead_g: 9.6255 - mae__dry__green_g: 15.6662 - mae__dry__total_g: 17.6528 - mae_all: 13.2045 - mae_gdm_g: 15.4338 - val_loss: 71.6312 - val_mae__dry__clover_g: 7.3179 - val_mae__dry__dead_g: 9.8230 - val_mae__dry__green_g: 13.8787 - val_mae__dry__total_g: 17.0415 - val_mae_all: 12.1002 - val_mae_gdm_g: 12.4399 - learning_rate: 1.0000e-04
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 89.1410 - mae__dry__clover_g: 7.0612 - mae__dry__dead_g: 9.7084 - mae__dry__green_g: 15.8077 - mae__dry__total_g: 18.0830 - mae_all: 13.1625 - mae_gdm_g: 15.1519 - val_loss: 67.7475 - val_mae__dry__clover_g: 7.3571 - val_mae__dry__dead_g: 9.7417 - val_mae__dry__green_g: 13.9538 - val_mae__dry__total_g: 16.4781 - val_mae_all: 11.9366 - val_mae_gdm_g: 12.1525 - learning_rate: 1.0000e-04
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 88.5731 - mae__dry__clover_g: 7.6741 - mae__dry__dead_g: 9.7304 - mae__dry__green_g: 15.7790 - mae__dry__total_g: 17.6840 - mae_all: 13.2869 - mae_gdm_g: 15.5671 - val_loss: 67.4138 - val_mae__dry__clover_g: 7.3477 - val_mae__dry__dead_g: 9.7236 - val_mae__dry__green_g: 13.9617 - val_mae__dry__total_g: 16.5778 - val_mae_all: 11.9490 - val_mae_gdm_g: 12.1344 - learning_rate: 1.0000e-04
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 87.0586 - mae__dry__clover_g: 7.6541 - mae__dry__dead_g: 9.7385 - mae__dry__green_g: 15.5657 - mae__dry__total_g: 17.7418 - mae_all: 13.2065 - mae_gdm_g: 15.3325 - val_loss: 66.8010 - val_mae__dry__clover_g: 7.3583 - val_mae__dry__dead_g: 9.6793 - val_mae__dry__green_g: 13.8239 - val_mae__dry__total_g: 16.6000 - val_mae_all: 11.9057 - val_mae_gdm_g: 12.0671 - learning_rate: 1.0000e-04
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 762ms/step - loss: 87.1999 - mae__dry__clover_g: 7.5473 - mae__dry__dead_g: 9.5117 - mae__dry__green_g: 15.7087 - mae__dry__total_g: 17.6630 - mae_all: 13.1540 - mae_gdm_g: 15.3394 - val_loss: 65.0527 - val_mae__dry__clover_g: 7.3814 - val_mae__dry__dead_g: 9.6295 - val_mae__dry__green_g: 14.0701 - val_mae__dry__total_g: 16.4475 - val_mae_all: 11.8976 - val_mae_gdm_g: 11.9596 - learning_rate: 1.0000e-04
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 754ms/step - loss: 86.4608 - mae__dry__clover_g: 7.4658 - mae__dry__dead_g: 9.6813 - mae__dry__green_g: 15.7254 - mae__dry__total_g: 17.5355 - mae_all: 13.0915 - mae_gdm_g: 15.0497 - val_loss: 64.1612 - val_mae__dry__clover_g: 7.4053 - val_mae__dry__dead_g: 9.5969 - val_mae__dry__green_g: 14.0988 - val_mae__dry__total_g: 16.5433 - val_mae_all: 11.9167 - val_mae_gdm_g: 11.9394 - learning_rate: 1.0000e-04
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 766ms/step - loss: 85.7783 - mae__dry__clover_g: 7.7346 - mae__dry__dead_g: 9.4024 - mae__dry__green_g: 15.6672 - mae__dry__total_g: 17.4439 - mae_all: 13.0146 - mae_gdm_g: 14.8250 - val_loss: 63.3476 - val_mae__dry__clover_g: 7.3998 - val_mae__dry__dead_g: 9.5783 - val_mae__dry__green_g: 13.9583 - val_mae__dry__total_g: 16.3726 - val_mae_all: 11.8252 - val_mae_gdm_g: 11.8169 - learning_rate: 1.0000e-04
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 763ms/step - loss: 84.1648 - mae__dry__clover_g: 7.8697 - mae__dry__dead_g: 9.5499 - mae__dry__green_g: 15.4777 - mae__dry__total_g: 17.2865 - mae_all: 13.1172 - mae_gdm_g: 15.4023 - val_loss: 63.3552 - val_mae__dry__clover_g: 7.3707 - val_mae__dry__dead_g: 9.5427 - val_mae__dry__green_g: 13.8637 - val_mae__dry__total_g: 16.4643 - val_mae_all: 11.8115 - val_mae_gdm_g: 11.8160 - learning_rate: 1.0000e-04
Epoch 30/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 758ms/step - loss: 84.0311 - mae__dry__clover_g: 7.4056 - mae__dry__dead_g: 9.1823 - mae__dry__green_g: 15.6294 - mae__dry__total_g: 17.4510 - mae_all: 12.9331 - mae_gdm_g: 14.9970 - val_loss: 64.2209 - val_mae__dry__clover_g: 7.3611 - val_mae__dry__dead_g: 9.5009 - val_mae__dry__green_g: 13.7843 - val_mae__dry__total_g: 16.5091 - val_mae_all: 11.8197 - val_mae_gdm_g: 11.9432 - learning_rate: 1.0000e-04
Restoring model weights from the end of the best epoch: 29.
[Student] Fold 3 best val_mae_all = 11.811
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 201ms/step
[Student] Fold 3 Kaggle-style weighted R2 = 0.4507

===== [Student Distill] Fold 4 (alpha=0.55, tau=1.0) =====
45/45 ━━━━━━━━━━━━━━━━━━━━ 9s 196ms/step
[Student] Fold 4 Train: 286 | Val: 71
[Student] load baseline backbone from ./ckpt/baseline_gram_fold4.weights.h5
[Student] backbone weights copied from baseline
Epoch 1/30

/Users/jiaweilong/Downloads/advMaths/final/venv_py3.11_tensorflow/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 42 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 750ms/step - loss: 343.8331 - mae__dry__clover_g: 6.7597 - mae__dry__dead_g: 11.3297 - mae__dry__green_g: 25.6999 - mae__dry__total_g: 43.4428 - mae_all: 23.9049 - mae_gdm_g: 32.2923 - val_loss: 329.6394 - val_mae__dry__clover_g: 5.4135 - val_mae__dry__dead_g: 10.6413 - val_mae__dry__green_g: 27.5342 - val_mae__dry__total_g: 41.1744 - val_mae_all: 23.4742 - val_mae_gdm_g: 32.6076 - learning_rate: 1.0000e-04
Epoch 2/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 311.6767 - mae__dry__clover_g: 6.8006 - mae__dry__dead_g: 10.9943 - mae__dry__green_g: 25.6294 - mae__dry__total_g: 40.3599 - mae_all: 23.1426 - mae_gdm_g: 31.9287 - val_loss: 276.5795 - val_mae__dry__clover_g: 5.4041 - val_mae__dry__dead_g: 9.9934 - val_mae__dry__green_g: 27.4794 - val_mae__dry__total_g: 35.5122 - val_mae_all: 22.0401 - val_mae_gdm_g: 31.8114 - learning_rate: 1.0000e-04
Epoch 3/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 745ms/step - loss: 277.8702 - mae__dry__clover_g: 6.8005 - mae__dry__dead_g: 10.5663 - mae__dry__green_g: 25.5291 - mae__dry__total_g: 37.0394 - mae_all: 22.2319 - mae_gdm_g: 31.2244 - val_loss: 245.5964 - val_mae__dry__clover_g: 5.4798 - val_mae__dry__dead_g: 9.6570 - val_mae__dry__green_g: 27.2171 - val_mae__dry__total_g: 32.1167 - val_mae_all: 21.0519 - val_mae_gdm_g: 30.7888 - learning_rate: 1.0000e-04
Epoch 4/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 245.8107 - mae__dry__clover_g: 6.8254 - mae__dry__dead_g: 10.1111 - mae__dry__green_g: 25.1681 - mae__dry__total_g: 33.7339 - mae_all: 21.2181 - mae_gdm_g: 30.2521 - val_loss: 231.7705 - val_mae__dry__clover_g: 5.5757 - val_mae__dry__dead_g: 9.3881 - val_mae__dry__green_g: 26.6097 - val_mae__dry__total_g: 30.9250 - val_mae_all: 20.4722 - val_mae_gdm_g: 29.8624 - learning_rate: 1.0000e-04
Epoch 5/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 747ms/step - loss: 217.5557 - mae__dry__clover_g: 6.9118 - mae__dry__dead_g: 9.8423 - mae__dry__green_g: 24.5457 - mae__dry__total_g: 30.9187 - mae_all: 20.2168 - mae_gdm_g: 28.8655 - val_loss: 225.5486 - val_mae__dry__clover_g: 5.6551 - val_mae__dry__dead_g: 9.2332 - val_mae__dry__green_g: 25.9455 - val_mae__dry__total_g: 30.6891 - val_mae_all: 20.1482 - val_mae_gdm_g: 29.2180 - learning_rate: 1.0000e-04
Epoch 6/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 188.6249 - mae__dry__clover_g: 7.0558 - mae__dry__dead_g: 9.5053 - mae__dry__green_g: 23.5447 - mae__dry__total_g: 27.9266 - mae_all: 19.0975 - mae_gdm_g: 27.4549 - val_loss: 207.9049 - val_mae__dry__clover_g: 5.8542 - val_mae__dry__dead_g: 9.0309 - val_mae__dry__green_g: 25.0919 - val_mae__dry__total_g: 28.9855 - val_mae_all: 19.3877 - val_mae_gdm_g: 27.9761 - learning_rate: 1.0000e-04
Epoch 7/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 748ms/step - loss: 161.7089 - mae__dry__clover_g: 7.2568 - mae__dry__dead_g: 9.4602 - mae__dry__green_g: 22.6042 - mae__dry__total_g: 24.8069 - mae_all: 17.9863 - mae_gdm_g: 25.8032 - val_loss: 198.9820 - val_mae__dry__clover_g: 5.9742 - val_mae__dry__dead_g: 8.9100 - val_mae__dry__green_g: 24.3309 - val_mae__dry__total_g: 28.3343 - val_mae_all: 18.9400 - val_mae_gdm_g: 27.1505 - learning_rate: 1.0000e-04
Epoch 8/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 138.2128 - mae__dry__clover_g: 7.7283 - mae__dry__dead_g: 9.3264 - mae__dry__green_g: 21.4162 - mae__dry__total_g: 22.3054 - mae_all: 16.8874 - mae_gdm_g: 23.6609 - val_loss: 189.0140 - val_mae__dry__clover_g: 6.0346 - val_mae__dry__dead_g: 8.8111 - val_mae__dry__green_g: 23.5259 - val_mae__dry__total_g: 27.3543 - val_mae_all: 18.3844 - val_mae_gdm_g: 26.1958 - learning_rate: 1.0000e-04
Epoch 9/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 762ms/step - loss: 116.7500 - mae__dry__clover_g: 7.8114 - mae__dry__dead_g: 9.3364 - mae__dry__green_g: 19.8598 - mae__dry__total_g: 20.0264 - mae_all: 15.7877 - mae_gdm_g: 21.9047 - val_loss: 179.0122 - val_mae__dry__clover_g: 6.1143 - val_mae__dry__dead_g: 8.7132 - val_mae__dry__green_g: 22.6933 - val_mae__dry__total_g: 26.4267 - val_mae_all: 17.8294 - val_mae_gdm_g: 25.1994 - learning_rate: 1.0000e-04
Epoch 10/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 101.7968 - mae__dry__clover_g: 7.9160 - mae__dry__dead_g: 9.6267 - mae__dry__green_g: 18.8221 - mae__dry__total_g: 18.5701 - mae_all: 15.0612 - mae_gdm_g: 20.3710 - val_loss: 171.3309 - val_mae__dry__clover_g: 6.1586 - val_mae__dry__dead_g: 8.5776 - val_mae__dry__green_g: 21.9572 - val_mae__dry__total_g: 25.6564 - val_mae_all: 17.3228 - val_mae_gdm_g: 24.2641 - learning_rate: 1.0000e-04
Epoch 11/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 779ms/step - loss: 89.5770 - mae__dry__clover_g: 8.2771 - mae__dry__dead_g: 9.4260 - mae__dry__green_g: 18.1270 - mae__dry__total_g: 17.1942 - mae_all: 14.3521 - mae_gdm_g: 18.7363 - val_loss: 154.0040 - val_mae__dry__clover_g: 6.2707 - val_mae__dry__dead_g: 8.4767 - val_mae__dry__green_g: 20.7757 - val_mae__dry__total_g: 23.9757 - val_mae_all: 16.4428 - val_mae_gdm_g: 22.7153 - learning_rate: 1.0000e-04
Epoch 12/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 760ms/step - loss: 81.4782 - mae__dry__clover_g: 8.3796 - mae__dry__dead_g: 9.2518 - mae__dry__green_g: 16.8672 - mae__dry__total_g: 16.7202 - mae_all: 13.6497 - mae_gdm_g: 17.0297 - val_loss: 142.2006 - val_mae__dry__clover_g: 6.3157 - val_mae__dry__dead_g: 8.3409 - val_mae__dry__green_g: 19.7258 - val_mae__dry__total_g: 22.7281 - val_mae_all: 15.7106 - val_mae_gdm_g: 21.4425 - learning_rate: 1.0000e-04
Epoch 13/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 770ms/step - loss: 76.1570 - mae__dry__clover_g: 8.0297 - mae__dry__dead_g: 9.3201 - mae__dry__green_g: 16.3641 - mae__dry__total_g: 16.1756 - mae_all: 13.2098 - mae_gdm_g: 16.1594 - val_loss: 134.2981 - val_mae__dry__clover_g: 6.3350 - val_mae__dry__dead_g: 8.2804 - val_mae__dry__green_g: 18.9714 - val_mae__dry__total_g: 21.9769 - val_mae_all: 15.1915 - val_mae_gdm_g: 20.3939 - learning_rate: 1.0000e-04
Epoch 14/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 758ms/step - loss: 71.8460 - mae__dry__clover_g: 8.1582 - mae__dry__dead_g: 9.5215 - mae__dry__green_g: 15.6725 - mae__dry__total_g: 16.1849 - mae_all: 12.9598 - mae_gdm_g: 15.2619 - val_loss: 121.2077 - val_mae__dry__clover_g: 6.4274 - val_mae__dry__dead_g: 8.1748 - val_mae__dry__green_g: 18.0058 - val_mae__dry__total_g: 20.8725 - val_mae_all: 14.5465 - val_mae_gdm_g: 19.2518 - learning_rate: 1.0000e-04
Epoch 15/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 755ms/step - loss: 66.8153 - mae__dry__clover_g: 8.3045 - mae__dry__dead_g: 9.3499 - mae__dry__green_g: 14.9443 - mae__dry__total_g: 15.6534 - mae_all: 12.5411 - mae_gdm_g: 14.4532 - val_loss: 109.5367 - val_mae__dry__clover_g: 6.4776 - val_mae__dry__dead_g: 8.1549 - val_mae__dry__green_g: 16.9101 - val_mae__dry__total_g: 19.6540 - val_mae_all: 13.8097 - val_mae_gdm_g: 17.8522 - learning_rate: 1.0000e-04
Epoch 16/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 63.2568 - mae__dry__clover_g: 8.1142 - mae__dry__dead_g: 9.8036 - mae__dry__green_g: 14.4897 - mae__dry__total_g: 15.3034 - mae_all: 12.2872 - mae_gdm_g: 13.7250 - val_loss: 101.0633 - val_mae__dry__clover_g: 6.5218 - val_mae__dry__dead_g: 8.1597 - val_mae__dry__green_g: 16.1018 - val_mae__dry__total_g: 19.0037 - val_mae_all: 13.3599 - val_mae_gdm_g: 17.0126 - learning_rate: 1.0000e-04
Epoch 17/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 764ms/step - loss: 61.6635 - mae__dry__clover_g: 8.2130 - mae__dry__dead_g: 9.4993 - mae__dry__green_g: 14.5164 - mae__dry__total_g: 15.4037 - mae_all: 12.3189 - mae_gdm_g: 13.9620 - val_loss: 93.3341 - val_mae__dry__clover_g: 6.5968 - val_mae__dry__dead_g: 8.1183 - val_mae__dry__green_g: 15.3769 - val_mae__dry__total_g: 18.4388 - val_mae_all: 12.9892 - val_mae_gdm_g: 16.4153 - learning_rate: 1.0000e-04
Epoch 18/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 753ms/step - loss: 58.9790 - mae__dry__clover_g: 8.5970 - mae__dry__dead_g: 9.6532 - mae__dry__green_g: 13.8137 - mae__dry__total_g: 14.7602 - mae_all: 12.0760 - mae_gdm_g: 13.5560 - val_loss: 95.1199 - val_mae__dry__clover_g: 6.4712 - val_mae__dry__dead_g: 8.1126 - val_mae__dry__green_g: 15.3319 - val_mae__dry__total_g: 18.5743 - val_mae_all: 12.9802 - val_mae_gdm_g: 16.4112 - learning_rate: 1.0000e-04
Epoch 19/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 59.0935 - mae__dry__clover_g: 8.2348 - mae__dry__dead_g: 9.0693 - mae__dry__green_g: 14.0942 - mae__dry__total_g: 14.7640 - mae_all: 11.8465 - mae_gdm_g: 13.0699 - val_loss: 100.8585 - val_mae__dry__clover_g: 6.3429 - val_mae__dry__dead_g: 8.0366 - val_mae__dry__green_g: 15.6049 - val_mae__dry__total_g: 19.0080 - val_mae_all: 13.1092 - val_mae_gdm_g: 16.5535 - learning_rate: 1.0000e-04
Epoch 20/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 751ms/step - loss: 58.0111 - mae__dry__clover_g: 8.1922 - mae__dry__dead_g: 9.3153 - mae__dry__green_g: 14.2368 - mae__dry__total_g: 14.8994 - mae_all: 11.9689 - mae_gdm_g: 13.2007 - val_loss: 89.7966 - val_mae__dry__clover_g: 6.4977 - val_mae__dry__dead_g: 8.1570 - val_mae__dry__green_g: 14.7661 - val_mae__dry__total_g: 18.2812 - val_mae_all: 12.7162 - val_mae_gdm_g: 15.8791 - learning_rate: 1.0000e-04
Epoch 21/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 58.3635 - mae__dry__clover_g: 7.9428 - mae__dry__dead_g: 9.4471 - mae__dry__green_g: 13.6906 - mae__dry__total_g: 15.3066 - mae_all: 11.9726 - mae_gdm_g: 13.4758 - val_loss: 94.9597 - val_mae__dry__clover_g: 6.4162 - val_mae__dry__dead_g: 8.0922 - val_mae__dry__green_g: 15.0294 - val_mae__dry__total_g: 18.6210 - val_mae_all: 12.8525 - val_mae_gdm_g: 16.1038 - learning_rate: 1.0000e-04
Epoch 22/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 759ms/step - loss: 55.5749 - mae__dry__clover_g: 8.4996 - mae__dry__dead_g: 9.6080 - mae__dry__green_g: 14.1573 - mae__dry__total_g: 14.8966 - mae_all: 12.0163 - mae_gdm_g: 12.9200 - val_loss: 85.6715 - val_mae__dry__clover_g: 6.5897 - val_mae__dry__dead_g: 8.1513 - val_mae__dry__green_g: 14.6326 - val_mae__dry__total_g: 18.1448 - val_mae_all: 12.6518 - val_mae_gdm_g: 15.7407 - learning_rate: 1.0000e-04
Epoch 23/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 756ms/step - loss: 57.7160 - mae__dry__clover_g: 8.0761 - mae__dry__dead_g: 9.3898 - mae__dry__green_g: 14.1501 - mae__dry__total_g: 14.7860 - mae_all: 11.9004 - mae_gdm_g: 13.1003 - val_loss: 87.1308 - val_mae__dry__clover_g: 6.6023 - val_mae__dry__dead_g: 8.1047 - val_mae__dry__green_g: 14.6568 - val_mae__dry__total_g: 18.2044 - val_mae_all: 12.6699 - val_mae_gdm_g: 15.7815 - learning_rate: 1.0000e-04
Epoch 24/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 706ms/step - loss: 51.5952 - mae__dry__clover_g: 8.3066 - mae__dry__dead_g: 9.6583 - mae__dry__green_g: 13.0233 - mae__dry__total_g: 14.5241 - mae_all: 11.5039 - mae_gdm_g: 12.0073
Epoch 24: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 757ms/step - loss: 56.1736 - mae__dry__clover_g: 8.6792 - mae__dry__dead_g: 9.3695 - mae__dry__green_g: 13.9147 - mae__dry__total_g: 14.8405 - mae_all: 11.9413 - mae_gdm_g: 12.9029 - val_loss: 88.2067 - val_mae__dry__clover_g: 6.5565 - val_mae__dry__dead_g: 8.0787 - val_mae__dry__green_g: 14.6479 - val_mae__dry__total_g: 18.2689 - val_mae_all: 12.6848 - val_mae_gdm_g: 15.8721 - learning_rate: 1.0000e-04
Epoch 25/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 766ms/step - loss: 57.1090 - mae__dry__clover_g: 8.4823 - mae__dry__dead_g: 9.5050 - mae__dry__green_g: 13.9962 - mae__dry__total_g: 14.9656 - mae_all: 12.0001 - mae_gdm_g: 13.0516 - val_loss: 84.1948 - val_mae__dry__clover_g: 6.6595 - val_mae__dry__dead_g: 8.0591 - val_mae__dry__green_g: 14.6093 - val_mae__dry__total_g: 17.9215 - val_mae_all: 12.5913 - val_mae_gdm_g: 15.7073 - learning_rate: 5.0000e-05
Epoch 26/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 750ms/step - loss: 55.4673 - mae__dry__clover_g: 8.4668 - mae__dry__dead_g: 9.2873 - mae__dry__green_g: 14.0598 - mae__dry__total_g: 14.3414 - mae_all: 11.8267 - mae_gdm_g: 12.9779 - val_loss: 81.8386 - val_mae__dry__clover_g: 6.6964 - val_mae__dry__dead_g: 8.1254 - val_mae__dry__green_g: 14.5352 - val_mae__dry__total_g: 18.0529 - val_mae_all: 12.6398 - val_mae_gdm_g: 15.7892 - learning_rate: 5.0000e-05
Epoch 27/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 693ms/step - loss: 50.8285 - mae__dry__clover_g: 8.2085 - mae__dry__dead_g: 9.4206 - mae__dry__green_g: 12.9947 - mae__dry__total_g: 14.1051 - mae_all: 11.3641 - mae_gdm_g: 12.0914
Epoch 27: ReduceLROnPlateau reducing learning rate to 2.499999936844688e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 742ms/step - loss: 56.1052 - mae__dry__clover_g: 8.5671 - mae__dry__dead_g: 9.4285 - mae__dry__green_g: 13.8582 - mae__dry__total_g: 14.7120 - mae_all: 11.9906 - mae_gdm_g: 13.3870 - val_loss: 82.5839 - val_mae__dry__clover_g: 6.6420 - val_mae__dry__dead_g: 8.1691 - val_mae__dry__green_g: 14.4844 - val_mae__dry__total_g: 18.0664 - val_mae_all: 12.6066 - val_mae_gdm_g: 15.6710 - learning_rate: 5.0000e-05
Epoch 28/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 28s 758ms/step - loss: 53.0276 - mae__dry__clover_g: 8.2232 - mae__dry__dead_g: 9.7052 - mae__dry__green_g: 13.6505 - mae__dry__total_g: 14.3544 - mae_all: 11.7294 - mae_gdm_g: 12.7136 - val_loss: 80.1831 - val_mae__dry__clover_g: 6.7153 - val_mae__dry__dead_g: 8.1791 - val_mae__dry__green_g: 14.4546 - val_mae__dry__total_g: 17.9819 - val_mae_all: 12.6076 - val_mae_gdm_g: 15.7072 - learning_rate: 2.5000e-05
Epoch 29/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 0s 755ms/step - loss: 47.7989 - mae__dry__clover_g: 7.8180 - mae__dry__dead_g: 9.6936 - mae__dry__green_g: 13.2744 - mae__dry__total_g: 13.8137 - mae_all: 11.3024 - mae_gdm_g: 11.9126
Epoch 29: ReduceLROnPlateau reducing learning rate to 1.249999968422344e-05.
36/36 ━━━━━━━━━━━━━━━━━━━━ 30s 809ms/step - loss: 52.3189 - mae__dry__clover_g: 8.0770 - mae__dry__dead_g: 9.6356 - mae__dry__green_g: 14.0202 - mae__dry__total_g: 14.4767 - mae_all: 11.8066 - mae_gdm_g: 12.8233 - val_loss: 78.7577 - val_mae__dry__clover_g: 6.7637 - val_mae__dry__dead_g: 8.1762 - val_mae__dry__green_g: 14.4878 - val_mae__dry__total_g: 18.0970 - val_mae_all: 12.6652 - val_mae_gdm_g: 15.8010 - learning_rate: 2.5000e-05
Epoch 30/30
36/36 ━━━━━━━━━━━━━━━━━━━━ 29s 795ms/step - loss: 54.5031 - mae__dry__clover_g: 8.7386 - mae__dry__dead_g: 9.8113 - mae__dry__green_g: 13.8183 - mae__dry__total_g: 14.6692 - mae_all: 11.9125 - mae_gdm_g: 12.5252 - val_loss: 77.3796 - val_mae__dry__clover_g: 6.8215 - val_mae__dry__dead_g: 8.1928 - val_mae__dry__green_g: 14.5614 - val_mae__dry__total_g: 18.1825 - val_mae_all: 12.7281 - val_mae_gdm_g: 15.8825 - learning_rate: 1.2500e-05
Epoch 30: early stopping
Restoring model weights from the end of the best epoch: 25.
[Student] Fold 4 best val_mae_all = 12.591
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 207ms/step
[Student] Fold 4 Kaggle-style weighted R2 = 0.3543

===== [Student Distill] 5-fold CV summary =====
MAE per fold: [11.205 12.328 11.984 11.811 12.591]
R2  per fold: [0.469 0.405 0.635 0.451 0.354]
mean R2 = 0.4627702221111635

===== [CNN Baseline - gram] CV summary ===== 15 epochs, 3 target
val_mae_all per fold: [10.121 11.914 10.549 10.01  10.141]
mean ± std = 10.54708251953125 ± 0.7075833822485404
weighted_r2 per fold: [ 0.304 -0.171  0.498  0.39   0.33 ]
basline_gram mean R2 = 0.2702052972636771

===== [CNN Baseline - gram] CV summary ===== 30 epochs, 5 target
val_mae_all per fold: [11.332 14.766 12.259 16.392 12.652]
mean ± std = 13.479974555969239 ± 1.8397128198302635
weighted_r2 per fold: [ 0.426  0.287  0.595 -0.147  0.351]
basline_gram mean R2 = 0.30244747404764405

===== [Student Distill] 5-fold CV summary ===== 15 epochs, 3 target
MAE per fold: [ 9.151 10.531 10.454  9.288  9.149]
R2  per fold: [0.383 0.414 0.353 0.48  0.231]
mean R2 = 0.37238640442242643

===== [Student Distill] 5-fold CV summary ===== 30 epochs, 5 target
MAE per fold: [11.306 12.196 12.005 12.301 12.586]
R2  per fold: [0.469 0.419 0.64  0.395 0.362]
mean R2 = 0.4569973935200549

===== [Student Distill] 5-fold CV summary ===== (α=0.2, τ=1.0), 15 epochs, 3 target
MAE per fold: [ 9.151 10.531 10.454  9.288  9.149]
R2  per fold: [0.383 0.414 0.353 0.48  0.231]
mean R2 = 0.37238640442242643

===== [Student Distill] 5-fold CV summary ===== (α=0.2, τ=1.0), 30 epochs, 5 target
MAE per fold: [11.285 12.204 12.007 12.213 12.611]
R2  per fold: [0.475 0.417 0.638 0.401 0.354]
mean R2 = 0.4568422577684272

===== [Student Distill] 5-fold CV summary ===== (α=0.5, τ=1.0), 15 epochs, 3 target
MAE per fold: [ 9.121  9.743 10.556  9.187  8.893]
R2  per fold: [0.457 0.428 0.421 0.537 0.356]
mean R2 = 0.43976178722121323

===== [Student Distill] 5-fold CV summary ===== (α=0.6, τ=1.0), 30 epochs, 5 target
MAE per fold: [11.199 12.325 11.998 11.8   12.604]
R2  per fold: [0.467 0.404 0.634 0.445 0.352]
mean R2 = 0.460478188988293

===== [Student Distill] 5-fold CV summary ===== (α=0.4, τ=1.0), 30 epochs, 5 target
MAE per fold: [11.238 12.348 12.005 12.191 12.555]
R2  per fold: [0.472 0.403 0.632 0.399 0.351]
mean R2 = 0.4513830060100158

===== [Student Distill] 5-fold CV summary ===== (α=0.5, τ=1.0), 30 epochs, 5 target ---> Second!!
MAE per fold: [11.21  12.336 11.941 11.874 12.572]
R2  per fold: [0.471 0.399 0.642 0.445 0.353]
mean R2 = 0.46223788567622853

===== [Student Distill] 5-fold CV summary ===== (α=0.55, τ=1.0), 30 epochs, 5 target ---> Best!!
MAE per fold: [11.205 12.328 11.984 11.811 12.591]
R2  per fold: [0.469 0.405 0.635 0.451 0.354]
mean R2 = 0.4627702221111635

In [63]:

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
from pathlib import Path

# Define data for the conclusion
models = [
    'Mean Baseline,',
    'CNN Baseline, 30 epochs, ~49mins',
    'Teacher Model, 30 epchs, ~65mins',
    'Student (Fine-tuned only), 30 epochs, ~73mins',
    'Distilled Student (α=0.5, τ=1.0), 30 epochs, ~73mins',   
    'Distilled Student (α=0.55, τ=1.0), 30 epochs, ~72mins',   
]

inputs = [
    'N/A',
    'Image Only',
    'Image + Metadata',
    'Image Only',
    'Image Only',
    'Image Only',
]

# Updated R² values from your notebook results
r2_scores = [
    0.243,
    0.302,
    0.740,
    0.457,
    0.462,
    0.463,
]

insights = [
]

# ============== Print Summary Statistics ==============
print("\n" + "="*60)
print("MODEL PERFORMANCE SUMMARY")
print("="*60)

for i, model in enumerate(models):
    print(f"\n{model}")
    print(f"  Inputs: {inputs[i]}")
    print(f"  Mean Weighted R²: {r2_scores[i]:.3f}")
    # print(f"  Insight: {insights[i]}")

print("\n" + "="*60)
print("KEY FINDINGS:")
print("="*60)
print(f"• Improvement from Mean Baseline → Best Distilled Student: "
      f"{((r2_scores[4] - r2_scores[0]) / r2_scores[0] * 100):.1f}%")
print(f"• Performance gap (Best Student vs Teacher): "
      f"{(r2_scores[2] - r2_scores[4]):.3f}")
print(f"• Best α=0.55 outperforms α=0.5 by: "
      f"{((r2_scores[5] - r2_scores[4]) / r2_scores[4] * 100):.1f}%")

============================================================
MODEL PERFORMANCE SUMMARY
============================================================

Mean Baseline,
  Inputs: N/A
  Mean Weighted R²: 0.243

CNN Baseline, 30 epochs, ~49mins
  Inputs: Image Only
  Mean Weighted R²: 0.302

Teacher Model, 30 epchs, ~65mins
  Inputs: Image + Metadata
  Mean Weighted R²: 0.740

Student (Fine-tuned only), 30 epochs, ~73mins
  Inputs: Image Only
  Mean Weighted R²: 0.457

Distilled Student (α=0.5, τ=1.0), 30 epochs, ~73mins
  Inputs: Image Only
  Mean Weighted R²: 0.462

Distilled Student (α=0.55, τ=1.0), 30 epochs, ~72mins
  Inputs: Image Only
  Mean Weighted R²: 0.463

============================================================
KEY FINDINGS:
============================================================
• Improvement from Mean Baseline → Best Distilled Student: 90.1%
• Performance gap (Best Student vs Teacher): 0.278
• Best α=0.55 outperforms α=0.5 by: 0.2%